### ISSUE TITLE
Outpost markers not updating completely when changing faction

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#1]
Sometimes outpost markers will update only the color and not the text when the outpost is changing faction.

**Comment by Spoffy** [comment]
Possible fix in place - need more info on when this happens.

**Comment by wurzel0701** [comment]
Does this still happens? Or is it fixed?

**Comment by AlexTriada** [comment]
> Does this still happens? Or is it fixed?

@Spoffy - are you there? you asked, we need close this issue?

**Comment by Spoffy** [comment]
Pretty sure this still happens, but not 100%.

**Comment by wurzel0701** [comment]
As we aren't sure if that still happens, I am closing this issue.
We can reopen once we have confirmation that it happens again
