### ISSUE TITLE
Prevent QRFs despawning in front of players

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#10]

**Comment by Bob-Murphy** [comment]
@wurzel0701
I think this was solved by your new system?
If so, please confirm & close.

**Comment by wurzel0701** [comment]
Not yet, this part is scheduled for 2.4

**Comment by wurzel0701** [comment]
Is this even happening any more?

**Comment by Bob-Murphy** [comment]
Anybody got an update on that?

**Comment by wurzel0701** [comment]
No further reports so far, which does not mean it isn't happening any more

**Comment by Bob-Murphy** [comment]
I'll close it for now. Can be reopened if reports come in.
