### ISSUE TITLE
CIV unit markers clutter up HC map view.

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#101]
I'm not actually sure there is any way to deal with this properly but if the CIV faction markers could be removed that would help a lot.

**Comment by PoweredByPot** [comment]
There is no mechanism by which we can change this. Documentation for HC is less than sparse and provides no technical information whatsoever. A flip through the config viewer did not reveal anything that even could be tackled with a script. There is a mod by Duda that COULD fix some of the issue, but I havent tested it yet, and I wouldnt consider it a solution anyways.

**Comment by PoweredByPot** [comment]
This is an engine issue. Happens in vanilla game editor with just a few units, a HC, and some civs.

If, however, the CIV's are 'agents' then they **_WILL NOT_** appear.

**Comment by Bob-Murphy** [comment]
Please don't start working on that problem as civ stuff most likely will be changed completely.

**Comment by PoweredByPot** [comment]
#337 #402 and assigning bob, all three issues are related

**Comment by MeltedPixel** [comment]
Civ Markers shouldn't be a problem anymore going forward with new system
