### ISSUE TITLE
move vtols to a plane array 

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1026]
*Version:* 2.2.2

*Mods:* CBA, TFAR, ACE(no-medical)

*Environment*: SP, MP LAN, MP host, MP dedi.

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***
vtols are in attack helicopter array, they are not helicopters!!!, so lets move them to a plane array say cas/attack
---

**Comment by CalebSerafin** [comment]
@SonorousMeerkat, this sounds familiar to something you covered in a meeting. Did you solve this?

**Comment by Lazejun** [comment]
they are removed entirely, you can close it, they can only serve as Support, there is no reliable spawn way on Ground to work with AI

**Comment by CalebSerafin** [comment]
Fixed in [#1149](https://github.com/official-antistasi-community/A3-Antistasi/pull/1149)
