### ISSUE TITLE
Starting Items for Night Combat.

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1033]
There are currently no Flares for Vanilla, given at the Start (Those would be Ace so part of fn_aceModCompat.sqf).
Sadly Vanilla itself has no Flares so there is only the Ace Option.

--------> Vanilla Flashlights given dont fit on all Weapons/most of the Weapons given dont support a Flashlight.

--------> RHS starting Gear doesent support any Flashlights.
All other possible starting weapons also dont support any Flashlights

--------> 3CB starting Gear doesent support any Flashlights as well BUT a Pistol could be changed since its the same but the other version does Support a Flashlight
("UK3CB_BAF_L107A1" to "UK3CB_BAF_L117A2") --------> Pistol Flashlight ("UK3CB_BAF_Flashlight_L105A1")

**Comment by jaj22** [comment]
I would have expected servers to be well past the starting weapons by nightfall, so starter weapon fitting doesn't seem important, but if you can arrange more flashlights then that's all good.
