### ISSUE TITLE
JNL Issue

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1035]
As once Reported by Mezcal \rhsusf\addons\rhsusf_fmtv\M1078A1P2_B_M2 has Floating Boxes

**Classnames:**
"rhsusf_M1078A1P2_B_M2_WD_flatbed_fmtv_usarmy",
"rhsusf_M1078A1P2_B_M2_WD_fmtv_usarmy"

  ["\rhsusf\addons\rhsusf_fmtv\M1078A1P2_B_M2",[
    [1,[-0.00732422,0.0195313,-0.487986],[12,3,13,4,5,2]],
    [1,[0.0366211,-1.80859,-0.435032],[6,7,8,9,11,10]]
  ]],

![20200517235132_1](https://user-images.githubusercontent.com/57111907/82161033-d0e04b80-9899-11ea-965b-c7f512b43d79.jpg)

![20200517235126_1](https://user-images.githubusercontent.com/57111907/82161035-d63d9600-9899-11ea-9adf-ceb406950f92.jpg)

I went Ahead and set it a bit lower.

  ["\rhsusf\addons\rhsusf_fmtv\M1078A1P2_B_M2",[
    [1,[-0.00732422,0.0195313,-1.1],[12,3,13,4,5,2]],
    [1,[0.0366211,-1.80859,-1.1],[6,7,8,9,11,10]]
  ]],

![20200517234735_1](https://user-images.githubusercontent.com/57111907/82161148-93c88900-989a-11ea-924a-7e62705b0325.jpg)

![20200517234740_1](https://user-images.githubusercontent.com/57111907/82161135-81e6e600-989a-11ea-8675-74325e411cea.jpg)

![20200517234750_1](https://user-images.githubusercontent.com/57111907/82161158-ae9afd80-989a-11ea-8e6b-ba474c32fd45.jpg)

**Added**
Mk19 and M2 Variant of Soccom Mrap that were missing before
![20200524164254_1](https://user-images.githubusercontent.com/57111907/82757022-16db6900-9dde-11ea-8f98-cc1f044d5cfa.jpg)

**Comment by SonorousMeerkat** [comment]
If you have the numbers for proper placement, PR them. I thought i caught all of them like that.
