### ISSUE TITLE
Find and Fix Bugs in TIOW after unstable merge

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#1037]
Just for personal tracking.
_But you're welcome to do my job._

**Comment by Lazejun** [comment]
Mission.Sqm outdated ----> Units and slots used are anciently Old, PVP Slots dont count up in Numbers (#733)
Basicly 0 Control Markers
0 Factories/Resources
Description.ext is outdated #1030 
Whiteboard is not a Map
File Size is also a bit big.
![grafik](https://user-images.githubusercontent.com/57111907/82286163-5e589400-999d-11ea-85b5-007d4ce22f8a.png)
Custom Flag texture
Missing RoadDB, Missing Call for it aswell (InitVarCommon)
Templates creating the Large Ships to be out of Line of sight almost hidden in all the Fog on the Map. --------> not realy a point
No Civ Vehicle Template yet
