### ISSUE TITLE
[Suggestion] Adjust Date of Mission to provide bright Moonlight

### ISSUE THREAD

**Issue by 1337zorn** [official-antistasi-community/A3-Antistasi#1044]
*Version:* General

*Mods:* General

*Environment*: General

Adjust Date of Mission to provide bright Moonlight to encurage more night-time gameplay, even during the early stage of the campaign.

If the Scenario is sopposed to be in another year i advise to use debug console: 
utils 3 and figure out a sufficient date.

List provided by Lazejun:
```
Altis
        year=2035;
        month=6;
        day=10;
        hour=10;
        minute=0;
Anizay
        year=2035;
        month=6;
        day=10;
        hour=10;
        minute=0;
Chernarus
        year=2035;
        month=7;
        day=11;
        hour=10;
        minute=0;
Chernarus Winter //Full moon but few Daylight cause of Winter
        year=2035;
        month=1;
        day=10;
        hour=10;
        minute=0;
Kunduz
        year=2035;
        month=7;
        day=11;
        hour=10;
        minute=0;
Livonia
        year=2035;
        month=6;
        day=10;
        hour=10;
        minute=0;
Malden
        year=2035;
        month=6;
        day=10;
        hour=10;
        minute=0;
Stratis
        year=2035;
        month=6;
        day=10;
        hour=10;
        minute=0;
Tembelan
        year=2035;
        month=6;
        day=10;
        hour=10;
        minute=0;
Tanoa
        year=2035;
        minute=0;
        month=1;
        day=10;
        hour=10;

Virolathi
         year=2035;
        month=6;
        day=10;
        hour=10;
        minute=0;


Sahrani
         year=2035;
        month=6;
        day=10;
        hour=10;
        minute=0;
Takistan

        year=2035;
        month=6;
        day=10;
        hour=10;
        minute=0;
```

**Comment by CalebSerafin** [comment]
Maybe add a param switch to select from that list or use darkness my old friend.
Yes, I know the params are getting a bit cluttered.

**Comment by jaj22** [comment]
Intending to implement this as part of my initZones refactor, which is probably my next significant project after 2.2.2. Arguably important enough to hack in as a short-term thing.

Don't see a need for a parameter. I'm not indulging the (possibly imaginary) sadists who like Arma pitch-black. It's not even realistic: It literally renders every scenery pixel as 0,0,0.

**Comment by Bob-Murphy** [comment]
Adapted and implemented for the 12 maps we have.
