### ISSUE TITLE
Markers not overlapping nearby roads causes incorrect attack targeting

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1047]
*Version:* Unstable and older

*Mods:* Any, but map-specific

*Environment*: Any

***Issue:***
initZones adds bases to a `blackListDest` array if they have no "good" road within their area. This means some attack or mission types can't target them.

The southwestern airbase on Malden is an example of a marker that doesn't overlap its roads, and so may not be treated correctly. 

Either the problem markers should be identified and fixed, or the blacklist algorithm adjusted for more generosity.

**Comment by Bob-Murphy** [comment]
merged into unstable
