### ISSUE TITLE
[bug] Outpost truck requires nearby road.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#1051]
*Version:* unstable 23/05/2020.

*Mods:* None

*Environment*: SP, MP LAN, MP host, MP dedi.

***Issue:***
Outpost truck requires nearby road. This means bush outposts cannot get a truck.

Problem at: 
https://github.com/official-antistasi-community/A3-Antistasi/blob/789aa07a058fe4e2ce48d8582978c8471e619856/A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf#L253
---

**Comment by jaj22** [comment]
I imagine this is because in some cases (eg. Kavala Castle) it wouldn't make any sense to place a truck if that location was inaccessible for trucks. 

Given that findSpawnPosition doesn't depend on roads, that should be an obsolete restriction in this case. Antistasi's road-accessibility checks and usage need sanity-checking in general though.

**Comment by CalebSerafin** [comment]
Well outposts do not need to have a marker placed. So that should be a map issue.

**Comment by Bob-Murphy** [comment]
This is not about the trucks at the vehicle markers, that is about the truck which spawns "at the flag" itself independently of the veh-markers.
John, feel free to correct me if I'm wrong.

**Comment by CalebSerafin** [comment]
I haven't seen trucks spawn independently. They have all spawned on the vehicle marker, or not spawned at all (unless its part of a reinforcement ect.).

**Comment by jaj22** [comment]
Yeah, there's no distinction now as far as I can tell. Outpost/resource spawns a truck on a "Vehicle" spawnplace. Airbases spawn a ton of random stuff on "Vehicle" spawnplaces.

I haven't checked whether all these spawnplaces are hardcoded or there's a fallback algorithm.
