### ISSUE TITLE
Error found in fn_log

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1089]
This error popped up in the small first test I just did on 2.2.2.
`10:35:10 "942.344: [Antistasi] | INFO | fn_punishment_FF_addEH.sqf | Punishment Event Handlers Added"
10:35:10 "942.344: [Antistasi] | INFO | fn_initPetros | initPetros completed"
10:35:10 A null object passed as a target to RemoteExec(Call) 'a3a_fnc_punishment_ff'
10:35:10 Error in expression <er = param [3, !(hasInterface && _level > 1)];
private _filename = "fn_log";

i>
10:35:10   Error position: <> 1)];
private _filename = "fn_log";

i>
10:35:10   Error >: Type Array, expected Number,Not a Number
10:35:10 File functions\Utility\fn_log.sqf [A3A_fnc_log]..., line 17
10:35:10 Error in expression <er = param [3, !(hasInterface && _level > 1)];
private _filename = "fn_log";

i>
10:35:10   Error position: <> 1)];
private _filename = "fn_log";

i>
10:35:10   Error >: Type Array, expected Number,Not a Number
10:35:10 File functions\Utility\fn_log.sqf [A3A_fnc_log]..., line 17`

**Comment by CalebSerafin** [comment]
```
10:35:10 "942.344: [Antistasi] | INFO | fn_punishment_FF_addEH.sqf | Punishment Event Handlers Added"
10:35:10 "942.344: [Antistasi] | INFO | fn_initPetros | initPetros completed"
10:35:10 A null object passed as a target to RemoteExec(Call) 'a3a_fnc_punishment_ff'
```
This error caused by the EH sometimes passing nulls. Will fix by adding checks in EH.
```
10:35:10 Error in expression <er = param [3, !(hasInterface && _level > 1)];
private _filename = "fn_log";

i>
10:35:10 Error position: <> 1)];
private _filename = "fn_log";

i>
10:35:10 Error >: Type Array, expected Number,Not a Number
10:35:10 File functions\Utility\fn_log.sqf [A3A_fnc_log]..., line 17
10:35:10 Error in expression <er = param [3, !(hasInterface && _level > 1)];
private _filename = "fn_log";

i>
10:35:10 Error position: <> 1)];
private _filename = "fn_log";

i>
10:35:10 Error >: Type Array, expected Number,Not a Number
10:35:10 File functions\Utility\fn_log.sqf [A3A_fnc_log]..., line 17`
```
This I thought I fixed, however it might cascade from the above error.

**Comment by CalebSerafin** [comment]
https://github.com/official-antistasi-community/A3-Antistasi/blob/fd71e4bd15bc4fe3b04e59dc4216675dee950641/A3-Antistasi/functions/Punishment/fn_punishment_oceanGulag.sqf#L33

**Comment by CalebSerafin** [comment]
I'll check this next server test.
