### ISSUE TITLE
poor redability of missionRequest and unnecessary addition file with missionRequestAuto

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1102]
*Version:* 2.2.2

*Mods:* CBA, TFAR, ACE(no-medical)

*Environment*: SP, MP LAN, MP host, MP dedi.

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***
poor redability of missionRequest and unnecessary addition file with missionRequestAuto

**Comment by Bob-Murphy** [comment]
merged
