### ISSUE TITLE
Format adjustment for "call A3A_fnc_log" lines for unification

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1110]
Most of the calls are 1-liners but some others are still multi-liners.
Here are the cases:

- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/AI/fn_occupantInvaderUnitKilledEH.sqf#L50
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Base/fn_aggressionUpdateLoop.sqf#L40
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Base/fn_getVehiclePoolForAttacks.sqf#L316
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Base/fn_getVehiclePoolForAttacks.sqf#L351
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Base/fn_getVehiclePoolForQRFs.sqf#L301
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Base/fn_getVehiclePoolForQRFs.sqf#L336
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf#L153
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/CREATE/fn_CIVinit.sqf#L62
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf#L153
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/CREATE/fn_wavedCA.sqf#L84
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Garrison/fn_selectReinfUnits.sqf#L33
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Garrison/fn_shouldReinforce.sqf#L4
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Missions/fn_AS_Traitor.sqf#L154
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Missions/fn_LOG_Bank.sqf#L129
- https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Missions/fn_LOG_Supplies.sqf#L103

https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Intel/fn_placeIntel.sqf
-->line 14
-->line 24
-->line 44

https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Missions/fn_convoy.sqf
-->line 415
-->line 466
-->line 521
-->line 661
-->line 696

https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Base/fn_markerChange.sqf
-->line 108
-->line 139
-->line 169
-->line 187
-->line 213
-->line 236
-->line 259

https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Base/fn_rebelAttack.sqf
-->line 17
-->line 26
-->line 94
-->line 101
-->line 181
-->line 392
-->line 404

https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Base/fn_startBreachVehicle.sqf
-->line 248
-->line 269

Following should **NOT** be changed as they are too massive:
- fn_patrolCA.sqf line 222
- fn_logPerformance.sqf line 32

**Comment by Toakan** [comment]
@Bob-Murphy is this needed now with log change stuff from Hakon?

**Comment by killerswin2** [comment]
Log changes, this can be closed now
