### ISSUE TITLE
Malden Persistent Save

### ISSUE THREAD

**Issue by newboerg** [official-antistasi-community/A3-Antistasi#1114]
*Version:* 1.0.

*Mods:* CBA, RHS

*Environment*:   MP dedi.

*.rpt attatched?* NO

*have you edited the missionfile?*: No

***Issue:***

MALDEN Version refuses to load Persistent Save.
Altis Version Works like a charm with the same Dedicated server setup.

**Comment by Lazejun** [comment]
The System is the same for all Maps, there should not be a Map specific Issue.
Are you sure there are no User Errors?

**Comment by newboerg** [comment]
maybe some kind of build error for the workshop malden map?

**Comment by newboerg** [comment]
Its like there is no save at all. but i if check the savefile in notepad++ my garage is there

**Comment by Bob-Murphy** [comment]
You are the first person reporting this and the version is published since the second of february.
It is very unlikely that there is an error in the mission.
Try getting the 2.2.1 version of malden from our release page in GitHub, maybe that helps in your case.
Also, I guess you waited until the "save done" window popped up ingame?
https://github.com/official-antistasi-community/A3-Antistasi/releases/tag/2.2.1

**Comment by newboerg** [comment]
of course i did wait, worked on altis too,
i found a steam workshop comment of someone having the same issue with just the malden map though.
INTERESTING, I did a SHA256 on the Workshop file and the Github release and they are different

**Comment by Bob-Murphy** [comment]
The way how we updated the mission is by being in the Arma 3 Eden Editor, then load the mission and then use the build in tool to upload it. This might have changed something.
On GitHub is the directly packed PBO.
With the next update we will use a script which links directly to the steam workshop and not go through Eden. Maybe that get's rid of that difference.

**Comment by newboerg** [comment]
Seems like its Working witht he Github version!

**Comment by Bob-Murphy** [comment]
Good to hear.
I hope that won't be happening again with the new updating system.
Have fun playing!
