### ISSUE TITLE
[Suggestion] More Breaching Charges.

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1129]
Since Breaching Charges are bound to the Static Array in the Rebell Templates of the Modset they are fixed.

Expanding the list would be a general Quickfix/Extention of the Usuable Charges but in the Case of people using more Mods or Classnames changing for whatever reason thoes explosives wouldnt be usuable.

There is also the Problem of 3CB-BAF using a lot of Vanilla Charges on Units but those are not set in any of the Arrays.

--------> Sorting by Explosive Power would be an easy way to ensure even undefined Charges would work but it might get funky when it allows Mines, even tho you could argue with Mines working pretty well as Improvised Explosives.

**Comment by jaj22** [comment]
The actual charges seemed to have reasonable "hit" values for explosive power. If using mines is acceptable then it shouldn't be difficult to implement an automatic selection system to replace the static arrays. Might have a crack at that.

**Comment by Bob-Murphy** [comment]
Talk to wurzel about the system, he made it.

**Comment by Lazejun** [comment]
Lets hope the "Hit" Value on Unsungs Punji Sticks is not that High, cause that would be a very Funny by Product, if we are going that way

**Comment by Lazejun** [comment]
Done manually in Rebell Templates with Template Rework, can be reopened if we go for a Autodetection solution
