### ISSUE TITLE
Helicopter response spawns more than necessary.

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#114]
Heli attack can spawn up to 6 at once, why is this and can we stop it.

**Comment by Bob-Murphy** [comment]
In my personal opinion it makes sense that not only 1 or 2 helis are send.
As we have plans to rework the QRF system (after we talked about it properly) it would be a small part of that larger task.

**Comment by Bob-Murphy** [comment]
@wurzel0701 
Is that covered by your stuff?
If so please give correct tag, milestone and close.

**Comment by wurzel0701** [comment]
Can do, will be tweaked in 2.4

**Comment by wurzel0701** [comment]
Amount of units is now based on aggression values, closing this issue
