### ISSUE TITLE
Rename fn_prestige.sqf - current name is unclear

### ISSUE THREAD

**Issue by shoter** [official-antistasi-community/A3-Antistasi#1141]
*Version:* all?

***Issue:***

This function is adding aggresion to factions. The last name I have for it is prestige. Something like fn_addAggo/fn_addAggression would sound much better.

**Comment by wurzel0701** [comment]
The input on this file needs to be adjusted completely, I will do this and take the name suggestion from here.

@shoter I will close your PR (once my own is up) as I need a more in depth change in the system to make more sense

**Comment by wurzel0701** [comment]
#1145 closed, as #1788 will take care of this and a more in depth change of the whole file
