### ISSUE TITLE
When mission is saved with high aggression then aggression is displayed as low at the start.

### ISSUE THREAD

**Issue by shoter** [official-antistasi-community/A3-Antistasi#1146]
*Version:* Current unstable

*Mods:* 
![obraz](https://user-images.githubusercontent.com/3819892/85204296-d22aeb00-b313-11ea-872d-6f0d3379e900.png)

*Environment*: MP + LAN

*have you edited the missionfile?*: No

***Issue:***

When starting a mission the current value of Aggression (at least for USA) is not taken into account. aggressionOccupants has value of 100 from the savegame and yet aggression is being displayed as `Low`.

This causes very quick jump from Low to High/Very High/Extreme on first update of UI Aggression.

**Comment by wurzel0701** [comment]
Thanks for the report, forgot to add the update HUD method in the loading routines.

Will be fixed shortly.
