### ISSUE TITLE
deleteTask can be dubble spawned

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1148]
*Version:* 2.2.1

*Mods:* CBA, TFAR, ACE(no-medical)

*Environment*: SP, MP LAN, MP host, MP dedi.

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***

This function is spawned with the intent of a long sleep which if its spawned again for any reasons it will delete the task twice, witch can cause some unwanted behavior, a block for non-existing task should also stop it from running trough so that when a mission actually ends it have another one in progress to delete the task...

**Comment by jaj22** [comment]
I'm not sure how this is possible given that Antistasi blocks creation of missions when there's already a mission of that type in the task list. See the BIS_fnc_taskExists calls in missionRequest and missionRequestAUTO.

Fairly annoying for debugging that you can't force-delete a task without breaking stuff, but I think it does hang together as written.

**Comment by HakonRydland** [comment]
main point is for testing, or for admin "bug fixing" mid game if something breaks etc. wont hurt to have deleteTask maintain a list of scriptHandlers of the corresponding deletion currently being done, and also allow for force termination of said spawn to be replaced by the new one, if that makes sense.

**Comment by HakonRydland** [comment]
theres also possible to bypass the taskExists check if the mission is requested multiple times in a short time frame, as it takes a few milliseconds before the task is actually created, this is mostly possible due to the fact mission request is no longer locked to commander only
