### ISSUE TITLE
Diving Gear doesn't appear

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1151]
According to a Player on the Test server during the Tests Diving Gear has not apeared in Seaport boxes anymore.

**Comment by jaj22** [comment]
Code looks correct. If you're unlucky it just rolls zero. Will check though.

**Comment by Lazejun** [comment]
I am also looking right now :D

**Comment by jaj22** [comment]
Got bunch in the first one I checked.

**Comment by Lazejun** [comment]
Weirdly enough on Altis it worked perfectly fine, on Stratis it didnt want to apply, adding a Sleep did make them spawn, but there is a lot more weird nonsense to the diveGear.

fn_createAISite adding random amount of Independent Rebreathers and Diving Googles,
fn_createAIOutpost also adding Rebreaters and Googles while it does also directly spawn diveGear and all of it could be taken care of with diveGear.

**Comment by Lazejun** [comment]
So now looking at Chernarus Summer just to be sure, without any changes.
First Crate 2 AAF Rebreathers 3 AAF Googles
Second Crate 4 AAF Rebreathers
Third Crate 1 Rebreather 4 Googles
-----------> the Random funnies that add Random up to 5 only applying, diveGear itself not since no Divesuits.
