### ISSUE TITLE
[Feature Request]: Enable IFA (Not Yet)

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1157]
Looking into it and at the Changelog of V40 they added a lot back in but some is still missing.

Editor

    Fixed: IPgate vehicles (SdKfz222, SdKfz234_X, AustinK5, Crusader Mk3, Crusader Mk1AA, Ju52) and groups are now hidden.

-------> They hide the Missing Vehicles in Editor now to prevent people from accidently using them.

* LIB_SdKfz234 (series)
* LIB_SdKfz222
* LIB_AustinK5 (series)
* LIB_JU52
* LIB_Crusader_Mk3
* LIB_Crusader_Mk1AA

Missing Vehicle in Wehrmacht Template:
vehNATOAPC = ["LIB_SdKfz234_4","LIB_SdKfz234_3","LIB_SdKfz234_2"]
vehNATOLightArmed = ["LIB_SdKfz222"];
vehNATOTransportPlanes = ["LIB_Ju52","LIB_Ju52","LIB_Ju52","LIB_Ju52"];
//Heli
vehNATOPatrolHeli = "LIB_Ju52";
![20200621140512_1](https://user-images.githubusercontent.com/57111907/85224117-41621700-b3c8-11ea-9397-89bcabfae974.jpg)

All of the Removed Equipment written out:
"LIB_32Rnd_9x19_Sten",
"LIB_30Rnd_770x56",
"LIB_20Rnd_762x63",
"LIB_1Rnd_89m_PIAT",
"LIB_1Rnd_89m_G_PIAT",
"LIB_ACC_P1903_Bayo",
"LIB_ACC_No4_Mk2_Bayo",
"LIB_M1918A2_BAR_Bipod",
"LIB_Sten_Mk2",
"LIB_Sten_Mk5",
"LIB_LeeEnfield_No4",
"LIB_LeeEnfield_No4_Scoped",
"LIB_LeeEnfield_No1",
"LIB_M1918A2_BAR",
"LIB_Bren_Mk2",
"LIB_PIAT",
"LIB_PIAT_Rifle",
"LIB_FG42"      (Maybe someone just forgot the G in that list)

The Equipment is completly back, only one changed a Classname the FG42 is now "LIB_FG42G"
Which is not that Important since we dont directly use Equipment Classnames (There are no WW2 Loadouts anyway)

----------> Maybe V41?

**Comment by Tiny-DM** [comment]
IFA has been integrated fully into Antistasi at this time. Closing.
