### ISSUE TITLE
Some functions place mortars inside or too close to buildings 

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1164]
*Version:* Unstable (not new)

*Mods:* Any

*Environment*: Any

***Issue:***
Mortar-placement functions will sometimes place mortars either inside or too close to buildings. Ideally the placement routines should make some attempt to place them in areas that are likely to have lines of fire.

**Comment by wurzel0701** [comment]
All non airport or non support mortars have been removed, both are placed on specifically designed positions
