### ISSUE TITLE
[Bug]: Tent Hangar Bad spawn

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1168]
During checking for Bad Spawns "Land_TentHangar_V1_F" randomly Explodes when the CSAT AAPlane spawns in it.

This doesent happen everytime but the only one i saw explode was the AA Variant, the Cas Variant spawned safe in it.

The Ground does impact it aswell but it happens on Straight surfaces aswell.

**Comment by MeltedPixel** [comment]
Closing as per @Bob-Murphy
