### ISSUE TITLE
Surrendered squad leads are not passing squad lead

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#1173]
When the leader of a squad surrenders, he does not passes squad lead to an active unit, effectively making the group immobile and a waste of resources.

When the squad leader surrenders, he should pass it to the first still active unit in his group.

**Comment by tpaclatee** [comment]
What would adding `_unit doFollow (leader _unit);` or something similar to "fn_surrenderAction" do?
