### ISSUE TITLE
Update the Github description

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#1174]
The displayed description is not only outdated, but isnt showing the most important features/ displays them badly.

Rewrite it with the new systems and improvement and the most important features Antistasi can deliver.

In my opinion, these are:

- Capture an island in a war against one or two enemy factions, which might fight each other

- Persistant war in all aspects, destruction stays the same way as your vehicles and garrisons

- Complete up to 18 (now more with Hakons mission?) missions, which randomly appear and can change to tied of the battle

- Dynamic reactions against your actions, play aggressive to recieve aggressive responces or play silently to avoid unwanted attention

- Play on alot of different maps to your liking. Hills, island, forest, you can play wherever you want

- Advanced AI system, the enemy and your friends, will heal wounded or downed units, cover themselves and use multiple other tactics to win against their foes

- Can be used with saved from the original 1.4 version of Barbolani, the original author

- Supports up to 3 Headless Clients and multiple modsets, including RHS, 3CB, TFAR and ACE

**Comment by Bob-Murphy** [comment]
done
