### ISSUE TITLE
[question][suggestion] CBA Integration

### ISSUE THREAD

**Issue by RZSenfo** [official-antistasi-community/A3-Antistasi#1179]
Idk if there ever was a discussion about this (I havent found anything in the issues or the discord):
A dependency on CBA could help with increasing the code quality and the performance dramatically in later iterations.

A quick example are the custom event handlers, which could significantly reduce the "arma-ness" of the revive system.
Another thing that could help with performance is the CBA "scheduler". The mission is full of spawn/sleep which is a known performance killer in ArmA. CBA provides waitUntil and other solutions for that matter.

Ofc such things could be implement in the mission itself to get rid of any dependency, but since ArmA3 missions arent really "start the game and join a random server" and Antistasi is more of a long term mission, I think it could pay off in the long run (given the fact that a lot of antistasi server host their mission with rhs or ace anyways)

(Sorry if this is a duplicate)

**Comment by SonorousMeerkat** [comment]
Our number 1 concern is avoiding dependencies as we have plenty of players that don't run any mods when they play. It also helps people start playing that have minimal experience with arma.
