### ISSUE TITLE
[Bug]: Params.hpp Crate Parameters Issue

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1180]
crateWepTypeMax doesent Display
![grafik](https://user-images.githubusercontent.com/57111907/85920875-d0af7480-b877-11ea-9463-793ade96039d.png)

**Shouldn't a lot of the Parameters Match Text and Value?**

Since a Value like 0 but the Text being 1 sounds sort of Missleading.

as a good example: Oh Helmets are 1 Per Crate thats nice, oh wait its actually 0.

------> Current Crate Parameters so you dont have to look in the file :D

     class crateWepTypeMax
     {
          title = "Maximum Weapon Types in Crates";
          values[] = {0,2,4,6,8,12,16};
          texts[] = {"1","3","5","7","9","13","17"};
          default = 9;
     };
     class crateWepNumMax
     {
          title = "Maximum Weapon Quantity in Crates";
          values[] = {0,1,3,5,8,10,15};
          texts[] = {"None","1","3","5","8","10","15"};
          default = 8;
     };
     class Spacer1
     {
          title = "";
          values[] = {""};
          texts[] = {""};
          default = "";
     };
     class crateItemTypeMax
     {
          title = "Maximum Item Types in Crates";
          values[] = {0,2,4,9};
          texts[] = {"1","3","5","10"};
          default = 4;
     };
     class crateItemNumMax
     {
          title = "Maximum Item Quantity in Crates";
          values[] = {0,1,3,5,10,15};
          texts[] = {"None","1","3","5","10","15"};
          default = 5;
     };
     class Spacer2
     {
          title = "";
          values[] = {""};
          texts[] = {""};
          default = "";
     };
     class crateAmmoTypeMax
     {
          title = "Maximum Ammo Types in Crates";
          values[] = {0,2,4,6,9,14,19};
          texts[] = {"1","3","5","7","10","15","20"};
          default = 6;
     };
     class crateAmmoNumMax
     {
          title = "Maximum Ammo Quantity in Crates";
          values[] = {0,1,3,5,10,15,20,25,30};
          texts[] = {"None","1","3","5","10","15","20","25","30"};
          default = 20;
     };
     class Spacer3
     {
          title = "";
          values[] = {""};
          texts[] = {""};
          default = "";
     };
     class crateExplosiveTypeMax
     {
          title = "Maximum Explosive Types in Crates";
          values[] = {0,2,4,9};
          texts[] = {"1","3","5","10"};
          default = 2;
     };
     class crateExplosiveNumMax
     {
          title = "Maximum Explosive Quantity in Crates";
          values[] = {0,1,3,5,10,15};
          texts[] = {"None","1","3","5","10","15"};
          default = 5;
     };
     class Spacer4
     {
          title = "";
          values[] = {""};
          texts[] = {""};
          default = "";
     };
     class crateAttachmentTypeMax
     {
          title = "Maximum Attachment Types in Crates";
          values[] = {0,2,4,6,9,12,15,19};
          texts[] = {"1","3","5","7","10","13","16","20"};
          default = 6;
     };
     class crateAttachmentNumMax
     {
          title = "Maximum Attachment Quantity in Crates";
          values[] = {0,1,3,5,7,10,15,20,30};
          texts[] = {"None","1","3","5","7","10","15","20","30"};
          default = 15;
     };

**Comment by jaj22** [comment]
I think there's a good argument for stripping all of these in favour of a general quantity-of-stuff option. It's a lot of fine detail cluttering the parameter list when we have no controls at all for far more important balance parameters.

**Comment by HakonRydland** [comment]
a general "Quantity in crates: Low, Medium, High" would be nice

**Comment by Bob-Murphy** [comment]
Shameless self ping so I remember that one @Bob-Murphy

**Comment by MeltedPixel** [comment]
Closing as per @Bob-Murphy.
