### ISSUE TITLE
Rebell Uniforms - Starting Arsenal - Side Issue.

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1191]
Currently we are using Vanilla Bluefor Uniforms on almost all Rebell Templates (exept IFA/3CB).

---------> Blue Uniforms are not able to be picked up when droped.
In fn_equipmentsort they are defined and the Green Rebell Uniforms are not added due to the Scope being 1.

{
	private _originUnit = getText (configfile >> "CfgWeapons" >> _x >> "ItemInfo" >> "uniformClass");
	private _uniformFaction = getText (configfile >> "CfgVehicles" >> _originUnit >> "faction");
	switch (_uniformFaction) do {
		//RHS
		case "rhsgref_faction_nationalist": {if ((!has3CB) and nameTeamPlayer isEqualTo "NAPA") then {allRebelUniforms pushBack _x};};
		case "rhsgref_faction_cdf_ng_b": {if ((!has3CB) and teamPlayer isEqualTo west) then {allRebelUniforms pushBack _x};};
		//3CB
		//case "IND_F": {if ((has3CB) and nameTeamPlayer isEqualTo "TTF") then {allRebelUniforms pushBack _x};};
		//IFA
		case "LIB_GUER": {if (hasIFA) then {allRebelUniforms pushBack _x};};
		//Vanilla
		case "IND_C_F";
		//BLUFOR used because O/I Gueriilla uniforms 'scope' = 1
		case "BLU_G_F": {allRebelUniforms pushBack _x};
	};

--------> I messed around with swapping it to Green Rebells ones but the Uniforms are not added so it might have to be added manually via Templates, directly by Classname.

**Comment by jaj22** [comment]
Yeah, the earlier filters in configSort remove anything that's not scope 2. Those greenfor rebel uniforms work fine in the arsenal but you'd need to add them manually in equipmentSort.

**Comment by Lazejun** [comment]
Personally I would like to allways have those Uniform but WW2 is a Special case, aswell as 3CB since Meers project and his Decision if he wants the Vanilla Rebells or not :D

**Comment by CalebSerafin** [comment]
We can't have always on defualt. We shouldt be able to switch everything off when using some other mod sets. Basically starting from an empty arsenal if needed.
