### ISSUE TITLE
[Change Request]: Allow Rebel AI to pilot heli

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#1196]
*Version:* 2.3

***Issue:***

Although AI piloting helicopters is a bit scandalous, some humans see a need for it. ie: A human gunning or something while AI fly; Retrieving helicopters from far away locations on servers where players are limited.

The section that needs changing: https://github.com/official-antistasi-community/A3-Antistasi/blob/1787bdcd6a8d13c4f2ce376bd91b9ed162ea775c/A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf#L98

**Comment by MeltedPixel** [comment]
Closing as per @Bob-Murphy, Not currently planned. Will re-open in the future if anything changes.
