### ISSUE TITLE
Player saves on disconnect losing data

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1198]
*Version:* Unstable, probably older

*Mods:* ACE + RHS, not sure if important

*Environment*: MP dedi + HC

***Issue:***
No replication case yet, but there are enough community-server incidents to confirm that there's a problem. Disconnecting (using "abort") often causes players to be saved with zero money and no loadout, as if the player unit changed during the disconnect/save process. Not yet sure how this happens, but it's possible that there's no reasonable workaround and the player save concept needs a general rethink.

**Comment by Mirv** [comment]
Did the server receive a disconnect message from the client in these situations?

Could easily envision this if the client just ghosts.

Then server is left running timeout protocol.

Before timeout protocol is finished - clean up protocols have removed that variable or wrote over etc.

**Comment by jaj22** [comment]
As far as I could tell through log browsing, onPlayerDisconnect was launching on time and savePlayer wasn't throwing any errors, implying that the player still had a valid unit. Note that if savePlayer was never called, you'd simply revert to the previous save, so that wouldn't give you zero money. Hence the conclusion that the player must have been moved to the wrong unit before disconnection.

It's possible that this was a load bug rather than a save bug, although I don't see a way that could result in zero money. #1232 should tell anyway, as it adds money/score/rank/garage-count logs on both player load and save.
