### ISSUE TITLE
fn_handleDamage.sqf tracking not being logged reliable

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1204]
We had a FF report we had to handle and regarding FF and I got suspicious that the logging is not properly working.
I then joined the test server and shot a few guys at HQ in the face whilst looking at the log.
What I can see is stuff like
` 4:35:37 "43791.9: [Antistasi] | INFO | fn_punishment_FF.sqf | ADMIN, Logged | Player: Bob Murphy [76561197981991967], _timeAdded: 60, _offenceAdded: 0.4"`
But what I do not see is 
`4:35:37 "RandomCunt was injured by Bob Murphy (UID: 9999999999999999), 3.057m from HQ"`

If you look at the logs I will post in the rpt channel on discord. The first case is at line 60242.

**Comment by CalebSerafin** [comment]
That was a design decision.
It only logs the collateral of its confirmed FF (warning or punish). But I can move the function from `punishment` to `punishment_FF` and log if it is an exemption(Admin, CAS, collision, ect.)

**Comment by CalebSerafin** [comment]
```
4:35:37 "RandomCunt was injured by Bob Murphy (UID: 9999999999999999), 3.057m from HQ"```
This is not my function, this is triggered when someone is hurt near hq. <br/>

I think @jaj22 implemented this.

**Comment by Bob-Murphy** [comment]
Oh!
I thought it was part of your system!
Never looked into the code regarding that until now. And indeed, it's in fn_handleDamage.sqf.
It was implemented over 2 years ago by Barbolani, touched by you  month ago and then by jaj.
Nevertheless, could you please look at it?
