### ISSUE TITLE
Introduce personal garage limiter with a parameter

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1210]
As discussed at the meeting we want to introduce a parameter for the amount of vehicles storable in the personal garage.
The faction garage has already been adjusted from tierWar*3 to tierWar*5.

File to work in: functions/Garage/fn_addToPersonalGarage.sqf

**Comment by HakonRydland** [comment]
param options: 
value: 0, 2, 10
Text: "Disabled", "2", "10"
default: 2

**Comment by jaj22** [comment]
I'd add at least a 5 into that array, and maybe a 3. 2->10 is a jump from painfully small to loads.
