### ISSUE TITLE
Overhaul Issue Template

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1211]
As discussed at the meeting please complete following tasks
- @jaj22 provide a list of bulletpoints of what information is required
- @SonorousMeerkat once John has supplied the list, change it and write it in an appropriate way.

**Comment by SonorousMeerkat** [comment]
Still waiting on this @jaj22

**Comment by jaj22** [comment]
Wait, this is a 2.3? Jesus.

**Comment by SonorousMeerkat** [comment]
this was a asap iirc

It isn't exactly a code thing...
