### ISSUE TITLE
Separate AI difficulty as well as mission difficulty into different parameters

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1212]
See meeting point 10 from the 4th July 2020.

**Comment by CalebSerafin** [comment]
### Meeting Notes 04-07-2020

> 10) Mission difficulty as well as AI difficulty will be seperated into different parameters --> Done by Wurzel as he is working on related stuff

**Comment by jaj22** [comment]
Done in attack/support rework.
