### ISSUE TITLE
Resolve the probable issue regarding the small patrols spawning in friendly AI

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1213]
As discussed at the meeting yesterday the might be the case that the small patrols around cities spawn in friendly AI at near positions (and keep them spawned in).
This can lead to a large amount of unnecessary AI loaded on the map and therefore impacting the overall performance.
Please look into it and make sure that the small patrols are not spawners.

**Comment by jaj22** [comment]
Ok, stuff that spawns and maybe shouldn't:

1. Enemy city patrols. Airport/outpost/factory/resource patrols do not.
2. Enemy roadblocks.
3. Enemy vehicle road patrols.
4. Airstrikes. While it might be helpful if your outposts shot them down, they spawn too slowly to do so, so it's a waste of spawning in practice.

Rebel garrisons do not spawn, even if HC squads are added to them, so the specified case shouldn't be possible without a player or HC squad somewhere nearby. Despawn distance for enemy garrisons is quite long though, typically 1.3km.

Dead units shouldn't spawn (even if Zeus-killed), with the nasty exception where you remote-control an HC squad and then get some of them killed. Locality issues with the killed EH.

**Comment by wurzel0701** [comment]
The list looks correct, I am not sure about rebel garrisons, do they really dont spawn in any other units?

In the end we can reduce spawner ability to players and rebel squad leaders of rebel AI squads, but that might not be needed in the near future

**Comment by jaj22** [comment]
From wavedCA testing I'd definitely add enemy AA & ground attack planes in general. They cover a large area and spam spawns/despawns, without any actual engagement because they're too fast.
