### ISSUE TITLE
Land Navigation Overhaul

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1224]
This issue contains multiple tasks which are all related to waypoints, navigation on roads and the systems behind it.
We currently have multiple systems which are determening paths and such for road traffic. These systems should get unified and enhanced if needed.
Systems which we should get rid of:
- fn_WPcreate
- roadsDB-system

System we should utilize to effectively replace the systems above and improve/enhance if needed:
- navGrid-system

**Comment by wurzel0701** [comment]
This will not be changed until Arma 3 v1.99.146404 is released (or accessable) as it needs a new feature from the 
nearestTerrainObject https://community.bistudio.com/wiki/nearestTerrainObjects function, which can detect streets by then
(if you believe the wiki)

**Comment by CalebSerafin** [comment]
@Bob-Murphy I assume this is resolved? from https://github.com/official-antistasi-community/A3-Antistasi/pull/1697 and https://github.com/official-antistasi-community/A3-Antistasi/pull/1900

**Comment by Bob-Murphy** [comment]
fixed and merged
