### ISSUE TITLE
QRFs can lock out other QRFs from being sent - permanently

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#1226]
It's theoretically possible for a QRF script crash to prevent QRFs from being sent, due to the previous QRF not being removed from `smallCAmrk` and `smallCApos`. See #1200 for more information.

We should change this system to at least minimise the possibility of it happening, or ideally prevent it entirely.

**Comment by wurzel0701** [comment]
That system is gone completely with the new support rework
