### ISSUE TITLE
Chernarus seaSpawn markers missing.

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1233]
Cherno summer and winter both have 0 seaSpawn markers, not even seaports have these markers so there is not even a boat of the AI at seaports.

seaSpawn markers if not in a seaport are civilian boat spawns and are **now** needed due to the **salvage mission** needing a boat.

Also Skalisty Island having a Radiotower gives Players a reason to go there which would be easier if they can get boats.

-------------> There is no Range Issue and Boat placement via Buy/Garage works pretty well since recent changes to it.
But Free boats would be nice.

**Comment by Bob-Murphy** [comment]
Will do.
