### ISSUE TITLE
3CB buyable civ Hilux is "not a civ vehicle"

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1237]
As already told verbally the Hulix which can be bought in the 3CB modset could not be used for going undercover.
I don't know if it only was happening in my case (edgecase) or in general.
This happened with the unstable build as of commit 6769885b66238d25a01b2e4be35432f73f0a135c on the 11th July on the test server.

**Comment by Lazejun** [comment]
Cause Civ Template uses:
All Takistani Civilian Vehicles
civVehCommonData = [
	"UK3CB_CHC_C_Ikarus", 0					// bus, dangerously large
	,"UK3CB_TKC_C_Datsun_Civ_Closed", 0.5
	,"UK3CB_TKC_C_Datsun_Civ_Open", 1.0			// cargo capable
	,"UK3CB_TKC_C_Hatchback", 0.5
	,"UK3CB_TKC_C_Hilux_Civ_Closed", 0.5
	,"UK3CB_TKC_C_Hilux_Civ_Open", 1.0			// cargo capable
	,"UK3CB_TKC_C_Lada", 0.5
	,"UK3CB_TKC_C_Lada_Taxi", 0.5
	,"UK3CB_TKC_C_LR_Closed", 0.5		// land rovers
	,"UK3CB_TKC_C_LR_Open", 0.5
	,"UK3CB_TKC_C_Sedan", 0.5
	,"UK3CB_TKC_C_Skoda", 0.5
	,"UK3CB_TKC_C_S1203", 0.5
	,"UK3CB_TKC_C_UAZ_Closed", 0.5
	,"UK3CB_TKC_C_UAZ_Open", 0.5
	,"UK3CB_TKC_C_Gaz24", 0.5
	,"UK3CB_TKC_C_Golf", 0.5

**Comment by jaj22** [comment]
My bad. Should have added civCar and civTruck to the flat arrays (arrayCivVeh, undercoverVehicles). Gonna re-check the logic there because I just spotted something else weird in the grep.

**Comment by SonorousMeerkat** [comment]
To confirm, this is your mistake @jaj22?

**Comment by jaj22** [comment]
Well, logically we'd use the same civ cars in the rebel template as the civ template, but making template-construction easier and less prone to undocumented screwups is probably a good thing, and in this case it's a trivial change.

Related problem: The box van used for the bank job also won't count as civilian unless I include it specifically. This one should really be templated, but it isn't. Will fudge it in temporarily.
