### ISSUE TITLE
Radio issue - Picked up radios by enemies are converting to the 2km range 154 radios and not to the 5km 148 radios

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1238]
This happened with the unstable build as of commit 6769885b66238d25a01b2e4be35432f73f0a135c on the 11th July on the test server.
Never was observed before, no clue what could be the source of that one.
Certainly needs some investigation.

**Comment by Lazejun** [comment]
A3-Antistasi/cba_settings.sqf
force TF_give_personal_radio_to_regular_soldier = false; --------> force TF_give_personal_radio_to_regular_soldier = True;

TF_give_personal_radio_to_regular_soldier

Enables distribution of commander radios to squadmates.

-------> 148Jems / ANPRC 152 are "Commander Radios"
