### ISSUE TITLE
[Bug] [SP] ACE3 No Respawn

### ISSUE THREAD

**Issue by Sentii** [official-antistasi-community/A3-Antistasi#124]
*Version:* 1.4c2.0.

*Mods:* CBA, , ACE3(with medical and RHS compats), RHSUSAF, RHSAFRF, RHSGREF, JSRS, TRYK, MLO, SMA, Enhanced Movement, other small ones

*Environment*: SP.

*.rpt attatched?* Yes
[Arma3_x64_2019-08-14_04-22-34.txt](https://github.com/official-antistasi-community/A3-Antistasi-1.4/files/3500745/Arma3_x64_2019-08-14_04-22-34.txt)

*have you edited the missionfile?*: Yes (added some workshop cars as civ in initVar) 

***Issue: Using ACE while in SP, when you die, you get a death screen with "Restart", "Team Switch", and "End" instead of respawning back at HQ. Restarting reverts to last persistent save***

Edit: Being told ACE no medical would fix it but is there a way I can keep medical(It's the whole reason I use ACE. Self-med)

**Comment by Toakan** [comment]
Out of the RPT: 
` 4:29:03 "BIS_fnc_log: [BIS_fnc_selectRespawnTemplate] onPlayerKilled template 'None' executed from function 'BIS_fnc_respawnNone'"`

Looks like it's not assigning respawns correctly.

**Comment by Toakan** [comment]
Upstream bug - https://github.com/A3Antistasi/antistasi-1.x/issues/284

**Comment by SonorousMeerkat** [comment]
Respawns have always been fucked in SP. Best to host a LAN  game to play it SP as it makes it much more reliable

**Comment by Bob-Murphy** [comment]
Singleplayer will be deactivated and integrated into multiplayer - therefore no fix
