### ISSUE TITLE
A collision punished someone.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#1244]
Version: 2.3

https://cdn.discordapp.com/attachments/647694189236322305/731880047538995220/unknown.png

Probably a bug with either Hit/Killed EH not reacting to collision and firing as if it was a shot.

```log
 9:10:46 "38823.5: [Antistasi] | INFO | fn_punishment.sqf | WARNING | Player: Stijn-oo [1234], _timeAdded: 60, _timeTotal: 60, _offenceAdded: 0.4, _overhead: 0.4, _offenceTotal: 0.12"
 9:10:52 "38829.5: [Antistasi] | INFO | fn_punishment.sqf | WARNING | Player: Stijn-oo [1234], _timeAdded: 60, _timeTotal: 119.834, _offenceAdded: 0.795685, _overhead: 0.4, _offenceTotal: 0.24"
 9:10:57 "38834.9: [Antistasi] | INFO | fn_punishment.sqf | VICTIM | Found Collateral: masai [0987]"
 9:10:57 "38834.9: [Antistasi] | INFO | fn_punishment.sqf | GUILTY | Player: Stijn-oo [1234], _timeAdded: 60, _timeTotal: 179.557, _offenceAdded: 1.19194, _overhead: 0.4, _offenceTotal: 0.36"
```

**Comment by Bob-Murphy** [comment]
Can confirm. I drove over multiple people yesterday but was luckily logged in as admin so I did not got punished.

**Comment by CalebSerafin** [comment]
It could be that when a collision occurs, the unit is passed in `source` *(Documented)* and `unit` *(Undocumented)* at the same time. Punishment_FF Collision Check only checks if the `unit` is a player.
https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#Hit
https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#Killed

Or even more fun: The EH have their own secret strategy!
