### ISSUE TITLE
Possible issue with players losing ACE menus

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1252]
*Version:* Unstable

*Mods:* ACE, 3CB (test server)

*Environment*: MP dedi + HC

***Issue:***
As this has been reported twice recently and not before, this is likely to have been caused by the ACE group join/leave removal patch (#1216).

Interesting question is how. My guess is that as the menu compile functions are slow, and ACE will call them itself (eg for the player's own unit class), two compile calls can end up modifying the ACE menus in the same frame, one in scheduled and one in unscheduled code. We should probably be running all of the menu-modifications as remoteExecCall to prevent this.

Kinda short on testing time though.

**Comment by killerswin2** [comment]
@jaj22 Been a year haven't heard of this happening in a while. Want to close?

**Comment by killerswin2** [comment]
No repeats or confirmations that this has again, closing. If persistence reopen.
