### ISSUE TITLE
Unified "Troops sent/Attack sent" messages in log lines

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1254]
### This is not a task which has to be completed now, but keep it in mind when you work on related code.

Please change your messages to confirm that a reinforcement/attack/airstrike **got send** with following wording.
This makes it easier to quickly be able to see which reinforments really got send.
Please **ONLY** adapt the final log line which is confirming the action, not such intermediate lines like "QRF requested. Target:%1, Source:%2, Type:%3, IsSuper:%4".

Here some examples. You see the pattern.
"Spawn performed: Land QRF sent on %1, type %2, veh count %3, troop count %4"
"Spawn performed: Air QRF sent on %1, type %2, veh count %3, troop count %4"
"Spawn performed: Airstrike of type %1 sent to %2"

Please note that the part which should be added is the "Spawn performed: " at the start. All information behind that of course is depending on what happened in the script.

**Comment by jaj22** [comment]
Done as far as I know.
