### ISSUE TITLE
Revive "Tank Arrays"

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1255]
Many moons ago someone made a PR for converting the Tank entry in the templates to accept arrays.

Some changes were requested but never done and it was forgotten. Can someone revive this and perhaps expand it to all vehicle vars so we can put more variety into things. #93 and #96 were the PRs associated with this, so most of the detail can be found there.

**Comment by Bob-Murphy** [comment]
will be done in new template system
