### ISSUE TITLE
[Change Request] - [Outdated] HUD Improvements

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#126]
Currently, the HUD consists of the top statistics bar and arsenal and income notifications

However, the statistics bar can be difficulty to read is relatively obtrusive.

This could be improved into a more elegant, easier to view user interface.

**Comment by PoweredByPot** [comment]
statistics.sqf
arsenalmanage.sqf
resourcecheck.sqf

**Comment by Bob-Murphy** [comment]
@Spoffy @PoweredByPot 
Update?

**Comment by Spoffy** [comment]
This is purely a future work exercise. It's possible it should be on the trello.

**Comment by PoweredByPot** [comment]
doom is doing UI menu things, lets make this go away for now until we see what he does.

**Comment by PoweredByPot** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI changes and reduction of player info](https://trello.com/c/gpXmW4oU/72-ui-changes-and-reduction-of-player-info)

**Comment by PoweredByPot** [comment]
bob is suppressing my free speech, but there is a card on Trello for this issue and the relevant discussion

**Comment by Bob-Murphy** [comment]
I'm still German :D

**Comment by Bob-Murphy** [comment]
@doommetal 
Please take this under your wing and adapt it in your second or third run
