### ISSUE TITLE
Using deleteVehicle on dead vehicle crew creates ghost objects

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1260]
*Version:* Unstable

*Mods:* Probably any, tested on vanilla

*Environment*: Any

***Issue:***
See https://community.bistudio.com/wiki/deleteVehicle. I had a couple dozen immovable ghost objects in Zeus after a wavedCA test. Both postmortem and the garbage cleaner should ideally handle the dead vehicle crew case correctly.

I'm not sure what happens if you delete the vehicle before the crew.

**Comment by jaj22** [comment]
Possibly fixed in Arma's 2.00 patch.

**Comment by Lazejun** [comment]
Can confirm, Ghost bodies get deleted after Garbage Clean

**Comment by CalebSerafin** [comment]
@Bohemia Interactive good fix 👍
