### ISSUE TITLE
Integrate Ivory Car Pack (civ cars)

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1263]
This pack would allow for a large amount of variety in the civilian vehicles in the game. 

Would also be a place to try making additive civ templates, i.e. do not replace existing entries, while keeping loading separate.

**Comment by SonorousMeerkat** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1888644057

**Comment by Bob-Murphy** [comment]
done
