### ISSUE TITLE
Remove obsolete active$RHSMod$ flags from code. 

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1270]
These calls are 64% unused.

activeUSAF and activeAFRF are only used in the ammunition script for checking something with 3CB and needs all 3 to be true.
activeGREF is used **everywhere** for no good reason. 

All instances can be replaced with hasRHS with **NO** change to functionality.

**Comment by Bob-Murphy** [comment]
done in mie
