### ISSUE TITLE
[Bug]: eject ai from statics at hq for comander (function/button)

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1279]
*Version:* 2.3

*Mods:* CBA, TFAR, ACE(no-medical)

*Environment*: SP, MP LAN, MP host, MP dedi.

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***

recently it was brought to my attention that things like putting ai in statics and then disbanding the group at hq can lead to the loss of the statics as you while no longer be able to disband the units anymore(short of killing them or the like) as such i recommend that we add a action / button for the commander only to eject all ai from statics at hq.

**Comment by ComboTombo** [comment]
Do note that even after the AI are no longer in a vehicle or static you will not be able to dismiss/refund them, so they'll just clog up space at HQ and you won't be able to get money back.

**Comment by SonorousMeerkat** [comment]
Then could the commander have an overriding dismiss?
One that doesn't need the same squad?

**Comment by HakonRydland** [comment]
could also just have dismiss garrison dismiss all ai at hq and make sure they are ejected from any vehicle as im not actually sure it will and if they will despawn properly if not on foot for varius reasons

**Comment by jaj22** [comment]
The issue here is loose player squad AIs left over after a player disconnects, right? Garrisons and HC groups can be managed.

Could just dismiss/delete player squad AI on disconnection if they're orphaned.

**Comment by HakonRydland** [comment]
problem is in general player squads with ai manning statics/vehicles that then the players all leave/disbands so that the ai is alone in the squad without players with no way for players to rejoin the ai or for the ai to be dismounted from the statics/vehicles, this is mainly a issue for hq, with ai manning the statics and the commander using bought ai(single units) to mount defenses then just leaving the squad.

**Comment by HakonRydland** [comment]
i think we could probably make a general if no players and not hc squad then disband squad (send back to hq and despawn/refund) if wed want to go that direction, although i think its a bit much for edge cases where this would be a problem (a minor one at that)

**Comment by jaj22** [comment]
It's not really an edge case, because if they're not sitting in a static weapon, they're hanging around sucking up CPU time and potentially spawning stuff, which is not too smart either. If it was an accidental connection then you still can't retrieve them due to the lack of ACE join group.

More persistent options that would take a bit more work:
1. Make the orphans into an HC squad.
2. Add a join group option to them.

**Comment by Tiny-DM** [comment]
The AI themselves can be ejected from a static using an action, and AI group cleanliness has improved drastically. Garrisoning AI at HQ can be dismissed now. Closing.
