### ISSUE TITLE
[BUG] Load Previous Session cuts over the Credits reel.

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#128]
Need to move / delay the "Load Previous Session" dialog to be centre of the screen and also after the Credits screen has been closed.

**Comment by PoweredByPot** [comment]
I have never encountered this issue. The dialog for me never pops up until I am in first-person perspective after the intro credits.

**Comment by Toakan** [comment]
Thinks its a race condition somewhere, but it was also during the time changes were being made to the credits in the first place so...

**Comment by wurzel0701** [comment]
I run into this every time, so I can confirm this happens.
To recreate:
Start mission
Hit Space once you are on the map (not the arma loading screen)
Have the dialogs overlap

**Comment by wurzel0701** [comment]
@Toakan you up for this, or should someone else do this?

**Comment by wurzel0701** [comment]
I tried but failed, I am not good with UI stuff, anyone up for this?

**Comment by Spoffy** [comment]
Fixed in 55882c58545e8c2e9160ff75608b9c64cc691835. I just delayed it until after the 'Load Previous Save' Dialog has finished.
