### ISSUE TITLE
Aircraft -> airstrike points HQ restriction is weird

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1289]
*Version:* Unstable

*Mods:* Any

*Environment*: Any

***Issue:***
The "turn aircraft into airstrike points" function (`functions/REINF/fn_addBombRun`) only works within 50m of the HQ, but you can no longer ungarage fixed-wing aircraft or the larger helis at the HQ, so this seems like an unreasonable restriction.

Should work more like the garaging functionality, allowing aircraft on rebel-only airfields to be turned into airstrike points.

**Comment by Bob-Murphy** [comment]
Agree.
Converting should work on airfields with the same parameters like the garaging.
