### ISSUE TITLE
Add case for police in cargoSeats.sqf

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#1295]
The new QRFs are using police cars on lower levels to keep the balance.

CargoSeats is unaware of specific vehicles, so the police cars are getting filled with 1 police driver and 4 military guys.

We should add a case in which police cars get seated with actual police units, not random military ones.

**Comment by jaj22** [comment]
Should also use the militia vehicles at lower war tiers. CargoSeats would need adapting for those too.
