### ISSUE TITLE
FF script logs every single offense as forgivable instead of only the conviction

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1300]
Every time a player get's found as guilty, the admin get's the possibility to forgive the player. That means that once the player is in the debug corner, he has 5 to 8 times the possibility to "ask for forgiveness" and the admin has the same amount of possibilities to forgive the player.
BUT the admin can also already forgive the player directly after he shot somebody and is not even yet in the debug corner.

The scroll-wheel options should only be called when somebody is being send to the debug corner, not before.
![image](https://user-images.githubusercontent.com/50651578/87840221-ca248380-c89e-11ea-9edb-5bbcff6686f8.png)

20:21:34 "1625.63: [Antistasi] | INFO | fn_punishment_release.sqf | FORGIVE | Player: name-removed  [id-removed]"
20:21:34 "1625.63: [Antistasi] | INFO | fn_punishment_release.sqf | FORGIVE | Player: name-removed [id-removed]"
20:21:34 "1625.66: [Antistasi] | INFO | fn_punishment_release.sqf | FORGIVE | Player: name-removed [id-removed]"
20:21:34 "1625.66: [Antistasi] | INFO | fn_punishment_release.sqf | FORGIVE | Player: name-removed [id-removed]"
20:21:35 "1626.05: [Antistasi] | INFO | fn_punishment_release.sqf | FORGIVE | Player: name-removed [id-removed]"
20:21:36 "1626.73: [Antistasi] | INFO | fn_punishment_release.sqf | FORGIVE | Player: name-removed [id-removed]"
20:21:36 "1626.89: [Antistasi] | INFO | fn_punishment_release.sqf | FORGIVE | Player: name-removed [id-removed]"
20:21:36 "1627.22: [Antistasi] | INFO | fn_punishment_release.sqf | FORGIVE | Player: name-removed [id-removed]"
20:21:37 "1627.92: [Antistasi] | INFO | fn_punishment_release.sqf | FORGIVE | Player: name-removed [id-removed]"

**Comment by CalebSerafin** [comment]
C
