### ISSUE TITLE
Template Selector Issues

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1312]
The one Case we have for an Arctic Map doesent actually apply due to being Case-Sensitive.

aridmaps = ["Altis","Kunduz","Malden","tem_anizay","**Tembelan**"];
tropicalmaps = ["Tanoa"];
temperatemaps = ["Enoch","chernarus_summer","vt7"];
**arcticmaps = ["chernarus_winter"];**

While the Correct one would be:
Chernarus_Winter

Just a few Examples, only Chernarus_winter comes with a capital C and W
![grafik](https://user-images.githubusercontent.com/57111907/87943742-c52e2280-ca9e-11ea-9f82-de30d06411ad.png)

Also Tembelan is more Temperate than Arid.
![20200720153925_1](https://user-images.githubusercontent.com/57111907/87944214-64531a00-ca9f-11ea-91c5-76c5845d3e51.jpg)
Tembelan Above

Malden Below
![20200720153956_1](https://user-images.githubusercontent.com/57111907/87944262-746af980-ca9f-11ea-9f4e-17e39504c5ea.jpg)

**Comment by SonorousMeerkat** [comment]
![image](https://user-images.githubusercontent.com/52983798/87956480-ff9bbd80-caa6-11ea-9eaa-87241e3de628.png)

Not in my folder...

**Comment by Lazejun** [comment]
Yes cause those are the ones from the Map template these are also wrong
