### ISSUE TITLE
Old RoadsX Variables in fn_initVarCommon.sqf

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1315]
We should get rid of Static Weapons set in fn_initVarCommon.sqf

Example of Altis:

roadsX setVariable ["airport",[[[21175.06,7369.336,0],62.362,"Tank"],[[21178.89,7361.573,0.421],62.36,"Tank"],[[20961.332,7295.678,0],0,"Mort"],[[20956.143,7295.142,0],0,"Mort"],[[20961.1,7290.02,0.262632],0,"Mort"]]];

roadsX setVariable ["airport_1",[[[23044.8,18745.7,0.0810001],88.275,"Tank"],[[23046.8,18756.8,0.0807302],88.275,"Tank"],[[23214.8,18859.5,0],267.943,"Tank"],[[22981.2,18903.9,0],0,"Mort"],[[22980.1,18907.5,0.553066],0,"Mort"]]];

They work as intended as long as the Building where they are placed are still intact.

![20200720181950_1](https://user-images.githubusercontent.com/57111907/87961166-a12a0b80-cab5-11ea-9fc9-913ac2f03146.jpg)
Its also a Questionable Position, especially with a ZU23

When its broken they will spawn on their Original Position and fall down.
Fun Fact, when they are Destroyed they wont spawn, but when the Building is destroyed before they have spawned they will Fall.
![20200720182623_1](https://user-images.githubusercontent.com/57111907/87961811-8b691600-cab6-11ea-9e78-231b1d3fcc7f.jpg)

**Comment by Bob-Murphy** [comment]
Just take the shit out
