### ISSUE TITLE
Rebel garrison FFs on spawn

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1319]
**Describe the bug**
Garrison troops fight eachother on spawning.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
Spawn garrison troops on 3CB Blufor

**Expected behaviour**
Them to not infight
**Screenshots**
See https://discordapp.com/channels/449481990513754112/647694189236322305/735521836208750752
**Environment (please complete the following information):**
Version: 2.3
Map (specify if Altis Blufor): AltisB

[  ] LAN Hosted
[  ] Private dedicated server
[  ] Private dedicated server with Headless client(s)
[  ] Community Server 1
[  ] Community Server 2
[  ] Community Test Server
[  ] Community Test Server 2

Modset: 3CB
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by jaj22** [comment]
I couldn't replicate this on unstable. Might be related to #1195, which is not usually very common but can persist if the wrong-group-side units remain spawned.

Removing those silly UN uniforms is something I can support though.

**Comment by Lazejun** [comment]
Besides the Uniforms the Units also spawned with Full Body Armor and Helmets D:

**Comment by jaj22** [comment]
That's weirder than I thought, because the rebel loadout code strips body armour and helmets. Guessing that 3CB somehow puts it back on afterwards.
