### ISSUE TITLE
KILL PEOPLE for driving/moving outside of the map

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1322]
**Describe what the fuck is wrong:**
Players have been observer driving outside of the map to circumvent enemy interaction and still be able to reach for example an airfield on the other side of the map without being engaged on their way.
This is not acceptable.

**Describe how to reproduce:**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
Just drive/walk/fly outside of the map.

**Requested change:**
Implement a system which kills people outside of the map, maybe including a timer and/or a message.
Only Jets/planes should be the exception because of their speed. Not Helis, other vehicles or people on foot.

**Comment by wurzel0701** [comment]
We might wanna do something like 

"You are leaving the mission area, return to it"

And then have a 15 seconds timer

**Comment by RetardedFoX** [comment]
Donnu if this will work, but what about an invisible box marker at the center of the map, radius · radius. Would maybe make the code a bit easier, but don't know for sure.

**Comment by Bob-Murphy** [comment]
merged
