### ISSUE TITLE
[Change Request]: Loot filter needs to be made hands-off for mod integrators.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1328]
**Is your feature request related to a problem? Please describe.**
fn_equipmentIsValidForCurrentModset is not compatible with MIE as you have to add your mods hasX flag to the check.

**Describe the solution you'd like**
Check for non-vanilla should be automated/changed to a flag for Modded == true so that it can be centrally controlled in detector.sqf

**Describe alternatives you've considered**
Completely automate it? Though i'm not sure how.

**Additional context**
none.

**Comment by SonorousMeerkat** [comment]
This likely expands to much of the loot generation system.

**Comment by SonorousMeerkat** [comment]
New alternative that we discussed in a meeting a while ago: **STATIC LOOT LISTS**
These would be the superior option as we'd have full control for balance and selection _and_ it'd be able to go in the templates folder.
It would also bring back sided loot! (Occupants giving occupant loot!)

**Comment by Chronophylos** [comment]
Static loot lists could also allow server administrators to tweak what is available as loot

**Comment by MeltedPixel** [comment]
Closing as per @Bob-Murphy. Not currently planned. Will re-open in the future if anything changes.
