### ISSUE TITLE
[Feature Request]: Implement "Sunshine Reggae" button into new UI

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1334]
**Is your feature request related to a problem? Please describe.**
Rain sucks and drops FPS

**Describe the solution you'd like**
Implement button into new UI

Set the time for the rain to stop gradually to 150 seconds.
Make it so the button can only be clicked once per 30 minutes and send the message "Prayers to the weather gods are being collected" or something funky

**Comment by MeltedPixel** [comment]
Implemented onto tent, but leaving issue open as this references the new UI having the button, not an addAction on a tent.

**Comment by Tiny-DM** [comment]
Implemented in new UI. Closing.
