### ISSUE TITLE
Intel trap is causing strife.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1341]
**Is your feature request related to a problem? Please describe.**
Regular complaints about the "trapped" intel.

**Describe the solution you'd like**
Replace the trap with a *prewarned* (10-30s) artillery strike.

**Describe alternatives you've considered**
A longer timer and chance to defuse the bomb.
and/or
a way to defuse the bomb *before* trying to grab the intel.

**Additional context**
none

**Comment by Masaigu1** [comment]
Currently, the intel laptop spawns on a table. When it has the explosive, it is attached the bottom of the table, and thus if you check underneath, you can see if its a trapped intel or not. In my opinion, one large issue is the fact that there is no way to defuse, remove, or pick up the C4 block, or interact with it in any way, and the explosive explodes with almost 0 warning.  This mechanic punishes players for being complacent or not being careful, but has no reward for the player if they are careful and spot the explosive beforehand. 

I do not think that a prewarned artillery strike is the right solution. I think that the booby trapped intel is not a bad idea, just that it could for example, be changed from a C4 block to a claymore,frag grenade or bounding mine, that will affect those in the immediate vicinity of the intel, but stay contained within it.  

The main point I want to make though, is that giving players the ability to defuse/disable the trap if they discover it is the most important improvement that could be made.

**Comment by Bob-Murphy** [comment]
merged
