### ISSUE TITLE
initVarServer crashes out on Arma versions below 1.95

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1344]
**Describe the bug**
Template sanity-checker uses `substring in string` which was new in Arma 1.95. Should have been `string find substring != 0` which works in much older versions. This crashes out initVarServer with an RPT error so that Antistasi doesn't start.

I don't know how much we care about supporting old versions, but this was an unnecessary incompatibility. IIRC when I wrote the code, the wiki was down again.

**Environment (please complete the following information):**
Version: 2.3
Arma version below 1.95

**Comment by Bob-Murphy** [comment]
merged
