### ISSUE TITLE
FFAA breaks the template system if loaded.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1358]
**Describe the bug**
Mission fails to init if FFAA is enabled due to old checks.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
Load a game with FFAA enabled.

**Expected behaviour**
Nothing to change.
**Screenshots**

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

[x] LAN Hosted
[x] Private dedicated server
[x] Private dedicated server with Headless client(s)
[ ] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Modset: Any + FFAA
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by HakonRydland** [comment]
fixed in 2.3.1
