### ISSUE TITLE
Rebel airstrikes won't drop bombs when ordered by non-hosting players

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1361]
**Describe the bug**
If the commander requests a rebel airstrike and isn't hosting (or SP), the rebel aircraft will spawn correctly and perform the flypast, but will not generate any bombs.

The rebel airstrike code (NATObomb, yes really) is unusual because it spawns the aircraft on the client. Due to the new locality check in setWaypointStatements, it only fires the airbomb spawn on that client as well. Airbomb only runs on server or HC, so no bombs are created.

**Quick fix:** Change the setWaypointStatements in NATObomb to act on the server rather than where the aircraft is local.
**Proper fix:** Split NATObomb into target selection and aircraft spawning scripts. Run the latter as scheduled or server.

**Environment (please complete the following information):**
Version: 2.3 (new bug)
Map (specify if Altis Blufor): Any
Modset: Any

**Comment by HakonRydland** [comment]
fixed in 2.3.1
