### ISSUE TITLE
3CB Jackal camera issue.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1362]
**Describe the bug**
If you dismount from the commanders seat with a certain option, your camera bugs out.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
use "dismount right" from the commander's position

**Expected behaviour**
Dismount normally

**Screenshots**
N/A
**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): Any

[ ] LAN Hosted
[ ] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[x] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Modset: 3CB
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Bob-Murphy** [comment]
merged
