### ISSUE TITLE
Vanilla templates don't have enough light AT

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1364]
**Is your feature request related to a problem? Please describe.**
The vanilla NATO templates generate few AT launchers in general, and specifically very few MAAWS launchers: One unit in the six standard squads. This is a problem because AIs only use unlocked launchers, no launchers are unlocked at the start of the game, and the MAAWS is the only unlockable NATO launcher. Unlocking it from crates is extremely unreliable due to different camo and mod 0/1 versions.

Additionally with ACE, the PCML is disposable and the Titan lacks SACLOS guidance, so direct-fire launchers are especially thin there.

Even the Titan ATs are rare except at roadblocks, because Hunters don't fit a 4-man squad (crew are allocated seperately) while trucks and APCs always carry 8-man squads.

**Describe the solution you'd like**
Throw more MAAWS launchers into the 8-man squads.

**Comment by SonorousMeerkat** [comment]
MAAWS is tanks DLC no?

**Comment by Lazejun** [comment]
Free

**Comment by SonorousMeerkat** [comment]
hmm, with 2.4 we can definitely add it to the kit. If there are AI that carry them we might be able to squeeze them into 2.3.1 at Bob's discretion.

**Comment by Lazejun** [comment]
Nato:
["B_soldier_LAT2_F", MTP
"B_T_Soldier_LAT2_F" Tropical 
,"B_W_Soldier_LAT2_F"] Woodland

AAF:
["I_Soldier_LAT2_F"]

CSAT:
has no MAAWS

**Comment by jaj22** [comment]
Yeah, the LAT2s are already used for NATO. There's just only one of those, plus a couple of PCML guys in the militia squads. CSAT has an RPG-32 guy in almost every squad, so that shouldn't need changing.
