### ISSUE TITLE
typo: vanilla shotgun mag classnames

### ISSUE THREAD

**Issue by dmorchard** [official-antistasi-community/A3-Antistasi#1365]
**Describe the bug**
https://github.com/official-antistasi-community/A3-Antistasi/blob/ed10359750ef6bd00bb3b37bd6ec40c592bdf6dd/A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf#L101
Shotgun mags fail to unlock at mission start as intended due classname typo.  Classnames should be `2Rnd_12Gauge_Pellets` & `2Rnd_12Gauge_Slug`.

**To Reproduce**
n/a

**Expected behaviour**
n/a

**Screenshots**
n/a

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): Livonia v2.3 (vanilla rebel enoch template file only)

[ ] LAN Hosted
[ ] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[ ] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Modset: vanilla
    
Time the bug occurred (Please leave in GMT+0):
n/a

**Additional context**
n/a

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.
n/a

**Comment by Lazejun** [comment]
Since the PR is allready touching the Template for Uniforms i slapped the correction in it.
#1357
