### ISSUE TITLE
Savegame backwards compatibility doesn't restore captured outposts and seaports

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1367]
**Describe the bug**
Savegames from Barbolani's versions are not correctly loaded if they include rebel or invader controlled outposts or seaports. This is because the original marker names were puesto_XX and puerto_XX, and these are not translated when loading the variables mrkSDK and mrkCSAT. See `functions/Save/fn_loadStat.sqf`.

**Environment**
Any community version since the translation, loading any original savegame.

**Comment by HakonRydland** [comment]
fixed in 2.3.1
