### ISSUE TITLE
Too much of initClient runs on HCs

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1372]
**Describe the bug**
I introduced an exitWith bug in initClient a while back that causes headless clients run through the whole file unintentionally. Doesn't seem to cause problems in most cases, but it should be fixed because that code isn't expected to be HC-safe.

**Environment:**
Version: 2.3
[X] Private dedicated server with Headless client(s)

**Comment by HakonRydland** [comment]
fix merged in 2.3.1
