### ISSUE TITLE
FF Return teleport clips player into ground and objects.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#1374]
**Describe the bug**
Ocean gulag has been reported of damaging and or knocking people unconscious.

**To Reproduce**
Teleport return from Ocean Gulag while in swimming animation. The server needs to lag or desync a bit as well.

**Expected behaviour**
Teleport to previous position without clipping into ground or objects

**Environment (please complete the following information):**
Version: unstable per date 28.07.2020

* [ ] LAN Hosted
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [x] Community Test Server 2

Mod set:
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN or the server for dedicated: 
ca. 14:00

**Comment by CalebSerafin** [comment]
_Originally posted by @CalebSerafin in https://github.com/official-antistasi-community/A3-Antistasi/issues/1351_
> Okay, I'll have a re-look at how the radio-fast travel moves the player, as the function used should be looking for a safe position in 50m. I could set a minor velocity up as I've heard that helps a bit. 
> 
> The animation is changed back to standing befor/during tp back; I should do it at start of punishment aswell.
> 
> Everything will have to be moved to client-side to see if that affects whether the platform spawns or not. Changing the size of it won't help if it does not spawn.
> 
> An RPT would be lovely to see if there are any script errors, like null object references in case of the platform.

**Comment by HakonRydland** [comment]
fix merged 2.3.1
