### ISSUE TITLE
Roadblocks spawning multiple vehicles (and no infantry)

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#138]
crossroad north of town of Neri 041 122,  intersection spawns roadblock but currently only an empty hmmvv is present. Coming through the region multiple times causes multiple hmmvv to spawn

**Comment by wurzel0701** [comment]
Is it only this one roadblock, or does it happens for everyone/multiple ones?

**Comment by PoweredByPot** [comment]
can we confirm this is still happening? I certainly haven't seen it.

**Comment by wurzel0701** [comment]
Closing until confirmation that this still happens
