### ISSUE TITLE
[Bug]: destroy outpost: roadblock case bad task description

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1388]
**Describe the bug**
reported on discord community version bug reports channel 12.08.2020, destroy  outpost mission spawned at grid 000064 as a destroy roadblock mission, the task description is incorrect and missing the wording "roadblock" making it read out "A is disrupting our..."

**To Reproduce**
try to spawn outpost conquer missions on control markers located on roads. to do so execute this in the debug console.
_sites = controlsX select {(isOnRoad (getMarkerPos _x))};
_site = _sites#0;
[[_site],"A3A_fnc_CON_Outpost"] remoteExec ["A3A_fnc_scheduler",2];

**Expected behaviour**
Proper formatting of the task description

**Screenshots**
https://cdn.discordapp.com/attachments/647694189236322305/743145760132169848/unknown.png

**Environment (please complete the following information):**
Version: 2.3
Map: Virolahti

[ ] LAN Hosted
[ ] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[x] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Modset: 3cb
    
Time the bug occurred (Please leave in GMT+0): 17:30

**Comment by Bob-Murphy** [comment]
Can we change the name in the test based on the marker type with %n within the string?
That would be prefered.
Also, when changing the string please delete the translations as they would be outdated.

**Comment by jaj22** [comment]
IIRC this was caused by markersX not including auto-generated roadblocks on headless clients and was fixed a while back.
