### ISSUE TITLE
Change supply mission crates to non-IDAP-marked and liftable ones

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1391]
**Is your feature request related to a problem? Please describe.**
Supply mission crates are not liftable and IDAP marked

**Describe the solution you'd like**
Change the crates to liftable ones which are not IDAP marked

**Comment by RetardedFoX** [comment]
Maybe something like this:
```
30 _truckX = "Land_FoodSacks_01_cargo_brown_F" createVehicle _pos; 
31 _truckX enableRopeAttach true;
```
in `fn_LOG_Supplies.sqf`?

**Comment by Bob-Murphy** [comment]
@RetardedFoX Would you mind opening a pull request for that?
Thank you.
