### ISSUE TITLE
Implement availability of Kestrel/Atrag

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1392]
**Is your feature request related to a problem? Please describe.**
There is no proper way to get Kestrel and/or Atrag within Antistasi. People would like to have it

**Describe the solution you'd like**
Put it in loot crates OR put it in marksman/sniper loadouts

The exact approach will be discussed.

**Comment by jaj22** [comment]
Anything else in this list that you want spawned in loot?

["Zasleh2","rhs_muzzleFlash_dtk","rhs_muzzleFlash_dtk1","rhs_muzzleFlash_dtk2","rhs_muzzleFlash_dtk3","rhs_muzzleFlash_ak5","rhs_muzzleFlash_uuk","rhs_muzzleflash_pgs64","rhs_muzzleflash_dtkakm","rhsusf_acc_muzzleFlash_SF3P556","rhsusf_acc_muzzleFlash_SFMB556","rhsusf_acc_muzzleFlash_ardec_m240","rhsusf_acc_muzzleFlash_M14_USGI_NM","ACE_Banana","ACE_HuntIR_monitor","ACE_microDAGR","ACE_Sandbag_empty","ACE_SpraypaintBlack","ACE_SpraypaintRed","ACE_SpraypaintGreen","ACE_SpraypaintBlue","ACE_key_master","ACE_key_lockpick","ACE_key_west","ACE_key_east","ACE_key_indp","ACE_key_civ","ACE_artilleryTable","ACE_IR_Strobe_Item","ACE_Chemlight_Shield","ACE_DAGR","ACE_M26_Clacker","ACE_DeadManSwitch","ACE_rope12","ACE_rope15","ACE_rope18","ACE_rope27","ACE_rope36","ACE_Flashlight_KSF1","ACE_Kestrel4500","ACE_ATragMX","rhsgref_muzzleFlash_L1A1"]

The following muzzle attachments are already sorted for RHS/ACE, so I suspect most of the muzzles above are old dupes:

["rhs_acc_tgpa","rhs_acc_pbs1","rhs_acc_tgpv","rhs_acc_tgpv2","rhs_acc_dtk4short","rhs_acc_dtk4long","rhs_acc_dtk4screws","rhs_acc_pbs4","rhs_acc_6p9_suppressor","rhs_acc_dtk3","rhs_acc_dtk","rhs_acc_dtkakm","rhs_acc_dtk1983","rhs_acc_dtk1","rhs_acc_dtk1l","rhs_acc_dtk1p","rhs_acc_dtk2","rhs_acc_uuk","rhs_acc_ak5","rhs_acc_pgs64","rhs_acc_pgs64_74u","rhs_acc_pgs64_74un","rhsusf_acc_M2010S","rhsusf_acc_M2010S_d","rhsusf_acc_M2010S_sa","rhsusf_acc_M2010S_wd","rhsusf_acc_SR25S","rhsusf_acc_SR25S_wd","rhsusf_acc_SR25S_d","rhsusf_acc_rotex5_grey","rhsusf_acc_rotex5_tan","rhsusf_acc_nt4_black","rhsusf_acc_nt4_tan","rhsusf_acc_omega9k","rhsusf_acc_rotex_mp7","rhsusf_acc_rotex_mp7_aor1","rhsusf_acc_rotex_mp7_winter","rhsusf_acc_rotex_mp7_desert","rhsusf_acc_SF3P556","rhsusf_acc_SFMB556","rhsusf_acc_ARDEC_M240","rhsusf_acc_m14_flashsuppresor","rhsusf_acc_m24_silencer_black","rhsusf_acc_m24_silencer_d","rhsusf_acc_m24_silencer_wd","rhsusf_acc_m24_muzzlehider_black","rhsusf_acc_m24_muzzlehider_d","rhsusf_acc_m24_muzzlehider_wd","rhsusf_acc_aac_scarh_silencer","rhsusf_acc_aac_762sd_silencer","rhsusf_acc_aac_762sdn6_silencer","rhsusf_acc_aac_m14dcqd_silencer","rhsusf_acc_aac_m14dcqd_silencer_d","rhsusf_acc_aac_m14dcqd_silencer_wd","ACE_muzzle_mzls_H","ACE_muzzle_mzls_B","ACE_muzzle_mzls_L","ACE_muzzle_mzls_smg_01","ACE_muzzle_mzls_smg_02","ACE_muzzle_mzls_338","ACE_muzzle_mzls_93mmg","rhsgref_sdn6_suppressor","rhsgref_acc_zendl","rhsgref_acc_falMuzzle_l1a1"]

**Comment by Bob-Murphy** [comment]
Please implement following assets:
"ACE_Kestrel4500"
"ACE_ATragMX"
"ACE_HuntIR_monitor"
