### ISSUE TITLE
Running with RHS but without GREF causes petros not to spawn

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1393]
**Describe the bug**
Apparently many players are trying to run Antistasi with AFRF & USAF but without GREF, which causes petros not to spawn, with no error message. initVarCommon sets hasRHS to true if either AFRF or USAF are present, but the new template selector in 2.3 assumes that GREF will be present if hasRHS is true.

If AFRF/USAF without GREF is no longer a working option, it should revert to vanilla and not print text that claims it's running with RHS.

This may be fixed in one of Meerkat's template PRs. Haven't checked yet.

**Comment by SonorousMeerkat** [comment]
Done in MIE

**Comment by wurzel0701** [comment]
Isnt MIE 2.4? If so please change the Milestone

**Comment by Bob-Murphy** [comment]
done with MIE
