### ISSUE TITLE
Destroy mission isn't created when a radio tower is selected

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1400]
**Describe the bug**
When requesting a destroy mission from Petros (or if one is requested automatically), Petros will sometimes respond with "I have a mission for you", and then no task is generated. This happens when an antenna is chosen as the target.

This is caused by a missing function prefix on line 121 of fn_missionRequest. `DES_antenna` should be `A3A_fnc_DES_antenna`.

**Comment by jaj22** [comment]
Will be fixed by #1101

**Comment by Bob-Murphy** [comment]
Merged.
