### ISSUE TITLE
3CB needs more secure mod checking

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1406]
**Is your feature request related to a problem? Please describe.**
Currently it is too easy to load 3CB without all the required mods for it to function.

**Describe the solution you'd like**
The detection should check for all the required mods.

**Describe alternatives you've considered**
Not alternative, but extended: Factions should be separately detected to allow for separate running.

**Additional context**
N/A

**Comment by Lazejun** [comment]
well MIE could allow has 3cb Faction gets Rebells TKM etc if you don't you still have hasRhs and it goes NAPA template, AFRF Inv etc hasBAF etc Bluefor is Factions only so no BAF needed anyway instead of only allowing one Complete Modset it would allow 3Cb vs RHS EQUIP depending on Map etc

**Comment by Bob-Murphy** [comment]
done with MIE
