### ISSUE TITLE
HQ Placement has to Check for Out of Map

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1411]
The Initial Maps Altis/Tanoa (Chernarus special Case) never needed a Check for Out of Map due to being Islands, but Complete Land Maps as:
Livonia,
Kunduz,
Takistan,
Virolahti,
Takistan,
Chernarus (To North and West)

Will have the Problem of Missclicks that leads to HQ being Out of Map.

**Comment by HakonRydland** [comment]
fix merged 2.3.1
