### ISSUE TITLE
Calling Airstrikes results in plane flying over & no bombs dropped

### ISSUE THREAD

**Issue by Mirv** [official-antistasi-community/A3-Antistasi#1427]
**Describe the bug**
Calling Airstrikes results in plane flying over & no bombs dropped

**To Reproduce**
Call an airstrike with no mods running on server

**Expected behaviour**
The plane should drop bombs, which explode.

**Screenshots**

**Environment (please complete the following information):**
Version: 2.3.0 & John's special patch
Map (specify if Altis Blufor):  Atlis & Tanoa

[ ] LAN Hosted
[x] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[ ] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Modset:  Antistasi Team Membership only - no others
    
Time the bug occurred (Please leave in GMT+0): 11:51 for 3 in a row calls
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated:   -0600 GMT (central time)

**Additional context**
Happens both maps, pre 2.3.0 I believe

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

---

File:

https://discordapp.com/channels/449481990513754112/647694189236322305/751517079059824661

**Comment by Lazejun** [comment]
Will be fixed in 2.3.1

This was the Previous issue which is closed but still in Testing of 2.3.1.
https://github.com/official-antistasi-community/A3-Antistasi/issues/1361

https://github.com/official-antistasi-community/A3-Antistasi/pull/1377
