### ISSUE TITLE
3CB BAF Static Weapons only have 1 Magazine

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1431]
Regarless of Type, the BAF Variants of the Static weapon only have 1 Magazine due to 3CB using a System Similar to ACE_CSW with forced Advanced Assembly resulting in ANY Weapon only having 1 Magazine.

Which leads to Static defenses being a lot less usefull than in other modset.

It would be intended for Static Crew to have the Ammo for their Weapon but the Units cannot Carry the Ammo due to it being to heavy.

Also 3CB BAFs default Crew for static weapon doesent get Ammo for the Statics either so not much we can do about it exept Replace it with RHS Variants, since its allready forced anyway.

**Comment by Bob-Murphy** [comment]
@SonorousMeerkat what you think about the replacing of units with RHS variants for that cause?

**Comment by Lazejun** [comment]
There are no Units those are Static weapons, they spawn Crew from the Templates
