### ISSUE TITLE
Ammobox still allows Editing of Pylons

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1447]
I thought disabling all Ace Interactions on the Vehicle Ammobox would prevent that still being a thing but i was wrong #1007.

Possible solutions would be changing the Box to a different Prop/Object that is not considered an Ammobox or overwrite that the Box is not gonna be considered as Ammobox so it wouldnt allow to edit Pylons.

----------> You should need to get an Ammotruck and not have it all at the start of the Game.

**Comment by Bob-Murphy** [comment]
Find a suitable asset and I'm fine with that.

**Comment by Lazejun** [comment]
I think i found the Perfect replacement,
![107410_20210220132832_1](https://user-images.githubusercontent.com/57111907/108595319-8a1b0700-737f-11eb-8c11-5a851cd669f8.png)

"Land_CargoBox_V1_F"

Tested on Altis, it works to just replace the Type of Box inside the Mission.sqm, would not even requiere touching the Editor.
so

type="Box_East_AmmoVeh_F";

to 

type="Land_CargoBox_V1_F";
