### ISSUE TITLE
Change getpos setpos in FF code to improve teleporting after punishment

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1458]
**Describe the bug**

@HakonRydland please add more information

**Comment by HakonRydland** [comment]
ahh yes, during last testing tuesday when a FF punishment was triggered on a player on top of a pipe, he was placed back on the ground instead of on the pipe after admin forgive action was used, i dont belive the action being used would alter the outcome, but more info is always good.

**Comment by CalebSerafin** [comment]
That's intended functionality, the return function finds the safest spot within 50m.
