### ISSUE TITLE
Flatbed trucks used in templates where passenger vehicles should be

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1462]
**Describe the bug**
The vehNATOTrucks, vehCSATTrucks and vehFIATruck variables should only contain passenger vehicles, as these are assumed to be capable of carrying infantry squads. Flatbed trucks can be moved to vehNATO/CSATCargoTrucks.

Known cases: 
UK3CB_TKA_I_V3S_Recovery in 3CB_Occ_TKA_Arid
UK3CB_TKA_B_Ural_Recovery in 3CB_Occ_BAF_Arid

There may be others.

**Comment by jaj22** [comment]
Not fixed, do not close.

**Comment by Bob-Murphy** [comment]
This one as well as the PR #1481 are getting moved to 2.3.2
