### ISSUE TITLE
Some charges can be unlocked by converting to throwables with ACE

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1466]
**Describe the bug**
Some charges can be converted to throwables (and back) with ACE by double-clicking them in the inventory, which allows them to be unlocked regardless of the unlockable explosives parameter. As far as I can tell, ACE hardcodes this in addon/grenades/functions/fnc_addChangeFuseItemContextMenuOptions.sqf, so the only charges affected are:

`"SatchelCharge_Remote_Mag"` ->  `"ACE_SatchelCharge_Remote_Mag_Throwable"`
`"DemoCharge_Remote_Mag"` -> `"ACE_DemoCharge_Remote_Mag_Throwable"`

These are the vanilla charges, relabeled to M112 and M183 by ACE. The RHS charges are probably not convertible at the moment because it's just those two charges hardcoded.

ACE does not appear to have added any config values to these charges to indicate their conversion status. It's purely internal hardcoding. At some point they'll probably realise that this is an abomination against addon coding and change it. On the other hand they might just hardcode more charges in the future, which is going to break any solution that uses category overrides.

**Comment by veteran29** [comment]
>  abomination against addon coding and change it
🤔 

If the feature is problematic for your mission you can easily disable it by forcing `ace_grenades_convertExplosives` setting to false via `cba_settings.sqf`.
Also all (2) throwable explosives have common parent: `ACE_SatchelCharge_Remote_Mag_Throwable` so it's quite easy to detect them right now.

**Comment by CalebSerafin** [comment]
@jaj22 Is this currently fixed?

**Comment by Lazejun** [comment]
no, it's prevented by server settings.

Possible methods would be blocking from unlocking by adding them to unknown category,

Force the settings by Mission

**Comment by CalebSerafin** [comment]
Hmm, then we could interact directly with CBA settings as veteran29 mentioned. It will be a direct fix preventing the problem from happening.

**Comment by Lazejun** [comment]
Cheap and easy solution but it will kill the feature,
as the only thing that's needed is to prevent unlocks
