### ISSUE TITLE
Garrisoned AI on destroyed towers fall to their death.

### ISSUE THREAD

**Issue by SamathyTheManathy** [official-antistasi-community/A3-Antistasi#1470]
**Describe the bug**
Garrisoned AI will spawn on outpost tower however if outpost tower is destroyed they will spawn on parts of the tower that no longer exist and fall to the ground causing themselves damage and sometimes death.

**To Reproduce**
Garrison AI at an outpost with a destroyed tower.
'Activate' it by being in proximity of the garrison.
Look under the tower.

**Expected behaviour**
AI spawns on destroyed tower but on the parts that are still 'there'

**Screenshots**
![20200912163527_1](https://user-images.githubusercontent.com/49008088/93398256-9544a500-f8be-11ea-959f-ad945c411521.jpg)
![20200912163526_1](https://user-images.githubusercontent.com/49008088/93398292-9ece0d00-f8be-11ea-96aa-f37634998c8e.jpg)
![20200912163538_1](https://user-images.githubusercontent.com/49008088/93398304-a1c8fd80-f8be-11ea-96bb-b9b3980c7e75.jpg)

**Environment (please complete the following information):**
Version: 2.3
Map (specify if Altis Blufor): 
Altis
Private dedicated server

Modset:

CBA-A3
ace

RHSAFRF
RHSUSAF
RHSGREF
ACE Compat - RHS United States Armed Forces
ACE Compat - RHS Armed Forces of the RUssian Federation
ACE Compat - RHS GREF

Zeus Enhanced
Zeus Enhanced - ACE3 Compatibility

Advanced Vault System
WMO - Walkable Moving Objects

Cryme's Gear Grabber - Virtual Arsenal Mod (doesn't seem to work)
Arsenal Search

GRAD Trenches
VET_Unflipping (doesn't seem to work)

ShackTac User Interface
VileHUD
GCam Cinematic Camera Tool

Ammocan
Vehicle Inventory System
Bullet Casings
Improved Grenades

No More Aircraft Bouncing
Real Engine
RHRM [REAL HERO's RAGDOLL MOD]
RR Immersive Maps by LAxemann
Sling Load Rigging

JSRS SOUNDMOD
Blastcore Edited (standalone version)
Enhanced Missile Smoke + Lighting Efx Mod v1.4
A3 Thermal Improvement
Light Blue Water Colour Mod
Reduced Haze Mod v3.1
MRB Vehicle Visibility
Immerse

**Additional context**
Haven't noticed it on other towers but on it happens 100% of the time on the HQ in the screenshot.
Can provide more info on request.

**Comment by jaj22** [comment]
Tracked this down to UPSMON_filterbuilding not removing destroyed buildings. Wasn't sure whether to bother dealing with this as UPSMON is probably getting dumped eventually, but it should be a pretty easy fix.

Enemy garrisons do it too, but that's less visible to players.
