### ISSUE TITLE
Allow commander to buy vehicles using faction rather than personal resources

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1473]
Apparently this was agreed in a meeting point that I barely remember. It's a good idea anyway, fixes a lot of learning curve problems in the early game.

**Comment by Bob-Murphy** [comment]
Not in a meeting but in another channel. But don't remember when and where exactly.

**Comment by kil0byt3** [comment]
Perhaps here? 

https://discord.com/channels/449481990513754112/593907409437589505/744235350721036428

**Comment by jaj22** [comment]
That's the one, thanks.
