### ISSUE TITLE
Typo in functions/save/fn_deleteSave.sqf omitted underscore for postfix .

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#1474]
**Describe the bug**
The underscore for postfix has been omitted.
https://github.com/official-antistasi-community/A3-Antistasi/blob/eb9da4dcb1ace3779aefe703acdbe56b4c8b9426/A3-Antistasi/functions/Save/fn_deleteSave.sqf#L15
This currently requires a bit of a hack-patch to work.

**To Reproduce**
Try use A3A_fnc_deleteSave without patching postfix as a global variable on the server.
This will throw a runtime error as `postfix` is undefined.

**Expected behaviour**
`postfix` is changed to `_postfix` and A3A_fnc_deleteSave  does not crash with valid inputs.

**Environment (please complete the following information):**
Version: July `22ba068 on May 31` => 2.3.1 `eb9da4d on September 15 `
Map (specify if Altis Blufor): 

[x] LAN Hosted
[x] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[ ] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Mod-set: Any will do

**Comment by jaj22** [comment]
I think some extra save vars got added as well, so I'll probably update those at the same time.

**Comment by Bob-Murphy** [comment]
Merged.
