### ISSUE TITLE
Headless clients fail to load

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#148]
2:17:41 "2791.68: [Antistasi] | INFO | Init finished."
 2:17:41 "hc/BIS_fnc_log: [module] BIS_fnc_moduleCurator (101.002 ms)"
 2:17:41 Weather was forced to change
 2:17:41 "Advanced Towing Loading..."
 2:17:41 "Advanced Towing Loaded"
 2:17:41 Error in expression <With {_return = _x select 3;};
}forEach jnl_attachmentOffset;

_return>
 2:17:41   Error position: <jnl_attachmentOffset;

_return>
 2:17:41   Error Undefined variable in expression: jnl_attachmentoffset
 2:17:41 File JeroenArsenal\JNL\Functions\fn_logistics_getCargoType.sqf [JN_fn..., line 25
 2:17:42 Error in expression <With {_return = _x select 3;};
}forEach jnl_attachmentOffset;

**Comment by Spoffy** [comment]
Closed in 32a0fe8204f88c0c816598d6826d04b2e58379f4
