### ISSUE TITLE
Missed case in pr #1485, seaports dont break undercover when in a aircraft

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1491]
**Is your feature request related to a problem? Please describe.**
It is still possible to airlift the crates at seaports, due to the new check only checking outposts, seaport is the only one missing from locations that spawn crates, so this is the only case thats missing
**Describe the solution you'd like**
add seaports to first argument in line 202 of goUndercover

**Describe alternatives you've considered**

**Additional context**

**Comment by jaj22** [comment]
Hah, knew I'd forgotten something there and I couldn't place it.

**Comment by jaj22** [comment]
I'm thinking that seaports should count for the land check as well (it's currently only outposts and roadblocks), given that they have loot crates and they're being heavily militarized in the map editor.
