### ISSUE TITLE
Reset autosave timer when doing a manual save

### ISSUE THREAD

**Issue by doommetal** [official-antistasi-community/A3-Antistasi#1495]
**Is your feature request related to a problem? Please describe.**
Should prevent corrupting the save when autosave happens while restarting the server.

**Describe the solution you'd like**
As in the title.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jaj22** [comment]
Needs a global variable added for next autosave (it's currently just a sleep), but not really a problem.
