### ISSUE TITLE
Enemy Guerrilla Uniforms On Vanilla

### ISSUE THREAD

**Issue by Brandantl** [official-antistasi-community/A3-Antistasi#1499]
**Describe the bug**
The enemy guerrilla faction on the the vanilla modset at the start of the game when the guerrilla exist use the same red trucks as our guerrilla faction but with 50cals on top. They also have the same uniforms as our guerrilla uniforms which is extremely confusing for the start of the game and results in a lot of TK. 

**To Reproduce**
Fresh Campaign, go to any resource. 

**Expected behaviour**
Different uniforms.

**Screenshots**
Not Necessary 

**Environment (please complete the following information):**
Version: Server 1 Version as of 9/27/2020
Official Server 1 (Tanoa)
    
Time the bug occurred (Please leave in GMT+0):
Not time dependent. 

**Additional context**

**Comment by Lazejun** [comment]
They are not Red its a known ignored Issue, its in Guerillia Colors on the server but only on the Server, Clients see ALL Offroads in Red.

That issue is also resolved already in #1357

**Comment by Brandantl** [comment]
Good thing that's not the point of this issue. So it's not resolved. It's not about the truck its about the uniform being the same.

**Comment by Lazejun** [comment]
Yes there are no Guerillia Factions anymore if you would look at the Informations in #1420

**Comment by Brandantl** [comment]
You should link this issue in that pull request as well.
