### ISSUE TITLE
Object spawning in outposts and such

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#150]
Current:
When a marker for an outposts is placed down on an outpost, the flag is automatically placed directly in the middle of the marker. The box (if suitable for that marker) is placed in the near vicinity of the flag and also a truck is placed randomly.

Problem:
As not all places are set up in the way, that the center of the marker is accessible, it can happen that the assets spawn inside of buildings/walls and the trucks explode and fly away like damn rockets.

Possible solutions:
Keep the random generated positions UNLESS certain (new) markers are placed down within the (for example) outpost marker. When the additional markers are placed down (3 different ones), the assets are being placed at the chosen position.

**Comment by wurzel0701** [comment]
Is #267 merged or just closed? Could close this issue then

**Comment by Bob-Murphy** [comment]
Done with #267
