### ISSUE TITLE
Purge BS-Loop from Hint Rendering

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#1504]
BIS_fnc_loop is the imposter of scheduling. Sometimes it forgets how to run. It pretends to be doing your task however, the code you gave it is not executing. It is 248 lines. It pasts the whole function into the RPT when adding an item.

Replace it with OnEachFrame and a counter.

Alternative: Pleed to BI to improve it.

The reported incident required the use of the dismiss key was required to display the hint.
This does correlate to an anomaly Caleb discovered while testing. However, at that time it was written off as it could not be reproduced.

**Comment by Bob-Murphy** [comment]
Merged.
