### ISSUE TITLE
PvP fast travel should attempt to find an empty position

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1507]
**Is your feature request related to a problem? Please describe.**
The PvP fast travel function simply picks a random position 10m from the target marker. This can put vehicles inside buildings, for example.

**Describe the solution you'd like**
Wouldn't be difficult to switch the code to findEmptyPosition like the rebel FT function. findEmptyPosition isn't great, but it's better than the current method.

**Describe alternatives you've considered**
Remove PvP?

**Comment by Bob-Murphy** [comment]
PvP will be disabled which makes this issue obsolete.
