### ISSUE TITLE
2.3.1 bug - A3A_fnc_createAIcontrols - two different ones

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1509]
Bug found in Mainserver 1 log when running 2.3.1 bugfix

```
14:03:55 Error in expression <
{
_pos = [getPos (_roads select 0), 7, _dirveh + 270] call BIS_Fnc_relPos;
_bun>
14:03:55   Error position: <_dirveh + 270] call BIS_Fnc_relPos;
_bun>
14:03:55   Error Undefined variable in expression: _dirveh
14:03:55 File functions\CREATE\fn_createAIcontrols.sqf [A3A_fnc_createAIcontrols]..., line 66
```

```
17:51:05 Error in expression <e getPos (_roads select 0);
_veh setDir _dirveh + 90;
[_veh, _sideX] call A3A_fn>
17:51:05   Error position: <_dirveh + 90;
[_veh, _sideX] call A3A_fn>
17:51:05   Error Undefined variable in expression: _dirveh
17:51:05 File functions\CREATE\fn_createAIcontrols.sqf [A3A_fnc_createAIcontrols]..., line 124
```

Log will be linked shortly in data dump channel

**Comment by HakonRydland** [comment]
`17:51:04 "armahosts/log: ERROR: [BIS_fnc_dirTo] Error: type ANY, expected OBJECT, on index 1, in [2177943: ,<null>]"`
bad arguments for dirTo, looks like the first issue, what happend here

**Comment by HakonRydland** [comment]
```
_radiusX = 20;
	while {true} do
		{
		_roads = _positionX nearRoads _radiusX;
		if (count _roads > 1) exitWith {};
		_radiusX = _radiusX + 5;
		};

	_roadscon = roadsConnectedto (_roads select 0);

	_dirveh = [_roads select 0, _roadscon select 0] call BIS_fnc_DirTo;

```
another one where the nearest road was not connected maybe

**Comment by jaj22** [comment]
> another one where the nearest road was not connected maybe

Yeah, likely. Not sure why it'd only be coming up now though. Roadblock placement is a bit random, so I guess it could be a rare one.

**Comment by jaj22** [comment]
Amusingly it searches for two roads within the radius, and then assumes that they'll be connected. Not guaranteed for Virolahti, apparently.

I can make the search a bit stricter, but what's the preferred result when it can't find any suitably connected roads in the vicinity? Don't build the roadblock, or just build it on the marker with a random facing?
