### ISSUE TITLE
2.3.1 bug - A3A_fnc_artillery

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1510]
Bug found in Mainserver 1 log when running 2.3.1 bugfix

```
19:39:25 Error in expression <3A_fnc_sizeMarker;

if (_posDestination inRangeOfArtillery [[_veh], ((getArtille>
19:39:25   Error position: <inRangeOfArtillery [[_veh], ((getArtille>
19:39:25   Error Type Array, expected String
19:39:25 File functions\AI\fn_artillery.sqf [A3A_fnc_artillery]..., line 27
```

Log will be linked shortly in data dump channel

**Comment by HakonRydland** [comment]
`17:51:04 "armahosts/log: ERROR: [BIS_fnc_dirTo] Error: type ANY, expected OBJECT, on index 1, in [2177943: ,<null>]"`
bad arguments for dirTo, looks like the first issue, what happend here

**Comment by HakonRydland** [comment]
was caused due to arty piece being destroyed
