### ISSUE TITLE
Change hint queue into stack.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#1516]
### Is your feature request related to a problem? Please describe.
The hint system requires old hints to be dismissed before new ones.

### Best Solution
Change the hint queue into a stack.
Then re-evaluate when new notification methods are added.

### Alternatives
Let the world burn.

### Anonymised Quote: 
> I honestly hate the new system for dismissing hints. Super annoying at doing command stuff now and I don't like having to close shit just to dismiss shit and reopen just to do it again
> Yes because changing the civ limit and ai limit etc is super stupid now
Trying to order ai and shit on map etc is hard to
Or make the hints persist on top so no matter whats open you can dismiss them if that's also possible

**Comment by Bob-Murphy** [comment]
Merged.
