### ISSUE TITLE
pvp variable is local, FF check cant see pvp players as such

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1520]
**Describe the bug**
The variable in the init of pvp players dosnt broadcast the pvp variable, and as FF is server run it therefor never recognizes pvp players

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant): go shot some pvp players on a dedicated server, you will get a FF notification and eventualy a FF punishment

**Expected behaviour**
for it not to punish players for pvp

**Screenshots**

**Environment (please complete the following information):**
Version: 2.3.1
Map (specify if Altis Blufor): 

[ ] LAN Hosted
[ ] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[x] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Modset: 
    
Time the bug occurred (Please leave in GMT+0): ca. 17:00
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Bob-Murphy** [comment]
Merged.
