### ISSUE TITLE
Menu's do not take you "back" correctly

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#153]
Some of the dialog menus do not take you back to the menu you used to access it, instead they either close the dialog completely or they take you back to the main Dialog menu.

This should be standardised.

**Comment by PoweredByPot** [comment]
one of my favorites, if you are commander and you look at a car to sell it, you must first click 'garage', then click 'back' and you end up on a screen with a 'sell' button.

**Comment by wurzel0701** [comment]
I need a list of back buttons, which do not lead back correctly, this is not really possible to see in the code. So I need more infos like this

DialogStart => Clicked Button => next dialog => back button => wrong dialog / which dialog would be correct

**Comment by PoweredByPot** [comment]
Player> Garage Vehicle > 
It then asks "personal or faction"
if you hit back, you then get something like:
"personal garage or sell"
then back again brings you to where you expect.

This is the only way for players to sell vehicles that I know of

**Comment by wurzel0701** [comment]
Closing as it is merged and fixed
