### ISSUE TITLE
Save Loop only hints to server (ie. it's own machine).

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#1530]
**Describe the bug**
Hints for saving are not broadcast to other players.

**To Reproduce**
Save on DS.

**Expected behaviour**
Hints are broadcast

**Screenshots**

**Environment (please complete the following information):**
Version: bugfix 8 Oct 2020
Map (specify if Altis Blufor):  All

[ ] LAN Hosted
[x] Private dedicated server
[x] Private dedicated server with Headless client(s)
[x] Community Server 1
[x] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Modset: Any

**Comment by Bob-Murphy** [comment]
Merged.
