### ISSUE TITLE
"Steal or Destroy Ammotruck" truck didnt spawn

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#1533]
**Describe the bug**
Had a steal or destroy ammotruck mission, but no truck spawned in. When the time ran out, the rebels won the mission and got the reward.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
Not sure how to reproduce that, it might be related to the marker tho

**Expected behaviour**
The truck should spawn in correctly

**Screenshots**
![20201009110101_1](https://user-images.githubusercontent.com/31988396/95586206-a48fbc00-0a40-11eb-96cf-77307b4e1161.jpg)

**Environment (please complete the following information):**
Version: 2.3.1 bugfix + further supports + LTC
Map (specify if Altis Blufor): 

[ ] LAN Hosted
[X] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[ ] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Modset: Alot of movement and sound enhancer, nothing changing AI or scripts
If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

Dont have access to the logs yet, will send them later

**Comment by jaj22** [comment]
Worked fine for me with vanilla bugfix branch. Apparently it's identifying the "correct" road in that screenshot, and it's a simple spawn function, so I'm not sure what could go wrong except another vehicle spawning in the same place and throwing them 500m away. I can't think of anything in LTC or supports that's could break it either, but I haven't tried that.

The ammotruck mission does wait for the outpost to hit spawner != 2, but that shouldn't matter here unless you're expecting it to show up immediately in Zeus.

**Comment by wurzel0701** [comment]
Not been able to replicate, closing it
