### ISSUE TITLE
Correct log in fn_handleDamage

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1536]
Please adapt the log so it also has "[Antistasi] | INFO | functionName.sqf" at the start like the others have it.
Below you find the exact line.

Also, if you can maybe change something that makes the line fire every time, that would be nice. We have way too much FF incidents which are not getting tracked with this.

Thank you.

https://github.com/official-antistasi-community/A3-Antistasi/blob/4de7095dcbbd69504f25fe35ba3da4ccebcd30fe/A3-Antistasi/functions/Revive/fn_handleDamage.sqf#L24

**Comment by CalebSerafin** [comment]
@Bob-Murphy  Can I remove this and add a "distance from HQ" item in punishment system log messages?

**Comment by Bob-Murphy** [comment]
As long as the log is reliably created with the data, I have no problem with moving it to another file.

**Comment by Bob-Murphy** [comment]
Merged.
