### ISSUE TITLE
[Bug]: Players can be side-switched with ACE vehicle loading

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1541]
**Describe the bug**

**Part 1:** When an unconscious unit is ACE-loaded into a vehicle by a unit of a different side, the unconscious unit will be moved to a new group of the driver/commander's side. I assume ACE does this because it works even without handcuffs, and non-captive players would block vehicle entry for players of a different side.

**Part 2:** Usually the unit will switch back to its original group (or a new one of the same ID, if deleted) when the unit wakes up or is removed from the vehicle. However, there are at least three reports of the unit persisting on the wrong side. I can't replicate this locally.

Even without the persistent switch bug, units being temporarily on the wrong side is problematic, as many Antistasi functions will assume that `side group player` is invariant. For example, PvP players may permanently acquire knowledge of HQ location, or the ability to use petros actions.

**To Reproduce**
I don't know how to reproduce the persistent case, but the temporary side switch is easy enough:
- With ACE, knock an enemy unit unconscious.
- Load that unit into a vehicle.

**Preferred Fix**

**Part 1:** With ACE we can't assume that side group is the long-term side of that unit. Any case that relies on a remoteExec side target is probably broken. Cases where side group is tested directly may need expanding to test a PvP variable on that unit.

**Part 2:** No known fix. Probably an ACE bug.

**Comment by jaj22** [comment]
I think I figured part 2. It's an ACE bug but their issue tracker requires reproducibility, which may be almost impossible to achieve due to server load requirements. Here's how it works anyway:

1. An unconscious or captive enemy is loaded into a vehicle. This triggers `ace_common_loadPerson`, local to the player doing the loading. This function directly calls `ace_common_switchToGroupSide`, which uses a global setVariable to record the previous group & side. This is still local to the loader.

2. Around the same time (server load dependent), an ace_unconscious wakeup event is fired. The ace_unconscious handler in ace_common's XEH_postInit fires `ace_common_switchToGroupSide`, local to the loaded player. This rewrites the previous group & side data globally even if the function did nothing, for example if the previousGroupSwitchTo array changes hadn't yet reached the client of the loaded player.

3. As we know from the Antistasi 0 player money on load bug, calling global setvariables from multiple locations does not work as expected: A setvariable broadcast from one client can apparently block a subsequent broadcast from the server. In this case, the previousGroupSwitchTo array may remain empty on the loaded player, so when they're eventually unloaded from the vehicle, their group is still not switched back.

**Comment by killerswin2** [comment]
@jaj22 we don't support PVP could we close this now?

**Comment by MeltedPixel** [comment]
Closing as per @Bob-Murphy
