### ISSUE TITLE
RHS VS1 ejection seat should be garbage cleaned

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1542]
**Is your feature request related to a problem? Please describe.**
The L39 and L159 aircraft from Blufor RHS CDF use the VS1 ejection seat (classname `rhs_vs1_seat`), which is not currently garbage cleaned.

**Describe the solution you'd like**
Add that classname to the garbage cleaner.

**Comment by Bob-Murphy** [comment]
done
