### ISSUE TITLE
Ammo truck mission has no spawn distance check, can spawn on top of players

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1546]
**Describe the bug**
Most missions that generate units on or near a marker are checked against the spawner list. The ammo truck mission isn't, so it may be spawned right in front of players. Annoying when you're trying to take an outpost and it dumps two squads on top of you. Also muh immersion.

**Expected behaviour**
Ammo truck mission shouldn't be generated for spawned outposts.

**Comment by AlexTriada** [comment]
+

**Comment by AlexTriada** [comment]
pls assign me for this issue
