### ISSUE TITLE
Enemy city attack victories do not increase government support

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1554]
**Describe the bug**
Since 2.3.1, enemy city attack victories apply very large city support changes in one call, right up to +100/-100 for a victory. This does not work as intended due to problems with the city support function:

1. The function applies government support changes first, and then rebel support changes. If a change would increase total gov+reb support beyond 100, the change is capped. Hence [100,-100] will often do the same thing as [0,-100], depending on previous state. This is by design, but it means the function doesn't work as expected with large swing values.

2. The capping code additionally has a bug where gov+reb+change > 100 but gov + reb < 100 will cause the support to reduce, instead of the originally intended result of increasing until gov+reb = 100. This is fixed in #1549.

I'll probably add a fix for point 1 in #1549 as well.

**Comment by Bob-Murphy** [comment]
merged
