### ISSUE TITLE
PvP spawn points should be placed within map borders

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#1557]
**Is your feature request related to a problem? Please describe.**
If PvP spawn outside of the map they will be subject to execution by explosion. Even next to their flag

**Describe the solution you'd like**
Move PvP spawns onto the map proper.

**Describe alternatives you've considered**
Add an exception to the execution if within their spawn marker.

**Additional context**
See picture dump.

**Comment by Bob-Murphy** [comment]
Thanks, Meerkat

**Comment by Bob-Murphy** [comment]
PvP will be disabled which makes this issue obsolete.
