### ISSUE TITLE
DesHeli missions spawning outside of the map

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1558]
Reported on discord at https://discord.com/channels/449481990513754112/647694189236322305/768452447801704489
![image](https://user-images.githubusercontent.com/50651578/96724491-2cb28180-13b0-11eb-83c3-30e902fa6053.png)

**Comment by HakonRydland** [comment]
Note to self: Des_Heli dosnt have a out of map block in its search for a suitable location
