### ISSUE TITLE
Make Resource Point Destruction Less Trivial

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#156]
Make it harder to accidentally destroy resource points with a stray grenade.

**Comment by Bob-Murphy** [comment]
The current system is that resources and factories get destroyed when a random placed civilian dies.

**Comment by wurzel0701** [comment]
The current system spawnes four civs and marks the outpost as destroyed once you kill all of them. As long as this mechanic is working as it should, it doesn't sounds to harsh to me. You just have to be careful with explosives of all kinds

**Comment by wurzel0701** [comment]
Closing as the system works as it should, just be careful around factories and resources

**Comment by Spoffy** [comment]
Reopened, because the system is unintuitive and still very easy to do by accident.

**Comment by wurzel0701** [comment]
Code done, debugging and testing will follow
