### ISSUE TITLE
Rebell Buyable Boats should be more logical

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1560]
**Is your feature request related to a problem? Please describe.**
There are currently 2 Buyable boats,
**civBoat**, Costs 200 buyable at HQ
**vehSDKBoat** Costs 400 buyable at Seaports by Buy Boat button

**In most cases you pay extra for SDKBoat, for Less slots and not being able to go Undercover.**

Most Templates used:
CivBoat:
3CB Templates used:
"C_Rubberboat" it has 1 Driver 4 Passenger Slots.
The rest used:
"C_Boat_Transport_02_F" as CivBoat it has 1 Driver 7 Passenger Slots.

vehSDKBoat
"B_G_Boat_Transport_01_F" same as "C_Rubberboat"
"I_C_Boat_Transport_01_F"  same as above
"I_G_Boat_Transport_01_F" same as above
**Describe the solution you'd like**

**A clear and concise description of what you want to happen.**
All Rebell Templates should use a **CivBoat** thats a small boat as "C_Rubberboat" 5 Slots in total
or "C_Boat_Civil_01_F" 3 Slots in Total.

All Rebell Templates should use a **vehSDKBoat** thats atleast worth the extra Money and not being able to go Undercover.
Also: **Side and Default Crew does not matter here, Boats spawn all without Crew only thing to watch out is that the Boat isnt used by Occ/Inv Faction**
For Example: 
Vanilla: Can't be changed unless we ignore DLC restriction 
![grafik](https://user-images.githubusercontent.com/57111907/96793638-09fa8a00-13fd-11eb-82fd-69efeeb65566.png)

With Apex Solution for SDKBoat
"I_C_Boat_Transport_02_F"

RHS: "rhsgref_hidf_rhib", for Bluefor, unknown about DLC cause it's just changed Crew.

3CB: 
"UK3CB_TKA_I_RHIB", Driver, Gunner, 10 Passengers, Armed with a .50 Cal.
"UK3CB_TKA_I_RHIB_Gunboat", Driver, Gunner, Rear Gunner, 7 Passengers, Armed with .50 Cal and a 40mm GMG in the Rear.
"UK3CB_TKA_B_RHIB_Gunboat", same as Above
"UK3CB_TKA_B_RHIB", same as Above
"UK3CB_BAF_RHIB_GPMG_DPMT", Driver, Gunner, 11 Passengers, Armed with a 7.62 GPMG.
"UK3CB_BAF_RHIB_HMG_DPMT", Driver, Gunner, 11 Passengers, Armed with a .50 Cal.

**Comment by jaj22** [comment]
Seems reasonable. I assume I_C_Boat_Transport_02_F is armed?

For vanilla it might be acceptable to ignore the DLC restriction here if there's no other option for superior boats (it's an optional purchase anyway), although you could instead use C_Rubberboat as the civ boat and C_Boat_Transport_02_F as the vehSDKBoat. It's certainly worth the extra money as it still supports undercover and it's much faster.

**Comment by Lazejun** [comment]
"I_C_Boat_Transport_02_F" nope, just Default Crew are Syndicate units, which doesent matter cause they spawn Empty

**Comment by Lazejun** [comment]
Also done with Template rework
