### ISSUE TITLE
HQ can sell Petros, breaking his personal money count into scalar NaN

### ISSUE THREAD

**Issue by ComboTombo** [official-antistasi-community/A3-Antistasi#1567]
**Describe the bug**
As HQ, you can get Petros into your group by clicking on the "Move HQ to different zone" button under HQ management. From there, you can select Petros and sell him via the Dismiss AI button under AI management. This will break HQ's personal money count, turning it into a NaN. Petros appears after a minute or so.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
1. As HQ, move to Petros and select "Move HQ to different zone"
2. Petros will now be in your squad. Sell him.
3. ???
4. Profit

**Expected behaviour**
HQ should not be able to sell Petros.

**Screenshots**
I got a video of it here https://youtu.be/klvE4MAaX7c

**Environment (please complete the following information):**
Version: 2.3.1
Map (specify if Altis Blufor): Tanoa

* [ ] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [X] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset: Community server's vanilla modset
    
Time the bug occurred (Please leave in GMT+0): Around 0940 UTC

**Additional context**
According to a member, the first instance of this bug was discovered by Masai at least 2-3 months ago, and that Masai reported it to an admin. Looking through the GitHub issues, I see no mention of such bug - although I may have not searched far enough - so here it is. I do not know if you can buy vehicles or units with money on scalar NaN, I didn't try it because I was on the community server and I didn't want to buy something using cheated money.

**Comment by CalebSerafin** [comment]
Main issues are here:
https://github.com/official-antistasi-community/A3-Antistasi/blob/26d88d5ff59fb7c521cf7c85b1af9100ee76e40d/A3-Antistasi/REINF/dismissPlayerGroup.sqf#L45
1) There is no filtering of units.
2) Petros is not in the unit cost list, this causes the addition to add scaler to nil.

So two changes:
1) implement filtering somehow. Maybe tagging units' objects on spawn.
2) Defensive programming that does not assume that every unit type has a cost value.

**Comment by jaj22** [comment]
There's an "owner" tag on purchased units, but the usage would need to be checked as it's also heavily used for remote control. Mission units should also be considered.

If it's too spaghetti then a specific petros check plus a default value on line 45 would do for the moment.

**Comment by AlexTriada** [comment]
pls assign me for this issue
