### ISSUE TITLE
Convoy Mission, Armor Convoy should be stealable.

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1568]
**Is your feature request related to a problem? Please describe.**
Armor Convoys lock the Armored Vehicle to prevent you from Stealing it.
https://github.com/official-antistasi-community/A3-Antistasi/blob/518facea4de9cdb090e0d5191445df3336402b4b/A3-Antistasi/functions/Missions/fn_convoy.sqf#L228

But the Text itself hints it's Steal OR Destroy so it should be able to be stolen.
https://github.com/official-antistasi-community/A3-Antistasi/blob/518facea4de9cdb090e0d5191445df3336402b4b/A3-Antistasi/functions/Missions/fn_convoy.sqf#L75

**Describe the solution you'd like**
We should remove the locking of the Vehicle cause the Text is missleading and disapointing.

**Describe alternatives you've considered**
We could also just remove the Part that mentions Stealing.

**Comment by RetardedFoX** [comment]
Would say it should be able to be stolen without needs of explosives, as many others in the community wants it to be. If not, then I would rather recommend to include some way to get explosives for this particular mission, instead of doing the lazy change text part.
My opinion.

**Comment by jaj22** [comment]
In theory petros could dump some appropriate explosives in the arsenal when handing you the convoy mission, although that's likely to run into conflicts when I sort out the charge categorization.

Alternatively, if armour convoys are intended to be relatively easy to steal, we could just remove the lock and avoid setting allowCrewInImmobile for that vehicle. Then the crew will probably jump out if the vehicle is disabled.
