### ISSUE TITLE
Look at destroyed marker rebuilding

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#157]
Cities are supposed to rebuild, however, the code is bugged so they can't be. Investigate whether this should be fixed.

**Comment by Spoffy** [comment]
Forget this - destroyed cities should never be repaired. Destroyed factories and resource points should be repaired, according to the code.

Rename destroyedCities to accurately represent the fact it contains resources and factories too

**Comment by wurzel0701** [comment]
Done in #349
