### ISSUE TITLE
Liberate commands for refugees and prisoners are broken for JIP clients

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1574]
**Describe the bug**
Release actions for refugees and POWs are created using a remoteExec of flagAction, JIP'd with the unit as ID (so that they're automatically removed from the queue when the unit is deleted). Shortly after, setCaptive is also JIP'd on the same unit and with the same ID, overwriting the flagAction remoteExec in the JIP queue. This means that clients that join after the mission is created will not have the liberate action.

Assuming that setCaptive isn't bugged, it shouldn't need (or benefit from) global execution, and it definitely shouldn't need JIP. The codebase would probably benefit from a general cleanup here to reduce unnecessary remoteExec/JIP spam, but in this case the locality of the unit on creation is guaranteed, so it should be safe to remove the remoteExec here even if setCaptive does have bugs.

**To Reproduce**
Probable: Start a refugee or POW mission. Log off and back on again. You will now not have the Liberate action in the dropdown menu on the refugees/POWs. Players that joined before the mission started will still have the action.

**Comment by AlexTriada** [comment]
pls assign me for this issue
