### ISSUE TITLE
JNL loading gets blocked when ACE Cargo full

### ISSUE THREAD

**Issue by ShoppyCodes** [official-antistasi-community/A3-Antistasi#1580]
**Describe the bug**
When using JNL to load something into the back of an Offroad (and I assume other vehicles), if you have a full ACE Cargo it says it has no space. However, you can empty the ACE Cargo, load JNL in the back, and then fill ACE Cargo again as a workaround.

**To Reproduce**
- Load a full ACE Cargo of stuff into vehicle
- Try to JNL load (Tested with supplies from supply mission and the big outpost boxes)
- It will tell you that you can't because its full.
- Unload ACE Cargo
- Load JNL (successfully works now ACE Cargo is not full)
- Now you have a box in the back of the car via JNL, try to load ACE Cargo
- It works, you now have a full car.

**Expected behaviour**
It would be ideal if you could load via JNL with a full ACE Cargo as well as load ACE Cargo with a full JNL load.

**Screenshots**

**Environment (please complete the following information):**
Version: Test Server 1 currently, sorry I don't know the version
Map (specify if Altis Blufor):  Altis normal/indi

* [ ] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [X] Community Test Server
* [ ] Community Test Server 2

Modset: RHS

**Comment by AlexTriada** [comment]
pls assign me for this issue

**Comment by CalebSerafin** [comment]
@HakonRydland I assume your rework already covers this?

**Comment by HakonRydland** [comment]
yes, iirc correctly JNL checks attached obj with a variable assigned to it(given on load), dont belive it clears it on unload, so if it was loaded with ace it would still count it.

**Comment by Bob-Murphy** [comment]
resolved because new logistics implemented
