### ISSUE TITLE
Fill crates with biome specific camos

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#159]
Outpost in the jungle should use different camos on weapons than outpost in the desert. As there is currently no idea how to actually do this (as we don't want to mark each outpost by hand), this will be stalled till we either have an idea or the time to dig deeper.

**Comment by PoweredByPot** [comment]
crates are getting a lot of love with loot crates 2. Although I don't deal directly with this issue in an awesome and intelligent manner, it will be better than the current implementation.

**Comment by Bob-Murphy** [comment]
This will not be worked on in near future if at all.
Can be reopened if the time comes.
