### ISSUE TITLE
Add a parameter for minimum items required for non-members to withdraw from arsenal

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#16]

**Comment by Bob-Murphy** [comment]
@Spoffy is this still needed? I don't see a need for it.

**Comment by Spoffy** [comment]
I still think this is valuable for other communities, and I'd like to see the option of reducing it here too (down to perhaps 10). I'd leave it open for now. Quick job to do, too.

**Comment by Bob-Murphy** [comment]
IIRC this one is currently set to 25.
Please implement this one and add it under the unluckItem class in params.hpp
