### ISSUE TITLE
Spam sell vehicle button.

### ISSUE THREAD

**Issue by mimizid** [official-antistasi-community/A3-Antistasi#1613]
**Describe the bug**
When using a mouse with macros or with an autoclick (such as a4tech bloody), you can get more money when selling equipment (instead of $25, I got up to $3k). Also with a set of garrisons. Thus, you can hire a huge number of units for a small amount of money, and then fire them and hire even more units. And so we repeat until the preservation breaks. 

**Screenshots**

**Environment (please complete the following information):**
Version: 1.4
Map: Takistan

* [x] LAN Hosted
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset:
CBA | CUP Terrain | RHS | ACE | Lambs | Enhanced Movement

**Additional context**
I noticed that this only happens under server loads.  Take a timeout to buy vehicles and recruit units. Even 0.5 seconds is enough.

**Screenshot**
Before and after. Since the server has just started, I was able to sell one pickup three times.
![20201210162310_1](https://user-images.githubusercontent.com/74767156/101766522-b6efaa00-3b04-11eb-9693-1d57fd0c656b.jpg)
![20201210162319_1](https://user-images.githubusercontent.com/74767156/101766524-b820d700-3b04-11eb-91ec-2b3fde5a20d0.jpg)

**Comment by CalebSerafin** [comment]
This fix for this lies in proper programming and not "just run put the functional code in the onClick event handler and hope it closes the menu in time.". 

My proposal is to move fn_sellVehicle to server-side (pass the cursorObject from then client). Place an "A3A_toBeDeleted" on the object to block other scripts (Variable is server scope only). Then run the rest of the code.
