### ISSUE TITLE
List of vehicles

### ISSUE THREAD

**Issue by riwarek** [official-antistasi-community/A3-Antistasi#1617]
**Is your feature request related to a problem? Please describe.**
After some time I have no idea how many and what vehicle I have. To check air vehs I have to go to the airfield, to check ground vehs I have to go to the HQ.

**Describe the solution you'd like**
It would be very convenient to make a list of vehs (faction and personal) under button. Just like "buy vehicle" button. This button may be active even outside the HQ.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by CalebSerafin** [comment]
Fixed in https://github.com/official-antistasi-community/A3-Antistasi/pull/1735
