### ISSUE TITLE
Move actions and dialogs that involve vehicles to the vehicle box.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#162]
Currently, accidents at HQ can occur when squishys and trucks mix. Allowing the vehicle crate to be in a designated open parking spot with vehicles never venturing towards the arsenal.

**Proposals:**
- [ ] Move the Garage and Faction Garage to the vehicle crate (except for Outposts and Airbases)
- [ ] Move the vehicle accessed arsenal screen to the Vehicle Box.
- [ ] Have Command Spawned AI Trucks spawn near the vehicle crate instead of the flag.

With these changes, we will sadly lose the ability to join the Antistasi Space Agency Program ASAP.

**Comment by Spoffy** [comment]
Done as of 89fc39d6c265adf32e220900827fd2653db171c0
