### ISSUE TITLE
Hired/liberated AI Drive Vehicles To/From Single Location

### ISSUE THREAD

**Issue by clairmont32** [official-antistasi-community/A3-Antistasi#1628]
**Is your feature request related to a problem? Please describe.**
AI hired cannot get into vehicles as passengers let alone be informed to drive them from one place to another. This also is the same for liberated AI.

**Describe the solution you'd like**
While physically present with the AI and an empty vehicle that is currently IDd as being under your ownership (get in as driver then get out), tell the AI to get in as driver then use map AI control to tell them to drive to a given location.

**Describe alternatives you've considered**
Drive a daisy chained set of vehicles to/from location with multiple trips.

**Additional context**
AI should be considered hostile towards other sides if they are controlled by you or have intent to join your side. Sending them into hostile environments should have them be shot at, killed or captured. This would result in losing HR and local support.

**Comment by SonorousMeerkat** [comment]
Hired full squads or squad members? I have hired squad members drive fairly often when i use them. Just a matter of learning how to use the AI controls in Arma. Not 100% on rescues like refugees but i assume they can drive too...

**Comment by Lazejun** [comment]
The Problem you are describing sounds more like your are having Issue with Arma 3 Ai controls rather than Antistasi.

"AI hired cannot get into vehicles as passengers let alone be informed to drive them from one place to another. This also is the same for liberated AI."

**Comment by clairmont32** [comment]
I may not be attempting it properly if the hired help under the Y menu based on your replies. Here's what I tried today-

Hired help
1. Press Y
2. Hire infantry squad and command them to go a couple meters away from the the truck
3. Walk over to truck, go into menu and Ctrl+Space click them
4. Back out of map and observe they're not controllable
5. Press F2-F8 but noticed they're not controllable 

Rescue Evac Mission:
1.  Liberate survivors
2. Control through F keys to go to vehicle
3. Use F keys to observe they only "get in vehicle" as passengers 

If the hired AI are able to be told to mount up into a vehicle, how is this done? How do you then also tell them to drive the vehicle to X location?

**Comment by SonorousMeerkat** [comment]
Rescue Evac Mission:

Select a unit, press 4(?) to get the mount menu, select vehicle, select driver's seat.
They will then mount up as driver.

Order as needed.

**Comment by clairmont32** [comment]
Oh, so it's not a F key but under the map just press one of the numbers? Did I miss this in some of the mission description or help menus?

**Comment by SonorousMeerkat** [comment]
This is base Arma AI controls. Antistasi doesn't change them at all.

(Note: "Select a unit" means with the F keys, and those instructions are for members of _your own squad_)

**Comment by Lazejun** [comment]
First of all you gotta know there is a difference in Behavior between High Command and Normal Arma Groups,

The "Hired" units are High Command, you give orders to their Group leader and he handles the rest accordingly,
If you buy them and give them a Truck they usually mount up and then can take orders, if you dont buy them a Truck you can just order them to walk, or Assign them a Vehicle via Y Menu AI Management.

F1-F10 to select a Group from 1 to 10, ^ <------ this key is Select all.
You can only give orders on Waypoints how they should behave and such.

They will dismount and Engage at will when under fire too.

Normal Arma Groups need your Input as Group Leader in the Case of the Rescue Mission, Ai tends to also get stuck in the Building when you directly tell them to mount up in a Vehicle, 
at best tell them to get Near the Vehicle first to ensure Arma pathfinding doesent do its thing.

F1-F10 to select a Group from 1 to 10, ^ <------ this key is Select all.
Keys: 
1 Move Menu
2 is Targets
3 Engage modes (Hold fire etc.)
4 Mount "Menu" (to specificly select vehicles)
5 Status
6 Actions (Open Inventory etc. Pick up weapons)
7 Combat Modes
8 Formations
9 Assign (For Color Teams)
0 Reply

**Comment by clairmont32** [comment]
> F1-F10 to select a Group from 1 to 10, ^ <------ this key is Select all.

Thanks for the explanation of this. It appears this was a lack of knowledge on how HC/Zeusing works in Arma. I've tried it in our server and it works as explained; albeit a little cumbersome in smaller area movements.

**Comment by clairmont32** [comment]
Is this a bug?
![20201220193604_1](https://user-images.githubusercontent.com/6239004/102728550-87a61d80-42fa-11eb-9c8b-747040719a2e.jpg)

**Comment by Bob-Murphy** [comment]
Are you playing an unpublished/unstable version?
It certainly looks like it.

**Comment by clairmont32** [comment]
Not that I'm aware of. A friend spun up the server about a week ago and we used the malden link provided in the readme
