### ISSUE TITLE
Typo in Stringtables, Fraction/Faction

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1635]
It seems Fraction and Faction was mixed.
![grafik](https://user-images.githubusercontent.com/57111907/103814960-e8f01f80-5062-11eb-9a09-48f6d83fc994.png)

**Comment by Toakan** [comment]
Oops...

**Comment by Preen1** [comment]
It builds character

**Comment by Preen1** [comment]
PR was approved, typos fixed

**Comment by Bob-Murphy** [comment]
will be closed automatically once merged
