### ISSUE TITLE
Malden, Outpost 12s Radiotower causes Bad Spawns/Bad Ammotruck Mission.

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1636]
AI realy wants to use the Helipad next to the Radiotower but its way to close so Ai **will** crash into it.

We should either move the Outpost Marker further away from the Radiotower as it also causes Bad spawns.

![107410_20210108211832_1](https://user-images.githubusercontent.com/57111907/104063790-0658f100-51fd-11eb-9c15-6f5efb4ae827.png)

As the Outpost itself is also not Connected to any road it spawns Ammotruck missions at the Dead end Marked in Red.

We could either accept the Fact that its that way and Any Ammotruck that spawns there will be less defended or move/remove Outpost_12

![grafik](https://user-images.githubusercontent.com/57111907/104064377-24732100-51fe-11eb-8a41-52a694b6b574.png)

**Comment by Preen1** [comment]
I've briefly gone through the Malden map and looked for suitable areas to move the Outpost to. I've found 5 areas that are: Connected to the main road structure, reasonably far away from other objectives, And have minimal changes in elevation. 
I've gone through and tested the areas to ensure that they will fit and they all seem to fit well barring a few minor tweaks for things like rocks and trees. 

I've also included the coords for each area, They correlate to the approximate center of the outpost. 
```

Numbered for easier identification. 
1: [6697.24,11380.6,0.00177383]
2: [6493.38,10681,0.00149536]
3: [5804.22,9973.2,0.00114441]
4: [4468.5,8509.04,0.00106812]
5: [6756.55,3325.45,0.0014267]
```
![20210203201136_1](https://user-images.githubusercontent.com/78278253/106836239-67d67900-665e-11eb-8aaa-ea0de57c58eb.jpg)
