### ISSUE TITLE
wrong code

### ISSUE THREAD

**Issue by AlexTriada** [official-antistasi-community/A3-Antistasi#1644]
https://github.com/official-antistasi-community/A3-Antistasi/blob/15db28d6dcc2f8888e0cb66d34e61ab12e220481/A3-Antistasi/functions/Base/fn_distance.sqf#L155

**Comment by AlexTriada** [comment]
this fixed with my #1643

**Comment by HakonRydland** [comment]
pls follow our issue templates

**Comment by AlexTriada** [comment]
> pls follow our issue templates

did you help me with that?

**Comment by HakonRydland** [comment]
when you click new issue, you will get a choice between; Bug report, Change requested, Feature suggestion, and Game balance. with descriptor of what they are used fore, for this it sounds like Change or bug.

as this issue has practically nothing in it, i recommend creating a new one and closing this one.

**Comment by AlexTriada** [comment]
i was not click new issue, i click in the file

**Comment by AlexTriada** [comment]
i dont know what the issue this might be, i find the wrong code that might will to issue
