### ISSUE TITLE
[Feature Request]: ACRE2 jamming

### ISSUE THREAD

**Issue by riwarek** [official-antistasi-community/A3-Antistasi#1645]
**Is your feature request related to a problem? Please describe.**
As far as I know when I use ACRE radios there is no jamming near Radio Towers.

**Describe the solution you'd like**
Jamming should be present.

**Describe alternatives you've considered**
none

**Additional context**
Possible solution of this problem may be implementation of this script
https://forums.bohemia.net/forums/topic/216214-release-acre2-custom-signal-calculation-jam-or-boost-your-radios-signals
https://github.com/diwako/ACRE2-Custom-Signal-Calculation

**Comment by Lazejun** [comment]
Could look into it, thanks for giving an example, most of us don't use Acre so it's kinda left behind 👀

**Comment by killerswin2** [comment]
This wasn't done

**Comment by Bob-Murphy** [comment]
Ah, it wasn't merged into unstable as it seems.
#2285 contains the following which I, I guess, misinterpreted.
![image](https://user-images.githubusercontent.com/50651578/228582928-19a5a65d-a4b3-4720-ac54-fb55dff489a4.png)

**Comment by Bob-Murphy** [comment]
Feature request was done and implemented with version 3.3.0
