### ISSUE TITLE
GitHub tab size

### ISSUE THREAD

**Issue by AlexTriada** [official-antistasi-community/A3-Antistasi#1650]
Please add file .editorconfig to the root of repository and add this lines to it
```
[*.{sqf,hpp,ext,inc}]
charset = utf-8
indent_style = tab
indent_size = 4
```
this change tab size in github veiw and editor in all branches that have this file
default tab size 8 is very ugly

**Comment by Giddius** [comment]
possibly add these two parameters(with whatever value):
```editorconfig
trim_trailing_whitespace = true
insert_final_newline = false
```

**Comment by AlexTriada** [comment]
Dude, in the GitHub veiw  window this is not necessary, do this in the editor settings

**Comment by Giddius** [comment]
yeah but isn't this also for overall uniformity and not only for viewing on github ( if you clone it and when you pushed it)?

**Comment by AlexTriada** [comment]
it is only for viewing on github, i don't know much more about overall uniformity, so if you want, you may yourself open the same issue - may be you are wright and others agree with you
