### ISSUE TITLE
Be able to change the surrender-crates as well as the box for the salvage mission based on modset/template

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1660]
**Is your feature request related to a problem? Please describe.**
I need this change for Things and Reasons

**Describe the solution you'd like**
Add the crate of choice to the templates directly under the ammobox and add comment that if the classname is changed, the new classname needs to be also defined in the logistics system.

**Describe alternatives you've considered**
don't have an alternative

**Comment by HakonRydland** [comment]
merged into new templates
