### ISSUE TITLE
Wiki: Script requests

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1678]
**Script request 1**
A script that reads out the cities and villages as well as the size and the amount of civs per city for the map loaded so we would have with Antistasi inculding the coordinates to be copied from.
Output format: `[name, amountCivs, type, position, radiusA, radiusB]`for each
This script can be depending on having Antistasi loaded.

**Script request 2**
A script that reads out all map markers from cfgWorld/mapname/names for the loaded map and gives out `[name, type, position, radiusA, radiusB]` for each.
This needs to be executable **without** Antistasi loaded.

Please add the scripts with a 1-2 sentence explanation (aka you can rephrase what I wrote in the requests) at the following wiki page.
https://github.com/official-antistasi-community/A3-Antistasi/wiki/random-dev-scripts

**Comment by Preen1** [comment]
Single script, not Antistasi dependent but will run with Antistasi.
 Posted to https://github.com/official-antistasi-community/A3-Antistasi/wiki/random-dev-scripts
