### ISSUE TITLE
Sahrani map feedback

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1686]
For now, use this to collect feedback regarding the map. Will be fixed in one push

- initial starting spot does not give easy access to a city, might needs replacing
- with the new support system in mind, quite a few positions could use some extra cover so players are not always on the silver plate
- dorky tower placement
![image](https://user-images.githubusercontent.com/50651578/106676776-c8f74180-65b7-11eb-9fbd-5f969477f771.png)
![image](https://user-images.githubusercontent.com/50651578/106676789-d0b6e600-65b7-11eb-9369-4f4c2efecc1b.png)

**Comment by Preen1** [comment]
From Firehawk: Fast-traveled to Airbase marked by 1 in an Offroad, ended up roughly at marker 2 at the airbase. Likely due to lack of road on Airbase
 [1?[](url)](url
![unknown](https://user-images.githubusercontent.com/78278253/106694992-4a8ea580-659f-11eb-9b3e-5dd5625ecc27.png)
)

**Comment by CalebSerafin** [comment]
From Discord: In Antistasi Sahrani, the default start location has "enemies nearby," making it usually impossible to go undercover or buy units, etc. Using default parameters, and running 3CB + RHS.

**Comment by Lazejun** [comment]
To make sure it doesent get lost:
outp_12_vehicle is not long enough for vehicles required are 10 meters!
outp_12_vehicle_1 is not long enough for vehicles required are 10 meters!
reso_8_vehicle is not long enough for vehicles required are 10 meters!
reso_5_vehicle is not long enough for vehicles required are 10 meters!
reso_4_vehicle is not long enough for vehicles required are 10 meters!
outp_13_vehicle is not long enough for vehicles required are 10 meters!
reso_14_vehicle is not long enough for vehicles required are 10 meters!

"outpost_14" might have the Vehicle marker too close to objects
![107410_20220218201435_1](https://user-images.githubusercontent.com/57111907/154747799-1d3ed32d-013f-4c05-9e7a-c1b962077baa.png)
![107410_20220218201439_1](https://user-images.githubusercontent.com/57111907/154747804-508808bc-9feb-4a1a-ab39-88be10785bef.png)

**Comment by Bob-Murphy** [comment]
No worries. I'm overhauling all maps and also starting every mission to look at the logs.
Here's part of my list
![image](https://user-images.githubusercontent.com/50651578/154759001-bfcd69a5-1646-4923-9cd7-769efdc83078.png)

**Comment by Bob-Murphy** [comment]
merged into unstable
