### ISSUE TITLE
[Change Request]: AI or FPS limiter? What is what?

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1699]
In the lines 858 until 995 in dialogs.hpp certainly is something fishy.
Multiple classes have AI limiter and FPS limiter mixed up.
Somebody please investigate.

![image](https://user-images.githubusercontent.com/50651578/107640278-526ed980-6c72-11eb-8e66-decb77ef83d1.png)
![image](https://user-images.githubusercontent.com/50651578/107640383-7d592d80-6c72-11eb-8f70-91bfd303e35a.png)

https://github.com/official-antistasi-community/A3-Antistasi/blob/aff24d3388a304b91a4cb82921d003b7b845955a/A3-Antistasi/dialogs.hpp#L858

**Comment by jaj22** [comment]
The classname for the AI limit dialog is `fps_limiter`. The references to the button text strings are `$STR_antistasi_dialogs_maps_fps_limiter_plus` and `$STR_antistasi_dialogs_maps_fps_limiter_minus`. That's it.

**Comment by CalebSerafin** [comment]
Probably something that can be refactored. FPS limiter is a misleading description of what it is.

**Comment by jaj22** [comment]
Closed. Dead code now.
