### ISSUE TITLE
Redo createCIV to use a non dynamically approach

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#1720]
**Is your feature request related to a problem? Please describe.**
With the change to the new navGrids createCIV had its _roads assingment replace by something that searches for the roads every time, which takes way more time than the old system. As the old roadsDBs got deleted, we need a different approach here.

**Describe the solution you'd like**
A solution would need to be faster than searching the road segments every time

**Describe alternatives you've considered**
Two alternatives:
- Search for roads once and then cache them to reuse them. Would be especially good for longer running server

- Use a random position around the city and then search the next nav point, keep in mind that nav point searching needs a bit of time too

**Additional context**
I am not entirely sure how slow the search actually is, nor how often it gets called anyways (depends on traffic parameter I guess), maybe that is something worth checking first, however, the file needs a rework to be adapted to our coding stylelines

**Comment by jaj22** [comment]
I checked the performance of `nearestTerrainObjects` and it's remarkably fast, even when spammed with random coords and radii around areas with high road density. Even the first call seems to have very low latency, so I'm guessing that the maps are encoded with spatial partition trees that make this command fast, at least by SQF standards.

Maybe Arma saved us some trouble for once.
