### ISSUE TITLE
MP on localhost don't want to initialize

### ISSUE THREAD

**Issue by riwarek** [official-antistasi-community/A3-Antistasi#1727]
**Is your feature request related to a problem? Please describe.**
Every session I play in SP I see this mode will be not supported in the near feature (BTW this black screen is extremely annoying). Advice is to run the game on localhost MP.
When I try to do this, not using dedicated server but simple localhost, game starts but no scripts are initialized. I know it may take some time but even when I wait a minute nothing happens.

**Describe the solution you'd like**
I am not sure isDedicated decide about initialisation of the scripts but if yes, it would be nice to inform player who runs the mission on localhost about it.
And please change this SP full screen message to help info.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by Lazejun** [comment]
A lot more informations would be requiered to get the Full Picture:
How are you launching the Missions, What Exact version are you using,
What Mods are you using, is it a Excessive amount of Mods?

Maybe include your Clients .RPT that would help a lot too

**Comment by riwarek** [comment]
I am not sure is it a bug or feature. I supposed it is a feature then I requested info about initialisation. Thats why I used Suggestion template.

My list of mods are:
https://steamcommunity.com/sharedfiles/filedetails/?id=1913659115

I run mission succesfullty in MP dedicated server mode and MP mode.
Problem occures only in MP localhost mode (LAN and Internet).

I use last unstable version from git. I build it by myself.

I will prepare and publish a movie. I will provide link to it here soon.

**Comment by SonorousMeerkat** [comment]
Your modset doesn't have any obvious issues to me, you said you gave it a minute but we do recommend 5-10 in case something is being particularly slow. 

Your RPT would be helpful in diagnosing if there is an issue here, please provide one from where the mission doesn't start.

We also don't recommend building the unstable branch unless you know what you are doing, stability isn't always guaranteed but we do try not to break things.

**Comment by Bob-Murphy** [comment]
> I use last unstable version from git. I build it by myself.
Please don't!
It's called unstable for a reason and we can't troubleshoot it as we can't even know which commit exactly you have!
Thank you.

**Comment by riwarek** [comment]
@SonorousMeerkat
In SP I have on my PC init script reaction in a 20-30 sec. Full setup takes 40-50 sec. It is worst scenario.
In MP dedicated, full setup takes about 20-30 sec. (it is significantly faster then in SP), there practically no init reaction in the briefing. 
Tommorow I will provide also RPT.
@Bob-Murphy 
I am aware of "unstable", hovewer I use unstable-Altis about 2 years and unstable Virolahti about half year. It is quiet stable :) Bugs are rather imperceptible. To be honest I have strong team which plays on unstable 2.4 modified by us and I really appreciate your work - this scenario should be provided as official. 
But no, we didn't touched init things.
Recently I just started play in SP and accidentaly discovered issues described in first post. I am just inform you. Nothing more.

**Comment by riwarek** [comment]
I see in logs such warning:

21:37:15 Warning Message: Include file D:\Users\rom\Documents\Arma 3 - Other Profiles\Czarny\mpmissions\AntistasiGithub\Map-Templates\Antistasi-Livonia.Enoch\defines.hpp not found.
--
This mpmission/AntistasiGithub is a directory where I keeep git anstistasi. 
I build this mission, convert i to pbo and I see this file in pbo. I also just copied whole uncomressed to pboe directory and I still see this warning.

**Comment by Bob-Murphy** [comment]
Based on the fact that you used unstable and we can not know off which commit you pulled it and you did edit the files on your own and don't have the time to deal with individual versions, we are not able to help you at all.
Please use the stable versions available at https://github.com/official-antistasi-community/A3-Antistasi/releases/latest.
This issue herewith is closed.

**Comment by riwarek** [comment]
Really? Thats all? I thought you are interesting in bugfixin of unstable. But OK.
