### ISSUE TITLE
No money rewards on enemy death

### ISSUE THREAD

**Issue by morrisons90** [official-antistasi-community/A3-Antistasi#1754]
https://github.com/official-antistasi-community/A3-Antistasi/blob/e62a46e4356b5a952f9228347af58c9196bae370/A3-Antistasi/functions/CREATE/fn_FIAinitBASES.sqf#L52

I was trying to see if I was meant to be getting something per kill and from what I can tell you are but not in multiplayer. Is this right?

I'm using a locally hosted game to play as a single player but there is no reward notification for kills.

Thank you.

**Comment by HakonRydland** [comment]
wrong file, its added but UI isnt updated. next resource tick or if you for example buy something it will update

**Comment by morrisons90** [comment]
Thank you
