### ISSUE TITLE
Battle menu under custom key

### ISSUE THREAD

**Issue by riwarek** [official-antistasi-community/A3-Antistasi#1760]
**Is your feature request related to a problem? Please describe.**
Battle menu button is hardcoded as a battle menu invoker. It is problematic because some of people use it to something else.

**Describe the solution you'd like**
Any button should be possible

**Describe alternatives you've considered**
none

**Additional context**
Possible change in fn_keys.sqf, line 6

`if (inputAction "User16" > 0) then
	{...}`

Then any button under User16 may be used. Of course it may be any free UserXX.
I already tested it and it works also with artillery combination.
It may also require info about binding need in init customHint, but this is rather easy to solve.

**Comment by CalebSerafin** [comment]
I think it is a good idea to do this now during the interim until we have a keybinding system.
We can copy&paste the EH code from customHintInit.
