### ISSUE TITLE
RHS turning out while starting engine damages players

### ISSUE THREAD

**Issue by Preen1** [official-antistasi-community/A3-Antistasi#1767]
**Bug Description**
Turning out as a driver while the engine is still in the "starting" phase will send all occupants of the tank (and in one case the actual tank itself) to the bottom left boundary of the map. As a result, those who are teleported will be killed as a result of the map boundary timer and the vehicle will be destroyed.

**To Reproduce**
Get into the driver's seat of a tank (in our case, the Woodland camo M1A1 FEP) and start the engine. While the engine is still starting, select the "turn out" action on the action menu. Your character should look to the left and your view should be locked.  You will then be teleported outside the map boundary (I think to 0,0 not certain, however.) and you and your tank will die after an agonizing 30 seconds.

**Expected behavior**
The player turns out of the driver's seat and does not get a one-way ticket to hell.

**Screenshots**
No screenshots, However, Server 1 logs will be attached from the point at which the bug occurred.
**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 
Virolahti

* [ ] LAN Hosted 
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [x] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset:
 Default modset for server one (Date 3/10/2020)

**Additional context**
 For reference in the attached server log, Eli Porter was in the driver's seat and turned out. Nix was the commander and was inside the tank, and Preen was in the gunner seat. Shawn and Espartero were in a second tank which also exploded but was not teleported. I am unsure what positions they were in but we believe that they were killed by another entity teleporting back into them and resulting in the tank getting arma'd

[Server-1 Log 3.10.21.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/6115010/Server-1.Log.3.10.21.txt)

**Comment by HakonRydland** [comment]
> Ah, RHS damages the turret so that it cannot move. Not sure what the best solution is here.
> 
> 1. Disable FF on vehicles.
> 2. Disable when RHS or some other mods are loaded.
> 3. Create a big blacklist of RHS vehicles that lock up the turret with that hack.

1) whats the source of the damage from armas pow? im assuming a player in the same vehicle.
2) can we detect what was damaged, vehicle or player in vehicle.
3) assuming damage was done only to overall damage, could "damaged" eh be used to work around this issue, or would there reported unreliability be an issue (ie, they are actually truly unreliable)

**Comment by CalebSerafin** [comment]
@Preen1 Was there any FF message?
According to logs from that day, the FF system did not fire.
Damage yes, FF no.

The FF system teleports players between 0,0 and 100,100. And places them on a sunboard. It also ejects players from vehicles.

**Comment by HakonRydland** [comment]
VR test found no triggering of "Dammage", "Hit", or "HitPart" EH on turn out/inn before, durring, and after engine start. (LH no other players in vehicle, only AI)

**Comment by Preen1** [comment]
@CalebSerafin No, none of the players involved got a message. I'd need to test it again but it also seemed like if you turned out of driver seat while you were the only occupant of the tank, then you would not get teleported

**Comment by CalebSerafin** [comment]
Note, although this case will be handled correctly. I would still like to know why RHS tanks are hurting people.

**Comment by Preen1** [comment]
I believe that it's a bug within RHS itself. My first guess would be that the player interacts with the turret weirdly when turning out of the driver seat. I know that a few other RHS vics won't let you turn out of the driver seat when the turret is in a specific position.
