### ISSUE TITLE
Enemy resource drains too quickly, leading to easy mission completion if you wait it out.

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#1778]
**What, in your opinion, is currently wrong with the balance?**
Currently if you spend an hour or two taking a single objective or two, the logic will throw a large amount of QRF in response. Continuing to flip an objective effectively drains the enemy pool, leaving you without any real challenge to the objective.

At this point, you the balance is out and makes it easier to take subsequent objectives.

**Describe the solution you'd like**
The regeneration rate needs to be increased.

**Comment by Toakan** [comment]
@wurzel0701 can you take a look at this one?

**Comment by jaj22** [comment]
Obsolete.
