### ISSUE TITLE
Game balance issue regarding the beginning of game (esp. for single player)

### ISSUE THREAD

**Issue by DracheTek** [official-antistasi-community/A3-Antistasi#1782]
**What, in your opinion, is currently wrong with the balance?**
In Vanilla game, the guerilla is started with .45 submachinegun and 9mm submachinegun. These two weapons does literally nothing against BLU body armor in 200~300m range, in which BLU force spots GUR squad and wipe them out with their automatic rifle and 2x scopes

**Describe the solution you'd like**
Unlock M-14 and AKM if apex is detected. 
Unlock Katiba if not
add some more missions that does not involve fighting but grants good amount of reputation so one can earn HR early in game. 

**Describe alternatives you've considered**
I would really like a dev come to explain why it is designed the way it is now.
I could fix this myself but I am just curious. Is that designed for multiplayer/coop?

**Comment by Lazejun** [comment]
The SMGs are already the Highest thats allowed.
Shotgun>Bolt Action> SMG

**Comment by wurzel0701** [comment]
This is the intended behaviour. Rebels in their starting phase have no access to body armor or anything beside shitty guns (there are suggestions to reduce that to pistol only too) and should not engage actual military troops in this stage. Hit and runs against police units are recommended to gather body armor, then hit and runs against roadblocks to get acceptable guns.

More missions that are especially designed for early game and involve less fighting are planned, but these take time. If you have a detailed idea for some, you are free to leave them here.

You can unlock whatever weapon you want at start, if you think you cannot make it without it, there are commands to unlock every piece of equipment out there.

However, we will not unlock assault rifles from start in any official version any more.

**Comment by DracheTek** [comment]
Robbing pair of police is the "proper" way to go through the early stage. noted. 

The problem is that less dangerous "civil support" mission (namely transporting boxes to cities) are very much "mixed" with military attempts (robbing ammo truck/snatch packages). If I happens to get missions in "more military" category, I have to wait for a very long period for a mission refresh. That is as well awkward in single player early game session. I suggest to add a checkbox that distinguish between "civil support mission" and "military raid mission".

As for suggestion to missions, I have not explored much into that because of the reason above. I may have to review code and come up with some ideas later.

**Comment by jaj22** [comment]
Support missions are split from logistics in 2.4. Even city support missions are quite dangerous though, and I wouldn't recommend attempting them without rifles and body armour. Ammo truck missions are often easier, although they're very location-dependent.

It's a lot easier to get over the initial equipment hurdle with RHS. Even if you're a barbarian who doesn't like the Kar98, you can just run over some police units to pick up good guns and level IV vests. Still, one vanilla roadblock gets you a lot of MXs.
