### ISSUE TITLE
[Change Request]: Split A3A_fnc_build

### ISSUE THREAD

**Issue by doommetal** [official-antistasi-community/A3-Antistasi#1793]
**Is your feature request related to a problem? Please describe.**
Needed for UI rework. Makes information about construction state able to be displayed as a tooltip on the construct button.

**Describe the solution you'd like**
Split the function into two parts:
1. A3A_fnc_canBuild: Checking if building is available, should return a boolean and an array of reasons if false
2. A3A_fnc_build: Everything from beyond the availability check

**Describe alternatives you've considered**
We could leave the function as is though this means either no UI feedback on why you can't construct (leaving it with the hintboxes) or it requires duplicate code for the checks to be able to be displayed in the UI.

**Additional context**
![construct](https://user-images.githubusercontent.com/4264673/111471377-20490f80-8729-11eb-8a52-d6f1c56b3a69.png)

**Comment by killerswin2** [comment]
not needed with the new builder
