### ISSUE TITLE
AI Skill not properly scaling

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#181]
AI skill doesn't correctly scale up and down according to difficulty. It varies between supersoldiers and dumb as a pile of bricks.

**Comment by Spoffy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve AI](https://trello.com/c/OBtEJQqj/38-improve-ai)

**Comment by AlexTriada** [comment]
For public servers it would be nice to make skill = 1 for all enemy bots and ours in params, I would be very grateful if I did not have to do this after each update

**Comment by PoweredByPot** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QRF Adjusts to playercount / easier SP QRF](https://trello.com/c/MH1fESAu/6-qrf-adjusts-to-playercount-easier-sp-qrf)

**Comment by PoweredByPot** [comment]
fixed in #273
