### ISSUE TITLE
Friendly AI did not spawn in static weapons

### ISSUE THREAD

**Issue by MrStonkus** [official-antistasi-community/A3-Antistasi#1811]
**Describe the bug**
Friendly AI did not spawn in static weapons.
This happened right after update to Version 2.4.0

**To Reproduce**
Buy static weapon, place. 
Garrison solders. Go away more than 1KM, came back, look how AI observe static weapons.

**Expected behaviour**
AI must spawn into static weapons.

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 
Altis

**Comment by Lazejun** [comment]
Are you sure you actually left Spawn distance, the units need to fully despawn.

I just tried it as of 2.4.0 and i can confirm it works on HQ.

![107410_20210322182651_1](https://user-images.githubusercontent.com/57111907/112032077-4cef9380-8b3c-11eb-9c39-1bdf8fc24283.png)

**Comment by MrStonkus** [comment]
I found a solution.
I disbanded the garrison and added them again.
It solved my problem.

But, refund for disbanded garrison was 0€ :(

**Comment by MrStonkus** [comment]
Solved, need disband and add again.

**Comment by MrStonkus** [comment]
> Are you sure you actually left Spawn distance, the units need to fully despawn.
> 
> I just tried it as of 2.4.0 and i can confirm it works on HQ.
> 
> ![107410_20210322182651_1](https://user-images.githubusercontent.com/57111907/112032077-4cef9380-8b3c-11eb-9c39-1bdf8fc24283.png)

This was with my garrison that was added to sector prior update.

**Comment by HakonRydland** [comment]
switching modsets could have caused the 0€ refund as it the unit class no longer exists.
in general switching from one version to the next within community is fine, changing mod sets is not, and switching from a 3rd party version to community can cause god knows how many issues as they could have fucked up a lot of stuff.
