### ISSUE TITLE
Adding Garrison issues.

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1814]
**Describe the bug**
High Command Squads will disaper and not be added to a Garrison if you add them via AI Management, Add to Garrison while they are not in the Area.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
Add a High Command Squad to a Garrison thats not within Range, the Garrison count will not increase.

**Expected behaviour**
It should add the Units to the Garrison, i checked and confirmed it worked in 2.3.2 so its very likely it broke due to Templates.

Modset:
Unrelated to the Issue.

**Additional context**
There are other Reports of Garrisons not working but i was not able to Reproduce those:
Apparently Ai doesent mount Statics (Could be that they never despawned the Area)

**Comment by Orange1861** [comment]
I can confirm that this only broke in the most recent update and it affects ALL garrisioning.
