### ISSUE TITLE
Several town markers appear in bad places on Tanoa, such as in water, on cliff faces, etc.

### ISSUE THREAD

**Issue by SpadesNeil** [official-antistasi-community/A3-Antistasi#1817]
**Describe the bug**
However Antistasi decides to place town markers is causing markers to appear in the water at many of the towns throughout the map. The result is that missions like delivering supplies cannot be completed. It also probably messes with some other things like fast travel or garrisons but I haven't tested any of that yet.

**To Reproduce**
1. Start a mission of Antistasi on Tanoa.
2. Check the location of own markers across the map. A whole bunch of them are in unreachable spots.

**Expected behaviour**
For town markers not to be in the water or on cliff faces. Instead of automatically assigning town markers based on where the town's name is written on the map, maybe have a means of overriding this when the position of those names are problematic, such as they are on many of Tanoa's towns.

**Screenshots**
These are just some examples. There are many more not listed.
![ArmA 3 Screenshot 2021 03 27 - 23 20 26 45](https://user-images.githubusercontent.com/6484985/112741714-09d75b00-8f56-11eb-9603-3b71dc2d4e2b.png)
![ArmA 3 Screenshot 2021 03 27 - 21 15 07 63](https://user-images.githubusercontent.com/6484985/112741715-0a6ff180-8f56-11eb-97e5-81d942734986.png)
![ArmA 3 Screenshot 2021 03 27 - 23 20 03 59](https://user-images.githubusercontent.com/6484985/112741716-0a6ff180-8f56-11eb-9e3f-f5a5ad13884d.png)
![ArmA 3 Screenshot 2021 03 27 - 23 20 15 76](https://user-images.githubusercontent.com/6484985/112741717-0b088800-8f56-11eb-81e2-bc141b782d9f.png)
![ArmA 3 Screenshot 2021 03 27 - 23 20 19 55](https://user-images.githubusercontent.com/6484985/112741719-0b088800-8f56-11eb-991e-3adde64b2e26.png)
![image](https://user-images.githubusercontent.com/6484985/112741806-c16c6d00-8f56-11eb-958b-dbbe75120a22.png)

**Environment (please complete the following information):**
Version: 2.4
Map: Tanoa

* [ ] LAN Hosted
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset: N/A, problem occurs regardless of mod set, including pure vanilla.
    
Time the bug occurred (Please leave in GMT+0): 11PM
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: EDT

**Additional context**
I do not fully understand how map markers are chosen for towns and I am only assuming that Antistasi chooses the markers based on the location of town names on the map. I have no idea if this is accurate. I just know when I tried to fix it myself in the editor, I wasn't able to do that because there was nothing there to change.

**Comment by jaj22** [comment]
Accidentally broken in 2.4. It used to move city markers to the nearest road, but the road-scanning code was removed during the pathfinding update, and now it just uses the original town name positions. These are particularly bad on Tanoa.

I'll be fixing this in the initZones refactor, as the city placement needs changing for some new maps anyway.
