### ISSUE TITLE
Difficulty is broken.

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#182]
1) the configs use a value of 0.5 for easy which I think is broken because it only accepts whole numbers.
2) the math that is used to create the difficulty scale applies equally to allied and enemy units. (should be inverse so easy has smart AI allies and stupid AI enemies and vice-versa)
3) the math that should create a slide of reasonable unit skill assignments is creating a broken range:
// current initial skill is [0.025,0.05,0.1] based on difficulty. at skillFIA = 10 [0.25,0.5,1] at 20 [0.5,1,2]

**Comment by PoweredByPot** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve AI](https://trello.com/c/OBtEJQqj/38-improve-ai)

**Comment by AlexTriada** [comment]
For public servers it would be nice to make skill = 1 for all enemy bots and ours in params, I would be very grateful if I did not have to do this after each update

**Comment by PoweredByPot** [comment]
@AlexTriada 
AISkill slides from 0 to 1, with 0.01 being an almost completely useless unit, to 1 being a super-soldier with perfect vision, and hearing, instant zeroing time, etc.

a reasonable range for AI skill as a whole is somewhere between 0.2 to 0.75ish

**Comment by Bob-Murphy** [comment]
@AlexTriada 
Based on what you have commited as a pull request i think it's good to say that you have at least decent skills when it comes to this programming stuff.
We have a dev-team in the antistasi community and if you are interested I would like to talk to you about the possibility that you maybe would like to join us instead of working "independent".
We certainly could use your skills.
So if you don't mind please feel free to join our TeamSpeak at 206.221.183.138 and we could have a little talk.
Also, have you been part of the ANtistasi Community in the past? Your name rings a bell for at least 1 guy.

**Comment by AlexTriada** [comment]
> @AlexTriada
> AISkill slides from 0 to 1, with 0.01 being an almost completely useless unit, to 1 being a super-soldier with perfect vision, and hearing, instant zeroing time, etc.
> 
> a reasonable range for AI skill as a whole is somewhere between 0.2 to 0.75ish

- i know)) recently we play only with bot skill = 1 and nobody want to play with  0.75 and more useless

> @AlexTriada
> Based on what you have commited as a pull request i think it's good to say that you have at least decent skills when it comes to this programming stuff.
> We have a dev-team in the antistasi community and if you are interested I would like to talk to you about the possibility that you maybe would like to join us instead of working "independent".
> We certainly could use your skills.
> So if you don't mind please feel free to join our TeamSpeak at 206.221.183.138 and we could have a little talk.
> Also, have you been part of the ANtistasi Community in the past? Your name rings a bell for at least 1 guy.

Yes it was me. I am speek english very low so so it’s unlikely that I can talk

**Comment by Bob-Murphy** [comment]
Was it you who worked in implementing VCOM in the past?

**Comment by AlexTriada** [comment]
> Was it you who worked on implementing VCOM in the past?

No) But really wanted and here I am!

**Comment by PoweredByPot** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QRF Adjusts to playercount / easier SP QRF](https://trello.com/c/MH1fESAu/6-qrf-adjusts-to-playercount-easier-sp-qrf)

**Comment by PoweredByPot** [comment]
fixed in #273
