### ISSUE TITLE
玩一段时间，大约一小时后，会出现卡死的情况。

### ISSUE THREAD

**Issue by lhc121212** [official-antistasi-community/A3-Antistasi#1821]
I test the original version 2.3 and 2.4 have a common problem, that is, after playing for a period of time, when the player revives, all kinds of functions are temporarily unavailable, that is to say, all kinds of links can't be clicked, and it will take a long time to recover. Previous versions did not have this problem.

**Comment by Toakan** [comment]
@lhc121212 What mods are you using with Antistasi?

Do you have an RPT from the server & client that can be shared?

**Comment by lhc121212** [comment]
> @lhc121212你用什么模组与安提斯塔西？
> 
> 您是否有可以共享的服务器和客户端的RPT？
RHS，
There are only two kinds of errors in RPT:
 1：
12:13:08 Suspending not allowed in this context
12:13:08 Error in expression <sleep 30; >
12:13:08   Error position: <sleep 30; >
12:13:08   Error 表达式内有一般错误
——————————————————
2：
12:13:07 Error in expression <[] spawn >
12:13:07   Error position: <>
12:13:07   Error 无效的表达
12:13:07 Error in expression <while {true} do >
12:13:07   Error position: <>
12:13:07   Error 无效的表达
12:13:07 Error in expression <}; >
12:13:07   Error position: <}; >
12:13:07   Error 丢失{
12:13:07 Error in expression <}; >
12:13:07   Error position: <}; >
12:13:07   Error 丢失{
