### ISSUE TITLE
On Tanoa, move PvP spawn points to better locations

### ISSUE THREAD

**Issue by SpadesNeil** [official-antistasi-community/A3-Antistasi#1822]
**Is your feature request related to a problem? Please describe.**
Mostly I want this done so I can have my issues on https://github.com/official-antistasi-community/A3-Antistasi/issues/1823 and https://github.com/official-antistasi-community/A3-Antistasi/issues/1824 fulfilled, but even if those get rejected, this change should be done anyway.

It's silly that the PvP spawns are so far away from their respective nations. They should be closer.

Yes I know PvP isn't being developed right now. Until the feature is totally removed, there's a chance it might come back in the future. The change is as easy as drag and drop to a new location. It really isn't that much trouble to do, and servers who use PvP will appreciate it still.

**Describe the solution you'd like**
Blue for Blufor, red for Opfor, I marked the islands where the PvP locations should be moved to.
![TanoaMarked](https://user-images.githubusercontent.com/6484985/112998169-c9393680-913b-11eb-9ed8-ed2ca00f1db3.png)

**Describe alternatives you've considered**
Any remote island along the edge of the map is fine. I just want Ravi-ta freed up for my other issue posts.

**Additional context**
Issues https://github.com/official-antistasi-community/A3-Antistasi/issues/1823 and https://github.com/official-antistasi-community/A3-Antistasi/issues/1824 cannot be resolved unless you at least move the outpost on Ravi-ta island.

**Comment by Preen1** [comment]
PvP is removed/being removed in the near future, so I'm not sure that moving the spawn points for Opfor & Blufor will do much

**Comment by Bob-Murphy** [comment]
PvP will be killed very soon.
Therefore this issue is obsolete.

**Comment by CalebSerafin** [comment]
Not gonna lie, that's a nice map stitch🗺. Thanks for putting in the effort 🚀

**Comment by SpadesNeil** [comment]
>PvP is removed/being removed in the near future, so I'm not sure that moving the spawn points for Opfor & Blufor will do much

>PvP will be killed very soon.
>Therefore this issue is obsolete.

This works too. As long as PvP spawns are off Ravi-ta Island, it can be used for new outposts.
