### ISSUE TITLE
Properly use ACRE2 items

### ISSUE THREAD

**Issue by bumbummen99** [official-antistasi-community/A3-Antistasi#1828]
**Is your feature request related to a problem? Please describe.**
ACRE2 is compatible with Antistasi but the mission does not add the items such as man packed radios or statically placeable radios.

**Describe the solution you'd like**
Properly integrate ACRE2 items into the mission. This could be done by unlocking all if ACRE is detected and also adding more advanced radios to enemy faction templates so they can be looted by the players.

**Describe alternatives you've considered**
Cheating the items with Zeus, that is not how a supported mod should work imo.

**Additional context**

**Comment by Bob-Murphy** [comment]
got merged in #1826
