### ISSUE TITLE
Sector counter did not changes after add units or squad who is already spawned

### ISSUE THREAD

**Issue by MrStonkus** [official-antistasi-community/A3-Antistasi#1829]
**Describe the bug**
Sector counter did not changes after add units or squad who is already spawned.

**To Reproduce**
Buy some units or squad.
Select them.
Add to your own sector as garrison.
Counter did not changes.

**Expected behaviour**
Show the updated sum of garrison units.

**Screenshots**
This is link to video.
https://youtu.be/VocB4Gbb8ec

**Environment (please complete the following information):**
Version: 
Map Altis 
Version lattest

Modset:
    
ACE3
And all recommended mods from official antistasi website.
![image](https://user-images.githubusercontent.com/28223642/113421514-ebe57c80-93d3-11eb-911f-d404f45ce598.png)

**Comment by Orange1861** [comment]
I can confirm that this only broke in the most recent update and it affects ALL garrisioning including Anizay.

**Comment by Lazejun** [comment]
Thats false informations, The Garrison Count on HQ never updated.

**Comment by Orange1861** [comment]
> Thats false informations, The Garrison Count on HQ never updated.

Ah, did not know that. Still, the garrison count on other areas isn't updating since the update and I suspect that the actual garrison itself isn't being saved either.
