### ISSUE TITLE
Mission can end when no members online

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#183]
Mission shouldn't end due to petros dying.

**Comment by PoweredByPot** [comment]
This is done in Petros' event handler for death, found in base\fn_initPetros.sqf. What we would need to do is promote an online player to member so that they could pick a new location.

`if (!isPlayer theBoss) then
                {
                {["petrosDead",false,1,false,false] remoteExec ["BIS_fnc_endMission",_x]} forEach (playableUnits select {(side _x != teamPlayer) and (side _x != civilian)})
                }`

**Comment by Spoffy** [comment]
Fixed in 3a9bb04c7b4075f7adbb01408a1480c59eff2b32
