### ISSUE TITLE
Mark Trenches to Persistent Save

### ISSUE THREAD

**Issue by Orange1861** [official-antistasi-community/A3-Antistasi#1840]
**Is your feature request related to a problem? Please describe.**
Currently, trenches don't persistent after a save and reload. This hurts HQ defense since trenches are a great way to improve HQ defense by providing us cover.

**Describe the solution you'd like**
Add trenches to be an object that is saved near flags. Similar to how vehicles and body bags are saved.

**Comment by killerswin2** [comment]
This is an feature of garbage cleaning. If we save trenches they will build up. Which can tank performance. As such we remove them through garbage cleaning
