### ISSUE TITLE
Marker cleanup problems in mortar support routine

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1843]
**Describe the bug**
The target and text markers created in SUP_mortarRoutine are not cleared up reliably. They're both deleted 60 seconds after the  end of a fire mission, but the next fire mission may be executed immediately (currentlyFiring is set false). Because createMarker fails with an empty string return value if the marker already exists, this will cause blank notifications and failures of enemies and civilians to move out of the target area.

The target marker isn't cleared by endSupport (only coverage & text), so that will probably cause half-blank notifications in the case where the mortar doesn't complete a fire mission for whatever reason.

**Comment by jaj22** [comment]
Correction: This doesn't cause blank notifications because those don't depend on the markers. It only prevents subsequent target markers from showing up reliably.

**Comment by wurzel0701** [comment]
I would say adding the shot number to it to identify the marker correctly could help
Otherwise instantly deleting the marker could help too, that would be the easy but dirty fix
