### ISSUE TITLE
@lhc121212 What mods are you using with Antistasi?

### ISSUE THREAD

**Issue by lhc121212** [official-antistasi-community/A3-Antistasi#1845]
I only use RHS, the version is the original version, without any changes. After testing for many times, it is stuck, and there is an error message, as follows:
15:51:21 Error in expression <[] spawn >
15:51:21   Error position: <>
15:51:21   Error 无效的表达
15:51:21 Error in expression <while {true} do >
15:51:21   Error position: <>
15:51:21   Error 无效的表达
15:51:21 Error in expression <}; >
15:51:21   Error position: <}; >
15:51:21   Error 丢失{
——————————————————
2:13:08 Suspending not allowed in this context
12:13:08 Error in expression <sleep 30; >
12:13:08   Error position: <sleep 30; >
12:13:08   Error 表达式内有一般错误

**Comment by Lazejun** [comment]
If we get the full rpt we might be able to understand the situation a lot better.

It could be that our Stringtables are causing issues when using Chinese or Arma 3 and RHS don't get along when using Chinese, but with the lack of RPT we can only guess.

**Comment by lhc121212** [comment]
> 如果我们得到完整的 rpt， 我们也许能够更好地了解情况。
> 
> 这可能是我们的字符串表在使用中文或Arma 3时造成问题，RHS在使用中文时不和睦相处，但由于缺乏RPT，我们只能猜测。

[arma3_x64_2021-04-12_13-42-43.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/6294405/arma3_x64_2021-04-12_13-42-43.zip)

**Comment by lhc121212** [comment]
I uploaded an RPT, please see if it helps

**Comment by CalebSerafin** [comment]
### When reporting bugs, Please fill in and replace text in the default issue template, it helps us a lot:
```md
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):


**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

* [ ] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset:
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**
Add any other context about the problem here.



If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.
```

***

### According the RPT, these mods were loaded:
| Original | Translation |
|-|-|
| @RHSSAF | |
| @RHSAFRF | |
| @RHSGREF | |
| @RHSUSAF | |
| @StarWar | |
| @ArmA2动画 (ArmaII Animations To ArmaIII) | @ArmA2 Animation |
| 新Cup地图 (CUP Terrains - Maps 2.0 1.0.0) | New Cup map |
| G.O.S Al Rayak | |
| 佛罗里达之钥 | Florida Key |
| @Arma Enhanced Movement翻墙跳跃 | @Arma Enhanced Movement Jumping over the wall |
| @Arma III 官方中文增强包 | ARMA III official Chinese enhancement package Version: 4.0 |
| @Drift_NoFatigue关闭疲劳 | Drifter's Fatigue Remover |
| @mao显示全身效果和血雾 | @mao shows full body effect and blood fog |
| 1638015543AI驾驶增强 | Driving enhancement |
| 498740884小队雷达 | Squad radar |
| [DEV] CUP Weapons | |
| [DEV] CUP Vehicles | |
| [DEV] CUP Units | |
| [DEV] CUP Terrains - Maps | |
| [DEV] CUP Terrains - CWA | |
| [DEV] CUP Terrains - Core | |
| @CUP_Chernarus 2020地图 | |

***
# Please follow these steps
### Just RHS
_Note: If a step is unclear, please report it so I can help._
1. In the Arma 3 Game Launcher, go to `MODS`. Click the button in the top right corner called `Unload All`
2. Load Only `@RHSAFRF`; `@RHSUSAF`; `@RHSGREF`
3. Play the game and see if there are any errors.
_If there are errors, stop and report it in the comments._
_If there are no errors, proceed to the following section._
### Addition Mods
4. From now, add one mod at a time to try find which mod is causing the errors.
5. Continue until the problem mod is found.
6. Comment which mod this was and avoid loading it when you want to play the game.

**Comment by CalebSerafin** [comment]
Closing this as no further information was given.
