### ISSUE TITLE
Airstrike aircraft spawn with double speed

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1864]
**Describe the bug**
Airstrike aircraft are spawned with FLY, which sets a fairly high starting velocity (eg. 152m/s for an A-10). Because velocityModelSpace isn't updated on setDir, the code then adds another 150m/s forward, giving a total ~300m/s, or a bit short of mach 1. This substantially shortens the travel time, possibly causing late visible spawns.

2.4 specific.

**Comment by CalebSerafin** [comment]
spawnVeheclePrecise can spawn aircraft based on its stall speed. (110% of it). The spawning code could switch to that. Or impliement the stall speed fetcher from it.
https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/CREATE/fn_spawnVehiclePrecise.sqf

**Comment by CalebSerafin** [comment]
In fact, I already had a branch but forgot to make a Pull Request. 🤦‍♂️

**Comment by jaj22** [comment]
The stall speed is a nice find, but I'm not sure I trust it sufficiently, and thrust-vector aircraft may have zero stall speed which would slow their airstrikes significantly. Currently inclined to go with 100m/s fixed, as that's reasonable for any plausible airstrike vehicle.
