### ISSUE TITLE
Inventory in vehicles should be safe from napalm.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#1895]
**Is your feature request related to a problem? Please describe.**
Had an Offroad full of loot, it seems after a napalm attack hit it the entire inventory was wiped. The vehicle was not fully blown up and you could access inventory but it was empty. 

No clue, it seemed like it happened right after a napalm strike. It damaged the vehicle to the point it had lost all its tires etc but was not fully blown up - could still get into the vehicle and access its now-empty inventory. Had 2 loot crates in the back of the car and one loot crate that was in the back of it (Not ACE Cargo) also disappeared. 

**Describe the solution you'd like**
Inventory not to be deleted.

**Additional context**
Car was not being towed or any other additional thing, it was just sat there on its own as normal.

**Comment by Bob-Murphy** [comment]
I'm against it.
If you brought a vehicle into a situation in which it is destroyed, it's gone with all the things inside.
Having inventory saved is too much of a "oh, you poor player, you have lost something" thing.
Players should be directed to think critically about their actions and to improve. This can not be achieved by taking them by the hand and not punishing them for sub-optimal actions.

**Comment by MeltedPixel** [comment]
Not at this time.
