### ISSUE TITLE
Parachutes can't deal with Elevation changes

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#1898]
**Describe the bug**
The Cheaty method of Opening the Parachutes in the last second is very Error prone with Elevation changes,
This problem can happen on All Maps, basicly on Hilly Dropzones most of the time.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
Have Ai Paradrop on an Outpost that is pretty Hilly, uneven Terrain and maybe even Trees.
some might survive, but most can hit the ground and die.
Using WavedCA from INV Airbases to OCC Outposts could show Results.
```sqf
["Target", "Source", 3] spawn A3A_fnc_wavedCA
```

**Expected behaviour**
We could probably increase the Height at which the Parachutes get deployed, maybe 10 to 15 meter above the current Cheat method should be fine.

**Comment by jaj22** [comment]
Rewritten in #2383
