### ISSUE TITLE
Big attacks in safe break the support system

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#1901]
**Describe the bug**
Saving during a big attack breaks the support system on loading as it would like to start the attack with supports before the needed variables are set.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
- Save during a big attack happening
- Reload
- BrokeTM

**Expected behaviour**
No brokeTM

Solution would be to switch the calls of aggresionUpdateLoop and initSupportCooldowns in the initServer file to prevent that to happen.

**Additional context**
Reported by Socrates in #bug-report-gameplay-feedback

**Comment by jaj22** [comment]
Fixed in rewrite.
