### ISSUE TITLE
A3A Medical is buggy with wounded loading, and Logistics system should not allow loading conscious units

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1904]
**Describe the bug**
What is said above, issue is only present when using our custom medical system thats enabled when ace medical is not detected, for the loading  being buggy, it reports back to the player trying to load that they are being helped, therefore blocking loading them, this is for unknown reasons not consistent

**To Reproduce**
injure someone, load them into a vehicle, unload and revive, they can now still be loaded until they respawn

**Expected behaviour**
this should not allow you to load conscious units into vehicles, and the loading should be more consistent

**Environment (please complete the following information):**
Version: 2.4.1 and 2.4.1.VN.01
Map (specify if Altis Blufor): Cam Lao Nam

* [ ] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2
* [x] Community SOG 1

Modset: CBA and TFAR Beta
    
Time the bug occurred (Please leave in GMT+0): ~19:00
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by MeltedPixel** [comment]
As per bob, should be fixed. Can be closed for now and reopened if reported again.
