### ISSUE TITLE
Error in paradrop.sqf during VN mission

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1906]
This error occured on the SOG servers, of course, during a paradrop.

```
2021/05/06, 11:15:31 Error in expression <ndom allSmokeGrenades;
private _smoke = _smokeGrenade createVehicle (getPosATL _>
2021/05/06, 11:15:31   Error position: <_smokeGrenade createVehicle (getPosATL _>
2021/05/06, 11:15:31   Error Undefined variable in expression: _smokegrenade
2021/05/06, 11:15:31 File mpmissions\__cur_mp.cam_lao_nam\functions\AI\fn_paradrop.sqf..., line 104
```

Log will be uploaded on discord.

**Comment by jaj22** [comment]
Apparently there's nothing in allSmokeGrenades. Not sure if this is tripping up in equipmentClassToCategories or itemSort yet. Autodetection sucks etc.

**Comment by jaj22** [comment]
That's odd. Can't replicate on either DS or localhost. allSmokeGrenades has six classnames on either. Maybe something that's already been fixed accidentally?
