### ISSUE TITLE
Set identities to units for voices/faces

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1914]
**Is your feature request related to a problem? Please describe.**
All spawned units have the standard faces and voices

**Describe the solution you'd like**
 - [ ] Make it possible to set identities in the templates for the AI

**Comment by Bob-Murphy** [comment]
This will be set up on vn-dev branch and then later implemented into unstable.
Should stay at initial identities when nothing is set in templates.

**Comment by Lazejun** [comment]
For players is bad, People should have the freedom to have their Own face/Custom faces.
Forcing it is bad, Period. 

Rebell Ai is fine.

**Comment by Bob-Murphy** [comment]
removed the point to also force faces on players.

**Comment by Bob-Murphy** [comment]
Maybe we will use this issue to also change the standard riflemen units to the other matching units (like medic, engineer). Will discuss that with Spoffy and then decide.

**Comment by Bob-Murphy** [comment]
done in 2.5.x
