### ISSUE TITLE
vn medical needs better compat with the entire revive system

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1915]
**Describe the bug**
on the VN branch, medical is broken for AI in askHelp, checking only for vanilla medical items when determining if an AI is capable of helping other units, theres likely more bugs like this hidden in the system, although the entire system majorly needs a rework, this is critical for low player counts where the players rely on AI to help them keep going against the numbers thrown at them, where larger groups would count on there superior numbers of players to help each other.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant): get knocked down with medical AI nearby, they will not be counted, and the system will claim that no units capable of helping you are nearby.

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

* [ ] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset:
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by jaj22** [comment]
I think the VN-specific problem and some others can be fixed fairly rapidly with an `askHelp` refactor. Shouldn't need to touch `help` unless we want to improve it.
