### ISSUE TITLE
Counter-attack system + separate gov/inv attack countdowns is broken

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1918]
**Describe the bug**
Ok, so we have separate attack cooldown timers for occupants and invaders. When an attack is completed (simulated or otherwise) these are incremented by 3600 seconds. Seems reasonable, except that gov vs inv attacker side is actually determined by aggression, so the side that reached cooldown 0 is not necessarily the one that gets the cooldown increase. This often leads to situations where one side spams attacks for a while. Later, it will go very quiet because one side now has several hours worth of stacked cooldowns.

In combination with the lack of randomization of attack targets, this can lead to results like three invader punishment missions being launched against the same city within 40 minutes.

**Expected behaviour**
Attacking side shouldn't attack again for a while. There should be no unexplained long activity pauses. Ideally enemies shouldn't attack the same objective repeatedly either.

**Comment by yakamashii2** [comment]
What if the ai used the zones around enemy territories and friendly territories to map out a super crude line around guerrilla positions and send attacks from outpost on the ai side to the player side. Using some RNG the attacks would seem more real, and would have the ai always attempting to encircle the player faction.
![20210512185257_1](https://user-images.githubusercontent.com/84109198/118062367-07895e80-b354-11eb-91f6-21bbbdd23182.jpg)
that should fix the issue of ai constantly attack the same outpost.
