### ISSUE TITLE
Punishments in large cities murder frame rates

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1919]
**Is your feature request related to a problem? Please describe.**
Punishment attacks currently spawn one city defender per 10 population. VN has some very large cities, and so can generate up to 200 defenders. Worse, it spawns every unit into one giant group. This is a performance disaster.

**Describe the solution you'd like**
Cap defender count somehow, and split them into more reasonable group sizes.

2000 pop may be excessive for one city anyway. Altis max is 650, and Kavala is barely playable. Splitting spawling cities into chunks may be an option.

**Comment by Rythoka** [comment]
Maybe spawn in only a set number of defenders at a time, and add more when the number drops below a certain threshold? e.g. spawn in only 50 defenders, when 25 have died spawn in 25 more, repeat until you hit the the total number of defenders.

I guess the biggest problem of this solution is that something like an airstrike might not hit as many targets as it could - but maybe it's worth the trade-off?

**Comment by Lazejun** [comment]
#1951 Just a hard limit of 40
