### ISSUE TITLE
Crates fail to load into vehicle, don't detect them.

### ISSUE THREAD

**Issue by yakamashii2** [official-antistasi-community/A3-Antistasi#1924]
**Describe the bug**
ammo crates, loot crates, mortars, city supplies, etc (anything that is supposed to be able to be loaded into a truck) fail to detect any vehicles put next to them, citing "no vehicle nearby."

**To Reproduce**
attempt to load crate into vehicle.

**Expected behaviour**
crate loads into vehicle, or tells player to "move vehicle closer"

**Environment (please complete the following information):**
Version: Version 2.4.1.VN.01 - 06th May 2021
Map: Cam Lao Nam

* [x] LAN Hosted

Modset: 
[Arma 3 Preset PRARIE FIRE.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/6469688/Arma.3.Preset.PRARIE.FIRE.zip)

rpt file and screencaps in comment

**Comment by jaj22** [comment]
I attempted to load a surrender crate into the stock VN offroad (purchased from the vehicle box), and it worked. Also no-one else has reported a problem, so I think we need more detailed reproduction info.

**Comment by yakamashii2** [comment]
let me load into the game real quick

**Comment by jaj22** [comment]
![20210513023201_1](https://user-images.githubusercontent.com/562040/118064768-8ea9f700-b393-11eb-83e2-3d2fba0d6502.jpg)

**Comment by jaj22** [comment]
Did you zeus in the vehicles or something? I can't find any legit method that doesn't work.

**Comment by yakamashii2** [comment]
probably mod compat issues.

what mods are you running alongside it?
also has the file on github different than the steam release? I have some parameters force set so I don't have to fuck with it.

**Comment by Bob-Murphy** [comment]
The file on GitHub is the same as the file on steam.
Parameters are being saved, therefore you only have to set them once and don't really mess with that.
The fact that you have adapted something in the init files leads me to the guess that you broke something on your init files.
As you modified the mission which we can't comprehend/retrace and due to the fact that the functionality IS working, this seems to be an issue that is introduced by yourself and we can't help you with that.

**Comment by yakamashii2** [comment]
HEY I FIGURED IT OUT

Blastcore/Hopecore somehow fucks the mission.
completely unsure how a visual mod fucks the entire mission.

**Comment by jaj22** [comment]
The original author of Antistasi, Barbolani, is hispanic.

If you can figure out a minimal broken modset then I can figure out exactly why it doesn't work and maybe work around it.
