### ISSUE TITLE
[Change Request]: Use VN withstand/revive system prevalent in campaign missions

### ISSUE THREAD

**Issue by yakamashii2** [official-antistasi-community/A3-Antistasi#1925]
**Is your feature request related to a problem? Please describe.**
Antistasi revive sucks. The withstand/revive system is way easier to use, and would allow solo player squads to res themselves without the ai, or at least crawl to safety instead of being dragged into a small rock and joining the VC Space program.

**Describe the solution you'd like**
Use a modified withstand/revive system from the campaign

**Describe alternatives you've considered**
just use it ripped straight out of the campaign, or even just allowing players to crawl away from the open to be able to be revived.

**Comment by CalebSerafin** [comment]
The only addition needed is a delayed addAction button that consumes medial supplies and revives the player. 
It will need to be compatible with template specified medical supplies. Be Vanilla, ACE, Halo, 40k ect.
Will not need to touch the AI reaction part to impliment this feature.

**Comment by CalebSerafin** [comment]
More ideas:
* A hold action and a button in the escape menu can be used. (The escape menu button is due to ACE blocking many actions)
* At the start of withstanding, it will alert nearby AI and allow them to shoot at the body.
* ACE medial will have players brought to minimum heart-rate and pressure to be stable, then ace_medical_fnc_setUnconscious.
* ACE one would consume items from the template. A custom entry will be required to select appropriate items.

**Comment by CalebSerafin** [comment]
We could load the vanilla revive system if no ACE is loaded.
The bellow nippit is an inspiration.
```sqf
if (! (isClass (configfile >> "CfgPatches" >> "ace_medical"))) then {
	diag_log "[Vindicta] Ace medican system is disabled, initializing standard Arma revive system";
	[1] call BIS_fnc_paramReviveMode; // Enabled
	[10]  call BIS_fnc_paramReviveDuration;
	[0] call BIS_fnc_paramReviveRequiredTrait; // 0 - no trait required
	[1.5] call BIS_fnc_paramReviveMedicSpeedMultiplier;
	[2] call BIS_fnc_paramReviveRequiredItems; // 2 - medkit or FAK
	[0] call BIS_fnc_paramReviveUnconsciousStateMode;
	[200] call BIS_fnc_paramReviveBleedOutDuration;
	[3] call BIS_fnc_paramReviveForceRespawnDuration;

	// Initialize BIS revive
	call BIS_fnc_reviveInit;
};
```
