### ISSUE TITLE
Players can be garrisoned

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1927]
**Describe the bug**
Groupleader can add players within his group to garrisons.
This person then is added to the garrison count and vanishing from the group menu (U).
Following error pops up in the personal rpt
```
22:16:21 Error in expression <tType = _x getVariable "unitType";
if ((_unitType == staticCrewTeamPlayer) or (_>
22:16:21 Error position: <_unitType == staticCrewTeamPlayer) or (_>
22:16:21 Error Undefined variable in expression: _unittype
22:16:21 File mpmissions\__CUR_MP.cam_lao_nam\REINF\addToGarrison.sqf..., line 51
22:16:21 âž¥ Context: [] L52 (mpmissions\__CUR_MP.cam_lao_nam\REINF\addToGarrison.sqf)
 [] L51 (mpmissions\__CUR_MP.cam_lao_nam\REINF\addToGarrison.sqf)
```

**To Reproduce**
Be on the server with another player, have him in your group, be the leader, use the Y menu to garrison.

**Expected behaviour**
Not add players to garrisons.

**Environment (please complete the following information):**
Version: VN-02

Did you make any changes to the code and if so, which changes:
nope

Map (specify if Altis Blufor): Cam Lao Nam

* [ ] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [x] Community Test Server
* [ ] Community Test Server 2

Modset:
    CBA, TFAR

**Comment by jaj22** [comment]
In general `getVariable "unitType"` is dangerous and should have a default. I'm not sure what the intention was. Empty string is probably fine?
