### ISSUE TITLE
Lootbox options not visible

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1928]
**Describe the bug**
Spectre did not have all options all options visible on the lootcrate. Neither when he spawned it nor when I spawned it whilst I could see them.
After he respawned, everything was visible and working perfect.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
not sure

**Expected behaviour**
show all options at all time

**Screenshots**
![image](https://user-images.githubusercontent.com/50651578/118187122-d5a0f680-b43e-11eb-9026-8cb3b2f4c7dd.png)

**Environment (please complete the following information):**
Version:  VN-02

Did you make any changes to the code and if so, which changes:
no

Map (specify if Altis Blufor): CLN

* [ ] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [x] Community Test Server
* [ ] Community Test Server 2

Modset: CBA, TFAR
    
Time the bug occurred (Please leave in GMT+0):
Server time approx 13:46:00

**Comment by jaj22** [comment]
Shouldn't be possible because the other two LTC actions have the same conditions. Maybe if removeAllActions got executed on the player somewhere in the middle of adding the LTC actions, but I'm not sure how that could happen. Vanilla revive glitch maybe...

**Comment by Bob-Murphy** [comment]
Only seen once, never heard anything else regarding that.
Can be re-opened if need be.
