### ISSUE TITLE
Convert healing action into hold-action

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#1930]
**Is your feature request related to a problem? Please describe.**
The issue is that the medic animation is not stopping when canceling the revive. Due to that you can loose precious seconds when under attack.

**Describe the solution you'd like**
Make the Antistasi heal function a hold action (spacebar) and cancel the animation when the bar is released.
Initial timer: 10seconds or 1 animation lenghts, whatever is longer.

**Describe alternatives you've considered**
Event handlers or such, as if I know anything about that...

**Comment by jaj22** [comment]
The code just needs a minor refactor to make cancels work properly. Currently there's far too much code in the AnimDone handler.

Hold actions are pretty complex to work with, and I don't see much benefit to them.

**Comment by Bob-Murphy** [comment]
If that solves the issue, I'm also fine with that one.

**Comment by CalebSerafin** [comment]
It could be styled like a hold action if you looking for consistency (Size 3 texture & icon, empty line between icon and text, text font RobotoCondensedBold).
