### ISSUE TITLE
CAS supports may be invulnerable to ground vehicle fire

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1938]
**Describe the bug**
The HandleDamage EH for the CAS supports may not return nil in some cases, causing unintentional behaviour. For example, in the case of the aircraft being hit by ground vehicle fire, the EH appears to return a scriptHandle.

This is separate from the known issue where the CAS aircraft won't abort its run unless actually destroyed.

**To Reproduce**
I guess set up a zu-23, set allowDamage false on yourself and the gun, and order a CAS support on top of you. Haven't tried it yet.

**Comment by Rythoka** [comment]
The spawn command return a scriptHandle, which might be causing the issue. I'll test and see if I can reproduce it.

**Comment by Rythoka** [comment]
Yup, they're definitely not taking damage from guns weapons - though if you kill the crew, the plane does crash and explode.

**Comment by jaj22** [comment]
Looks like you fixed this properly for SUP_CAS. However the problem may be broader as other supports have similar event handlers. Gonna need to check them all.

**Comment by Rythoka** [comment]
Yeah, looks like it does affect other supports; I haven't tested it yet, but it looks like SUP_ASF can't be damaged by bullets from other aircraft...
