### ISSUE TITLE
Helicopter crashes shows as infantry and turns to enemy pilot after gc

### ISSUE THREAD

**Issue by Giddius** [official-antistasi-community/A3-Antistasi#1943]
**Describe the bug**
If an helicopter crashes, it will still show up as Enemy Infantry on High Command. After you garbage clean the helo, an enemy helo pilot takes the place of the helo crash. He either get spawned in, pops up from the ground, or actually replaces the wreckage. 

I only saw this on Virolahti with a little bird, but got told from other players that it is constantly happening, but it isn't happening with every helo wreck.

**To Reproduce**
* shot down helo attacking hq or flying by HQ, (preferably Littlebird)
* look at the wreck in high command
* garbage clean

**Expected behaviour**
Either have the Pilot near the wreck even before gc or not have a pilot there (before or after gc).

**Screenshots**
![107410_20210518230045_1](https://user-images.githubusercontent.com/60372374/119239627-aa0ec200-bb4a-11eb-804d-b66d4bc658fe.png)
![107410_20210518230625_1](https://user-images.githubusercontent.com/60372374/119239635-b5fa8400-bb4a-11eb-8da1-05cb4e8f96d4.png)

Version: current community server

Did you make any changes to the code and if so, which changes: NO

Map (specify if Altis Blufor): Virolahti 

* [ ] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [x] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset:
    RHS
Time the bug occurred (Please leave in GMT+0): 2021-05-18 21:06:00

**Comment by jaj22** [comment]
There have been several reports of AI pilots surviving crashes with ACE and remaining in the heli, and the pilots appearing on garbage clean would logically be the outcome. 

I wouldn't say this is a specific bug that we can or should fix, but we do have a general problem of poor cleanup. Many of our vehicle spawning routines have cases where a vehicle/group can get stuck and sit around forever, with the spawner flag active so they keep rebel garrisons spawned too.

**Comment by Giddius** [comment]
To more precise, I check out the wreckage all around, he was not actually in the heli. He was either clipped inside the wreckage model (doubt it, as I checked if I can see any part of the infantry model), was pushed into the ground by the wreck (and kept there by the wreck) , or something completly different. He was not visible in any way and I also fired at the wreck to see if I could damage him.

**Comment by jaj22** [comment]
I think that's normal. Arma deals incorrectly with live units in dead vehicles, which is arguably its fault, but then I've never seen it happen in vanilla. Units surviving vehicle death is probably ACE's fault.

**Comment by Rythoka** [comment]
Looks like this is an issue ACE is addressing already: https://github.com/acemod/ACE3/pull/8063

**Comment by Bob-Murphy** [comment]
ACE issue, therefore closed
