### ISSUE TITLE
New garage additional feature requests

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#1988]
# A list of all feature requests for the new garage.

---
## Ambient noise in garage
Suggestion: Disable ambient noise in garage with [enableEnvironment](https://community.bistudio.com/wiki/enableEnvironment)
Notes: disable in `onLoad`, re-enable in `onUnload`

---

**Comment by 1337zorn** [comment]
## Toggle Auto Refuel in Garage On/Off via Addon Settings

**Comment by 1337zorn** [comment]
### Show Both, Lockpad and Magnifying Glass, when someone is looking at it

**Comment by 1337zorn** [comment]
### Show the Name of the Person who Locked the Vehicle

**Comment by 1337zorn** [comment]
### Maybe Change the Magnifying Glass with a Hand Symbol?
As someone "is currently holding onto" / "working" / "using" that vehicle in the garage, a simply Hand Symbol might be more intuitive to understand without explaination.
