### ISSUE TITLE
[Bug]: Commander none dedicate server

### ISSUE THREAD

**Issue by PrincipeAgustin** [official-antistasi-community/A3-Antistasi#1996]
### Describe the bug

If the commander in a dedicate server logout or crashes, the commander role not switch. 

i suggest that a vote commander option or a admin auto commander to prevent this problem.

### How to reproduce

logout as a commander 

### Version

2.4.1

### Have you altered the code?

No

### Map

Altis

### What server?

Private dedicated server

**Comment by jaj22** [comment]
Is this accurate? As far as I know, commander should switch on disconnect. In the case of a crash, Arma might take a minute to timeout, but logouts should definitely execute the commander switch handler.

**Comment by PrincipeAgustin** [comment]
No it isent, i was using original anti-stasi from the workshop
