### ISSUE TITLE
Unsynchronized destroyed buildings

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#2]
Destroyed buildings are not synchronized correctly. AI will think a building is destroyed and shoot through them. One player sees the building destroyed while another does not etc.

Might be fixed by commenting out statSave\loadAccount.sqf line 60:
`["destroyedBuildings"] call fn_LoadStat;`

**Comment by Spoffy** [comment]
I need to know if there's been a case of two players seeing different things. Because if not, this might be a bug with the AI in base Arma.

I suspect it's a base Arma bug either way.

**Comment by Spoffy** [comment]
from what i remember of  the admins explaining it at least 6 months ago, it is an issue where antistasi tries to make destroyed building persistent but the server/game overrules the model loading. this causes a limbo state where, in game logic, the building is destroyed, but physically appears undamaged.

that being said, the other day i had players running over the roof of what appeared to be a destroyed HQ prefab

**Comment by Spoffy** [comment]
Possibly fixed in 3185b89b1ab49ef93ef01d1b017fd15bdca9a410

Closing until re-reported.

**Comment by Bob-Murphy** [comment]
Re-opened through #311

**Comment by Bob-Murphy** [comment]
Temporary fix for the problem in #355 .

**Comment by Bob-Murphy** [comment]
@Spoffy @SonorousMeerkat 
Update/Milestone?

**Comment by Spoffy** [comment]
Should be fixed in 22b6f71e6c106de130fe98e700e26693fd37e60b
