### ISSUE TITLE
[Garage] Add vehicle count information to the garage interface

### ISSUE THREAD

**Issue by sevenjames** [official-antistasi-community/A3-Antistasi#2006]
### Related problem

Garage vehicle count and limit are not displayed anywhere.

### Proposed feature

Add to the garage interface:
- current number of vehicles stored in the garage
- current maximum number of vehicles allowed in garage

For example:
Vehicles Stored: 13
Vehicle Limit: 24

This information will help players to make informed strategic decisions about what to store in the garage.

**Comment by JoostB-Windesheim** [comment]
Maybe adding upgrades to the garage as well? for adding only a few to the current max depending on war level and payments for the upgrade ofc. Might be a little out of scope tho

**Comment by HakonRydland** [comment]
Already configurable with cba enabled
