### ISSUE TITLE
[Bug]: Loot crate infinite garaging

### ISSUE THREAD

**Issue by killerswin2** [official-antistasi-community/A3-Antistasi#2038]
### Describe the bug

Loot create can be garaged infinite amount of time. 

### How to reproduce

Destroy the vehicle that the crate is attached to.
Unload crate. 
Garage

or 
Destroy the vehicle that the crate is attached to.
Unload crate. 
GC
Garage

### Version

2.5.0

### Have you altered the code?

No

### Map

Anizay

### What server?

Community Server 1

### Mods

```html
RHS and 3CB Factions
```

**Comment by HakonRydland** [comment]
fixed with 2.5.0
