### ISSUE TITLE
[Refactor]: refactor enemyNearCheck

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#2043]
### Is the requested change related to a problem?

its inefficient

### Describe the solution you'd like.

should use inAreaArray with units <Side> to skip filtering through civ and reb units

### Additional context

need to check that units <Side> dont exclude units spawned with the wrong side but then had its side switched by joining a group of another side

**Comment by jaj22** [comment]
Completed.
