### ISSUE TITLE
[Bug]: Petros is not recieving ammo when using ACE

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#2070]
### Describe the bug

When Petros gets equipped ACE transforms his medic items into the ACE medic items, taking up all the inventory space he has, blocking it for all further objects. This means he does not recieve any ammo besides the one mag in his rifle.

### How to reproduce

Start up the game with ACE

### Version

2.5.2

### Have you altered the code?

No

### What i have changed

```markdown
I did, but only the rifle selection, its not important
```

### Map

Every map that Petros is on

### What server?

Private dedicated server

### Mods

```html
ACE
Also RHS, but that does not really matter
```

**Comment by jaj22** [comment]
The only straightforward workaround I can see for this is adding a vest/bandolier to Petros.

**Comment by Bob-Murphy** [comment]
As discussed in the meeting we'll do that.
Will write down the summary tomorrow.
