### ISSUE TITLE
[Feature Request]: Fine Control over HighCommand-related vehicle spawns.

### ISSUE THREAD

**Issue by 1337zorn** [official-antistasi-community/A3-Antistasi#2073]
### Related problem

Whenever the commander spawns a squad with a vehicle or a crewed vehicle asset, it will spawn at the nearest road relative from HQ position. There is no fine-grain control where newly recruited vehicle assets spawn, sometimes resulting in these facing some obsticle which in turn can create a deadlock or worse, lots of explosions due to vehicle colissions.

### Proposed feature

Instead of these vehicles being spawned to the closest road relative to HQ, 
1. have them search for the closest road from Garage Box.
2. copy the orientation from the Garage Box (the direction commander is facing when he is placing down the box) and apply it also to the spawned vehicles.

### Alternative solutions

Have a designated "spawn vehicles" thing you can place, like a composition of road barriers formed in a U shape or a Hangar / Workshop / "Actual Garage" Type of building. If AI would be compatible with it.

**Comment by 1337zorn** [comment]
This might actually be more a Change Request of something already existing, sorry for the mix up.

**Comment by CalebSerafin** [comment]
Hmm, adding a placement preview similar to buildings could work. after the commander finds a spot it will then find the nearest face pos.
