### ISSUE TITLE
[Bug]: Arsenal fails to associate RHS AFRF AK-103/4 with ammo

### ISSUE THREAD

**Issue by Briggybros** [official-antistasi-community/A3-Antistasi#2074]
### Describe the bug

When in the arsenal, the AK-103 and AK-104 do not have associated ammo. You can still take the ammo from the all ammo list, so the problem is not too great. The issue does not present in the vanilla virtual arsenal. Persists over save & restart.

### How to reproduce

1. Unlock unlimited AK-103 or AK-104
2. Unlock unlimited 57-N-231 ammo (I think this is the correct ammo from memory)
3. Notice that the 'ammo for equipped weapons' tab does not contain any ammo for the AK-103/4

### Version

2.5.1

### Have you altered the code?

No

### Map

Malden 2035

### What server?

Private dedicated server

### Time bug occured (Server time/UTC)

All the time

### Mods

```html
@CBA_A3;@DUI_SQUAD_RADAR;@ENHANCED_MOVEMENT;@VET_UNFLIPPING;@RHS_USAF;@RHS_AFRF;@RHS_GREF;@RKSL_ATTACHMENTS;@3CB_FACTIONS;@3CB_BAF_WEAPONS;@3CB_BAF_VEHICLES;@3CB_BAF_UNITS;@3CB_BAF_EQUIPMENT;@3CB_BAF_UNITS_RHS;@3CB_BAF_WEAPONS_RHS;
```

**Comment by HakonRydland** [comment]
this is due to bad rhs configs, nothing we can do about it

**Comment by Briggybros** [comment]
@HakonRydland If it were on RHS wouldn't it be present in the virtual arsenal too?

**Comment by HakonRydland** [comment]
we use the config to determine what mags to show as compatible

**Comment by reyhard** [comment]
"this is due to bad rhs configs, nothing we can do about it" not true. Antistasi is used very outdated fork of VA which misses support for magazineWells which were introduced around 4 years ago
Here is fix for it if anyone is interested in fixing it https://github.com/reyhard/A3-Antistasi/commit/ca2eb0b3bb41bfcf1c14f9d7f980254681ced29b

**Comment by Lazejun** [comment]
You could just make a PR 🤔

**Comment by jaj22** [comment]
Gonna unclose this as it's very fixable. Probably use #2114 plus trivial arsenal changes rather than the linked code. Making the arsenal code less complex is always good.
