### ISSUE TITLE
[Bug]: savegame load for loadouts_rebel fails

### ISSUE THREAD

**Issue by TheJJ** [official-antistasi-community/A3-Antistasi#2076]
### Describe the bug

An error occurs when loading the server state:

```
2021-08-21 16:36:27:697 | Antistasi | Info | File: A3A_fnc_loadServer | Starting Persistent Load. | Called By: A3A_fnc_initServer
2021-08-21 16:36:27:707 | Antistasi | Error | File: A3A_fnc_returnSavedStat | Variable countCA does not exist. | Called By: A3A_fnc_getStatVariable
Weather was forced to change
Error in expression <vate _garrison = +(_x select 1);
{

if (_x find "loadouts_rebel" != 0) then { co>
  Error position: <_x find "loadouts_rebel" != 0) then { co>
  Error Undefined variable in expression: _x
File mpmissions\__cur_mp.Altis\functions\Save\fn_loadStat.sqf..., line 150
"server/BIS_fnc_log: [BIS_fnc_preload] ----- Scripts initialized at 19972 ms -----"
18:37:28 Game started.
```

### How to reproduce

Not sure what we did for the bug to trigger. It was a 2.4 map, we updated to 2.5.0 and 2.5.1 and played happily with a few server restarts.

### Version

2.5.1

### Have you altered the code?

No

### Map

Altis

### What server?

Private dedicated server

### Time bug occured (Server time/UTC)

2021-08-21 16:36:27:707 CEST

**Comment by Lazejun** [comment]
Thanks for Creating the issue,

We are aware of the Issue, there are Multiple methods to solve it quickly, pinned in the help channel on Discord.

Will prevent it from happening #2067
