### ISSUE TITLE
Improve AI Weapon selection

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#208]
AI like to take bolt actions/SMGs  when there are ARs available. They should really pick their weapons a bit better.

**Comment by wurzel0701** [comment]
In my private version i placed an VR unit and let the commander change its outfit for each AI class. Spawned AI will have this outfit as their default loadout. There is no need to do it like this, just dropping ideas. Something similar may be better suited

**Comment by marko2552** [comment]
> In my private version i placed an VR unit and let the commander change its outfit for each AI class. Spawned AI will have this outfit as their default loadout. There is no need to do it like this, just dropping ideas. Something similar may be better suited

@wurzel0701 can you explain this in more detail? Really want to change the default gear. Thanks.

**Comment by wurzel0701** [comment]
**Just as an information, as PoweredByPot is already on it and I would prefer not to interfere with anyones work or ideas. Pot will solve this issue, and my approach will not be in the official version!**

My personal approach was to set an VR units with all AIs off and set it as captive, so it does not distract attacking enemies. The prototype in the VR world looks like this.

![20190902084052_1](https://user-images.githubusercontent.com/31988396/64095386-f4d91c80-cd5e-11e9-922a-82dd4197612c.jpg)

The unit got two actions added, "Set loadout" and "Switch loadout".
- Set loadout: Only accessable by commander, asked which class (MG, medic, engineer and so on) should be set, then opens the Arsenal for the VR unit, with only the unlocked weapons displayed. The commander is now able to set a loadout for this class with the arsenal, by either choosing a specific item to use always or settting up an array of possible items.

- Switch loadout: Accessable by everyone, opens a dialog which class should be shown, selected class loadout will be shown on the VR unit. If an array of equal items is choosen by the commander, this item will change every five seconds.

Result will look similar to this
![20190902084920_1](https://user-images.githubusercontent.com/31988396/64095704-de7f9080-cd5f-11e9-8631-117c0617c5c5.jpg)

But this is just my personal approach. You can copy it if you like, but it will not be in the official version!

**Comment by marko2552** [comment]
@wurzel0701 thanks man!

**Comment by PoweredByPot** [comment]
**I want to be clear first that my ideas for gear encompass almost all facets of gear and equipment, and as I plan to fix it, it will likely not be merge-able (is that a word?) without a lot of pain and suffering.**

The basis of my plan convert the current purpose of templates from identifying specific units to instead identifying specific roles. There will only be a "Template" for each side of the war. The actual engine value "side" as well as faction will be passed to the template for rebels/NOTgovt/invaders.

The InitVar file now generates arrays that contain all the units of a particular type for the given "side" value, NO MATTER WHAT MODS YOU HAVE LOADED. Players will now choose in parameters what "side" and what "faction" for that side they would like each of rebels/NOTgovt/invaders to have.

The files formerly known as templates (prince reference), now look within those arrays for units that match a set of parameters for each role, and fill them according for the rest of the mission to use. They then scrape those units just like before to gather the "loot" lists based on what items the selected units are wearing.

InitVar now has final say on what items are available at the start, and the section where it decides so is the ONLY place in the file that items are dealt with at all, hopefully bringing a lot more clarity to the process.

**Comment by Bob-Murphy** [comment]
@PoweredByPot @SonorousMeerkat 
Has this been worked on or maybe even fixed?

**Comment by PoweredByPot** [comment]
Closing this issue, as many changes have been made regarding this, and they need to be monitored and balanced.
