### ISSUE TITLE
[Bug]: fn_help Can Have a 10-20 Second Timeout for Drags

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2080]
### Describe the bug

**Quote from report**
> i hate how they dont revive me
i mean it seems like they do
but only if you don't upgrade their skill level

### How to reproduce

Test AI revive with low friendly AI skill.
Test AI revive with high friend AI skill.

### Version

2.5.1

### Have you altered the code?

No

### Map

Any

### What server?

LAN Hosted

### Mods

| Mod Name                                                | Steam Link |
| - | - |
| CBA_A3                                                  | http://steamcommunity.com/sharedfiles/filedetails/?id=450814997  |
| RHSUSAF                                                 | http://steamcommunity.com/sharedfiles/filedetails/?id=843577117  |
| RHSAFRF                                                 | http://steamcommunity.com/sharedfiles/filedetails/?id=843425103  |
| ace                                                     | http://steamcommunity.com/sharedfiles/filedetails/?id=463939057  |
| CUP Terrains - Core                                     | http://steamcommunity.com/sharedfiles/filedetails/?id=583496184  |
| CUP Terrains - Maps                                     | http://steamcommunity.com/sharedfiles/filedetails/?id=583544987  |
| Arsenal Search                                          | http://steamcommunity.com/sharedfiles/filedetails/?id=2060770170 |
| Blastcore Edited (standalone version)                   | http://steamcommunity.com/sharedfiles/filedetails/?id=767380317  |
| DCON's Multiplayer Vehicle Spawner                      | http://steamcommunity.com/sharedfiles/filedetails/?id=1420266916 |
| Remove stamina                                          | http://steamcommunity.com/sharedfiles/filedetails/?id=632435682  |
| RHSGREF                                                 | http://steamcommunity.com/sharedfiles/filedetails/?id=843593391  |
| Remove stamina - ACE 3                                  | http://steamcommunity.com/sharedfiles/filedetails/?id=782415569  |
| Reduced Haze Mod v3.1                                   | http://steamcommunity.com/sharedfiles/filedetails/?id=1397683809 |
| Personal Arsenal                                        | http://steamcommunity.com/sharedfiles/filedetails/?id=457905859  |
| JSRS SOUNDMOD                                           | http://steamcommunity.com/sharedfiles/filedetails/?id=861133494  |
| JSRS SOUNDMOD - RHS AFRF Mod Pack Sound Support         | http://steamcommunity.com/sharedfiles/filedetails/?id=945476727  |
| JSRS SOUNDMOD - Reloading Sounds                        | http://steamcommunity.com/sharedfiles/filedetails/?id=1429098683 |
| BettIR (Legacy v0.2.1)                                  | http://steamcommunity.com/sharedfiles/filedetails/?id=2260572637 |
| Immerse                                                 | http://steamcommunity.com/sharedfiles/filedetails/?id=825172265  |
| Align                                                   | http://steamcommunity.com/sharedfiles/filedetails/?id=903134884  |
| ACE 3 Extension (Animations and Actions)                | http://steamcommunity.com/sharedfiles/filedetails/?id=766491311  |
| ACE 3 Extension (Gestures)                              | http://steamcommunity.com/sharedfiles/filedetails/?id=1355481562 |
| GCam Cinematic Camera Tool                              | http://steamcommunity.com/sharedfiles/filedetails/?id=909893746  |
| ACE Compat - RHS Armed Forces of the Russian Federation | http://steamcommunity.com/sharedfiles/filedetails/?id=773131200  |
| ACE Compat - RHS United States Armed Forces             | http://steamcommunity.com/sharedfiles/filedetails/?id=773125288  |
| ACE Compat - RHS: GREF                                  | http://steamcommunity.com/sharedfiles/filedetails/?id=884966711  |
| LAMBS_Suppression                                       | http://steamcommunity.com/sharedfiles/filedetails/?id=1808238502 |
| RHS Helicopters Sound Improve                           | http://steamcommunity.com/sharedfiles/filedetails/?id=2178398365 |
| JSRS SOUNDMOD - RHS USAF Mod Pack Sound Support         | http://steamcommunity.com/sharedfiles/filedetails/?id=1180533757 |
| JSRS SOUNDMOD - RHS GREF Mod Pack Sound Support         | http://steamcommunity.com/sharedfiles/filedetails/?id=1180534892 |

**Comment by jaj22** [comment]
Triage: User smoking too much crack. Posted wrong(?) modlist (this one has ACE in it, so revive obviously doesn't work). Posted example video from Barb's version.

**Comment by jaj22** [comment]
I did test combat revives in case something got broken recently, and the medic was picking me up with quasi-religious devotion. Worst part is that there seems to be a 10-20 second timeout on the drags, but then fn_help is one of those functions that needs a refactor before you can follow the control flow. Maybe later.

**Comment by spaghetti-toast** [comment]
This is actually an intended feature as AI are smart enough to know that reviving players will, on average, reduce their lifetime significantly.

**Comment by jaj22** [comment]
Fixed in #2644
