### ISSUE TITLE
[Bug]: Cant exit Virtual Arsenal

### ISSUE THREAD

**Issue by Imsenki** [official-antistasi-community/A3-Antistasi#2082]
### Describe the bug

Since the 2.5//2.5.1 Update I cant use the arsenal anymore: I cant exit it and its empty, which makes the whole scenario unplayable. For some reason if i try to load a saved loadout I can equip all items in that loadout even though my arsenal is seemingly , but i still cant leave the arsenal.

### How to reproduce

Start the scenario, open the Arsenal, mash keys and realize nothing works.

### Version

2.5.1

### Have you altered the code?

No

### Map

Altis

### What server?

LAN Hosted

### Mods

```html
CBA_A3 	Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
Enhanced Movement 	Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=333310405
Enhanced Map 	Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=2467589125
POLPOX's Base Functions 	Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=1862880106
Enhanced Arsenal 	Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=2217110167
Enhanced Visuals 	Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=880703327
Enhanced Soundscape 	Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=825179978
DynaSound 2 	Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=825181638
```

**Comment by Lazejun** [comment]
Thats a Mod issue.

You are using a Mod that Modifies ontop of the Virtual Arsenal, remove the Mod and you won't have the Issue.
