### ISSUE TITLE
Change the Garage to the 1.9 style by Jeroen.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#209]
It's a better garage with more functionality, Bob has apparently spoken with Jeroen Not about getting a more updated version for implementation however nothing has come of this yet.
Figured it'd be worth having it officially up on here.

**Comment by CalebSerafin** [comment]
@HakonRydland Has solved this with https://github.com/official-antistasi-community/A3-Antistasi/pull/1735
