### ISSUE TITLE
Using custom loadouts on planes to improve combat abilities

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#211]
Using the custom loadouts of planes would make it possible to design specific planes for specific roles, which would be:
- Air superior fighter (Fast, packed with AA missiles)
- Multi purpose (Good mix between AG missiles, unguided rocket, AA missiles and Bombs)
- Bomber (Packed with AG missiles, unguided rockets, unguided and guided bombs)
- SEAD (Suppression of Enemy Air Defense) (Packed with cluster bombs and Anti-Radar-missiles)

Would make planes more effective without using more AI units

**Comment by Bob-Murphy** [comment]
@wurzel0701 
Please add to Trello and close here.

**Comment by wurzel0701** [comment]
Done
