### ISSUE TITLE
[Bug]: After picking up a lamp object, there is no drop action

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2154]
### Describe the bug

After picking up a lamp object, there was no scroll wheel action to drop it, so you were stuck carrying it until respawning or debug console use. Seemed repeatable on the test servers, and also happened to other players.

### How to reproduce

Pick up a lamp object.

May be DS-specific. I haven't checked it locally.

### Version

2.5.3 test

### Have you altered the code?

No

### Map

Doesn't matter

### What server?

Community Test Server 2

**Comment by killerswin2** [comment]
Hmm... I wonder if the add action is getting removed on respawning.

**Comment by HakonRydland** [comment]
It does with vanilla thanks to a3a revive system

**Comment by HakonRydland** [comment]
See flagAction

**Comment by killerswin2** [comment]
Nope that's not the problem. :( There's a call to readd the action in flagaction.

**Comment by jaj22** [comment]
Confirmed respawn bug. Needs adding to onPlayerRespawn, probably near initLootToCrate.

Amusingly you can workaround by walking up to your old corpse with the lamp, so we should probably be stripping actions on death too.
