### ISSUE TITLE
[Bug]: When Vehicle Load despawns it still blocks the seats

### ISSUE THREAD

**Issue by PulsarNeutronStar** [official-antistasi-community/A3-Antistasi#2164]
### Describe the bug

When you transport City Supplies in a vehicle and the mission timer runs out, the palette with the supplies despawn.
The vehicles cargo is still occupied, but you cannot unload anything since nothing is loaded, keeping the seats disabled.

Workaround: Garage -> Ungarage to reset vehicle

### How to reproduce

Spawn City Supply, Load in Offroad, Skip Time to Fail Mission.

### Version

latest on Community Servers as of 08.10.2021

### Have you altered the code?

No

### Map

Takistan

### What server?

Community Server 1, Community Server 2

### Additional context

Suggestion: When Driver enters/leaves the car, check if cargo is still there, else free cargo.

As a side note, the city supplies usually leave an empty pallets when the mission is completed (not sure if the mission fails it will stay as is, leave palette or despawns completely, maybe a solution is possible utilising the pallets somehow.

**Comment by Bob-Murphy** [comment]
The normal vanilla offroad?

**Comment by 1337zorn** [comment]
vehicle shouldnt be relevant but yes

**Comment by killerswin2** [comment]
Is the pallet object in the cargo still? Like is there a pallet there?
