### ISSUE TITLE
[Feature Request]: Scarcity of Fuel

### ISSUE THREAD

**Issue by 1337zorn** [official-antistasi-community/A3-Antistasi#2166]
### Related problem

Gurilla Warfare comes with many different restrains and difficulties differencienting it from normal modern warefare. Many of these aspects are behind the scenes regarding logistics. 

Currently in Antistasi, all vehicles that are spawned - ether bought at base, found in a city or stolen from the enemy - come with a full fueltank and the only occation one has the need for fuel is when they recover an asset with a broken fueltank.

In version 1.9 most vehicles spawned with with an near empty fueltank, the gameplay was different and people had to consider fuel as an economy they needed to pay attention on - Gas Stations became tactically important and every fueltruck one came across has been highly valued - even in mid to late game.

### Proposed feature

Shortterm:
1. Vehicles bought from the Base/Faction should come with random fuel value of 5%-20%
2. Civilian Vehicles should spawn with a random fuel value of 10-50%
3. Military Ground Vehicles should spawn with a random fuel value of 25-75%.
4. Military Air Vehicles should spawn with a random fuel value 75%-100%. (optional)

Midterm:
1. Seaports (and/or Factory) add Action at Flag to 
A) with ace: Refuel an existing Fueltruck  (500l for 500€) 
`(get current fuel supply + 500)) set fuel supply)`
B) With and without ACE: Buy Civilian Fueltruck for idk 2000~5000€?

2. Have the option to BUY an object at base or at a seaport - for example fuelcans on a pallet - that can be used as a (infinite) refueling source that could even be transported via offroad. (For relocation of HQ, it needs to be manually transported).

### Additional context

`_jeepOne setFuel 0.5;`
https://community.bistudio.com/wiki/setFuel

https://ace3mod.com/wiki/framework/refuel-framework.html
https://ace3mod.com/wiki/framework/refuel-framework.html#23-setting-the-fuel-supply

**Comment by Bob-Murphy** [comment]
please add a titel

**Comment by Bob-Murphy** [comment]
SOG PF assets
![image](https://user-images.githubusercontent.com/50651578/137597132-1c475c1b-98c2-4882-9dd7-b7969e3ec0b5.png)

**Comment by 1337zorn** [comment]
Vanilla Assets

![107410_20211016190631_1](https://user-images.githubusercontent.com/56258612/137597408-27e8e718-71cb-4527-934a-ef295f9d913a.png)
![107410_20211016190629_1](https://user-images.githubusercontent.com/56258612/137597409-64acff9e-c860-4d40-9c3f-023a539f9dce.png)
![107410_20211016190630_1](https://user-images.githubusercontent.com/56258612/137597410-bfc461af-88d5-4706-894a-b48a3a6ade80.png)
![107410_20211016190627_1](https://user-images.githubusercontent.com/56258612/137597412-b3842fcd-3868-4507-b4a3-fd7abcde2758.png)
![107410_20211016190626_1](https://user-images.githubusercontent.com/56258612/137597413-20dafbc8-0fcb-4dcf-9132-f24c85bb31e5.png)
![107410_20211016190446_1](https://user-images.githubusercontent.com/56258612/137597414-31628d93-3c5a-4d1f-98c8-9bf88bc3deb0.png)

**Comment by 1337zorn** [comment]
Ace implementation:
https://ace3mod.com/wiki/framework/refuel-framework.html

**Comment by 1337zorn** [comment]
How to deploy Fuel:
Buayble entity (Huron Fuel Container) like an addon/upgrade to HQ that can hold a certain pool of Fuel.
(optional: needs to be moved manually when HQ moves - Problem: How? Vanilla only huron can transport it.
-> alternative: different OBJ like CargoNet(barrels) )

How to fill up pool:
a) Fill up via Ticker depending on Factory, Resource, Seaport, friendly towns etc.
b) Side Mission: Steal/Buy/Pickup canisters / pallets / whatever from the area
c) Buy Fuel from Gas stations.
d) Find it at enemy outposts coparable to the outpostlootcrate (green)
e) to be continued

**Comment by CalebSerafin** [comment]
@killerswin2 What is the completed vs Todo checklist for this Feature Request?

**Comment by killerswin2** [comment]
@CalebSerafin Can be closed, it is basically complete. Might add other stuff later, but this is a good stopping point.

**Comment by Bob-Murphy** [comment]
@CalebSerafin 
Please add the correct milestone and connect the related PRs that the reason for closing that issue before closing it.

**Comment by CalebSerafin** [comment]
Closed in <https://github.com/official-antistasi-community/A3-Antistasi/pull/2207>
