### ISSUE TITLE
[Change Request]: Improve enemyNearCheck 

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2167]
### Is the requested change related to a problem?

enemyNearCheck is used as a blocker for various management actions, for example recruiting squads, buying vehicles or adding to garrisons. The current function is a basic proximity check, and often returns true in cases where enemies are unengaged and difficult to locate.

### Describe the solution you'd like.

Switch all related checks over to a method similar to that in addBombRun: Only consider enemies that have targets near the action point.

**Comment by killerswin2** [comment]
#2043
