### ISSUE TITLE
[Change Request]: Add ACE Ropes to ACE Arsenal init

### ISSUE THREAD

**Issue by PulsarNeutronStar** [official-antistasi-community/A3-Antistasi#2172]
### Is the requested change related to a problem?

ACE Ropes can be used for Fast Roping and soon for Towing.
Also other mods are falling back on the ace ropes for many different things.

### Describe the solution you'd like.

Adding the ace ropes in its different lenghts to the Ace arsenal init should be an easy task.

### Alternative solutions

Spawn them randomly in civilian spawned vehicles inventory.

**Comment by killerswin2** [comment]
Ace, now adds ropes to the vehicles on init. We don't really need to unlock them now as you can get them with in 20 seconds of mission start with garaging and un-garaging a vehicle.
