### ISSUE TITLE
Airfield spawning of Tanks, AA and Mortars - Fix for other maps

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#218]
https://github.com/official-antistasi-community/A3-Antistasi-1.4/blob/f11222cffddc9374bae519eb7ec41f654c64f916/A3-Antistasi/initVar.sqf#L546-L548

The code as it is has set markers for mortars and other stuff spawning on airfields but the coordinates are from altis.
To do:
Implement markers which can be placed in the mission.sqm's which determine where mortars, AA and tanks are spawning.
Idea:
- 2 Markers -  one for mortars - one for heavy vehicles
- Mortars should be spawned 100% of the time.
- other vehicles like AA, Tanks or heavy artillery should spawn randomly
- Spawn is controlled by random roll to 100 - based on the roll we can set a probability with which what vehicle type spawns

Bad example:
```
if (rand >= 0 && rand < 46) then {
spawn aa-tank
}
else if (rand >=46 && rand < 90 then {
spawn at-tank
}
else
{
spawn mortars
}
```

**Comment by wurzel0701** [comment]
Done for Altis, Tanoa and Malden in #289.
The other maps need to be done tho

**Comment by Bob-Murphy** [comment]
Map markers introduced to every map.
