### ISSUE TITLE
Include a "Parameter" check in the Travis Validation

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#220]
It would be good to get a list of broken, unused or undeclared variables in the code base to prevent further occurence of #214 

I believe the below lines do this, from the SQF validation, but don't know enough about Python to throw it in the main script Travis is using.

https://github.com/official-antistasi-community/A3-Antistasi/blob/0e05e9b6abc76a9697a5c260dbe329605ab38dd5/Tools/sqfvalidator/sqf/analyzer.py#L112-L126

**Comment by Bob-Murphy** [comment]
@Toakan 
Do we still want/need this one?

**Comment by Toakan** [comment]
Not particularly. As Spoffy said in Discord, we need to look at flipping back to the prior version which is from here : https://github.com/LordGolias/sqf but it will need a bit of travis fuckery.
