### ISSUE TITLE
[Bug]: Spawned HC squads not boarding vehicles consistently

### ISSUE THREAD

**Issue by darkith** [official-antistasi-community/A3-Antistasi#2203]
### Describe the bug

Playing private server on Virolahti.
Summoned HC squads with vehicles (AA, Mortar, AT cars, etc) are often not mounting their vehicles, especially (but not exclusively) if spawned when commander is >50m from base (so, using the new random placement instead of the new garage placement).  Seems to happen if the soldiers and vehicles spawn far apart from each other...like they only path towards their vehicle for so long/far before giving up. Sometimes some (but not all) of the crew successfully mount, sometimes none if the crew spawn and vehicle location are particularly distant. If the vehicle is placed near base center and therefore likely closer to random crew spawn, it seems to happen much less, but does happen if they struggle to path around other objects/buildings.

And once they've failed to mount, no amount of AI Management->Mount does anything, only way to get them on is Temp AI Control.  
The Mount/Dismount also fails to work on squads that successfully mount their vehicle. (perhaps this is a separate bug?)

### How to reproduce

Summon HC squad with vehicle (eg AA truck).  Place vehicle at furthest distance from base center.  Depending on where the squad randomly spawns, they will path towards it, but randomly fail if the distance (or some other hidden metric) is too far.

### Version

2.5.3.vt7 from releases

### Have you altered the code?

No

### Map

Virolahti

### What server?

Private dedicated server with Headless client(s)

### Time bug occured (Server time/UTC)

repeatedly

### Mods

```html
ACE Compat - RHS AFRF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=773131200
ACE Compat - RHS USAF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=773125288
ACE Compat - RHS: GREF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=884966711
Automated Ace No Medical	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2158809703
CBA_A3	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
CUP Terrains - Core	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=583496184
CUP Terrains - Maps	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=583544987
Enhanced Movement	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=333310405
Gruppe Adler Trenches	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1224892496
RHSAFRF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843425103
RHSGREF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843593391
RHSUSAF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843577117
ShackTac User Interface (DISCONTINUED)	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=498740884
Task Force Arrowhead Radio (BETA!!!)	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=894678801
VET_Unflipping	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1703187116
Virolahti - Valtatie 7	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1926513010
Zeus Enhanced	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1779063631
Zeus Enhanced - ACE3 Compatibility	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2018593688
```

**Comment by darkith** [comment]
This is a duplicate? Could I get a link? I searched before submitting and couldn’t find anything existing. 

Be nice to be able to follow the status until it’s resolved….for our small group it’s pretty game-breaking, as the commander is usually out on the attack with the troopers when we get a Punishment or Attack. In the past, the commander would recruit AA trucks, AT cars, Troop trucks, waits for them to board, then FT as close to the area under attack as possible. But, with the bug, instead of AA/AT vehicles or mounted troops able to travel, we just get a handful of guys on foot at the nearest FT accessible site, unable to do anything useful or get anywhere quickly.

**Comment by killerswin2** [comment]
https://github.com/official-antistasi-community/A3-Antistasi/issues/170

**Comment by darkith** [comment]
To clarify, the but shows up when the AI are spawned and *without* using the Temp AI Control. 

It appears to be related to the new “garage placement” code for AI vehicle placement (meant to avoid intersection kabooms from the old “drop it in the middle of the base”), because now the AI are spawning too far from the vehicle (sometimes almost opposite sides of the base circle)
https://github.com/official-antistasi-community/A3-Antistasi/pull/2108

I think it could be resolved by having the AI spawn within a much closer radius to the vehicle spawn location (whether the manual “garage placement” or the new “fallback random”).

**Comment by killerswin2** [comment]
This is not related to the new placement of vehicles for HC squads. This has happened before the change.

**Comment by killerswin2** [comment]
This is generally a problem with AI, they have trouble with vehicles, mounting and un-mounting. Really I shouldn't have used DUP, but it is a know issue. Just one that might not be able to be solved on our end.

**Comment by darkith** [comment]
Roger. I do recall it happening before the change, but it seemed to be more the exception than the rule in the handful of versions we played previously. 
It seems to be horrifically worse and repeatable now. I’ve remotely spawned a dozen mounted AI squads in a row and had maybe 1 or 2 actually show up mounted.

**Comment by jaj22** [comment]
This probably is a new problem, or at least one that's got worse. The old placement code used to spawn troops in the vehicle when they were bought with it, at least for AA/AT trucks. Spawning the squad closer to the vehicle should help.

@darkith Do you have a picture of an HQ location or two that are highly likely to show the problem? My standard test location hasn't had a problem but it's likely to be related to road positions.

**Comment by darkith** [comment]
![20220109132111_1](https://user-images.githubusercontent.com/1299114/148693420-4e25ccf9-2fa0-40b4-8e42-b89804856b4b.jpg)
![20220109132125_1](https://user-images.githubusercontent.com/1299114/148693422-0b241b1a-0636-4ebf-be1e-f098af3c6592.jpg)

This is where our base has been for most of this map (virolathi, 033091).  A few buildings, and there's sometimes trees if I've forgotten to Clear Forest.  
There's a bit more object clutter now, but it was happening before we had as much garrison/statis/heli crap lying around.
It's not a guaranteed failure, sometimes it seems to happen infrequently, and sometimes I'm summoning mortar teams and it takes me 5-8 tries to get one to actually use their quad. Not sure if it's related to AI load or what...

**Comment by darkith** [comment]
@jaj22

**Comment by jaj22** [comment]
Couldn't replicate with what I expected to be the worst case of putting the vehicle as far as possible from the HQ (random placement is limited to 50m, same as manual placement) and having the infantry spawn in the opposite direction (so 80m total distance).

My guess is that either the AIs are struggling to path through vehicles placed around the HQ, or they're getting aggro'd and either attackDrillAI or basic Arma AI is telling them to stay out of the vehicle.

It's still a new issue in the sense that the AIs used to be moved directly into the vehicle, and that would likely mitigate most problems if the behaviour was restored. However, that's now a fairly elaborate refactor. Spawning the AIs next to the vehicle would be easy and at least work around the potential pathing problems, and generally reduce the time-to-use.
