### ISSUE TITLE
[Bug]: No toolkits in the mission

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#2208]
### Describe the bug

Current unstable does not have toolkits.
Might be due to incorrect capitalisation.
Some infos (only readyble for devs) here: https://discord.com/channels/449481990513754112/509992121021890560/914210331016982528

### How to reproduce

start current unstable

### Version

unstable

### Have you altered the code?

No

### Map

all

### What server?

Community Test Server

**Comment by Lazejun** [comment]
closed by #2209
