### ISSUE TITLE
Stuff for stringtable in mission.sqm's

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#221]
Hi Tad,

I found stuff in the files which is not changes by the strings.
I also don't know if this stuff is set in the respective description.ext's or if we have to set it here.
Please find out and fix.

Thank you.

https://github.com/official-antistasi-community/A3-Antistasi/blob/dda9e7ced319f5ffa12f7577c5e236cd112a12f5/A3-Antistasi/Templates/A3-AA-BLUFORTemplate.Altis/mission.sqm#L150-L157
-------
https://github.com/official-antistasi-community/A3-Antistasi/blob/dda9e7ced319f5ffa12f7577c5e236cd112a12f5/A3-Antistasi/Templates/A3-WotPTemplate.Tanoa/mission.sqm#L428-L429
-------
https://github.com/official-antistasi-community/A3-Antistasi/blob/dda9e7ced319f5ffa12f7577c5e236cd112a12f5/A3-Antistasi/Templates/A3-WotPTemplate.Tanoa/mission.sqm#L140
-------
https://github.com/official-antistasi-community/A3-Antistasi/blob/dda9e7ced319f5ffa12f7577c5e236cd112a12f5/A3-Antistasi/Templates/A3-ArmiaKrajowaTemplate.chernarus_summer/mission.sqm#L144-L150
-------
https://github.com/official-antistasi-community/A3-Antistasi/blob/dda9e7ced319f5ffa12f7577c5e236cd112a12f5/A3-Antistasi/Templates/A3-AATemplate.Altis/mission.sqm#L158-L165

**Comment by Toakan** [comment]
@Bob-Murphy Are any of these likely to change between now and next release?
