### ISSUE TITLE
[Feature Request]: Purchasable fuel tanks should not be confused with fuel sources.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2213]
### Related problem

Some players on the test server had an intuitive feeling that the fuel tanks could act as fuel sources in the garage.

### Proposed feature

We need to think of a way to make it obvious that garaging the fuel tank will refund it rather than adding it to the garage.
This could be as simple as a name change when buying or the wording used for garages "fuel-sources".

### Alternative solutions

In future, we can go with a managed fuel resource which would probably make more sense than magical buying. But a simpler solution can be applied now without much code effort.

**Comment by killerswin2** [comment]
Easiest solution is to make it commander only and use the sell vehicle instead of garage vehicle. I might attempt to jerry-rig fuel source tab in Hakon's garage, I have a function that removes the fuel from sources in the garage.

**Comment by HakonRydland** [comment]
dont attempt to jerry rig the garage, it is for enterable vehicles only and should not be cluttered with misc stuff like this.
personally i belive a improved dialog would resolve this, with context sensitive text.
as for renaming "fuel sources" in the garage, i struggle to find an apt alternative as fuel sources are not limited to fuel trucks, but can be rather any vehicle with the appropriate configuration, so to provide. example: iirc vanilla has armored vehicles (command vehicles) that are fuel sources.

as a temporary solution, making it an commander only option under the sell vehicle button would work.
