### ISSUE TITLE
Check maps if towns need to be disabled

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#2221]
### Is the requested change related to a problem?

Missing mapinfo regarding towns that might need disabling for following maps:
- [x] Altis
- [x] Virolahti
- [x] Takistan
- [x] Sahrani
- [x] Livonia
- [x] Chernarus Summer
- [x] Chernarus Winter

### Describe the solution you'd like.

Check and implement if needed

**Comment by CalebSerafin** [comment]
The list turned into a checklist. All members should be able to check.

**Comment by jaj22** [comment]
There's a farm "town" with a resource on it in northwest Virolahti. That one probably shouldn't be counted as a town.

Generally any really small group of buildings with another marker on it shouldn't count as a town.

**Comment by jaj22** [comment]
"Pop Ivan" on Chernarus definitely shouldn't count as a town:

https://cdn.discordapp.com/attachments/647694189236322305/954391318694592563/bug.png

**Comment by Bob-Murphy** [comment]
merged into unstable
