### ISSUE TITLE
Check maps if Antennas should be added

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#2222]
### Is the requested change related to a problem?

Missing mapinfo regarding Antennas for following maps:
- [x] Anizay
- [x] Kunduz
- [x] Malden

### Describe the solution you'd like.

Check and implement if needed

**Comment by CalebSerafin** [comment]
Turned list into a checklist. All members should be able to check.

**Comment by Bob-Murphy** [comment]
merged into unstable
