### ISSUE TITLE
Check maps if population needs modification

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#2223]
### Is the requested change related to a problem?

Missing mapinfo regarding population that might needs modification for following maps:
- [x] Takistan
- [x] Tembelan Island
- [x] Sahrani
- [x] Malden

### Describe the solution you'd like.

Check and implement if needed

**Comment by CalebSerafin** [comment]
Turned list into a checklist. All members should be able to check.

**Comment by Bob-Murphy** [comment]
merged into unstable
