### ISSUE TITLE
Things to change for move to mod

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#2227]
This issue is to collect things that need updating/fixing for the move to mod:

- [x] UI or fix for colour overwrite

- [x] #2233

- [x] Automated build system via GitHub Actions that published to Steam Workshop
- trigger when something is merged into unstable
- have a consecutive build number that's also visible in ingame UI (also needs UI integration from @CalebSerafin )
- have the ## of the merged PR automatically published in the change notes on steam (steam API)

**Comment by CalebSerafin** [comment]
Hide side faction parameter settings.
Fix red and white UI buttons. Due to naming conflicts. Present in main menu and arsenal

**Comment by CalebSerafin** [comment]
Update/Correct Takistan Map Info.

**Comment by HakonRydland** [comment]
Top bar not shown on spawn, A3A_InfoBarRegistre contained the key: "KEYS"

**Comment by HakonRydland** [comment]
Investigate potential issue with Faction fuel number not transmitting to clients properly

**Comment by Bob-Murphy** [comment]
@HakonRydland everything done in here?

**Comment by HakonRydland** [comment]
Yes

**Comment by Bob-Murphy** [comment]
checklist completed
