### ISSUE TITLE
[Bug]: Sahrani and other maps may have uninteractable fuel stations.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2228]
### Describe the bug

Sahrani's fuel stations cannot be interacted with.
Either fix by Eden editor hide and place.
Or automatically hide and place fuel stations on load.

### How to reproduce

Load.

### Version

2.5.4

### Have you altered the code?

No

### What i have changed

```markdown
Unstable Mod Dev
```

### Map

Sahrani

### What server?

Community Test Server

### Time bug occured (Server time/UTC)

00:42:00

### Mods

```html
3CB BAF
```

**Comment by killerswin2** [comment]
Ace Compact for Cup Terrains not in cmd line for test server 1.

**Comment by Bob-Murphy** [comment]
Good to know.
That never was needed before as there was no ace interaction needed with map assets.

**Comment by killerswin2** [comment]
All servers in the future will need it now.

**Comment by killerswin2** [comment]
![Screenshot 2022-01-26 013609](https://user-images.githubusercontent.com/8095345/151121888-9f22d9aa-cfb2-4eac-b282-714c50e2a1e6.png)
Yeah, verified that It's just a not having the right compat on the server
