### ISSUE TITLE
- [ ] Update/Correct Takistan Map Info.

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#2234]
- [ ] Update/Correct Takistan Map Info.
2022/01/25, 109:51 String STR_antistasi_mission_info_sara_mapname_text not found.
In string table-use sarah instead of sarani.

_Originally posted by @CalebSerafin in https://github.com/official-antistasi-community/A3-Antistasi/issues/2227#issuecomment-1021469485_

**Comment by Bob-Murphy** [comment]
For Sahrani it's `sara`, not `sarah`
