### ISSUE TITLE
[Change Request]: Reduce enemies close radi

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2255]
### Is the requested change related to a problem?

It's too big.
Its annoying makes garrisons impossible.
No indicator = Make it smaller.

### Describe the solution you'd like.

Reduce all enemies too close radi.

### Alternative solutions

Re-add smokeAndCough

**Comment by jaj22** [comment]
As far as I know every case where this is used is now fixed.
