### ISSUE TITLE
[Bug]: Invader carrier position is broken on Sahrani

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2258]
### Describe the bug

The invader carrier is placed too far away from the mainland airports on Sahrani, preventing invaders from making progress beyond the southern half of the southern island.

Needs to be moved within 10km of a mainland airport, while remaining within 10km of the tiny island in the southwest. The general rule is that all airports should be reachable by 10km airport hops.

### How to reproduce

This template is dumb and annoying.

### Version

Anything with Sahrani in it

### Have you altered the code?

No

### Map

Sahrani

### What server?

Community Test Server

**Comment by Bob-Murphy** [comment]
merged into unstable
