### ISSUE TITLE
[Feature Request]: Add Expansion Information for Antistasi

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2269]
### Related problem

![Desktop Screenshot 2022 02 19 - 14 01 46 57](https://user-images.githubusercontent.com/31820984/154799977-7360e0ab-8700-407a-975f-8f39ff0d79c8.png)

### Proposed feature

![Desktop Screenshot 2022 02 19 - 14 02 22 54](https://user-images.githubusercontent.com/31820984/154799982-20a72470-e5b1-47a4-b0f4-21f7c0a42691.png)

**Comment by Bob-Murphy** [comment]
merged into unstable
