### ISSUE TITLE
Petros/Maru Consistency

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#2279]
Petros is only Maru on Tanoa
https://github.com/official-antistasi-community/A3-Antistasi/blob/d3db576a54679e2fcc58e6087f4034e462e7cb40/A3A/addons/core/functions/Base/fn_createPetros.sqf#L26

https://github.com/official-antistasi-community/A3-Antistasi/blob/d3db576a54679e2fcc58e6087f4034e462e7cb40/A3A/addons/core/functions/init/fn_initClient.sqf#L457-L458

Stringtables doesen't know either so its Petros or Maru or both.
https://github.com/official-antistasi-community/A3-Antistasi/blob/d3db576a54679e2fcc58e6087f4034e462e7cb40/A3A/addons/core/Stringtable.xml#L87-L96

Some Maps Description.exts like Maru while he is not on the Map.
https://github.com/official-antistasi-community/A3-Antistasi/blob/d3db576a54679e2fcc58e6087f4034e462e7cb40/A3A/addons/maps/Antistasi_Enoch.Enoch/description.ext#L32-L37

https://github.com/official-antistasi-community/A3-Antistasi/blob/d3db576a54679e2fcc58e6087f4034e462e7cb40/A3A/addons/maps/Antistasi_Kunduz.Kunduz/description.ext#L32-L37

https://github.com/official-antistasi-community/A3-Antistasi/blob/d3db576a54679e2fcc58e6087f4034e462e7cb40/A3A/addons/maps/Antistasi_Malden.Malden/description.ext#L32-L37

https://github.com/official-antistasi-community/A3-Antistasi/blob/d3db576a54679e2fcc58e6087f4034e462e7cb40/A3A/addons/maps/Antistasi_Stratis.Stratis/description.ext#L32-L37

https://github.com/official-antistasi-community/A3-Antistasi/blob/d3db576a54679e2fcc58e6087f4034e462e7cb40/A3A/addons/maps/Antistasi_tem_anizay.tem_anizay/description.ext#L32-L37

https://github.com/official-antistasi-community/A3-Antistasi/blob/d3db576a54679e2fcc58e6087f4034e462e7cb40/A3A/addons/maps/Antistasi_Tembelan.Tembelan/description.ext#L32-L37

https://github.com/official-antistasi-community/A3-Antistasi/blob/d3db576a54679e2fcc58e6087f4034e462e7cb40/A3A/addons/maps/Antistasi_vt7.vt7/description.ext#L32-L37

**Comment by CalebSerafin** [comment]
I agree that this can be flattened to just Petros. 👍 he has become the de-factor shadow-man in the struggle.

**Comment by Bob-Murphy** [comment]
Yep.
#KillMaru

**Comment by Bob-Murphy** [comment]
merged
