### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#228]
Hi AlexTriada,

we have the first batch of english strings you can translate to russian.
The file is call Stringtable.xml and is in the main folder.
Please follow the instructions Tad has posted in the Wiki. You can find it at the following link:
https://github.com/official-antistasi-community/A3-Antistasi/wiki/Languages-and-Localisation

Also, for the moment please stop putting up pull requests as we have a few bugs we definitely need to fix for the current release which is a little bit fucked. Therefore we would not merge them anyway ;)

Please don't close that issue when you have translated the first batch. Tad or I will close it once the stringtable is completed.

**Comment by AlexTriada** [comment]
OK, i start the translate work

**Comment by Bob-Murphy** [comment]
Please note that I found a small error within the stringtable which i fixed. Please look here what I did.
https://github.com/official-antistasi-community/A3-Antistasi/commit/963a0042ced667b061a33ef62d864eb38ec88ad2

Also, please don't translate the version number as it automatically pulls the correct one from original.

**Comment by AlexTriada** [comment]
ok! don't translating the version number

**Comment by killerswin2** [comment]
@Bob-Murphy check if we can close this now that we have more translations.
