### ISSUE TITLE
Non used variable set : _adminType

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#229]
This is weird, if your admin state is != 0 then you're forgiven. Why are we then setting an admin type if the player is an admin?

https://github.com/official-antistasi-community/A3-Antistasi/blob/dda9e7ced319f5ffa12f7577c5e236cd112a12f5/A3-Antistasi/punishment.sqf#L58-L61

This line:
```SQF
_adminType = "Voted";
	if (call BIS_fnc_admin == 2) then {_adminType = "Logged"};
```
Could become:
```SQF
	if (call BIS_fnc_admin == 2) then {_adminType = "Logged"} else {_adminType = "Voted";};
```

Better yet, why is this even calling the same function twice in a check? Call the check once, store in a Parameter then check the parameter.

ie:
```SQF
_adminType = call BIS_fnc_admin
if (_adminType != 0) exitWith 
{
	if (_adminType == 2) then {_adminType = "Logged"} else {_adminType = "Voted";};
        [format ["%1: [Antistasi] | INFO | PUNISHMENT | EXCEPTION, ADMIN, %2 | %3", servertime, 
_adminType, _playerStats]] remoteExec ["diag_log", 2];
	["TK NOTIFICATION!\nYou would be punished but it appears you remembered to #login before you started killing people.."] remoteExec ["hint", player, false];
};
```

**Comment by CalebSerafin** [comment]
Done in [PR#244](https://github.com/official-antistasi-community/A3-Antistasi/pull/244).
