### ISSUE TITLE
[Bug]: Civ Heli in civ are not used nor allow undercover

### ISSUE THREAD

**Issue by killerswin2** [official-antistasi-community/A3-Antistasi#2293]
### Describe the bug

Civilian helicopter don't have any references. 

### How to reproduce

Spawn a helicopter in the civ list in the template and it will not be undercover, nor do civ helis spawn in game.

### Version

2.6.1

### Have you altered the code?

No

### What i have changed

```markdown
n/a
```

### Map

Altis

### What server?

Community Test Server

**Comment by jaj22** [comment]
Not a bug, more of a feature stub :P

**Comment by killerswin2** [comment]
resolved
