### ISSUE TITLE
Tasks for JIPs

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#23]
*Version:* current unstable

*Mods:* Enhanced Soundscape, Enhanced Movement, CBA

*Environment*: MP all

*.rpt attatched?* no

*have you edited the missionfile?*: yes

***Issue:***

I don't think I have ever encountered an occasion where tasks have properly propagated for JIP clients. I know this was an issue before the saving system changes, and I still haven't looked at those at all.

**Comment by Spoffy** [comment]
I believe this is a base Arma issue - but I'll look into it.

**Comment by AlexTriada** [comment]
Does anyone do it now?

**Comment by PoweredByPot** [comment]
https://community.bistudio.com/wiki/Arma_3_Task_Framework

After reading through the forums, if we use the new task system properly, we should not be having problems with JIP tasks. At first glance I could not see what we are doing wrong, other than trying to implement the system within our own custom functions.

**Comment by Bob-Murphy** [comment]
@Spoffy @PoweredByPot 
Any new information regarding this?

**Comment by PoweredByPot** [comment]
apparently JIP detection is broken on any dedicated server using the -autoinit parameter. Since the mission cannot complete init without a player present to choose the starting HQ location anyways, there is really no point in trying to find another way to fix this.
