### ISSUE TITLE
[Feature Request]: Toggle Antistasi Revive System

### ISSUE THREAD

**Issue by RufusVulpecula** [official-antistasi-community/A3-Antistasi#2300]
### Related problem

A parameter to disable A3 revive system, even without ACE medical running would offer more compatibility for various community damage handlers.

### Proposed feature

There's already a check for ACE medical. A mission parameter toggle should be easy to implement.

### Alternative solutions

For the last year I've been playing the scenario with a friend with revive system disabled. I've deleted the ACE medical check at line 43 of "fn_handleDamage.sqf" and line 50 of "fn_handleDamageAAF.sqf" and just left "exitWith {};" and it works without any issues. I'm sure an additional parameter check here to "exitWith {};" would be easy to implement as well.

**Comment by killerswin2** [comment]
You didn't need to duplicate the issue.

**Comment by RufusVulpecula** [comment]
Thought it would not be visible, feel free to delete the one necessary please. Sorry!

**Comment by killerswin2** [comment]
No worries, we see all the messages

**Comment by killerswin2** [comment]
I'll assign myself to other issue to get more eyes on it.

**Comment by Bob-Murphy** [comment]
will be closed as dublicate of #1503

**Comment by Bob-Murphy** [comment]
Just because an issue is old does not mean that we are forgetting it.
