### ISSUE TITLE
Rebels can approach downed heli mission whilst undercover

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#2311]
Observed on testserver 2.
A player could approach the downed heli without any issue.
We should the area break undercover as that can be counted as suspicious behaviour
![ArmA 3 Screenshot 2022 04 02 - 02 36 27 47](https://user-images.githubusercontent.com/50651578/161357293-c3a3407e-30bf-4832-8919-755096693ba9.png)
.

**Comment by jaj22** [comment]
Prevented in #2574
