### ISSUE TITLE
[Bug]: Assigning a Squad to Garrison does not make them Mount statics until restart

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#232]
As in subject. If you assign a Squad to a Garrison, they will not mount any statics in the area until the server is restarted and the Garrison is rebuilt.

**Comment by AlexTriada** [comment]
need to check, before you just needed to respawn this point

**Comment by Bob-Murphy** [comment]
This most likely will be influenced by the AI change.
Don't start working on it.

**Comment by wurzel0701** [comment]
I take this, I am reworking the code for joining a garrison anyways, so I can do it

**Comment by wurzel0701** [comment]
Done in #759

**Comment by jaj22** [comment]
Patched into old garrison code a while back. Eventually worked on DS.
