### ISSUE TITLE
Error in A3A_fnc_CSATCrate occured

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#236]
Whilst testing i ran into an error in CSAT crate. Please fix.

7:53:59 Error in expression <s = getArray (configFile / "CfgWeapons" / _thingX / "magazines");
_crate addMaga>
 7:53:59   Error position: </ _thingX / "magazines");
_crate addMaga>
 7:53:59   Error /: Type Array, expected Number,String,Not a Number
 7:53:59 File Ammunition\CSATCrate.sqf [A3A_fnc_CSATCrate]..., line 30

All i did was come near to an opfor-seaport, the stuff spawned and the error popped up.
I have NOT looked into the crate, therefore it's uncertain if the error has an effect on what's on the crate. This also needs to be checked.

**Comment by Bob-Murphy** [comment]
I just checked again - with the current unstable version (last commit  e59ba31b1658c0cc67b87c84dd6ea80fa4edcd3f) the error still occurs and the **CSAT box with RHS modset is empty.**
![image](https://user-images.githubusercontent.com/50651578/64183173-bf6d2580-ce69-11e9-89bd-d7f50108de9f.png)
![image](https://user-images.githubusercontent.com/50651578/64183188-c8f68d80-ce69-11e9-807b-5bb9906364b3.png)

**Comment by Bob-Murphy** [comment]
RHS Blufor is working
![image](https://user-images.githubusercontent.com/50651578/64183423-2c80bb00-ce6a-11e9-8753-7115c8525bc9.png)

**Comment by Bob-Murphy** [comment]
Now i came across a **similar problem in Vanilla at the BLUFOR crate**
16:54:14 Error in expression <s = getArray (configFile / "CfgWeapons" / _thingX / "magazines");
_crate addMaga>
16:54:14   Error position: </ _thingX / "magazines");
_crate addMaga>
16:54:14   Error /: Type Array, expected Number,String,Not a Number
16:54:14 File Ammunition\NATOCrate.sqf [A3A_fnc_NATOCrate]..., line 31

but at least something loaded
![image](https://user-images.githubusercontent.com/50651578/64184570-efb5c380-ce6b-11e9-8798-a5c20f35b640.png)

**Comment by Bob-Murphy** [comment]
Same problem with **VANILLA OPFOR**
But now this is also partly loaded
![image](https://user-images.githubusercontent.com/50651578/64184723-30add800-ce6c-11e9-8f81-fb418db74aa9.png)

**Comment by PoweredByPot** [comment]
fixed in d18c6de
