### ISSUE TITLE
[Bug]: Interface Hang on Garage.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2360]
### Describe the bug

x

### How to reproduce

x

### Version

2.5.4

### Have you altered the code?

Yes

### What i have changed

```markdown
x
```

### Map

Tanoa

### What server?

Community Test Server

### Time bug occured (Server time/UTC)

x

### Mods

```html
x
```

### Additional context

x

**Comment by jaj22** [comment]
No reports for a while, gonna assume that the fix worked.
