### ISSUE TITLE
[Game balance]: Players Hunker down and wreck QRF

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2361]
### What is wrong with the balance currently?

Currently, players can plan to hunker down and dig trenches and defend against any attacks. artillery explodes at ground level, and only kills players who are not hunkered down. 

### Describe the solution you'd like.

Maybe bring back napalm but make the damage delayed to that players can run away?
Or cluster munitions for detected hunkering down.

**Comment by Rythoka** [comment]
Another realistic option would be to send an attack elsewhere, forcing players to respond to that attack, where they will have less of an opportunity to dig-in.

**Comment by jaj22** [comment]
Gonna call this as closed. QRF responses are now heavily front-loaded, so digging in after flipping a flag rarely makes much difference. You can dig in before you start attacking, but I wouldn't say that's one of the most effective strats. Tends to result in you losing your transport vehicle to arty and having to walk 300m over open ground with scattered enemies taking pot-shots.

Also enemy napalm is usable now (and default on), although I'm tempted to double the use rate.
