### ISSUE TITLE
[Bug]: Refund fuel on save.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2363]
### Describe the bug

Fuel is not refunded on save when within HQ.

### How to reproduce

Save and load.

### Version

2.5.4

### Have you altered the code?

Yes

### What i have changed

```markdown
Test Server
```

### Map

Tanoa

### What server?

Community Test Server

### Time bug occured (Server time/UTC)

5/10/22 17:35:44

### Additional context

Feedback:

Make fuel containers either get saved or refund when server restarts

**Comment by jaj22** [comment]
Pretty sure this is fixed in #2449, or supposed to be.
