### ISSUE TITLE
[Game balance]: AI respond immeditally to AT or AA missles.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2364]
### What is wrong with the balance currently?

Support call is instant for AA missile launches

### Describe the solution you'd like.

Give the players more time

### Additional context

Feedback

Decrease frequency for mortar response after someone fire a guided AA/AT missile. It's not very realistic IMO

**Comment by jaj22** [comment]
Fixed in #2383.
