### ISSUE TITLE
[Feature Request]: Add vehicle cost to templates.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2372]
### Related problem

x

### Proposed feature

Templates should define vehicle costs.
This should be a gradual change and use the current auto-detection / assumption as a stand-in.

### Alternative solutions

x

### Additional context

x

**Comment by killerswin2** [comment]
This should wait until we have static loot lists, or have working json support.

**Comment by killerswin2** [comment]
https://github.com/official-antistasi-community/A3-Antistasi/pull/2546 partly addresses this for rebels

**Comment by killerswin2** [comment]
This was resolved in #2546
