### ISSUE TITLE
[Bug]: Check garage preview light placement

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#2375]
### Describe the bug

The light source in the preview is opposite the camera, which results in the dark unlit side facing the camera. It's not too bad since there is plenty of ambient light. But it would look way better with the light positioned around 45 degrees from the camera.

### How to reproduce

x

### Version

x

### Have you altered the code?

No

### What i have changed

```markdown
x
```

### Map

x

### What server?

Community Test Server

### Time bug occured (Server time/UTC)

x

### Mods

```html
x
```

### Additional context

x

**Comment by Tiny-DM** [comment]
Is this still an issue? According to the code, the light source should be attached directly to the preview camera, and I haven't noticed this issue. Will test later.
