### ISSUE TITLE
potential variable name change from translations update

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#24]
This is a change request that only affects the codebase.

Can we please change the references to "controls" to "Roadblocks". I know the Spanish variable "controles" was super misleading, but defining them as "controls" or "control points" really isn't accurate.

**Comment by PoweredByPot** [comment]
This issue does not address the problem correctly. There are actually two types of installations handled by this one variable: roadblocks and wilderness camps.

Closing as it should be handled with all other variable re-names.

**Comment by Bob-Murphy** [comment]
Outdated and not needed anymore.
