### ISSUE TITLE
[Bug]: Segmentation fault when hosting Cam Lao Nam on Linux

### ISSUE THREAD

**Issue by DomiStyle** [official-antistasi-community/A3-Antistasi#2406]
### Describe the bug

The linux dedicated server crashes when trying to load Antistasi on the map Cam Lao Nam. Every other mission tested with this map works, all other maps on Antistasi work as well.

### How to reproduce

1. Download the dedicated server with the creator DLC on Linux with `steamcmd +force_install_dir /<installdir>/arma3 +login <username> +app_update 233780 -beta creatordlc validate +quit`
2. Start the server
3. Join the server
4. Select slot and hit join
5. Server crashes after the mission downloaded about 2000 KB

### Version

2.5.4

### Have you altered the code?

No

### Map

Cam Lao Nam

### What server?

Private dedicated server with Headless client(s)

### Mods

```html
-mod=vn
```

### Additional context

[log.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/9113367/log.txt)

I'm not sure whether to report this to Bohemia or here but I guess I'll start here since it only happens in this mission.

There's a similar issue here: https://github.com/Savage-Game-Design/Mike-Force/issues/2

That one is resolved by copying the files mentioned in https://github.com/Savage-Game-Design/Mike-Force/issues/2#issuecomment-834478064 though.

**Comment by HakonRydland** [comment]
This is not a antistasi issue, and the described workaround is for the users servers, reason for the problem looks like its caused by using a/some/all air assets, as we need to use said assets we cant fix this issue.

You should as the mike force team suggested report it to BI.

**Comment by fbuchmeier** [comment]
I had the same issue with Cam Loa Nam until the [latest Prairy Fire patch v1.2.1](https://forums.bohemia.net/forums/topic/234698-sog-prairie-fire-changelog/?do=findComment&comment=3465825).

Now the missions loads correctly without any segmentation faults.
