### ISSUE TITLE
[Bug]: can pick up any object when trying to carry a carriable object

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#2425]
### Describe the bug

you can carry objects not intended to carry

### How to reproduce

flick to another object when using the carry action (the time from action click to pointing at new target need to be as low as possible)

### Version

2.4.2

### Have you altered the code?

No

### Map

-

### What server?

LAN Hosted, Private dedicated server, Private dedicated server with Headless client(s)

**Comment by killerswin2** [comment]
Might be time to place the add actions on the carriable object or I finally merge all the carrying code...... like I said I would 5 months ago....

**Comment by jaj22** [comment]
Bear in mind that this specific issue doesn't need anything difficult for a fix. Because carryingCrate is only used for carrying surrender crates, it can simply check whether the object is a valid crate in the pickup case. It already does in the drop case.

**Comment by killerswin2** [comment]
Didn't close on merge

**Comment by jaj22** [comment]
#2426 was busted and had to be reverted, so reopened.

We can just do the trivial fix as described above if we need this patched up before the next release.

**Comment by Bob-Murphy** [comment]
@jaj22 was that ever done?

**Comment by jaj22** [comment]
Not yet, no.
