### ISSUE TITLE
[Bug]: Livonia Antistasi 2.5.4 3CB Factions version not working

### ISSUE THREAD

**Issue by awpexx** [official-antistasi-community/A3-Antistasi#2437]
### Describe the bug

When trying to play Antistasi 2.5.4 on Livonia with the 3CB Template, it doesn't load (no info bar, no interactions of any sort, no items in arsenal, the mission just doesn't load). I also tried the Vanilla Template and RHS Template and they work as they should. This only happens when the 3CB Template is loaded.
I have tested this with ace and no ace and it still gives this bug.
I have also tested this with no mods beside the 3CB Template (eg. no gruppe adler trenches, no ace, mo nothing except the 3CB Template) and it still results in this bug.
![image](https://user-images.githubusercontent.com/49695288/185203982-55c5f31d-c67a-49c0-9bcf-c741145a1630.png)
![ArmA 3 2022 08 17 - 18 12 52 02_Moment](https://user-images.githubusercontent.com/49695288/185204601-cb00cb9e-8cde-4936-bc84-561dbf5efa1e.jpg)
![ArmA 3 2022 08 17 - 18 12 52 02_Moment(3)](https://user-images.githubusercontent.com/49695288/185208419-161126cc-8f8b-4aba-9dfb-0c5a30cbff93.jpg)
![ArmA 3 2022 08 17 - 18 12 52 02_Moment(2)](https://user-images.githubusercontent.com/49695288/185208705-1660f3ae-ad3c-4f0f-9caa-41d4089f22d6.jpg)

### How to reproduce

-Load the 3CB mod template (RHS AFRF, RHS USAF, RHS GREF, RHS SAF and 3CB Factions)
-Load the Antistasi Livonia Mission on any server
-Load in the mission
-Map screen will be funky with the markers (eg. no outpost markers, airbases, etc. no antistasi markers)
-When you actually load in, you can wait for hours and the mission will never load (no GUI, interactions, no nothing)
- you can still walk around and do normal stuff eg check inventory
- arsenal will also have no items
![image](https://user-images.githubusercont
![ArmA 3 2022 08 17 - 18 12 52 02_Moment](https://user-images.githubusercontent.com/49695288/185208512-9c5411af-9eef-4ecc-b8c7-4939b8684ed4.jpg)
![ArmA 3 2022 08 17 - 18 12 52 02_Moment(3)](https://user-images.githubusercontent.com/49695288/185208531-bee9dc68-57fa-471a-88a6-9a693e3ea33a.jpg)

ent.com/49695288/185206565-6f975310-561e-49ef-93ec-df622709e7f4.png)
![image](https://user-images.githubuser
![ArmA 3 2022 08 17 - 18 12 52 02_Moment(2)](https://user-images.githubusercontent.com/49695288/185206649-40c275ac-6ee2-469c-bfcf-c635dddca275.jpg)
content.com/49695288/185206606-0ab9a47b-5eca-4f48-9c59-fb3e74664e8c.png)
![image](https://user-images.githubusercontent.com/49695288/185208877-3d92f8a0-ebde-4b32-9e18-089340d0ffd7.png)

### Version

2.5.4

### Have you altered the code?

No

### Map

Livonia

### What server?

LAN Hosted

### Mods

```html
I couldn't load the HTML file here so I put in text from the RPT, if you need the HTML file, DM me on discord: awpexx#3730


JSRS Soundmod - RHS SAF Support CE.20.0419
JSRS Soundmod - RHS GREF Support CE.20.0419
DUI - Squad Radar v1.9.3
@Blastcore Edited (standalone version)
VET_Unflipping - 1.3.2
Gruppe Adler Trenches
Looting Enhanced
Enhanced Movement Rework
@ACE Compat - RHS- SAF
@ACE Compat - RHS- GREF
@ACE Compat - RHS USAF
@ACE Compat - RHS AFRF
3CB Factions
JSRS Soundmod - RHS USF Support CE.20.0419
JSRS Soundmod - RHS AFRF Support CE.20.0419
Enhanced Movement
Advanced Combat Environment 3.15.0
RHS: Serbian Armed Forces
RHS: GREF
JSRS Soundmod - CE.20.0423
RHS: United States Forces
RHS: Armed Forces of the Russian Federation
Community Base Addons v3.15.7
```

### Additional context

I couldn't load the RPT file here, if you need it, contact me on discord: awpexx#3730

**Comment by Bob-Murphy** [comment]
fixed and published, sorry for the delay
