### ISSUE TITLE
[Feature request]: ACE cargo should be extracted on garaging 

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2447]
I was going to put this in the general vehicle deleted EH, but it turns out that ACE already deletes the attached objects in its own deleted EH, so there's no perf issue. Not sure if that was added recently or I mis-tested before.

Some working code. Not sure if you'd want this added straight to the garage code or a public proxy:
```
{
    if !(_x isEqualType objNull) then { continue };
    if (typeOf _x in ["ACE_Wheel", "ACE_Track"]) then { continue };
    [_x, _veh] call ace_cargo_fnc_unloadItem;
} forEach (_veh getVariable ["ace_cargo_loaded", []]);
```

**Comment by HakonRydland** [comment]
in general i preferer to keep anything not directly connected to the garage in proxy functions, i will take a look at implementing it this week
