### ISSUE TITLE
[Bug]: Cam Lao Nam issues discovered during attack/support testing 

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2451]
It's important for outposts to have vehicle spawn places on CLN where possible because the factions there will often be low-air. The following outposts should definitely have spawn places added: 19, 22, 31, 32, 33, 34, 35, 36, 38. Ideally outposts 26 and 28 too, but that may involve some unreasonable boundary stretching. One option might be to create additional off-road nav points.

Additional bug: The spawn point for airport_5 (Maxwell Island) is placed on top of the spawn point for airport_6.

**Comment by Bob-Murphy** [comment]
all done besides outpost 26

**Comment by Bob-Murphy** [comment]
merged into unstable
