### ISSUE TITLE
Convoy mission ignores vehicle not available

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#247]
The convoy mission chooses the convoy escort vehicles in the following section 

https://github.com/official-antistasi-community/A3-Antistasi/blob/dda9e7ced319f5ffa12f7577c5e236cd112a12f5/A3-Antistasi/Missions/CONVOY.sqf#L200-L217

As seen, if the vehicle _typeVehEsc is not available a new _typeVehX is selected, but the last line spawns the _typeVehEsc. One of the variables is obsolete in this case.

**Comment by wurzel0701** [comment]
In line 204, the wrong vehicle type is removed from the vehicle pool too

**Comment by Bob-Murphy** [comment]
@wurzel0701 
I think this was solved by your new system?
If so, please confirm & close.

**Comment by wurzel0701** [comment]
Will be in 2.4. Currently the new system does not gets called

**Comment by wurzel0701** [comment]
Should the old system still be fixed, or just accept the issue?

**Comment by wurzel0701** [comment]
Done in #417
