### ISSUE TITLE
Duplicate NV Goggles in Arsenal

### ISSUE THREAD

**Issue by Auroraah** [official-antistasi-community/A3-Antistasi#248]
- Version 2.1.1
- MP LAN Server
- No edits made to mission file

It is possible to duplicate NV goggles in the Arsenal

Steps to reproduce:

1. Save a loadout without NV goggles
2. Add NV to your character
3. Load the loadout from step 1

2 sets of NV goggles are added back to the arsenal

**Comment by PoweredByPot** [comment]
NVG's were badly handled within the code and this will be dealt with as part of Loot Crates 2

**Comment by Bob-Murphy** [comment]
@PoweredByPot 
Update?

**Comment by PoweredByPot** [comment]
closing as this should be dealt with properly now.
