### ISSUE TITLE
Update WW2 mission.sqm

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#249]
clean of dependencies
connect with hc_sub

**Comment by CalebSerafin** [comment]
Mission.sqm is updated everywhere on this Github. It is only missing on steam workshop.

**Comment by Bob-Murphy** [comment]
@CalebSerafin Thank you.
Will check it nevertheless :)

**Comment by Bob-Murphy** [comment]
done
