### ISSUE TITLE
[Change Request]: Change 'Edit Terrain Object'-Module to 'Hide Terrain Objects'-Module if Objects are hidden

### ISSUE THREAD

**Issue by targetingsnake** [official-antistasi-community/A3-Antistasi#2504]
### Is the requested change related to a problem?

Buildings are not hidden the correct way, when people loading ingame. If module fails server needs a restart.

### Describe the solution you'd like.

Change 'Edit Terrain Object'-Module to 'Hide Terrain Objects'-Module if Objects are hidden

### Alternative solutions

none to my knowledge

**Comment by CalebSerafin** [comment]
Do you have cases where the Edit Terrain Object module fails?

**Comment by targetingsnake** [comment]
> Do you have cases where the Edit Terrain Object module fails?

we had issues most recent posted on discord in #help (28.10.2022 20:14 UTC)

**Comment by CalebSerafin** [comment]
So it looks to be repeatable? I would opt for only replacing the cases that break as I believe that EditTerrainObject is faster that Hide Terrain Objects. Previous startup times were noticeably longer before we switch to EditTerrainObject .

**Comment by Bob-Murphy** [comment]
I'll go over the map, hence I asked him to open this ticket for me.
