### ISSUE TITLE
Petros doesent get a Loadout applied.

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#2516]
Each time you Load a Save/Start a New Save Petros spawns without a Loadout applied,
Easy to Spot by him Wearing a Vanilla Uniform "U_IG_Guerilla2_3" or with
```sqf
petros getVariable "UnitType";
```
This should return "loadouts_reb_militia_Petros".
Each Time he Respawns he gets the Loadout applied and wears whatever Uniform he is supposed to Wear.

**Comment by jaj22** [comment]
Ah yeah, my bad. Stripped some stuff from createPetros and figured we didn't need to delete & recreate him on startup anymore, but the uniform is only set in A3A_fnc_createUnit.

**Comment by jaj22** [comment]
Should be fixed in #2522.
