### ISSUE TITLE
Excempt adminLogged and dev steam64s from the member radius

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#2530]
This makes no sense to happen when I'm logged in as admin and teleporting around to check dev stuff.
![image](https://user-images.githubusercontent.com/50651578/200177370-2911dc9f-7ca2-4045-a19b-59988d64b08f.png)

**Comment by HakonRydland** [comment]
yea an admin exemption is reasonable

**Comment by killerswin2** [comment]
Yeah, but only when logged in
