### ISSUE TITLE
[Bug]: Minefields

### ISSUE THREAD

**Issue by Air989** [official-antistasi-community/A3-Antistasi#2540]
### Describe the bug

I was placing down an AP and an AT Minefield there it worked without a problem.
But when i try to place down a second Minefield of any type it always says that i need at least 5 mines of that type but i have about 60 of each.

### How to reproduce

Place the mines down and then go ahead and place a second minefield down.

### Version

2.5.4 

### Have you altered the code?

No

### Map

Altis

### What server?

Private dedicated server, Private dedicated server with Headless client(s)

### Time bug occured (Server time/UTC)

5:30 ETC

### Mods

```html
Ace3
CBA_3
ACRE 2
Jsrs soound mod
```

**Comment by jaj22** [comment]
Only one specific AT and one specific AP mine will work. That error message isn't used for anything except checking the mine count, so I'm guessing that the first call uses all the mines of the correct type, and then for the second you only have wrong-type mines.

**Comment by Air989** [comment]
> Only one specific AT and one specific AP mine will work. That error message isn't used for anything except checking the mine count, so I'm guessing that the first call uses all the mines of the correct type, and then for the second you only have wrong-type mines.

Okay bud thank you i will look into this and see i have had this happen before and alot of they people have had this happen too. 

https://www.reddit.com/r/A3AntistasiOfficial/comments/yti68w/need_help_with_minefields/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by Air989** [comment]
> Only one specific AT and one specific AP mine will work. That error message isn't used for anything except checking the mine count, so I'm guessing that the first call uses all the mines of the correct type, and then for the second you only have wrong-type mines.

Okay so I tested this and a few others did as well in the Reddit post and it still won't work I think it may have something to do with when the item becomes infinite in the arsenal again I'm no dev but I'm trying to find the issue.

**Comment by Lazejun** [comment]
-1 is less than 5.

In general there are just a few simple issues, Wrong mines and Infinite mines.

The minefield feature is supposed to be reworked at some point, it's pretty useless anyway, you have more success planting mines yourself

**Comment by Air989** [comment]
> -1 is less than 5.
> 
> 
> 
> In general there are just a few simple issues, Wrong mines and Infinite mines.
> 
> 
> 
> The minefield feature is supposed to be reworked at some point, it's pretty useless anyway, you have more success planting mines yourself 

Okay thank you!
