### ISSUE TITLE
[Bug]: Problems with Case Sensitivity on Linux dedicated server

### ISSUE THREAD

**Issue by returntoreality** [official-antistasi-community/A3-Antistasi#2588]
### Describe the bug

On linux the dedicated server would not start with an error "ErrorMessage: Cannot open file '/srv/steamcmd/arma3/@Antistasi\addons\garage' "
Linux filesystems are case sensitive, so the paths to the addons need to be in the correct case. When creating symlinks to the pbos the server starts.
inside the @Antistasi/addons folder:
```console
ln -s JeroenArsenal.pbo jeroenarsenal.pbo
ln -s Garage.pbo garage.pbo
ln -s Logistics.pbo logistics.pbo
ln -s Events.pbo events.pbo
ln -s GUI.pbo gui.pbo
```
I guess the addons are referenced somewhere in lower case and this works on Windows but not on Linux

### How to reproduce

Try starting a dedicated server on a Linux machine. 

### Version

3.0.0

### Have you altered the code?

No

### What i have changed

```markdown
I did not alter the code
```

### Map

n/a

### What server?

Private dedicated server

**Comment by jaj22** [comment]
Can you confirm that you needed all five of those symlinks? Or did you only test with five or none?

Not seeing anything plausible as a miscasing from our end, although I may have lost something in the preprocessor spaghetti. Will keep looking.

**Comment by returntoreality** [comment]
Well at least the first two. I have not checked if the others are definitely needed.

**Comment by jaj22** [comment]
Also, what if you just lowercase the original folders rather than using the symlinks? Wondering if Arma itself is just lowercasing all PBO references.

**Comment by returntoreality** [comment]
I tested now all files and they all have to be lowercase. I also tested to just rename instead of symlinking GUI.pbo to gui.pbo and that worked as well.

**Comment by Bob-Murphy** [comment]
So us lowercasing the folders which create the PBOs will solve this issue for others that use linux based Arma servers, correct?

**Comment by returntoreality** [comment]
I have not tried building the mod after lowercasing the folders (just renaming the files) but if that results in lowercased files I'd guess that this is the case.

**Comment by jaj22** [comment]
Yeah, looks like Arma just forces all references to lower-case rather than trying to given case first, which is disappointing. Means we should lowercase all the addon folder/PBO names for the next version. Not sure whether JeroenArsenal should be changed to jeroen_arsenal or jeroenarsenal. @HakonRydland ?

**Comment by arron1993** [comment]
An FYI to anyone encountering this the Arma wiki has documented this problem with mods in general and provides a command you can run on the mod directories.

The command - `find . -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;`

The docs - https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server#Case_sensitivity_.26_Mods

Tested this myself and it appears to work.

**Comment by Bob-Murphy** [comment]
merged
