### ISSUE TITLE
[Bug]: Player markers are somewhat broken

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2590]
Root cause is probably that `format ["%1", _unit]` is used as the name for the markers, which changes if a player changes squad, and probably even if they respawn in the same squad, leaving old markers around the map until the GPS is toggled.

Should be switched to something like `["A3A_pmrk_%1", name _unit]`, but that needs checking for remote control behaviour.

**Comment by Bob-Murphy** [comment]
merged
