### ISSUE TITLE
[Change Request]: Disable collision on carried HQ assets

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#2593]
### Is the requested change related to a problem?

People use HQ assets to slap people around when carrying them.
https://medal.tv/de/games/arma-3/clips/MZPdVVclOdSSt/1duLTNfEz54h?invite=cr-MSxJUDIsNzE5MTc1OTAs

### Describe the solution you'd like.

Disable collision of carried items like it was done for lootcrates and buyable items.

### Alternative solutions

Ban every steamID in existence so it doesn't happen anymore.

**Comment by killerswin2** [comment]
https://github.com/official-antistasi-community/A3-Antistasi/pull/2670 closes
