### ISSUE TITLE
[Bug]: Loading a Save gives INV Markers back.

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#2596]
### Describe the bug

When loading a Save in any Gamodemode all Starting Markers for INV that were taken by GOV will be given back to INV when you load a Save.

Its a lot more Noticeable on Maps like Sahrani and Takistan due to the 50 50 Split in Gamemode 3 (Reb vs GOV).

### How to reproduce

Quick way:
Start a Game in Gamemode 3 (Reb vs GOV), Save the Game, Load the Save.

At the first start everything works, GOV has all Markers, when you load the save all Starting Markers for INV will be given back to INV, even in Gamemode 3 where they wouldnt get anything.

The other way:
Start a Game on Takistan in Gamemode 1/2 both work the same for this.
```sqf
[Occupants,"airport_1"]remoteExec["A3A_fnc_markerChange",2];
[Occupants,"outpost_5"]remoteExec["A3A_fnc_markerChange",2];
[Occupants,"outpost_6"]remoteExec["A3A_fnc_markerChange",2];
[Occupants,"outpost_7"]remoteExec["A3A_fnc_markerChange",2];
[Occupants,"outpost_8"]remoteExec["A3A_fnc_markerChange",2];
[Occupants,"resource"]remoteExec["A3A_fnc_markerChange",2];
[Occupants,"resource_5"]remoteExec["A3A_fnc_markerChange",2];
[Occupants,"resource_6"]remoteExec["A3A_fnc_markerChange",2];
[Occupants,"airport_1"]remoteExec["A3A_fnc_markerChange",2];
```
Give all INV Starting Markers to GOV.

Save and Load the save,
["airport_1","outpost_5","outpost_6","outpost_7","outpost_8","resource","resource_5","resource_6"] will all be given to INV when you load the save.

### Version

3.0.0

### Have you altered the code?

No

### Map

Any Map, Takistan, Sahrani are just good to see the Issue.

### What server?

LAN Hosted

### Additional context

I realy hate these.

**Comment by jaj22** [comment]
Ah yeah, the save doesn't actually set occupant markers at all, just invaders and rebels. So whatever is set to invader beforehand is retained. I think there's actually an old bug with this on gameMode 1: If occupants capture an invader starting marker, it's returned to invaders on loading the save.

**Comment by Bob-Murphy** [comment]
merged
