### ISSUE TITLE
[Tools] Build tool needs to generate meta file with correct workshop id

### ISSUE THREAD

**Issue by HakonRydland** [official-antistasi-community/A3-Antistasi#2629]
currently we use the dev 1 id, this needs to be using the correct one as the launcher uses the meta.cpp id for auto mod fetching from steam

**Comment by Bob-Murphy** [comment]
We should move to 3 different keys (main, dev1, dev2) either way and not include the version number.
No clue when/if Armahosts will fix the issue of not deleting old keys, hence better safe than sorry from our end.
The version number is within the mission either way, so it's not critical to have it as part of the key.

**Comment by Bob-Murphy** [comment]
done
