### ISSUE TITLE
Repair Vehicles not working

### ISSUE THREAD

**Issue by reynonic** [official-antistasi-community/A3-Antistasi#2649]
I am doing Antistasi Plus 2.0. didn't know if this was a known issue with Antistasi - The Mod 2.0 or maybe I have a bad mod, like something in the ace suite or car packs or Global Mobilization that  might cause this. Garaging repairs, but vehicles and engineers don't repair for me. Delete if not allowed. Thanks.

**Comment by reynonic** [comment]
Can give my HTML, if it is thought this might be A3.0, along with any server logging, though I might need help finding the most appropriate logs for this.

**Comment by jaj22** [comment]
Do you have a case where repairing does work? Outside Antistasi? Different modset? Different factions? If no-one else reported a problem then that suggests it's something specific that you're doing.

**Comment by jaj22** [comment]
No response, assuming user error.
