### ISSUE TITLE
[Change Request]: Refactor the towing script

### ISSUE THREAD

**Issue by killerswin2** [official-antistasi-community/A3-Antistasi#2650]
### Is the requested change related to a problem?

We need to refactor the towing script to remove the execVM call it requires. Once we refactor the script execVM can be move to the exec blacklist for the mission. 

### Describe the solution you'd like.

Do something similar to the UPSMON refactor. Allow for Arma to compile the sqf functions at mission start instead of during mission init.

### Alternative solutions

- We could also just remove this script and only have spawn by players at HQ instead of in towns.

- Create our own script that uses setTowParent and ropes.

**Comment by MeltedPixel** [comment]
See also #2543

**Comment by MeltedPixel** [comment]
Also connected #2173

**Comment by MeltedPixel** [comment]
Additional #825

**Comment by killerswin2** [comment]
Closing because of near duplicates
