### ISSUE TITLE
[Bug]: Number of the same item required to unlock is stuck to 25

### ISSUE THREAD

**Issue by AAAAAAAAlan** [official-antistasi-community/A3-Antistasi#2658]
### Describe the bug

Parameter "Number of the same item required to unlock" is stuck to 25, even if you choose other options.

### How to reproduce

Installed mods: Antistasi - The Mod.

1. Start a fresh mission with parameter "Number of the same item required to unlock" set to any value other than 25. (For example, 15)
2. Transfer 15 pieces of the same weapon to arsenal.

AS IS: You will see 15 pieces of this weapon in arsenal. Weapon would be unlocked only if you add up another 10 pieces. (Because of default 25pc value)
TO BE: Weapon should be unlocked and become infinite. 

I made a small showcase video of this bug: https://www.youtube.com/watch?v=Owc3FOAd-XY

Also, please let me know if there is a way to fix it manually with editing save files.

### Version

3.1.0

### Have you altered the code?

No

### Map

Altis

### What server?

LAN Hosted

### Mods

```html
Only Antistasi - The Mod
```

**Comment by Lazejun** [comment]
That's not an Issue.

You put in Items, you didn't wait for a Resource tick/you didn't let the arsenal refresh itself.

Wait 10 minutes (Resource tick)

Or Transfer another Crate to arsenal, any other Item than the one you put in and it will unlock the Starter pistol in your test.
(Each time a crate is transferred it refreshed itself).
