### ISSUE TITLE
[Bug]: Static gunners can spawn with simulation disabled

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2666]
Generally the simulation-toggling code used when a marker is beyond spawn distance ignores troops in vehicles. However, both enemy mortars and other statics run NATOinit on their crew before placing them in the vehicle. The fail case looks like this:

1. Player moves within spawn distance of enemy base.
2. Within a few seconds, player moves just out of spawn distance of enemy base.
3. Marker continues spawning, but NATOinit switches the spawned units to simulation disabled.
4. Static crew are moved into statics with simulation disabled.
5. Static crew never have their simulation enabled, because they're in a vehicle.

**Comment by killerswin2** [comment]
https://github.com/official-antistasi-community/A3-Antistasi/pull/2677 closes
