### ISSUE TITLE
Rewrite fn_initSpawnPlaces

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#2667]
In the `_vehicleSpawns` section is at least one error in which `_width` and '_length' got confused - line 148.
Hence the vehicle spawning is not completely working as it should.
At least this part needs a rewrite.

**Comment by Bob-Murphy** [comment]
Code and error messages are incomprehensible as numbers are doubled and error messages are based on doubled numbers and not the real numbers in the editor.
```
    _length = (_size select 0) * 2;
    _width = (_size select 1) * 2;
```
```
if(_length < 10) then
      {
        Error_1("InitSpawnPlaces: Marker %1 is not long enough for vehicles, required are 10 meters!", _x);
      }
```

This is based on the fact that in the editor the dimensions given for `A` and `B` of a rectangle are NOT, as one would assume, the external dimensions of the rectangle.
![image](https://user-images.githubusercontent.com/50651578/225436504-d348250d-9ae8-449f-b7c6-9233f2fce34b.png)

The dimensions given for `A` and `B` of a rectangle are the distance from the middle towards the outside. Hence the outside dimensions of the marker are (2A+2B).
![image](https://user-images.githubusercontent.com/50651578/225438326-683152fe-f187-4d16-b3fb-30fc4e9d4cdb.png)

This can be confirmed by placing two markers with `A` and `B` = 1 on the map and placing them 1m apart.
If `A` and `B` would be the outside diameter, both would reach half a meter towards the other and there they should touch, but not overlap.
As this is not the case but `A` and `B` indeed are the distance from the middle towards the outer line, they overlap completely and the outside of one square reaches the middle of the other one.
![image](https://user-images.githubusercontent.com/50651578/225438152-7e3d2587-da54-4f51-958d-de02ae4f500c.png)

**Comment by Bob-Murphy** [comment]
Vehicles are spawning outside of the marker area
![ArmA 3 Screenshot 2023 03 15 - 21 13 11 21](https://user-images.githubusercontent.com/50651578/225439535-ce1b9944-a8bb-4afd-988f-25b582425dc2.png)
![ArmA 3 Screenshot 2023 03 15 - 21 13 37 34](https://user-images.githubusercontent.com/50651578/225439542-aaa750b1-71b6-4576-b9dd-dbb61cfb728f.png)
![ArmA 3 Screenshot 2023 03 15 - 21 13 48 61](https://user-images.githubusercontent.com/50651578/225439567-c8c4ec61-ab66-4480-8b04-2dafc2448b5c.png)

**Comment by killerswin2** [comment]
closed by two prs
