### ISSUE TITLE
[Bug]: When selecting new HQ position after Petros death, Synd_HQ may have incorrect position   

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2675]
placementSelection and relocateHQObjects (called by placementSelection) both set Synd_HQ for some reason. relocateHQObjects is remoteExec'd on the server so we have a network fight.

placementSelection probably shouldn't be setting anything. Also could be cleaned up to remove the new-game branches which are no longer used.

**Comment by killerswin2** [comment]
Didn't close on merge
