### ISSUE TITLE
[Change Request]: Add bombs to other aircraft for diving bombing where appropriate

### ISSUE THREAD

**Issue by killerswin2** [official-antistasi-community/A3-Antistasi#2676]
### Is the requested change related to a problem?

#2674 current only does IFA. We will need to expand it to other aircraft where appropriate.

### Describe the solution you'd like.

find aircraft that can carry unguided bombs and extend them to have bombs in the pylons.

**Comment by jaj22** [comment]
I think "where appropriate" is currently nowhere. Jets are not sensible for divebombing.

**Comment by killerswin2** [comment]
not needed
