### ISSUE TITLE
AI Autoloot Fail

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#269]
From discord, raised by Nodus Cursorius. 

Error:
 6:45:04 Error in expression <ing = _unit getVariable "rearming";
if (_rearming) exitWith {_unit groupChat "I >
 6:45:04   Error position: <_rearming) exitWith {_unit groupChat "I >
 6:45:04   Error Undefined variable in expression: _rearming
 6:45:04 File AI\autoLoot.sqf [A3A_fnc_autoLoot]..., line 9
 6:45:07 Error in expression <ing = _unit getVariable "rearming";
if (_rearming) exitWith {_unit groupChat "I >
 6:45:07   Error position: <_rearming) exitWith {_unit groupChat "I >
 6:45:07   Error Undefined variable in expression: _rearming
 6:45:07 File AI\autoLoot.sqf [A3A_fnc_autoLoot]..., line 9

https://github.com/official-antistasi-community/A3-Antistasi/blob/d9dbe27ec1561daf008e3ae4aaf5de34f650c2d7/A3-Antistasi/AI/autoLoot.sqf#L8-L9

**Comment by Bob-Murphy** [comment]
@Toakan @CalebSerafin @Spoffy 
Anybody got information about if this was worked on or how to fix this?

@Spoffy could that be part of 2.3 - AI milestone?

**Comment by Spoffy** [comment]
This is (relatively) unrelated to the AI milestone in terms of code, but could put it in regardless, given it's vaguely AI related in terms of theme.

**Comment by Spoffy** [comment]
Linking to #553

**Comment by CalebSerafin** [comment]
The requirement for AI to do looting has been subverted by loot-crates added by @HakonRydland https://github.com/official-antistasi-community/A3-Antistasi/pull/1343
