### ISSUE TITLE
[Bug]: Undercover players on foot can walk on enemy airfields

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2729]
Site-dependent undercover checks are only executed when the player is in a vehicle, so undercover players on foot can walk through roadblocks, outposts, airports and detection zones with no chance of detection.

At least this feels like a bug. Makes it ridiculously easy to steal tanks. Foot units should have the same location-based detection as ground vehicles do.

**Comment by MeltedPixel** [comment]
Merged and Fixed
