### ISSUE TITLE
[Bug]: mrkWIN can flip the wrong marker

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2732]
Ok, this has a few layers.

1. mrkWIN simply finds the nearest marker in markersX to the flag and calls markerChange on it. It's possible for the flag to be closer to an invalid marker such as a hill marker, and attempt to flip that instead.

2. The one case I know where this is possible is outpost_14 on Chernarus Summer. Probably needs a rare flag placement too.

3. It's not possible on the other two versions of Chernarus because the hill detection logic for specops positions only runs on Chernarus Summer and Altis. This raises the question of whether other maps have sufficient specops positions defined.

Point 1 can be fixed by only checking acceptable markers in mrkWIN, but point 3 needs checking.

**Comment by MeltedPixel** [comment]
Merged
