### ISSUE TITLE
Chernarus: Renovate Outposts

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#276]
I have spoken to some players on the server, and they thought that Chernarus would be better if it felt bigger by adding more outposts. I agree as by looking on the map, the outposts can be more dense inland.

We should discuss adding more outposts (Not open wheat fields with a flag pole) to Chernarus (There are hectares of Free Real estate in the north-west region). This also includes renovating the current wheat fields with flagpoles into outposts. We can do the style in default 2035 containers outposts and worry about outpost customisation as a feature for templates. (Chernrus has computers and Giant TV towers all over the place anyway.)

**Comment by Bob-Murphy** [comment]
That's easier said than done and there are three potential ways to do so.
1. We use WW2 assets from IFA. This makes it way more diverse and interesting for the ArmiaKrajowa mission BUT is creating dependencies. As an info: We have removed all the dependencies from the map so we can play it with other modsets like RHS which then wouldn't be possible.
2. We use CUP assets. This would be possible as CUP core and CUP maps needs to be enabled as Chenarus_summer needs that anyway. With this option we could decorate the map a little bit, increase the immersion and make it a little more difficult with adding manned towers and such. But to be able to have towers manned, a lil bit of coding would need to be done. This assets look old and are not integraded in the code whatsoever.
3. We use vanilla Arma 3 assets. This would make more sense when you play the mission with another modset than only IFA and the WW2 Theme. This option only would use placing the assets in the editor and it would work automatically with the scripts we already have and would be more compatible with modsets like RHS or 3CB. On the other side it wouldn't look good in IFA.

It is completely clear that we can't satisfy all and it's not easy to find the best way but we'll think about it.

I'll work on that in the future.

**Comment by Bob-Murphy** [comment]
Chernarus Winter Done

**Comment by Bob-Murphy** [comment]
Done.
