### ISSUE TITLE
[Bug]: RHS AFRF roadblock vehicle (militia light armed) is not armed

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2765]
Not sure how old this is, but RHS AFRF's militia light armed vehicle is `rhs_tigr_m_vv`, which is not armed and makes their early-game roadblocks rather too easy. Should be replaced by `rhs_tigr_sts_vv`.

**Comment by jaj22** [comment]
> the tigr_sts has an automatic grenade launcher in addition to its primary 7.62 PKM, im not sure if that would be too strong for the militia? Also concerned if it's not a bit too powerful for how easy it'd be for the player to steal it?

Not sure AIs know how to use the GL.  It's powerful in the hands of a player but also CAS bait, so probably not a huge balance issue. Rather have an armed than unarmed vehicle anyway, even if it's not perfect.

**Comment by ante185** [comment]
> > the tigr_sts has an automatic grenade launcher in addition to its primary 7.62 PKM, im not sure if that would be too strong for the militia? Also concerned if it's not a bit too powerful for how easy it'd be for the player to steal it?
> 
> Not sure AIs know how to use the GL. It's powerful in the hands of a player but also CAS bait, so probably not a huge balance issue. Rather have an armed than unarmed vehicle anyway, even if it's not perfect.

The Dshka UAZ would be an option is what im thinking

**Comment by jaj22** [comment]
> The Dshka UAZ would be an option is what im thinking

Sure, if it's suitable. Check that it has a decent fire arc, because roadblocks that can't shoot down the road are pretty daft.

**Comment by ante185** [comment]
> > The Dshka UAZ would be an option is what im thinking
> 
> Sure, if it's suitable. Check that it has a decent fire arc, because roadblocks that can't shoot down the road are pretty daft.

360* turret .50 cal, but completely unarmored- the RHS equivalent of the vanilla armed offroad

**Comment by ante185** [comment]
fixed in #2805 on jul 5th
