### ISSUE TITLE
[Bug]: Clusters of unmoving enemies

### ISSUE THREAD

**Issue by OtherBarry** [official-antistasi-community/A3-Antistasi#2774]
### Describe the bug

Frequently when attempting to take objectives, there are clusters of enemies, usually 4-8, that appear to be frozen. They don't move at all when getting shot at, unless they are killed. Sometimes they'll fire their weapons, but it'll just be into the ground as they are in a relaxed pose.

This doesn't happen to all enemies, nor on all objectives, but I'd say there's 1-3 clusters of these bugged troops on around 70% of objectives.

### How to reproduce

Load in game of antistasi, attack outposts. May require higher war level or aggression for there to be enough enemies for the bug to occur.

### Version

3.2.0

### Have you altered the code?

No

### Map

Altis

### What server?

Private dedicated server with Headless client(s)

### Time bug occured (Server time/UTC)

Multiple times

### Mods

```html
@3cb_factions
@ace
@ace_compat___rhs_afrf
@ace_compat___rhs_usaf
@ace_compat___rhs:_gref
@ace_compat___rhs:_saf
mods/@antistasi___the_mod
mods/@cba_a3
@cup_terrains___core
@cup_terrains___cwa
@cup_terrains___maps
@rhsafrf
@rhsgref
@rhssaf
@rhsusaf
```

### Additional context

Using 1 headless client.

**Comment by jaj22** [comment]
Couldn't replicate from the description, and I can't see a way it could happen in the Patcom code. If you were attacking from very long ranges (>400m) then they may remain in their safe-patrol state, but in that case they're typically moving, and they should progress to aggressive behaviour shortly after you close the distance.

Had a couple of similar (but less detailed) reports so I might be missing something, but I'm not sure what.

**Comment by jaj22** [comment]
Are you absolutely sure that you're running that same modset on both the dedicated server and the headless client?

**Comment by OtherBarry** [comment]
>If you were attacking from very long ranges (>400m) then they may remain in their safe-patrol state, but in that case they're typically moving, and they should progress to aggressive behaviour shortly after you close the distance.

This is definitely not the case - they're stationary and stay as such no matter how close you get. They do rotate around like normal AI would, but they don't move, and there's no animation for the rotation, the model just rotates on the spot.

>Are you absolutely sure that you're running that same modset on both the dedicated server and the headless client?

Below is the commands that start the servers and the headless clients (note recently switched to 4 HC instead of 1, issue still occurrs). They're running on the same machine. The only difference I see is that the headless clients don't have the advanced towing/rappelling/etc mods, as they are server mods.

It is possible that these mods are causing issues. Occasionally petros is stuck in a rappelling position, and doesn't respond to AI commands when trying to move HQ. I'm not sure if/how it relates to the main issue, but I'll do some testing without these mods enabled and see if the issue still occurs.

```
Arma server: /home/steam/arma3/arma3server "-mod=mods/@3cb_factions;mods/@ace;mods/@ace_compat___rhs_afrf;mods/@ace_compat___rhs_usaf;mods/@ace_compat___rhs:_gref;mods/@ace_compat___rhs:_saf;mods/@antistasi___the_mod;mods/@cba_a3;mods/@cup_terrains___core;mods/@cup_terrains___cwa;mods/@cup_terrains___maps;mods/@rhsafrf;mods/@rhsgref;mods/@rhssaf;mods/@rhsusaf" -noSound -world=empty -port=2302 "-serverMod=mods/@advanced_rappelling;mods/@advanced_towing;mods/@advanced_sling_loading;mods/@advanced_urban_rappelling" -filePatching -config=configs/CIRS-Antistasi
HC1: /home/steam/arma3/arma3server -connect=127.0.0.1 "-mod=mods/@3cb_factions;mods/@ace;mods/@ace_compat___rhs_afrf;mods/@ace_compat___rhs_usaf;mods/@ace_compat___rhs:_gref;mods/@ace_compat___rhs:_saf;mods/@antistasi___the_mod;mods/@cba_a3;mods/@cup_terrains___core;mods/@cup_terrains___cwa;mods/@cup_terrains___maps;mods/@rhsafrf;mods/@rhsgref;mods/@rhssaf;mods/@rhsusaf" -password=password -noSound -world=empty -port=2302 -filePatching -client
HC2: /home/steam/arma3/arma3server -connect=127.0.0.1 "-mod=mods/@3cb_factions;mods/@ace;mods/@ace_compat___rhs_afrf;mods/@ace_compat___rhs_usaf;mods/@ace_compat___rhs:_gref;mods/@ace_compat___rhs:_saf;mods/@antistasi___the_mod;mods/@cba_a3;mods/@cup_terrains___core;mods/@cup_terrains___cwa;mods/@cup_terrains___maps;mods/@rhsafrf;mods/@rhsgref;mods/@rhssaf;mods/@rhsusaf" -password=password -noSound -world=empty -port=2302 -filePatching -client
HC3: /home/steam/arma3/arma3server -connect=127.0.0.1 "-mod=mods/@3cb_factions;mods/@ace;mods/@ace_compat___rhs_afrf;mods/@ace_compat___rhs_usaf;mods/@ace_compat___rhs:_gref;mods/@ace_compat___rhs:_saf;mods/@antistasi___the_mod;mods/@cba_a3;mods/@cup_terrains___core;mods/@cup_terrains___cwa;mods/@cup_terrains___maps;mods/@rhsafrf;mods/@rhsgref;mods/@rhssaf;mods/@rhsusaf" -password=password -noSound -world=empty -port=2302 -filePatching -client
HC4: /home/steam/arma3/arma3server -connect=127.0.0.1 "-mod=mods/@3cb_factions;mods/@ace;mods/@ace_compat___rhs_afrf;mods/@ace_compat___rhs_usaf;mods/@ace_compat___rhs:_gref;mods/@ace_compat___rhs:_saf;mods/@antistasi___the_mod;mods/@cba_a3;mods/@cup_terrains___core;mods/@cup_terrains___cwa;mods/@cup_terrains___maps;mods/@rhsafrf;mods/@rhsgref;mods/@rhssaf;mods/@rhsusaf" -password=password -noSound -world=empty -port=2302 -filePatching -client
```

**Comment by jaj22** [comment]
Advanced Rappelling is known to do this when installed on the server. If you hadn't provided a modlist without it then I'd have asked specifically. Do not run Advanced Rappelling.

We should block it in the next version.

**Comment by OtherBarry** [comment]
Ah yeah missed the serverMods in that initial mod list. Thanks for the info. I'll make a PR to chuck it in the banned mods in the documentation.

Is it advanced rappelling specifically, or the whole suite? Are we still able to use towing and sling loading (or even urban rappelling)?

**Comment by killerswin2** [comment]
Towing and Sling are fine. Rappelling breaks a lot of stuff.

**Comment by jaj22** [comment]
I'm still curious about how/why, but not curious enough to read someone else's animation code.

**Comment by killerswin2** [comment]
Yeah, not really wanting to sit down and read the code for every mod that breaks. Too much work.

**Comment by OtherBarry** [comment]
Haven't had this issue appear since removing the rappelling mods, so marking as solved.
