### ISSUE TITLE
[Bug]: Artillery possible unable to fire

### ISSUE THREAD

**Issue by targetingsnake** [official-antistasi-community/A3-Antistasi#2775]
### Describe the bug

Some artillery units turrets, e.g. MLRS systems from GM don't have a 360° rotation on the turret/launcher complex

### How to reproduce

Go ingame test mlrs.

### Version

3.x

### Have you altered the code?

No

### Map

every

### What server?

LAN Hosted

**Comment by ante185** [comment]
A possible if crude solution would be rotating the artillery vehicle towards the target through script

**Comment by targetingsnake** [comment]
@ante185 i think that would be the only possible solution unless there are player units near by which can see the truck rotating

**Comment by ante185** [comment]
Suggested implementation by giddi:
```
params ["_firing_unit", "_target_unit"]

private _start_dir = getDir _firing_unit;

private _end_dir = _firing_unit getDir _target_unit;

private _increment = 30;

if {_end_dir<_start_dir} do {


    while {(_start_dir - _increment) > _end_dir} do {
        _firing_unit setDir (_start_dir - _increment);
        _start_dir = (_start_dir - _increment);
        uiSleep 0.5;

    };

} else {

    while {(_start_dir+_increment)< _end_dir} do {
        _firing_unit setDir (_start_dir + _increment);
        _start_dir = (_start_dir + _increment);
        uiSleep 0.5;
    };
};


_firing_unit setDir _end_dir;
```
