### ISSUE TITLE
[Change Request]: Duplicate vehicle entries in rebel templates

### ISSUE THREAD

**Issue by ante185** [official-antistasi-community/A3-Antistasi#2779]
### Is the requested change related to a problem?

FIA and SDK rebel templates for vanilla have duplicate entries

SDK: line 15, line 22
[https://github.com/official-antistasi-community/A3-Antistasi/blob/master/A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf](url)
`["vehiclesAT", ["I_C_Offroad_02_AT_F", "I_C_Offroad_02_AT_F"]]`
`["vehiclesCivCar", [  >"C_Offroad_01_F"<  , "C_Hatchback_01_F", "C_Hatchback_01_sport_F",   >"C_Offroad_01_F"<, "C_SUV_01_F"]]`

FIA: line 22
[https://github.com/official-antistasi-community/A3-Antistasi/blob/master/A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf](url)
`["vehiclesCivCar", [ >"C_Offroad_01_F"< , "C_Hatchback_01_F", "C_Hatchback_01_sport_F",  >"C_Offroad_01_F"< , "C_SUV_01_F"]]`

### Describe the solution you'd like.

SDK can for their AT vehicles either lose one of the entries, or have the latter be changed from the jeep to the pickup should the be desired

SDK & FIA civ cars just needs one of the C_Offroad_01_F (pickup) changed to the C_Offroad_02_F (Jeep)

**Comment by jaj22** [comment]
> SDK & FIA civ cars just needs one of the C_Offroad_01_F (pickup) changed to the C_Offroad_02_F (Jeep)

C_Offroad_02_F is DLC-limited, right? So it'd need a condition for the FIA template.
