### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#2782]
### Related problem

ZEN implemented that Zeus can edit/delete all map markers.

### Proposed feature

Add a snipped which either blacklists the Antistasi Marker or enable that only Zeus Places Markers can be edited.

Link to a ZEN PR regarding that:
https://github.com/zen-mod/ZEN/pull/736

**Comment by MeltedPixel** [comment]
It looks like the default state of the implementation is All Markers is disabled and Zeus placed markers is enabled.
