### ISSUE TITLE
[Game balance]: Reduced cost of armed rebel vehicles with lower calibre

### ISSUE THREAD

**Issue by ante185** [official-antistasi-community/A3-Antistasi#2803]
### What is wrong with the balance currently?

Currently cars armed with 5.56 and 7.62 MGs are priced across most/all templates at the same price point as the .50 cal armed vehicles.

### Describe the solution you'd like.

Default price for a car with a .50 is 700.
I propose a reduction of 100€ for 7.62 armed vehicles, such as the PK datsun and hilux from 3cb/CUP
And a reduction of 200€ for 5.56 armed vehicles like the lmg jeep from the Apex/tanoa expansion

**Comment by jaj22** [comment]
Fair enough. Ideally do some practical effectiveness tests, but the suggested changes seem safe.
