### ISSUE TITLE
[Bug]: Overcrowded sandbag bunkers

### ISSUE THREAD

**Issue by ante185** [official-antistasi-community/A3-Antistasi#2810]
### Describe the bug

At outpost
![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/49555217/f91d63ec-6693-4324-b26e-47215ecda01e)

Overcrowded bunker - garrisoned infantry and HMG get in eachother's way
Expectation: either the bunker is garrisoned, or there is a HMG - never both

### How to reproduce

Visit enough outposts with sandbag bunkers and it will happen eventually 

### Version

3.2.0

### Have you altered the code?

No

### Map

Any

### What server?

LAN Hosted

### Mods

Vanilla

**Comment by MeltedPixel** [comment]
Ill take a look at this, I probably just need to add some filtering.
