### ISSUE TITLE
Custom classname for multiple vehicles

### ISSUE THREAD

**Issue by SirChickenKCMG** [official-antistasi-community/A3-Antistasi#2815]
### Is the requested change related to a problem?

I need somebody to create a custom classname in the config_fixes pbo which applied the textures to a stated vehicle classname and hence creates a new vehicle when RHS is loaded.

### Describe the solution you'd like.

Please for the following vehicles: 

RHS_Mi8mt_vdv

author = "Red Hammer Studios";
displayName = "Camo #2";
factions[] = {};
textures[] = {"rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_body_g_camo2_co.paa","rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_det_g_camo2_co.paa"};

RHS_Mi8MTV3_vdv

author = "Red Hammer Studios";
displayName = "Camo #2";
factions[] = {};
textures[] = {"rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_body_g_camo2_co.paa","rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_det_g_camo2_co.paa"};

RHS_Mi8MTV3_heavy_vdv

author = "Red Hammer Studios";
displayName = "Camo #2";
factions[] = {};
textures[] = {"rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_body_g_camo2_co.paa","rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_det_g_camo2_co.paa"};

RHS_Mi8mtv3_Cargo_vdv

author = "Red Hammer Studios";
displayName = "Camo #2";
factions[] = {};
textures[] = {"rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_body_g_camo2_co.paa","rhsafrf\addons\rhs_a2port_air\mi17\data\camo\mi8_det_g_camo2_co.paa"};

### Additional context

This is for the helicopters in the RHS PPLF faction. Please swap them out with the new custom ones when done

**Comment by targetingsnake** [comment]
related PR: #2814

**Comment by Bob-Murphy** [comment]
@Tiny-DM please check

**Comment by Tiny-DM** [comment]
#2814 never got integrated or merged anywhere, and from what I can see all vehicles are behaving as they are supposed to; the classnames already spawn in with the listed camos. Not sure if there's a mistake here, or if you're asking for a different camo to be applied than the listed one, but going to close for now as #2814 is dead. Feel free to reopen if necessary.
