### ISSUE TITLE
Avoid 'side petros' Checks

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#282]
The gamemode has a real dependency on Petros being alive, but situations keep cropping up where he's dead, even temporarily. 

The main issue it's causing is players that join can't access the arsenal, or get the wrong loadout, or the wrong spawn, as well as other things.

To start - remove 'side petros' from all the init code (initPlayerLocal and initServer)

**Comment by wurzel0701** [comment]
The `faction` command returns the faction, regardless of the state (destroyed etc.)

Maybe this can be used to replace `side`

**Comment by Spoffy** [comment]
The issue is Petros not existing, rather than the 'side' command. Also, faction can return many values for a given side.

**Comment by Bob-Murphy** [comment]
@Spoffy 
Update?

**Comment by Spoffy** [comment]
Partially resolved. Needs more work.

**Comment by Mirv** [comment]
Is this still in the works?  Link partial if you can?  I'm trying to dive a few issues a day for if I do chase the db project so catching up to your work goes faster.

**Comment by tpaclatee** [comment]
> 
> 
> Is this still in the works? Link partial if you can? I'm trying to dive a few issues a day for if I do chase the db project so catching up to your work goes faster.

I tried the suggested fix of removing the (side) casting from all petros calls but could not resolve further

**Comment by Mirv** [comment]
> > Is this still in the works? Link partial if you can? I'm trying to dive a few issues a day for if I do chase the db project so catching up to your work goes faster.
> 
> I tried the suggested fix of removing the (side) casting from all petros calls but could not resolve further

By resolve no further, you go into game, kill petros and then try to do the outlined tasks - they can't be completed?

Have you chased files besides the init's?

**Comment by tpaclatee** [comment]
I have searched for other references to Petros that would affect this, but I probably missed something. I just can't seem to find what is checking on his status and needs to be changed

**Comment by Mirv** [comment]
I need some sleep, but how many of the 90 petros mentions did you check?  (just gathering info here)

https://github.com/official-antistasi-community/A3-Antistasi/search?q=petros&unscoped_q=petros

**Comment by CalebSerafin** [comment]
Checks that use side Petros:

* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/9d0b2f4e967cbba2e03a44904e12ceba7b752bb5/A3-Antistasi/functions/Save/fn_saveLoop.sqf#L26
* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/9d0b2f4e967cbba2e03a44904e12ceba7b752bb5/A3-Antistasi/functions/init/fn_initServer.sqf#L91

Checks that use side (group Petros):

* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/872f16d9548bceff2f1eabaf59ff8e85cca56da3/A3-Antistasi/functions/Ammunition/fn_itemSort.sqf#L1
* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/872f16d9548bceff2f1eabaf59ff8e85cca56da3/A3-Antistasi/functions/Ammunition/fn_itemSort.sqf#L7

* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/ee9d3977c7ef40240f2e92fe97b95ca4bc7632a2/A3-Antistasi/functions/Base/fn_buildHQ.sqf#L3
* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/ee9d3977c7ef40240f2e92fe97b95ca4bc7632a2/A3-Antistasi/functions/Base/fn_buildHQ.sqf#L17

* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/26d88d5ff59fb7c521cf7c85b1af9100ee76e40d/A3-Antistasi/functions/Base/fn_flagaction.sqf#L29
* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/26d88d5ff59fb7c521cf7c85b1af9100ee76e40d/A3-Antistasi/functions/Base/fn_flagaction.sqf#L30

* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/ee9d3977c7ef40240f2e92fe97b95ca4bc7632a2/A3-Antistasi/functions/Base/fn_moveHQ.sqf#L10


* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/d2a42e4b4ee9c9412eb5ac4756e81dc349d52b55/A3-Antistasi/functions/Base/fn_onPlayerDisconnect.sqf#L23

* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/b893769f95ac458296b368c7ee436efb860add5a/A3-Antistasi/functions/init/fn_initClient.sqf#L84
* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/b893769f95ac458296b368c7ee436efb860add5a/A3-Antistasi/functions/init/fn_initClient.sqf#L486
* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/b893769f95ac458296b368c7ee436efb860add5a/A3-Antistasi/functions/init/fn_initClient.sqf#L487

* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/ff9de1b9a1565634a0ad338e0de0054873f71899/A3-Antistasi/functions/init/fn_initVarCommon.sqf#L22

* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/12041930bebbb56fedcf0d219e2d828779c686cb/A3-Antistasi/functions/Missions/fn_missionRequestAUTO.sqf#L3

* [ ] https://github.com/official-antistasi-community/A3-Antistasi/blob/b5d8921d7598c7e88336b89bc6517275e88ceb37/A3-Antistasi/functions/Save/fn_varNameToSaveName.sqf#L7

**Comment by tpaclatee** [comment]
I believe group petros should work

**Comment by CalebSerafin** [comment]
The only side Petros check that should exist is the one that defines 
`teamPlayer = side group petros;` in initVarCommon. As that is defined other function should use that as groups can become unreliable as the game progresses, or if the commander moves HQ and other group joining interactions. In terms of performance would be better if functions use a predetermined variable rather than checking side of a group.

**Comment by tpaclatee** [comment]
so, `side group petros` becomes `teamPlayer`? So would ` if (teamPlayer == west) then { ` be correct, and should I change all checks to that?

**Comment by CalebSerafin** [comment]
Yes. If along the way of replacing them you discover that teamPlayer is undefined or incorrect: that would be an issue with it(I say that as the code base has a history of fantastic surprises)

**Comment by tpaclatee** [comment]
ok all `side petros` and `side group petros` are now `teamPlayer`

**Comment by Mirv** [comment]
@CalebSerafin - wow that's quiet a bit of work there - ty! - can I ask how you determined that for future code diving?

**Comment by CalebSerafin** [comment]
@Mirv I use Visual Studio Code with `SQF Language`; `SQF Lint`; `SQF Wiki`; `Arma 3 - Open Last RPT`; extensions. Lint&Language provide the feature of finding the definitions and references of code symbols. However `petros` is defined in the mission, so I search for `side petros`, `side group petros` and  `side (group petros)`. There is a possibility of a Petros reference hiding somewhere, but that chance is low.
