### ISSUE TITLE
[Bug]: Repair station gone after save

### ISSUE THREAD

**Issue by Lord-Leonard** [official-antistasi-community/A3-Antistasi#2831]
### Describe the bug

I placed a repair station and after saving and loading it was gone.
I expected the repair station to still be there.

### How to reproduce

1. Buy a repair station 
2. Place repair station 
3. Safe the game
4. Load the game

### Version

3.2.0

### Have you altered the code?

No

### Map

Tanoa

### What server?

Private dedicated server

**Comment by jaj22** [comment]
Already fixed for next version.

**Comment by Lord-Leonard** [comment]
when will it arrive?

**Comment by Bob-Murphy** [comment]
Somewhat soon. We are currently testing the release candidate on our servers.
