### ISSUE TITLE
Civilian Vehicles in Mod Templates

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#284]
Civilian vehicles were set in rebel templates, and I have relocated them to initVar along with the rest of the civilian things. Later I will consider a civilian template split but for now there are other issues.

When we use RHS we add a list of urals to the existing vanilla vehicles and thats it.
- are there not other RHS vehicles that could be added?
- is it OK to just add RHS vehicles to vanilla or should we be replacing them instead?

When we use 3CB we replace civilian vehicles completely, because 3CB has a lot of them.

We dont replace Vanilla boats ever, except in IFA when we remove them all completely.

**Comment by PoweredByPot** [comment]
dealt with in loot crates part 2

**Comment by Bob-Murphy** [comment]
@PoweredByPot 
Update/Milestone?

**Comment by PoweredByPot** [comment]
closing, dealt with and needs balancing
