### ISSUE TITLE
[Bug]: Helicopters parked near the Headquarters flagpole no longer saved

### ISSUE THREAD

**Issue by jkaryan** [official-antistasi-community/A3-Antistasi#2867]
### Describe the bug

When capturing a helicopter and landing it near the Headquarters flagpole, they don't get saved when doing a persistent save. They used to be saved in 3.2.0, I've had up to 4 helicopters around my headquarters at one time.

### How to reproduce

-Capture an enemy helicopter
-Fly and land it near your Headquarters flagpole
-Do a persistent save
-Exit the game
-Load the save
-Observe that the helicopter is missing

### Version

3.3.1

### Have you altered the code?

No

### Map

Vironlahti

### What server?

LAN hosted

### Time bug occured (Server time/UTC)

01:00 UTC

### Mods

```html
3CB Factions	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1673456286
ace	Steam	https://steamcommunity.com/sharedfiles/filedetails/?id=463939057
ACE Compat - RHS AFRF	Steam	https://steamcommunity.com/sharedfiles/filedetails/?id=773131200
ACE Compat - RHS USAF	Steam	https://steamcommunity.com/sharedfiles/filedetails/?id=773125288
ACE Compat - RHS: GREF	Steam	https://steamcommunity.com/sharedfiles/filedetails/?id=884966711
ACE Compat - RHS: SAF	Steam	https://steamcommunity.com/sharedfiles/filedetails/?id=2174495332
Antistasi - The Mod	Steam	https://steamcommunity.com/sharedfiles/filedetails/?id=2867537125
CBA_A3	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
CUP Terrains - Core	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=583496184
Enhanced Movement	Steam	https://steamcommunity.com/sharedfiles/filedetails/?id=333310405
Enhanced Movement Rework	Steam	https://steamcommunity.com/sharedfiles/filedetails/?id=2034363662
RHSAFRF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843425103
RHSGREF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843593391
RHSSAF	Steam	https://steamcommunity.com/sharedfiles/filedetails/?id=843632231
RHSUSAF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843577117
Virolahti - Valtatie 7	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1926513010
```

### Additional context

None.

**Comment by rautamiekka** [comment]
Don't call it a Dedicated if it ain't a Dedicated, then.

**Comment by jaj22** [comment]
Huh, not really sure how that one got through a week of community testing. The perils of non-private variables, I guess: You can have a pretty bad typo bug and it works based on something that happened earlier in the code.

It's not just helis, although they're the problem case because you can't garage them. No vehicles will save consistently.

**Comment by jkaryan** [comment]
> Don't call it a Dedicated if it ain't a Dedicated, then.

In my defense there's no option for that kind of server in the dropdown list, and space to type it in, other than additional context. The list has just LAN, dedicated server, headless dedicated server, the community servers and the community test servers...

**Comment by killerswin2** [comment]
Those are called self-hosting, but in reality you are making a LAN connection with yourself

**Comment by jkaryan** [comment]
> Those are called self-hosting, but in reality you are making a LAN connection with yourself

Learned something new, thanks!
