### ISSUE TITLE
[Research / Evaluation] Which spawn function places AI in buildings and which, if any, blacklist for buildings are they using?

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#2869]
We have a multitude of different spawn functions within Antistasi and they seem to be using different or maybe no blacklists.
Some functions use `A3A_buildingBlacklist`, PATCOM is using `PATCOM_Building_Blacklist` which is build on the first.
But even though two SPE bocages who have buildingPos are added to `A3A_buildingBlacklist`, there still are reports from AI spawning in it. These two bocages being the following:
- Land_SPE_bocage_long_mound
- Land_SPE_bocage_short_mound

With the new PATCOM system we also should not be in the situation anymore where the AI just spawns in and then never moves.
Hence getting the info and overhauling all blacklists could very much improve the variety of where AI spawn whilst creating one or multiple different backlists for different purposes.

**Comment by jaj22** [comment]
Also found these two with four building positions each:

"Land_SPE_bocage_short_mound_lc"
"Land_SPE_bocage_long_mound_lc"

**Comment by jaj22** [comment]
Ok, went through all the bocage mounds and it's just those four with building positions. The "tree" mounds don't have any.
