### ISSUE TITLE
Do something about headless client logic positions

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2875]
Apparently some AI responses to fire only trigger when the shot is within a limited distance of the headless client logic object, leading to AIs acting especially oddly in some cases. This could be mitigated by moving the HC logic objects near the HQ when it's moved, and possibly by forcing garrisons beyond that distance to spawn on the server.

Could do with some testing to check if this is necessary, although the HC logic move is a simple change.

**Comment by rautamiekka** [comment]
Could the HC logic objects follow the HQ with something as simple as `hcLogic attachTo [hq]` ?

**Comment by jaj22** [comment]
The HQ's a marker rather than an object but in theory they could attach to an HQ object. Probably safer to just move them with the HQ though.

**Comment by rautamiekka** [comment]
Fair enough. Shame the game ain't smart enough to just `getPosATL hqMarker` for transparency.

**Comment by MildlyInterested** [comment]
Some background info from TCVM:
It seems like AI on HCs are not aware of rounds hitting close by if the HC module they are on is more than ~8.5 km away from the battle.
https://www.youtube.com/watch?v=DtEUMCbNeaE
https://www.youtube.com/watch?v=CAP1BXOdj0Y
Relevant ticket (reports critical distance ~5 km)
https://feedback.bistudio.com/T162941

Code snippet that got posted back then to move HCs to the average player position:
https://github.com/BourbonWarfare/POTATO/blob/master/addons/miscFixes/XEH_serverPostInit.sqf#L13-L73
