### ISSUE TITLE
[Feature Request]: Make flags great again.

### ISSUE THREAD

**Issue by MeltedPixel** [official-antistasi-community/A3-Antistasi#2878]
### Related problem

Recently we've had to disable flags/ remove units with flags because they stay around after a unit is destroyed.

### Proposed feature

Utilize the flag feature for players to attach nations flag to acceptable vehicles.

Editor code example:
`_this forceFlagTexture "\A3\Data_F\Flags\Flag_red_CO.paa";`

Script code will have to be different.

**Comment by MeltedPixel** [comment]
#2871

**Comment by Lazejun** [comment]
This is heavily advised against and wasn't added to the Garage previously for performance reasons

**Comment by rautamiekka** [comment]
Yeah, would be good to read the wiki for [`forceFlagTexture`](https://community.bistudio.com/wiki/forceFlagTexture):

`Forced flag texture is an additional flag texture, which visually overrides original flag texture and therefore is very expensive to simulate, so use the functionality sparingly.`

**Comment by MeltedPixel** [comment]
I'm cool with that, had a few people message me over the last couple weeks asking about it. So I figured I would toss it up for them.

**Comment by MeltedPixel** [comment]
Closing issue, Please reference this if further inquires are made about adding flags to vehicles.
