### ISSUE TITLE
[Bug]: SPE normandy, Too many Air drops

### ISSUE THREAD

**Issue by killerswin2** [official-antistasi-community/A3-Antistasi#2879]
### Describe the bug

Center of Map in Normandy, vehicle placements aren't potential correct. Resource_2 is the generally location.

### How to reproduce

Center of map

### Version

3.3

### Have you altered the code?

No

### Map

Normandy

### What server?

Community Server 2

**Comment by killerswin2** [comment]
Resource_2

**Comment by jaj22** [comment]
resource_2 is quite thin on outposts within road distance but it's still several with low-air. Couldn't replicate any issues locally but I guess we'll keep an eye on it. Could just be a coincidence and all the outposts were either flipped to the other faction, depleted or under attack.

**Comment by killerswin2** [comment]
I may have been drunk
