### ISSUE TITLE
Version 3.3.2 - 27th July 2023 does not contain the mod

### ISSUE THREAD

**Issue by zwang20** [official-antistasi-community/A3-Antistasi#2888]
### Is the requested change related to a problem?

The release [3.3.2](https://github.com/official-antistasi-community/A3-Antistasi/releases/tag/3.3.2) does not contain a mod download, such as the one found in [3.3.1](https://github.com/official-antistasi-community/A3-Antistasi/releases/tag/3.3.1).

### Describe the solution you'd like.

Add a zip file of the mod release.

**Comment by Bob-Murphy** [comment]
done
