### ISSUE TITLE
[RFC]: Config fixes load order method 

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2892]
The current CfgPatches for config_fixes looks like this:
```
class CfgPatches {
    class ADDON {
        // stuff
        #if __has_include("\CUP\Weapons\CUP_Weapons_DynamicLoadout\mk82\CUP_mk82_pod.p3d")
        requiredAddons[] = {"A3_Weapons_F", "CUP_Weapons_DynamicLoadout"};
        #else
        requiredAddons[] = {"A3_Weapons_F"};
        #endif
        // more stuff
    };
};
```
I don't think this can be generalized easily, because `#if` can't be nested in Arma and also it'd blow up violently once we had more than a handful of potential dependencies.

The best single-file method I've come up with looks like this:
```
#if __has_include("\CUP\Vehicles\CUP_Vehicles_LoadOrder\config.bin")
#define DEPEND_CUP ,"CUP_Vehicles_LoadOrder"
#else
#define DEPEND_CUP
#endif

#if __has_include("\rhsgref\addons\rhsgref_main\config.bin")
#define DEPEND_GREF ,"rhsgref_main_loadorder"
#else
#define DEPEND_GREF
#endif

class CfgPatches {
    class ADDON {
        // stuff
        requiredAddons[] = {"A3_Data_F_AoW_Loadorder" DEPEND_CUP DEPEND_GREF};
        // more stuff
    };
};
```
This works but because you'd still need __has_includes all over the rest of the config, which seems messy. My preferred method so far is to create a subfolder in config_fixes for each mod dependency, and then have a config.cpp in each that looks like this:
```
#if __has_include("\rhsgref\addons\rhsgref_main\config.bin")

class CfgPatches
{
    class ADDON {
        // stuff
        requiredAddons[] = {"rhsgref_main_loadorder"};
        // more stuff
    };
};

// These are now RHS-specific config
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"

#endif		// __has_include
```
Any config files included here can now be clean (no conditional includes), as that's already handled. RHS stuff goes in RHS folder, CUP stuff goes in CUP folder and so on. Any objections?

**Comment by jaj22** [comment]
Forgot that I need a different name in CfgPatches for each of these, so something like this in config_fixes script_component:
```
#define PATCHNAME(x) ADDON##_##x
```
and then `class PATCHNAME(RHS)`

**Comment by killerswin2** [comment]
#if can be nested???

**Comment by killerswin2** [comment]
oh.... wait, that's one of the dumb commands

**Comment by jaj22** [comment]
Actually maybe it's just #ifdef that can't be nested. Still a bad idea though. Consider what it looks like when you have just three different modsets that need config fixes applied.

**Comment by killerswin2** [comment]
there is a new config entry coming in 2.14 or 16 that handles this problem

**Comment by jaj22** [comment]
> there is a new config entry coming in 2.14 or 16 that handles this problem

It's a straight-up replacement for my second method though, not the first one. Basically just replaces the #if __has_include wrapper on each file. I don't think it works at all for the single-file methods.

**Comment by jaj22** [comment]
Completed in #2885
