### ISSUE TITLE
Medic and Squad Leader Identification sucks

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#292]
We currently use an array that simply selects the first unit from every squad and says "this is squad leader", and we do the same selecting the last unit in a squad and say "this is medic".

The result is that templates MUST follow this format or garrisonRe-org gets all fucked up. This could be done an infinite number of better ways, but we can fix this later.

**Comment by PoweredByPot** [comment]
Waiting for #289 to be complete

**Comment by Bob-Murphy** [comment]
@PoweredByPot 
Update/Milestone?

**Comment by PoweredByPot** [comment]
@SonorousMeerkat did you plan on dealing with this in templates changes, or did you want me to fix it real quick-like?

**Comment by Bob-Murphy** [comment]
@SonorousMeerkat @Spoffy 
do we still need that as a separate issue as the whole system is getting overhauled?

**Comment by Spoffy** [comment]
Leave open, added to templates project, needs to be kept in mind

**Comment by killerswin2** [comment]
This is no long relevant do to new template system and complieMissionAssets. If issue is persistence reopen.
