### ISSUE TITLE
[Bug]: `JeroenArsenal\JNG\recompile.sqf` does not exist

### ISSUE THREAD

**Issue by LordGolias** [official-antistasi-community/A3-Antistasi#2924]
### Describe the bug

Not sure how this shows itself ingame, but the line `call compile preProcessFileLineNumbers "JeroenArsenal\JNG\recompile.sqf";`
in file `A3A/addons/jeroen_arsenal/JNG/fn_garage_requestOpen.sqf` points to a non-existent file (`JeroenArsenal` vs `jeroen_arsenal`).

### How to reproduce

Not sure

### Version

unstable

### Have you altered the code?

No

### Map

Any

### What server?

LAN Hosted

**Comment by killerswin2** [comment]
We don't use JNG anymore. That is the old garage.
