### ISSUE TITLE
Ace throwing not breaking undercover

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#2957]
There've been reports of throwing grenades with ACE not breaking undercover and people abusing it.
Should be looked into and fixed.

**Comment by jaj22** [comment]
Should already be fixed for 3.4:
https://github.com/official-antistasi-community/A3-Antistasi/pull/2842

Feel free to test with unstable.

**Comment by Bob-Murphy** [comment]
fixed
