### ISSUE TITLE
[Change Request]: Add new ACE medical Item to starting rebel equipment

### ISSUE THREAD

**Issue by Vlash271** [official-antistasi-community/A3-Antistasi#2980]
### Is the requested change related to a problem?

New medical Item added by ACE will not appear in the starting Arsenal.

Medical - `ACE_suture`

### Describe the solution you'd like.

Add the item `ACE_suture` to the starting rebel equipment.

**Comment by jaj22** [comment]
What does this do?

**Comment by Bob-Murphy** [comment]
Basically needle and thread which can be set tu be used on stitching a wound based on the settings.
Perfectly fine to add it.
![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/50651578/fff63017-cc44-4802-a3eb-8d06b464ad4d)

**Comment by jaj22** [comment]
In retrospect this is a dumb waste of network traffic and we shouldn't encourage it :P
