### ISSUE TITLE
[ACE "feature"]: Need to rewrite every case that checks the engineer unit trait

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2985]
Apparently ACE now strips the engineer unit trait on client init, and it didn't before. This means that any Antistasi code that uses the engineer unit trait will now break:
1. Default commander slot can now vanilla-repair vehicles (fixed).
2. Neither the new or old construction stuff will work.
3. Intel disarm will not work.
4. Arsenal default loadout code will not work correctly for engineers. Not sure if used.
5. AIs are probably now incapable of repairing vehicles with ACE, so there's no point in buying engineers. Untested.

**Comment by killerswin2** [comment]
`fnc_isEngineer = {
    params ["_unit"];
    _unit getVariable ["ACE_IsEngineer", _unit getUnitTrait "engineer"]
};`

**Comment by jaj22** [comment]
ACE code seems quite confused about whether ace_isEngineer is supposed to be a bool or number (0-2) now, so I went for the nil check instead.

**Comment by killerswin2** [comment]
kk, is this is a pr already?

**Comment by killerswin2** [comment]
Also, make a mention for veteran29 if you make that a function. He wrote it.

**Comment by jaj22** [comment]
Yeah I dumped it all into #2978 because that already had the default commander engineer trait fix.

**Comment by killerswin2** [comment]
seems like they use a number, for training level

**Comment by jaj22** [comment]
The current code sets true if the unit trait is engineer, but it is apparently valid to put a number there too. Hence the solution in #2978,

**Comment by jaj22** [comment]
Done I think. At least no-one reported any further issues for a few days.
