### ISSUE TITLE
Leftover AI In Vehicle prevent claiming or despawning.

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#299]
Seems there is an issue with the "surrender" for Vehicle crews which stops them from disembarking or changing seats when the majority of their squad is destroyed.

From Discord: CF_MAG
```
- we've had a few instances where an APC or Tank basically became invulnerable with 1 guy in there that wouldn't die.
- it'll be completely disabled, but not able to destroy it or get the guy out
```

**Comment by wurzel0701** [comment]
My PR #58 solves exactly this problem. Making it a feature :D

So if anyone solve this, the PR needs a review

**Comment by wurzel0701** [comment]
PR updates, now compatible with mods, needs only a review and testing
