### ISSUE TITLE
[Bug]: setIdentityLocal is using hasACE on JIP

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#2995]
setIdentityLocal is using the hasACE var, but it's a JIP function so that often won't exist at the point of execution.

Could fix by using the original ACE CfgPatches lookup, but I'm going to check why the hell ACE needs another name parameter first. Effects are non-critical.

**Comment by killerswin2** [comment]
That was introduced in #2804

**Comment by jaj22** [comment]
Looks like all ACE stuff uses the `ace_common_fnc_getName` accessor to get the name, and that has no fallbacks. ACE itself sets this as an initPost XEH. Not sure how that interacts with JIP timing.

However, this doesn't matter because ACE setName sets global vars on the unit (ACE_name and ACE_name_raw). Therefore we don't need to put it in setIdentityLocal at all: It can just be set in setIdentity as a one-off. ACE won't reset it on non-local units so that shouldn't be problematic. Units that exist pre-JIP are clearly non-local.
