### ISSUE TITLE
[Bug]: Building placer UI doesn't work too well on anything except 1080p

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#3005]
The building placer is offsetting everything from the screen center rather than the screen edges, making assumptions about both the screen aspect and the size of the pixel grid. Turns out even 4K (3840x2160) is fairly busted because Arma rounds pixelGridNoUIScale to 4-pixel boundaries, so you end up with 16 on 1080p and 36 on 4K.

No screenshots provided because github is fucking garbage.

**Comment by LordBallsVein** [comment]
<img width="960" alt="ArmA_3_Screenshot_2023 10 27_-_12 28 36 39" src="https://github.com/official-antistasi-community/A3-Antistasi/assets/113407058/0d7f48df-90b3-44b1-a702-f3fb3daedf64">

1080p

<img width="1280" alt="ArmA_3_Screenshot_2023 10 27_-_12 29 06 79" src="https://github.com/official-antistasi-community/A3-Antistasi/assets/113407058/48fea513-648e-4ff4-b6a1-4428f31f30ed">
1440p

4k image too large but similar to the 4k one.
