### ISSUE TITLE
[Bug]: AutoGC doesn't work in 3.4.0 BETA

### ISSUE THREAD

**Issue by Tiny-DM** [official-antistasi-community/A3-Antistasi#3017]
### Describe the bug

The automatic garbage clean, which should normally trigger every 2 hours, is broken in the beta and does not automatically garbage clean at all. For example, Server 1 just got its first GC since the server started, meaning 20 hours had passed between the GCs, which has severely impacted the server performance. This bug appears to have developed with a change fairly recently, as the automatic GC and final warning messages were definitely working when the beta began being tested.
![20231029152713_1](https://github.com/official-antistasi-community/A3-Antistasi/assets/148804148/bd6b4b59-44f0-4719-a2d2-806e3cfc596d)

### How to reproduce

Start an Antistasi server, let time pass (longer than the configured AutoGC interval) and watch as nothing happens. Manually GCing at this point will show a gap between GCs longer than the interval.

### Version

3.4.0

### Have you altered the code?

No

### What i have changed

```markdown
n/A
```

### Map

Altis

### What server?

Community Test Server

### Time bug occured (Server time/UTC)

6:45 AM ish server time

### Mods

```html
Not relevant, look at the command line for CUP if you need a reference.
```

**Comment by jaj22** [comment]
Auto GC is disabled on test server 1. It's disabled by default because it's generally not something smaller servers want or need.

Should probably implement that default parameters external config.
