### ISSUE TITLE
Players can duplicate static weapons

### ISSUE THREAD

**Issue by Auroraah** [official-antistasi-community/A3-Antistasi#302]
Version 2.1.2 Altis BLUFOR, MP LAN

It is possible to duplicate static weapons.

**Process (Example with Mortar):**

- Add both the mortar tube and bipod backpacks to a vehicle
- Open the vehicle inventory, right click the tube into your inventory
- Right click the bipod into your inventory so it swaps with the tube (Important! If you take the tube backpack off and then add the bipod it doesn't work)
- Stand next to the vehicle and you get an Assemble Mortar scroll option
- After assembling the mortar, the mortar tube backpack will still be in the vehicle inventory

Video Example: https://www.youtube.com/watch?v=yAbpLiJDS5Y

**Comment by CalebSerafin** [comment]
Tested and confirmed outside Antistasi with RHS and Vanilla.
This is an issue with base Arma 3.
I'll check if it is in the Bug Tracker
Will close as Antistasi is not the cause.

**Comment by CalebSerafin** [comment]
Oh my god, you can abuse this to create an auto turret with the vanilla morter backpacks. Great.
