### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jolle808** [official-antistasi-community/A3-Antistasi#3036]
### Describe the bug

My friend can't open the arsenal and when he spawns in he does not spawn at HQ but at random locations in the middle of the map.

### How to reproduce

Don't know.

### Version

3.4.0

### Have you altered the code?

No

### What i have changed

```markdown
Nothing
```

### Map

Altis

### What server?

Private dedicated server

**Comment by jaj22** [comment]
That means he's not loading the mod. Everyone needs to be loading the Antistasi mod:
https://official-antistasi-community.github.io/A3-Antistasi-Docs/beginners_guide/raw_beginners_guide.html#how-to-set-up-a-game
