### ISSUE TITLE
[Bug]: More garbage in the garage

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#3040]
"rhs_rhino_trigger" needs adding to the garage blacklist, wherever that is. It's some sort of anti-mine object that attaches to the front of some RHS IFVs.

**Comment by Tiny-DM** [comment]
To reproduce: 
Spawn a vehicle with the Rhino attachment from RHS. A lot of vehicles use this, but the M1245 (CROWS/M2) was used to reproduce. Use the action "Lower Rhino" on the vehicle, which will attach an invisible Rhino trigger. Should be fixed soon.
