### ISSUE TITLE
Create marker for vehicle spawn in outposts - Bob of the Day

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#305]
We have the problem that the vehicle (which automatically spawns as part of for example an outpost) likes to spawn in placed objects and then blows up happily.
Please create a marker that once placed automatically places the vehicle which is part of the automatic spawn exactly on that position.
If there is no special-car-marker within the (for example) outpost-marker the vehicle still should spawn randomly.

Random spawn
![image](https://user-images.githubusercontent.com/50651578/64925483-5edad280-d7f1-11e9-9b59-cda680752987.png)

Vehicle gets placed on marker and not randomly
![image](https://user-images.githubusercontent.com/50651578/64925493-8c278080-d7f1-11e9-9138-fe9844e6f463.png)

**Comment by wurzel0701** [comment]
On it, will take some time

**Comment by wurzel0701** [comment]
Done in #289, needs testing and merging
