### ISSUE TITLE
[Change Request]: The big book of WW2 Issues

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#306]
This post will serve as the holder of the required fixes for WW2 to be reasonably playable.
The points raised here will vary from minor to major gameplay changes.
1) General difficulty. - As generic as this sounds, WW2 is just easy because the AI can't seem to handle bolt actions that well.
2) Paradrops should only be used for Attacks, not QRF. - Paradrops were not a go-to tactic, they required a huge amount of planning well in advance. 
3) Air asset use/AI could do with a tweak. - Stuka bombing raids are fair game, but they shouldn't loiter too long after they drop their ordanance. Especially with how poor the friendly AA is.
4) Armour, there really should be more of it. - I'm going to see if any have external passengers (ala BMP) to get armour into the apc slot. if not then multitank could do with finishing.

**Comment by MeltedPixel** [comment]
Can be closed, as per bob.
