### ISSUE TITLE
FF parameter adjustment

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#3060]
Could you please switch up the FF functionality a bit?
Currently `tkPunish` enables/disables the tracking as well as the punishment which I believe could be improved.

Please apply the following changes in the params:
New - `tkTracking` - enables/disables the tracking and the pop-ups - enabled by default
Existant - `tkPunish` - enables/disables only the punishment being applied - disabled by default

**Comment by jaj22** [comment]
Why? What's the use case?

**Comment by Bob-Murphy** [comment]
Exemplary usecase:
Small community, open server but not much changing in players.
They sometimes fuck around, shoot each other at HQ, hence they don't want the punishment to trigger and send people to the turtles.
Nevertheless, they still want to be able to track what happened in case somebody is being a dick on purpose, hence the tracking and the pop-ups can be useful.

**Comment by Bob-Murphy** [comment]
As an alternative, have it always log into the RPT and have the param enable/disable hints and punishment.
Hence the info is still tracked and no additional param.

**Comment by jaj22** [comment]
Nah, punishment is quite expensive to run at the moment (every time a rebel unit is hit by anything, it sends a heavy remoteExec to the server) so there needs to be a way to disable it entirely.

Another option would be to expand the parameter to three options (disabled, notify only, punishment), but that would require #3042 to be merged first.

**Comment by Bob-Murphy** [comment]
I'd be perfectly happy with that solution.
