### ISSUE TITLE
Destroy Heli Mission - Invalid Outcome

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#307]
```There is an open case to handle, the truck loads the helicopter and drives back, what if I steal it on the way back and bring it the HQ and garage it there. I should have won the mission in this case, but the real outcome would be a mission failed I guess```

See PR #270

**Comment by Bob-Murphy** [comment]
@Spoffy @PoweredByPot 
Update/Milestone?

**Comment by PoweredByPot** [comment]
closed, Wurzel fixed this
