### ISSUE TITLE
[bug] Indestructible enemy vehicles

### ISSUE THREAD

**Issue by AlexTriada** [official-antistasi-community/A3-Antistasi#310]
### Version of the mission:
- [x] 2.1.2
- [x] unstable branch
### Mods: 
- [x] CBA 
- [x] TFR   
- [ ] ACE (no medical)   
- [x] ACE   
- [x] RHS  
- [ ] others:
### Environment: 
- [ ] SP     
- [ ] MP host server     
- [x] MP dedicated server
### .rpt file attatched? 
- [ ] YES        
- [x] NO
### Do you edite the missionfile?
- [ ] YES
- [x] NO
## Issue:
Enemy vehicles such tanks, APCs and other vehicle, MRAPs, Helicopters are undestructible - (bug with blinking vehicle) teleporting from one place to another (not the distance lag) we can destructing it, but need many ammo for that (it's not normal 20 RPG to APC)

**Comment by CalebSerafin** [comment]
Could you test this with vanilla vehicles? RHS has a more detailed damage layout, so unless you know where to hit some vehicles they will not cook off.

**Comment by AlexTriada** [comment]
> Could you test this with vanilla vehicles? RHS has a more detailed damage layout, so unless you know where to hit some vehicles they will not cook off.

dude, i know how must working damage RHS vehicles, as i say this is the bug with indestructible vehicles, are you hear about that bug first time?

**Comment by SonorousMeerkat** [comment]
Yes, this is the first we've heard of this bug and with us not modifying the damage of vehicles, we are skeptical that this is something to do with Antistasi.

**Comment by AlexTriada** [comment]
Hmm, this bug was already long time as i know, very interesting ...

**Comment by AlexTriada** [comment]
Or this bug is only on my server, or somebody lye to me) probably problem is in my server settings, need to think about that

**Comment by Bob-Murphy** [comment]
I know what you mean - have seen it whilst being admin month ago. It (at least for me) seems very rare and I don't know what could trigger that.
This has - as far as i know - nothing to do with the "new" rhs update because it also was before that.
I normally just blow the vehicles up with zeus before the players can reach it because it's bugged

**Comment by CalebSerafin** [comment]
Closed until evidence is provided this is connected to Antistasi or Antistasi with RHS.
