### ISSUE TITLE
[bug] Destruct towers and houses are loading on the same place with unbroken one 

### ISSUE THREAD

**Issue by AlexTriada** [official-antistasi-community/A3-Antistasi#311]
### Version of the mission:
- [x] 2.1.2
- [x] unstable branch
### Mods: 
- [x] CBA 
- [x] TFR   
- [ ] ACE (no medical)   
- [x] ACE   
- [x] RHS  
- [ ] others:
### Environment: 
- [x] SP     
- [x] MP host server     
- [x] MP dedicated server
### .rpt file attatched? 
- [ ] YES        
- [x] NO
### Do you edite the missionfile?
- [ ] YES
- [x] NO
## Issue:
After load persistant server save destruct towers and houses are on the same place with unbroken one

**Comment by PoweredByPot** [comment]
this one of our oldest issues. We are starting to think it might be an engine issue.
#2

**Comment by AlexTriada** [comment]
> this one of our oldest issues. We are starting to think it might be an engine issue.
> #2

i don't think so)

**Comment by nirousseau** [comment]
also facing this issue after a server restart.

**Comment by Bob-Murphy** [comment]
This bug is not a duplicate itself. This Issue is re-opening #2 as the possible fix 3185b89b1ab49ef93ef01d1b017fd15bdca9a410 did not work.
Also #355 has been opened for a temporary fix.
