### ISSUE TITLE
Log Line Adaptations

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#3111]
1. Add a log which, after a commander called in a rebel airstrike, contains the following information:
`Commander Playername [UID] called in [type] airstrike from [start-coordinates] to [end-coordinates], [start-coordinate distance to HQ]m from HQ `

2. A3A\addons\core\functions\Supports\fn_SUP_airstrikeRoutine.sqf
line 60 - add bomb type and coordinates to debug line

**Comment by jaj22** [comment]
SUP_airstrikeRoutine is the support airstrike code, not related to rebel airstrikes. Sure you want that logged?

**Comment by Bob-Murphy** [comment]
Just fyi, support code adjustion was intended to more easily be able to know what hit where in case people are confused on "is it friendly or foe".
