### ISSUE TITLE
Helicopter garage logic overhaul

### ISSUE THREAD

**Issue by gbestwick** [official-antistasi-community/A3-Antistasi#312]
A feature request, which may not be viable.

It'd be fantastic if it was possible to retrieve helicopters from the garage where there is a helipad beside the outpost. For example the outpost in Syrta, or the outpost North-East of Lakka.

But, obviously it shouldn't be able to Spawn airplanes. (Although, it'd be a hoot to try to take off down the roads...)

**Comment by wurzel0701** [comment]
The data we need for this is there in #289.
It can be used to do this on every possible site

**Comment by gbestwick** [comment]
Excellent! Thank for you looking into this, and giving it consideration.

**Comment by Bob-Murphy** [comment]
@wurzel0701 
Update on this one please.

**Comment by Bob-Murphy** [comment]
@wurzel0701 Disregard.

New plan and solution:
Civilian helicopters can be bought, and they as well as unweaponized military choppers can be garaged as well as pulled from the garage at base.
Every armed chpper as well as jets and gunships ONLY can be garaged and ungaraged at an airfield.

**Comment by Bob-Murphy** [comment]
Somebody please work on this one.

**Comment by jaj22** [comment]
So would you want a Huron (unarmed) to be garaged and ungaraged at HQ, but not the version with the side miniguns? Or is this a misinterpretation? I'd need some research on how to reliably detect weapon mountings.

Easier method here is to decide by template categories. For example you could allow patrol helis and the civ heli, but not attack helicopters. Not sure which way to go with transport helis, although the safe method would be to limit them to airports.

**Comment by killerswin2** [comment]
fixed with new garage system
