### ISSUE TITLE
[Bug]: Petros does not respawn when killed

### ISSUE THREAD

**Issue by Tiny-DM** [official-antistasi-community/A3-Antistasi#3122]
### Describe the bug

When Petros is killed by the enemies, the faction is supposed to lose 90% of it's resources and give a menu to the commander, letting them know that Petros needs to be replaced at a new location. Across three instances on the test servers (one unknown airstrike, one Mk82 airstrike, and one SU-25 gunrun) Petros has died, resources have been lost, and no new menu is created for the commander. This requires the server to be restarted to get Petros back, which clearly isn't optimal.

### How to reproduce

NOTE: These steps are NOT TESTED as I have not gotten the chance to reproduce this bug yet, but assumedly it should be relatively straightforward.
1. Start a new game
2. Place Petros out in the open or somewhere otherwise vulnerable.
3. Call in some sort of damaging support (that isnt napalm) on him.
4. When the support arrives, he will die, resources will be lost, and no menu will be presented to the commander.

### Version

3.5.0

### Have you altered the code?

No

### What i have changed

```markdown
n/A
```

### Map

Kujari, UMB Colombia

### What server?

Community Test Server, Community Test Server 2

### Time bug occured (Server time/UTC)

Approx 23:55 UTC, 2.1.24. Serve time 16:55

### Mods

```html
n/A, 3CB and RHS factions
```

### Additional context

After some basic research, no errors appear in the log, and the Petros monitor appears to be run locally. A local RPT for the event is not available, I will try to reproduce the error and get one. I executed some debug lines to see if I could pull him back, but eventually figured it would be easier to just restart the server. Log name is `arma3server_x64_2024-02-01_02-50-30` in the dev drive, will link in the RPT channel.

**Comment by jaj22** [comment]
I'll have a crack at replicating this later today if you haven't.

**Comment by jaj22** [comment]
Ok, this is a simple bug from #3089 (localization). The hintC in placementSelection gained array bracket around the strings, which is not valid syntax for the title parameter.
