### ISSUE TITLE
[Bug]: New SLAT IFVs breaking CBA enhanced event handlers due to missing inheritance

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#3127]
The SLAT IFV classes overwrite the EventHandlers class, which breaks CBA's enhanced event handler system (and possibly other mods) because it attaches its event handlers to parent classes and expects them to be inherited. EventHandlers should be inherited and modified instead of overwriting.

**Comment by ante185** [comment]
#3128 will not close this issue as the WS IFV's possess the same problem
