### ISSUE TITLE
Review CSAT Punishment missions

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#313]
CSAT Punishment missions are a ingest death sentence for a town unless the renal forces can master up mobile antiair vehicles within one minute.
Opinion:
Players should be given more of an opportunity to lesson these punishments. However, the existence of punishment missions do also pressure the players to jury up and finish the mission. (when our own official server had 4 people max)

I believe this should be discussed and not taken as granted.

**Comment by PoweredByPot** [comment]
addressed in #317. Closing this.
