### ISSUE TITLE
[Bug]: Player can become immortal when changing group right after fast travelling

### ISSUE THREAD

**Issue by thegamecracks** [official-antistasi-community/A3-Antistasi#3164]
### Describe the bug

When fast travelling, it is possible to become permanently immune to damage when changing groups soon after fast travel has completed.

From a cursory glance at the source code, I think it might be due to fn_fastTravelRadio.sqf not keeping track of the group's original units before it runs `_x allowDamage true`, letting the player bypass it by changing group:
https://github.com/official-antistasi-community/A3-Antistasi/blob/6a9361ca19bae5e5b63f8d102564957f7b352144/A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf#L151-L152
If this theory is correct, it should be fixable by storing `units _groupX` in a variable instead of re-evaluating it across the file.

### How to reproduce

1. Start a multiplayer game
2. Make a new group in the [U] Group Management dialog
3. Start fast travelling to a location like HQ
4. Once it finishes fast travelling, open Group Management, leave the group, and create a new group (verify that the group name has changed)
5. After some time, check `isDamageAllowed player` in debug console

### Version

3.5.1.e520f09

### Have you altered the code?

No

### Map

Tanoa

### What server?

Private dedicated server

**Comment by jaj22** [comment]
fastTravelRadio needs a rewrite, but if that's not done before the next release then we can quick-fix.

I feel like I've written this exact thing before for the same function...
