### ISSUE TITLE
Police weapon selection

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#318]
Currently the police dynamically improve their equipped weapon based on war level and/or aggression. This statically pick vanilla weapons regardless of modset. if nothing else can someone find me this file so i can nuke it for modded games. (if you do it yourself you'll probs do the detection better :P)

**Comment by Bob-Murphy** [comment]
@SonorousMeerkat 
Done or not?
Also, please put in your project.

**Comment by SonorousMeerkat** [comment]
Not within the scope of the project, this is not a part of the templates. will look into this after finishing the project.

**Comment by Bob-Murphy** [comment]
Question: Do we need it? The police should not run around with damn big guns because this is what the military has.

**Comment by PoweredByPot** [comment]
This has been fixed, Police use a random SMG until war level 5, then a random AR.

**Comment by Bob-Murphy** [comment]
wait what? a random AR? Me no like.
Wouldn't it make more sense if they would have pistol/punpgun until 5 and then change to SMG? We are not in the states where everybody has some full auto stuff

**Comment by PoweredByPot** [comment]
The trick here is making a change that works for all versions. We do not currently manage/sort handguns at all. 

Beyond that, yes we absolutely _could_ give them a handgun at first. By war level 5 though, police are usually not the biggest issue on the map, and I fear giving them only handguns and eventually an SMG would make them quite useless.

**Comment by Bob-Murphy** [comment]
it's not the job of the cops to effectively take you out, it's their job to harass you

**Comment by Bob-Murphy** [comment]
Done
