### ISSUE TITLE
Explosive shield around HQ

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#320]
> @Admin Another mine was found at base today about 10 minutes ago. I have no suspect or real time line on when it got placed.
> Might have to implement some sort of anti mine shield around base similar to the grenade one. Though that might be more difficult done than said.

We should add a handler for placement so we can catch mines and explosives. This is striaght forward in vanilla, however I do not know what the process will be for ACE3.

**Comment by Spoffy** [comment]
I'm not sure, but this might be fixed.

**Comment by Bob-Murphy** [comment]
It has been fixed for vanilla.
The question is if we can fix it for ACE as well @Spoffy

**Comment by CalebSerafin** [comment]
This has been solved aeons ago.
