### ISSUE TITLE
Validation errors of 3CB templates (Post Mag Well update?)

### ISSUE THREAD

**Issue by ante185** [official-antistasi-community/A3-Antistasi#3218]
Several factions now attempt to load incompatible magazines into their guns after 3CB sorted out their mag well stuff

[Arma3_x64_2024-04-13_19-14-35.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/14968190/Arma3_x64_2024-04-13_19-14-35.txt)

**Comment by jaj22** [comment]
Does it still work, or do they end up without (working) ammunition?

**Comment by ante185** [comment]
> Does it still work, or do they end up without (working) ammunition?

It does not work, they get one magazine that is force-loaded by the script that dresses the unit up, but they cannot reload

**Comment by jaj22** [comment]
Ok, ideally we get a fix for this into 3.5.3 then.
