### ISSUE TITLE
[Change]: Start default arsenal limits at 0

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#3230]
An idea I liked from a Discord suggestion: Instead of setting the default guest limits around the unlock limit, start them at zero. If commanders want to unlock an item or preserve some of it for member use, they can set the limit higher. Guest commanders would be allowed to increase guest limits to the unlock limit, but not reduce them.

The vast majority of gear found either will never be unlocked or isn't very useful to unlock, so given that few commanders use the limits dialog at the moment, this seems like a better approach for weapon variety. On the other hand, there would be a effective reduction in member privileges. Not sure how controversial that's going to be.

**Comment by ante185** [comment]
I think this'll hit the kinda best of both honestly.
Non-members wont by default feel super left out, and members can ensure that if there's any toy that they particularly care about then they can reserve it/make the commander up the limit.
Probably gonna be initially controversial but i think even the biggest haters would warm up to it eventually

**Comment by Bromancho** [comment]
If the suggestion was the one from Crusader_Lite on the 5th of April, this was a suggestion for the community servers. Having it as a parameter with whatever default you'd like sounds great to me. This would be the best of both worlds. This way the community servers can still do their votes to change the mission parameters according to how the community would like it played.

**Comment by Bromancho** [comment]
If I recall correctly, the main thing kneecapping the limits system for commander was that it wasn't saved restart to restart. Also how will this play with guided launchers? I think I recall that launchers defaulted to 45 before they could be taken and ammo for those was 75. Will it all be 0 as well?

**Comment by jaj22** [comment]
> If I recall correctly, the main thing kneecapping the limits system for commander was that it wasn't saved restart to restart.

Ah yeah, forgot about that. I'll sort it out in the same PR.

> Also how will this play with guided launchers? I think I recall that launchers defaulted to 45 before they could be taken and ammo for those was 75. Will it all be 0 as well?

It was a multiplier so they'd be zero too.
