### ISSUE TITLE
[BUG] ACRE2 (possibly also TFAR) integration not working

### ISSUE THREAD

**Issue by Godlikehobbit** [official-antistasi-community/A3-Antistasi#324]
### Version of the mission:

* [x]  A3-Antistasi 2.1.2

### Mods:

* [x]  CBA_A3

* [x]  ACRE2

* [x]  ACE

* [x]  RHS

### Environment:

* [ ]  SP
 
* [ ]  MP host server

* [x]  MP dedicated server

### .rpt file attatched?

* [ ]  YES

* [x]  NO

### Do you edit the mission file?

* [ ]  YES

* [x]  NO

## Issue:
---

Turns out they don't work in 2.1.2 either haha. Recruiting a squad or trying to create a roadblock gives the "You need a radio in your inventory..." message but does not recognize the ACRE radios.

**Comment by SonorousMeerkat** [comment]
We are aware of an issue in the unstable branch causing radios to be unavailable. We will be applying a fix there momentarily.

**Comment by SonorousMeerkat** [comment]
Although, ACRE was implemented a very long time ago and it is entirely possible that it is now incompatible. For that reason, we recommend using TFAR instead.

**Comment by Godlikehobbit** [comment]
I think this is a separate issue to the unstable branch issue, the getRadio.sqf script looks for "acre_" in a units assignedItems, using find which is case sensitive, in my testing the acre radios are all uppercase and the player (possibly other units as well) get "ItemRadioAcreFlagged"

**Comment by SonorousMeerkat** [comment]
Yes, my bad, we literally, just found a different issue regarding spawning.

**Comment by Godlikehobbit** [comment]
https://github.com/official-antistasi-community/A3-Antistasi/blob/5c46a050714d06f56a71e5701c1c42c0475792fc/A3-Antistasi/Ammunition/getRadio.sqf#L17
___
I'd have to do more testing but from what I can tell this is the fix
`private _radioPosition = _items findIf {_x == "ItemRadio" || {_x find "tf_" > -1} || {_x find "Acre" > -1}};`

**Comment by Godlikehobbit** [comment]
Going through the TFAR class names, they use TFAR_ as their prefix

**Comment by SonorousMeerkat** [comment]
Yeah, TFAR definitely still works, we don't use ACRE on the official community server, so we've never noticed issues with it. I don't think it was really touched since barbolani implemented support for it.
