### ISSUE TITLE
[Bug]: Enemy arty markers are asynchronous with support

### ISSUE THREAD

**Issue by Tiny-DM** [official-antistasi-community/A3-Antistasi#3245]
Markers for enemy artillery/mortars will often appear either a minute or two before impact, which is somewhat reasonable for full artillery, but the markers will also stick around for several minutes after the fire mission is complete, dissuading players from entering the area. The deletion of the marker needs to be closer to the actual completion of the fire mission which can be roughly approximated using shell count and getArtilleryETA. Regardless, the marker doesn't need to immediately disappear, it just needs to disappear in a somewhat timely manner

**Comment by jaj22** [comment]
Intentional simplification. The marker synchronization before was a disaster. But yeah, could probably use a better estimate.
