### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sapphon** [official-antistasi-community/A3-Antistasi#3247]
### Describe the bug

What happens:

* Approach Offroad
* Select "ride in back" from wheel menu
* be the shotgun

**OR**

* Approach Offroad
* Select "get in offroad as passenger" from wheel menu
* be in the truck bed

What I think should happen:

vice-versa

### How to reproduce

See above

### Version

3.5.4

### Have you altered the code?

No

### Map

Altis

### What server?

LAN Hosted, Private dedicated server, Private dedicated server with Headless client(s)

### Mods

```html
None, other than Antistasi
```

**Comment by ante185** [comment]
this is outside the scope of Antistasi

**Comment by jaj22** [comment]
(It's a very old Arma bug)
