### ISSUE TITLE
[Bug]: You can softlock Petros by moving him

### ISSUE THREAD

**Issue by sapphon** [official-antistasi-community/A3-Antistasi#3248]
### Describe the bug

* Pick up Petros
* Run as far as you can
* Note that in some cases you are prohibited from using him or moving him back, because he's "too far"
  * Note that in those cases, the only solution is to reset your whole HQ and all of its associated pieces, vs. just Petros

### How to reproduce

See above

### Version

3.5.4

### Have you altered the code?

No

### Map

Altis

### What server?

LAN Hosted, Private dedicated server, Private dedicated server with Headless client(s)

### Mods

```html
None
```

**Comment by jaj22** [comment]
Save/load also works because Petros' position is reset. Also fixed in #3210 if I can ever get a review on it.

**Comment by Sheepy3** [comment]
should this issue be closed?

**Comment by jaj22** [comment]
Yeah, should be fixed in #3210.
