### ISSUE TITLE
[Change Request]: OpticsAAF needs testing on WW2

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#330]
OpticsAAF is generated by looking at the guns available, then listing all attachments that can fit them.

Currently, the game just doesn't spawn optics for WW2 - presumably because they contain non WW2 gear.

The optics list needs checking on WW2 - and the generation improving if it proves to contain modern gear.

If it's improved, we then need to enable them to appear in crates (see #315)

**Comment by Bob-Murphy** [comment]
@Spoffy 
Will that be dealt with by the new templates automatically?

**Comment by Spoffy** [comment]
Needs attaching to the change from dynamic generation to tool-assisted static lists. Don't know if we have a project for that? We could probably could a bunch of issues grouped up.

**Comment by MeltedPixel** [comment]
Can be closed, as per bob.
