### ISSUE TITLE
Airports don't spawn helicopters

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#333]
Possibly to due with '_busy' and A3A_fnc_addTimeForIdle from Patrols.

**Comment by Spoffy** [comment]
Same for Attack vehicles (line 304)

**Comment by wurzel0701** [comment]
As I currently change it in #289, should I remove the busy flag?
Another thing that keeps units from spawning is the available mechanics.
Most vehicles are simply not available most times

**Comment by wurzel0701** [comment]
Its not a bug the game mechanics are working as they should.

The game mechanic may not be that good in this point...

**Comment by wurzel0701** [comment]
Fixed in #345
