### ISSUE TITLE
[Bug]: Seaports will not remove undercover

### ISSUE THREAD

**Issue by Tiny-DM** [official-antistasi-community/A3-Antistasi#3347]
You can use an undercover helicopter to fly into a seaport, grab the ammobox, and leave for free with no threat. Seaports should either not spawn ammocrates or remove undercover, preferably the latter.

**Comment by jaj22** [comment]
Hmm. There's no undercover removal for slingloading? Should add that at least.

Seaports probably should be added to airspaceControl.
