### ISSUE TITLE
[DON'T FIX] Typo in marker on altis

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#335]
The marker "spawnpoint" does not gets recognized by the new marker detection as it is not "spawnPoint". I already fixed this in #289 and we probably don't want to merge mission.sqms, so don't fix this even if you see this

**Comment by Bob-Murphy** [comment]
@wurzel0701 
Implemented and fixed?
If so, please give milestone, marked as fixed and close.

**Comment by wurzel0701** [comment]
Should be fixed as long my updated sqm is used
