### ISSUE TITLE
Civilians need random faces, and to shut up.

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#337]
Based on the code civilians shouldnt be talking ever, but apparently they still do.

After my CfgSearch PR comes in civilians will all have the same face for a given race, I need to randomize it based on available faces.

**Comment by Spoffy** [comment]
I've never heard a civilian talk since those changes were implemented. But we could still hunt it down.

**Comment by PoweredByPot** [comment]
this can still be done with the new civilian modules we want to use, but the identities will have to be moved to description.ext or something similar.

**Comment by killerswin2** [comment]
Done in #2316
