### ISSUE TITLE
[Bug]: Tags function causes script errors

### ISSUE THREAD

**Issue by ILikeRubberDuckies** [official-antistasi-community/A3-Antistasi#3394]
### Describe the bug

```
File x\A3A\addons\core\functions\init\fn_tags.sqf..., line 26
Error in expression <ze='0.5' shadow='2' color='#7FFF00'>" + format['%1 %2',_target getVariable ['uni>
Error position: <format['%1 %2',_target getVariable ['uni>
Error 1 elements provided, 2 expected
```

Tags are still displayed normally (as far as I can tell).
![image](https://github.com/user-attachments/assets/bb824ba9-c4a9-4a1e-bf01-65490510bb1b)

### How to reproduce

1. Run vanilla Antistasi
2. Look at Petros or other friendly AI

### Version

unstable?

### Have you altered the code?

No

### Map

Altis

### What server?

LAN Hosted

### Mods

```html
-
```

**Comment by jaj22** [comment]
Probably needs profiling or dev branch to replicate. I think BI added sanity-checking to `format`, so now a lot of old code is throwing these errors.

Is that our only one? Would be surprised.

**Comment by ILikeRubberDuckies** [comment]
I am on profiling. But so far I have not seen any others pop up.
