### ISSUE TITLE
[Change Request]: Make the carpet bomb support less fake

### ISSUE THREAD

**Issue by ante185** [official-antistasi-community/A3-Antistasi#3426]
### Is the requested change related to a problem?

Current carpet bomb routine is currently too fake and impossible to counter as the bombs are just spawned in above the target area.

### Describe the solution you'd like.

Tie the support to aircraft(s) that get dispatched from the enemy airbase/support corridor.

One option is making the strike be multiple airstrikes ran in parallel, alternatively if available a larger plane can be used.

**Comment by rautamiekka** [comment]
Might work with [fireAtTarget](https://community.bistudio.com/wiki/fireAtTarget) (or some other) if you can get the lining up to work some way.

^ The comments have a comparison table for the different similar commands, minus the [BIS_fnc_fire](https://community.bistudio.com/wiki/BIS_fnc_fire) mentioned at the top of the article.
