### ISSUE TITLE
[Bug]: item piles are too aggresively clean away

### ISSUE THREAD

**Issue by ante185** [official-antistasi-community/A3-Antistasi#3447]
### Describe the bug

When using a loot crate and it becomes full in the process of looting, too often you can see that the leftover pile of stuff you've failed to loot be deleted in front of your eyes.

### How to reproduce

Unknown, presumably this occurs due to infrequent garbage cleans and too much dead stuff laying around on the server.

### Version

3.7.0

### Have you altered the code?

No

### Map

Any

### What server?

Community Server 1, Community Server 2, Community Test Server, Community Test Server 2

**Comment by jaj22** [comment]
Oh yeah, it already flags the cases for the hint message, so it's a straightforward fix.
