### ISSUE TITLE
initialRifles and autoRearm.sqf

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#347]
The global variable 'initialRifles' set in templates is used **_only_** for the auto-rearm function. That function only uses it to attempt to rearm units if their primary weapon is in that list, or nothing. It then goes on to compare nearby weapons against a static list of weapons that I think are equal to 'initialRifles' on the vanilla templates.

**Comment by Bob-Murphy** [comment]
@SonorousMeerkat @PoweredByPot 
Is this still an issue or has this been fixed due to your stuff?

**Comment by PoweredByPot** [comment]
this is still an issue, separate from either of our current work. The real underlying problem here is the auto-rearm script and its operation.

**Comment by wurzel0701** [comment]
Is this done in #414 or does this needs further work?

**Comment by PoweredByPot** [comment]
this fixes this specific issue yes.

**Comment by wurzel0701** [comment]
Ok, closing as the PR is already pending

**Comment by Bob-Murphy** [comment]
Issues should be closed once PRs are successfully merged.

**Comment by Spoffy** [comment]
Resolved in #414
