### ISSUE TITLE
[Temporary] Remove Persistent building destruction scripting

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#355]
Due to Schrodinger's buildings, can we temporarily remove the scripting that attempts to make destruction persistent, At least until we have a better solution.

**Comment by SonorousMeerkat** [comment]
Based on current lack of fix for #2

**Comment by Spoffy** [comment]
I'll just fix it in a way I didn't want to, and do it properly.
