### ISSUE TITLE
PvP Player rearm box

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#364]
Box at PvP player's spawnpoint that replaces their loadout. Also clears the items on the ground in a 100m radius to deny loadout duping.

**Comment by Bob-Murphy** [comment]
No box needed, script can be added to the flag.
This saves us placing something new which can glitch through the map.

**Comment by Bob-Murphy** [comment]
PvP will be disabled which makes this issue obsolete.
