### ISSUE TITLE
Rewrite Create Unit

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#384]
Make all instances of createUnit call a function. This opens the door to using a pool of units, which should disable spawn time (or at least enable us to call setUnitLoadout without massively increasing overhead)

**Comment by Bob-Murphy** [comment]
@Spoffy 
Update/Project?

**Comment by Spoffy** [comment]
This needs doing before 385 can be done, which in turns needs doing before 386 can be done... or maybe that's the other way round. Anyway, this needs to be put in a milestone. 2.3 is possibly a good spot for it.

**Comment by wurzel0701** [comment]
Is probably done with the template stuff already

**Comment by CalebSerafin** [comment]
This is already done
