### ISSUE TITLE
Make spawning units side-agnostic

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#385]
Currently, units are spawned on a side, and even putting them in a group doesn't meaningfully change that side - AI will still shoot at other AI. 

In order to move ahead with the template reworks, we need to be able to spawn a single unit on any side.

Pot's proposed solution (setUnitLoadout) on a unit seems like a suitable solution for this problem. Potentially incurs performance overhead, so should be done after #384

**Comment by Bob-Murphy** [comment]
@Spoffy 
Update/Project?

**Comment by Spoffy** [comment]
Needs doing.

**Comment by Bob-Murphy** [comment]
@Spoffy 
Whil this be covered by new template system as well as 384?

**Comment by Spoffy** [comment]
Yes, leave open, it's part of the new template system.

**Comment by CalebSerafin** [comment]
This new template system is now in the game.
