### ISSUE TITLE
Create a changelog for 2.2

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#391]
Bob lost track (I think we all did) of the changes. Start a list here and add every change you have made since 2.1.2. I would seperate it in major (direct change of a gamemechanic), groundwork (mostly for me, things that are there, but the player cant see), minor (small changes to gameplay), bugfixes and code changes

Major
- [Wurzel] Changed vehicle spawn mechanic, vehicles should be spawned in logical positions and without  explosions
- [Wurzel] Added random convoys driving around (These are neither random nor just driving around, but you have to wait for the full picture)
- [Wurzel] Random convoys attack roadblocks on their ways
- [Wurzel] Added the ability to breach open vehicles with explosives
- [Meerkat] Complete overhaul of starting weapons and equipment for all variations of rebel side.
- [PBP] Created parameters to allow DLC gear
- [PBP] Created parameters to modify or prohibit crate loot
- [PBP] Created parameters to allow unlocked guided launchers and explosives
- [PBP] Created a parameter to stop an unlocked weapon from unlocking its first valid magazine
- [PBP] Rebuilt Items system completely
- [PBP] Rebel AI now appropriately gear from unlocked equipment (Vest/Helmet/Backpack)
- [PBP] Complete re-balance of AI Skill
- [Bob] Added new map Malden - only 37 playable slots (25 rebell + 12 PvP)
- [Bob] Added new map Livonia
- [Bob] Added new map Kunduz - only 37 playable slots (25 rebell + 12 PvP)
- [Bob] Added new map Tembelan Island

Groundwork
- [Wurzel] Reworked the garrison system to build a new reinforcement system on top of it
- [Wurzel] Added a system to simulate convoys of all types
- [Meerkat] Template names and precursory files created
- [PBP] Items system now scans config for defines instead of relying on manual input
- [PBP] Began work on removing faction or side names from variable names throughout mission
- [PBP] Extensive sorting and commenting on format for template files, and initVar
- [PBP] Moved all units of the same side to the same template (police and militia)
- [PBP] Added logging to various server functions
- [PBP] Stopped modifying items in 'onPlayerRespawn'
- [PBP] Stopped player reading a significant portion of initVar on connecting to a server

Minor
- [GodlikeHobbit] Undercover medics can now heal civilians/undercover players without becoming overt
- [GodlikeHobbit] Added an option to disable civilian traffic
- [PBP] Balance pass for "CSAT Punishment" mission

Bugfixes
- [Wurzel] Dialog back buttons now work correctly
- [GodlikeHobbit] ACRE radios are now recognized correctly
- [GodlikeHobbit] Fixed an error relating to toolkits being added to the arsenal incorrectly
- [GodlikeHobbit] Fixed one of the civilian traffic options not working
- [PBP] Fixed broken easy difficulty setting
- [PBP] Fixed "Destroy the Helicopter" mission
- [PBP] Fixed access to HC squad level commands on map interface
- [PBP] Certain weapons no longer include base attachments with them
- [PBP] Fixed many bad case and improper item defines throughout the mission
- [PBP] Fixed most cases of exploding vehicles when Outposts spawn
- [PBP] Fixed money loss on death to only penalize once
- [PBP] There should be much less inconsistency in save data
- [Bob] Playable rebell units stripped so their initial gear can't be glitched in

Code changes
- [Wurzel] Changed destroyedCities to destroyedSites
- [PBP] Significant refactoring and organizing of various scripts throughout the mission

Known issues
- [GodlikeHobbit] Undercover medics cannot heal without breaking cover while looking at an overt unit (A fix for this is WIP)

**Comment by Godlikehobbit** [comment]
Minor
- Undercover medics can now heal civilians/undercover players without becoming overt

Bugfixes
- ACRE radios are now recognized correctly
- Fixed an error relating to toolkits being added to the arsenal incorrectly

Known issues
- Undercover medics cannot heal without breaking cover while looking at an overt unit

**Comment by SonorousMeerkat** [comment]
current:
Groundwork:
Template names and precursory files created

Awaiting Pull:
Groundwork.
small initVar addition to accept new gear arrays.
Minor: (ish)
Complete overhaul of starting weapons and equipment for all variations of rebel side.

**Comment by wurzel0701** [comment]
Check it on unstable
File : A3-Antistasi/changelog_2_2.sqf

Add or change what I have missed

**Comment by Bob-Murphy** [comment]
Please don't change anything in here anymore.
I'm working on it locally.
