### ISSUE TITLE
Fix waypoint at convoy spawn

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#392]
As already stated in the dev-team channel once a calculated convoy gets spawned in by a player it spawns stationary without a waypoint and does not move at all.

Fix needed.

Please and Thank you.

**Comment by Bob-Murphy** [comment]
![image](https://user-images.githubusercontent.com/50651578/66605050-a285e980-ebaf-11e9-82d0-16d39217c1c4.png)
2 convoys wanted to go past my position, got spawned and stuck

**Comment by Bob-Murphy** [comment]
![image](https://user-images.githubusercontent.com/50651578/66605167-d5c87880-ebaf-11e9-8b52-4cd9175ee521.png)
Sorry, 3 different convoys. My bad.

**Comment by Bob-Murphy** [comment]
On a similar note, don't the marker get deleted once they reach the target?
![image](https://user-images.githubusercontent.com/50651578/66606029-82efc080-ebb1-11e9-9a07-9f1e6d2692fa.png)

**Comment by wurzel0701** [comment]
Should be all fixed, needs testing

**Comment by wurzel0701** [comment]
Spoffy fixed it
