### ISSUE TITLE
ACE items modification breaks Launcher class detection

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#395]
I wrote a new method of launcher class detection both because of the new parameter, and because the old one failed with ACE, but it turns out this one fails with ace for a similar but different reason.

In this case ACE changes the `nameSound` property of all missile launchers to `aalauncher` for no apparent reason. The real question here is where specifically to fix it. The problem arises when (if) a weapon is unlocked and gets put in the wrong array, it will be equipped by the wrong class. If we fix it in `arsenalManage` I _think_ that it will still be a problem when the server loads and deals with any existing unlocked launchers. My gut says this should be dealt with in the `aceModCompat` function because I am pretty sure that loads completely before the server would try to load any save data. 

The problem is I don't actually know what could be done in their that would prevent this from happening.

**Comment by PoweredByPot** [comment]
It's worth noting that ACE also changes the class of some bullet-based weapons as well

**Comment by Spoffy** [comment]
Fixed as of c2745c4917beedc00c00621c0a881537c5f7d8d9, using launcher detection based on ammo's "airLock" parameter.

Not viable to deal with in 'Ace mod compat', because ACE (and CBA) make some *very* specific changes to launchers.
