### ISSUE TITLE
@Godlikehobbit, please message me on discord. Would like to talk to you.

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#397]
First of all thank you for your help regarding Antistasi. Some good stuff you did here.
Therefore I'd like to talk to you and ask you if you are maybe interested in joining the Dev team as a Dev helper.

So just feel free to comment here or contact me on discord.

Best regards,
Bob

**Comment by Godlikehobbit** [comment]
PM'd on discord
