### ISSUE TITLE
[Feature Request]: Get Convoy Vehicles to Follow Each Other

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#398]
Because of the FSM implementation, the build in convoy separation doesn't work. We'll need another FSM to "follow vehicle" in order to build proper convoys.

**Comment by wurzel0701** [comment]
Can't it be integrated into the current FSM? Give it a "_previousVehicle" parameter and slow the vehicle down if it comes to close to it and speed the vehicle once the distance is too large

**Comment by Spoffy** [comment]
It could, but I'd rather have a seperate FSM for it - they logically separate concepts. One is following a path, the other is following a vehicle. 

By keeping them de-coupled, we help ourselves be flexible in the future.

**Comment by wurzel0701** [comment]
How about doing a convoyFSM, which reduced the code which need to be executed?

**Comment by wurzel0701** [comment]
@Spoffy you think this can be done in 2.3 AI or postponed to 2.4?

**Comment by Tiny-DM** [comment]
Vehicles will now follow each other mostly reliably, holding a set pace. Closing issue.
