### ISSUE TITLE
[Bug]: Civilians are spawned locally on players, causing RPT spam

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#402]
fn_ambientCivs is called in initPlayerLocal, but somehow the mission loses track of them by the time they come up for deletion.

Although probably not the _only_ cause, I highly suspect this will reduce a significant amount of the `Error: Object (X : XXX) not found`
or
`Server: Object X:XXX not found (type_XXX)`

We have talked about creating agents for Civs instead of real units, perhaps this is another motivator to work towards that?

**Comment by Bob-Murphy** [comment]
This will most likely be effected by the change of the civilian system.
Don't work on it.

**Comment by PoweredByPot** [comment]
working on new civilian system will have to be done at the map-level for now. Tried to make a script based implementation but placing modules via script sucks.

**Comment by PoweredByPot** [comment]
assigned Bob too because he loves the eden editor, apparently.

**Comment by MeltedPixel** [comment]
This is corrected with #2683
