### ISSUE TITLE
WW2 Explosives/Detonators availablility

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#404]
Can't remember the details for certain, but i think we were giving WW2 the wrong detonator for the job.

**Comment by SonorousMeerkat** [comment]
This was something mentioned to me offhand one day by another player, after which noted it on my project. If we could keep an eye out for what this is in the next round of testing i would appreciate it.

**Comment by Bob-Murphy** [comment]
@SonorousMeerkat 
Is that already in unstable?

**Comment by SonorousMeerkat** [comment]
I haven't done anything to fix this. It was (i believe) to do with the equipment given based on ACE being enabled. This is done in initVar.

**Comment by SonorousMeerkat** [comment]
IFA was disabled and (imo) should be replaced with a different modset in NTS. Either way the template would be made from scratch thus fixing the problem.
