### ISSUE TITLE
Kill Template Redirection

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#407]
By this, I mean loading one template chain-loading another template, instead of itself. It's confusing and easy to miss, therefore bad.

**Comment by Bob-Murphy** [comment]
@Spoffy 
Have you properly conveyed the issue to @SonorousMeerkat ?
@SonorousMeerkat Please link this to your project if it's matching.

**Comment by Spoffy** [comment]
Have not, need to.

**Comment by SonorousMeerkat** [comment]
Phase 4, added to project

**Comment by SonorousMeerkat** [comment]
Linked to MIE Phase one, was probably fixed before that though with selector.sqf.
