### ISSUE TITLE
Watch maps and load screens on player init for markers or reports of same

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#408]
I have removed a section of code from initPlayerLocal that removed a players map and GPS very early on connection. It is believed that this was done in order to prevent players from seeing the orders given to AI units and associated spawn markers on the map during loading.

I removed these items because we now set a players loadout directly very shortly after this is done, and also because it makes it more difficult to track modifications to items. The result is no more `CWeaponSlotsManager::DeleteWeapon: wrong weaponID!` console spam anymore.

Lets continue to keep an ear out for any reports that can give specific circumstances about when this may occur.

**Comment by PoweredByPot** [comment]
Doom saw the markers today when initializing a LAN hosted mission

**Comment by Bob-Murphy** [comment]
Closing this as no new information
