### ISSUE TITLE
Trench Cleanup

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#410]
Find a way to make ace trenches get cleaned by a garbage clean. possibly by model name?
Might be worth making it not delete a trench with a player nearby but that is a secondary issue.

**Comment by Spoffy** [comment]
Delete trenches if nobody in 300m or so?

**Comment by Bob-Murphy** [comment]
Somebody please add trenches to garbage clean with the check if players within 300m

**Comment by CalebSerafin** [comment]
Completed in PR #1049
