### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#412]
Please complete the "How to build from GIT" part of the Readme based on the Tool you have implemented. List it as a tool which does the work automatically and stuff.

**Comment by CalebSerafin** [comment]
Is this for PackageMission.ps or Antistasi Dev Deploy.exe?

**Comment by Bob-Murphy** [comment]
I think Wurzel has already done it in #475 which is waiting for merging.
Could you please check if the tools which were added by you (I don't know which exactly you added) are correctly described in Wurzels change?
