### ISSUE TITLE
Rework function/AI/autoRearm.sqf

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#418]
The overall function of this script is extrem performance hungry with a lot of logic flaws, improve to the following logic :
- Run towards the nearest crate
- Take whatever you need 
- Check if unit still needs rearm
- Repeat if some gear is missing

**Comment by PoweredByPot** [comment]
My fix is working, but its pretty apparent how poor this script works currently. I had three troops with starter SMG's completely ignore MX rifles because they were on the ground, and not inside a container.

**Comment by wurzel0701** [comment]
Refactor issue, nobody got time for that anyways
