### ISSUE TITLE
Cannot get assassination missions on invader only.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#421]
(from discord, probably an issue from invader only's creation.)
SamichToday at 3:36 AM
Petros will not give me assasination missions, he says cities, patrolled jungles, or airports need to be closer than 4km away. My HQ is about 500m north of the default location so I have no idea why he says this.
 
John JordanToday at 3:59 AM
@ Samich If that's Altis, who owns Kavala?
 
SamichToday at 4:06 AM
Playing against AFRF only and I do not own it
 
John JordanToday at 4:06 AM
I thought redfor never owned towns.
maybe the game thinks that too :P
 
SamichToday at 4:07 AM
Possibly, no fighting dirty russians then
:pensive:
 
SamichToday at 4:14 AM
It works fine against only nato. odd
 
John JordanToday at 4:21 AM
Checked the code. It has a specific check for Occupant-owned airports. Not sure why, but that disables it for reb vs inv.
 
SamichToday at 4:30 AM
Interesting, thank you for the explanation as to why it doesnt work

**Comment by CalebSerafin** [comment]
This will be done properly in 2.4 template handling. Not priory right now.

**Comment by SonorousMeerkat** [comment]
Not necessarily, as it stands the new system will work the same as old due to not having time for the functionality changes. Sides etc still need to be respected.

2.4s implementation is just to make the new gear templates work. Not for the full implementation.

**Comment by CalebSerafin** [comment]
They will benefit the ability of towns to be controlled by invader. Right now as I've worked on this, we have to have Invader soldiers spawning in occupant controlled towns. So, then I'll have to expand this to allow invader to control towns. Have riflemen as police or no police at all. And make sure Invader Towns don't break anything else.

**Comment by Bob-Murphy** [comment]
invader only is disabled
