### ISSUE TITLE
Moving HQ on server start does NOT move the player

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#436]
As it says, on first load of a server if the player in commander slot chooses to move the starting HQ, he gets left behind at the default starting position.

**Comment by Toakan** [comment]
I've triggered this issue on Altis and Tanoa. Definitely replicated.

**Comment by Bob-Murphy** [comment]
Update on this fucker?
One of the cases was that guests joined before the commander did, the commander then changed the HQ location and the already spawned players didn't get teleported.

**Comment by Spoffy** [comment]
Needs testing again.

**Comment by Spoffy** [comment]
According to dev team meeting, no longer an issue.
