### ISSUE TITLE
Rewrite fn_ACEpvpReDress 

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#441]
fn_ACEpvpReDress uses old mod-detection method (source: pot) and needs to be overhauled

**Comment by Bob-Murphy** [comment]
Is this still an issue?

**Comment by Spoffy** [comment]
Still an issue, needs integrating with the rest of the PvP loadout stuff.

**Comment by Bob-Murphy** [comment]
PvP will be disabled which makes this issue obsolete.
