### ISSUE TITLE
Implement BI respawn menu for PVP sides

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#443]
https://community.bistudio.com/wiki/Arma_3_Respawn#Respawn_Templates

We should be able to implement BI's fancy GUI respawn menu with loadout/role options for _just_ PVP player sides without much difficulty, and thus give them a little more flexibility in loadouts without giving them completely free choices.

**Comment by Bob-Murphy** [comment]
Nope.
