### ISSUE TITLE
Non-member distance leash doesn't grab players vehicle

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#446]
In rare occasions HQ can be relocated and cause non-member players to be leashed back. During these cases player vehicles are not preserved.

Obviously there will have to be some considerations made about whether or not the vehicle comes too. Damage, combat status, etc.

**Comment by Spoffy** [comment]
Were they actually in the vehicle? As any vehicles you're driving are actually teleported with you.

**Comment by Spoffy** [comment]
I'm not sure this is an issue - as we can't easily teleport vehicles players aren't in, and it sounds like they were stood next  to their vehicles in this case. 

There might be an argument for extending the member leash on HQ move though (or similar), to avoid screwing squads already in the field.

**Comment by Bob-Murphy** [comment]
no new issues therefore closed for now
