### ISSUE TITLE
DS CTD Error on Tanoa

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#449]
```
18:17:24 ErrorMessage: File mpmissions\__cur_mp.Tanoa\mission.sqm, line 440: .ScenarioData: Member already defined.
18:17:24 Application terminated intentionally
ErrorMessage: File mpmissions\__cur_mp.Tanoa\mission.sqm, line 440: .ScenarioData: Member already defined.
```
https://github.com/official-antistasi-community/A3-Antistasi/blob/0ecbf4d8f06a499558b9c4d2ce86ad7a89ac3b67/Map-Templates/Antistasi-WotP.Tanoa/mission.sqm#L152-L164

https://github.com/official-antistasi-community/A3-Antistasi/blob/0ecbf4d8f06a499558b9c4d2ce86ad7a89ac3b67/Map-Templates/Antistasi-WotP.Tanoa/mission.sqm#L437-L440

The error is pretty clear, but I don't know why its suddenly here now.

**Comment by Toakan** [comment]
It's because the class has already been defined. Just need to throw the Author up into the one above.
