### ISSUE TITLE
[bug] FIA garrisons replaced on load by CSAT squad

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#453]
*Version:* 2.2 unstable, 0ecbf4d8f06a499558b9c4d2ce86ad7a89ac3b67

*Mods:* None. Altis greenfor vanilla.

*Environment*: MP dedi.

*.rpt attached?* [arma3server_x64_2019-10-31_23-55-30.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/3796239/arma3server_x64_2019-10-31_23-55-30.zip)

*have you edited the missionfile?*: No

***Issue:***

When loading from a save, FIA garrisons are replaced with a CSAT squad. When spawned, they shoot each other. Factories and outposts sometimes flip to blue on load as well. Not sure if related.

I eventually pinned this down to functions/init/fn_initGarrisons, specifically this line:

https://github.com/official-antistasi-community/A3-Antistasi/blob/0ecbf4d8f06a499558b9c4d2ce86ad7a89ac3b67/A3-Antistasi/functions/init/fn_initGarrisons.sqf#L97

initGarrisons is called before the game is loaded, but either due to scheduling or unknown marker sides, it takes effect afterwards, overwriting all the garrisons. The effect is much more obvious with the FIA garrisons, but all garrisons are overwritten.

**Comment by PoweredByPot** [comment]
@wurzel0701, this is your work. I'm trying to read through it myself and see if this could be the case, but maybe you could answer before I am certain.

**Comment by wurzel0701** [comment]
Its mine, PR #454 will fix this, damn scheduling I haven't thought of this case
