### ISSUE TITLE
Saving error when loading an old save

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#460]
When running an older save from 2.1.2, the first instance of a Save within 2.2 will throw the following error.

This is a completely Vanilla game save, no mods are used.
```
"[Antistasi] Saving player ********** on side GUER"
Error in expression <etText (configFile >> "CfgMagazines" >> _weaponMagazine >> "displayName")};
case>
  Error position: <_weaponMagazine >> "displayName")};
case>
  Error Undefined variable in expression: _weaponmagazine
File functions\Ammunition\fn_arsenalManage.sqf [A3A_fnc_arsenalManage]..., line 1107
Error in expression <_updated = format ["%1%2<br/>",_updated,_name];


if (unlockedUnlimitedAmmo == 1>
  Error position: <_name];


if (unlockedUnlimitedAmmo == 1>
  Error Undefined variable in expression: _name
File functions\Ammunition\fn_arsenalManage.sqf [A3A_fnc_arsenalManage]..., line 1113
Error in expression <etText (configFile >> "CfgMagazines" >> _weaponMagazine >> "displayName")};
case>
  Error position: <_weaponMagazine >> "displayName")};
case>
  Error Undefined variable in expression: _weaponmagazine
File functions\Ammunition\fn_arsenalManage.sqf [A3A_fnc_arsenalManage]..., line 1107
Error in expression <_updated = format ["%1%2<br/>",_updated,_name];


if (unlockedUnlimitedAmmo == 1>
  Error position: <_name];


if (unlockedUnlimitedAmmo == 1>
  Error Undefined variable in expression: _name
File functions\Ammunition\fn_arsenalManage.sqf [A3A_fnc_arsenalManage]..., line 1113
"538.776: [Antistasi] | INFO | Persistent Save Completed."
```

After another save, it then throws this into the RPT.

```
Warning Message: No entry 'bin\config.bin/CfgWeapons.'.
Warning Message: No entry '.scope'.
Warning Message: '/' is not a value
Warning Message: Error: creating weapon  with scope=private
Warning Message: No entry '.displayName'.
Warning Message: '/' is not a value
Warning Message: No entry '.nameSound'.
Warning Message: '/' is not a value
Warning Message: No entry '.type'.
Warning Message: '/' is not a value
Warning Message: No entry '.picture'.
Warning Message: '/' is not a value
Warning Message: No entry '.Library'.
Warning Message: No entry '.libTextDesc'.
Warning Message: '/' is not a value
Warning Message: No entry '.model'.
Warning Message: '/' is not a value
Warning Message: No entry '.simulation'.
Warning Message: '/' is not a value
Warning Message: No entry '.fireLightDuration'.
Warning Message: '/' is not a value
Warning Message: No entry '.fireLightIntensity'.
Warning Message: '/' is not a value
Warning Message: No entry '.fireLightDiffuse'.
Warning Message: Size: '/' not an array
Warning Message: Size: '/' not an array
Warning Message: No entry '.fireLightAmbient'.
Warning Message: Size: '/' not an array
Warning Message: Size: '/' not an array
Warning Message: No entry '.weaponLockDelay'.
Warning Message: '/' is not a value
Warning Message: No entry '.weaponLockSystem'.
Warning Message: '/' is not a value
Warning Message: No entry '.cmImmunity'.
Warning Message: '/' is not a value
Warning Message: No entry '.weight'.
Warning Message: '/' is not a value
Warning Message: No entry '.lockingTargetSound'.
Warning Message: Size: '/' not an array
Warning Message: No entry '.lockedTargetSound'.
Warning Message: Size: '/' not an array
Warning Message: No entry '.detectRange'.
Warning Message: '/' is not a value
Warning Message: No entry '.muzzles'.
Warning Message: Size: '/' not an array
```

Which indicates that there is a Magazine being compared with a value of '/' which should be dropped instead.

**Comment by jaj22** [comment]
Not sure what's up with the line numbers here (I have the same issue), but the first one is a simple error on line 44 of arsenalManage:

https://github.com/official-antistasi-community/A3-Antistasi/blob/2ea0f3651a61fedb4d988ecc00516ed2ffd68135/A3-Antistasi/functions/Ammunition/fn_arsenalManage.sqf#L44

Should be `_item` there rather than `_weaponMagazine`. The second error (undefined variable _name) is a follow-on with the same cause.

That error only affects the text output, so it shouldn't corrupt the arsenal & unlock lists, and so shouldn't be related to the CfgWeapons error spam. Not sure where that one comes from yet.

**Comment by PoweredByPot** [comment]
the line numbers you are given is caused by the iteration of the loop, vs the actual line number of the file.

Good spot on the bad variable, I've added it to the fix branch I am building and credited you @jaj22

**Comment by PoweredByPot** [comment]
second error is related to loading a saved loadout in the arsenal, have not been able to work out the cause yet, but it happens in vanilla on a clean save with a loadout that contains ONLY a civilian uniform.

**Comment by PoweredByPot** [comment]
the half related to bad variables has been dealt with in #470, the other part still eludes me but I suspect it has to do with loading a saved loadout that has no weapons. The event can be recreated by loading any loadout that contains only a uniform.

**Comment by jaj22** [comment]
I'm getting the same CfgWeapons error spam in vanilla when the first FIA garrison spawns. Oddly enough, the error shows up on the client, not the server, and I don't think setUnitLoadout is ever used on garrison troops.

Similarly, I think I'm getting the CfgWeapons error on the *server* when a player picks a loadout in the arsenal. Given that I've also had similar issues in Escape recently, my best guess is that Arma recently added a networking bug with unit loadouts.

**Comment by Bob-Murphy** [comment]
After a test by Spoffy no error appeared.
Can be re-opened if needed but fine for now.
