### ISSUE TITLE
Client side error for FNC_Dress

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#461]
Loaded a Vanilla save, this error was thrown. 

```
19:48:00 "167.168: [Antistasi] | INFO | MP Client | JIP?: true"
19:48:00 Error in expression <RebelUniforms), []],[],[],(selectRandom allCivilianHeadgear),"",[],["ItemMap","">
19:48:00   Error position: <allCivilianHeadgear),"",[],["ItemMap","">
19:48:00   Error Undefined variable in expression: allcivilianheadgear
19:48:00 File functions\Ammunition\fn_dress.sqf [A3A_fnc_dress]..., line 19
```

Contents of `allcivilianheadgear` if it helps:

```
["H_Booniehat_khk","H_Booniehat_oli","H_Booniehat_mcamo","H_Booniehat_tan","H_Booniehat_dgtl","H_Booniehat_khk_hs","H_Cap_red","H_Cap_blu","H_Cap_oli","H_Cap_headphones","H_Cap_tan","H_Cap_blk","H_Cap_blk_CMMG","H_Cap_brn_SPECOPS","H_Cap_tan_specops_US","H_Cap_khaki_specops_UK","H_Cap_grn","H_Cap_grn_BI","H_Cap_blk_Raven","H_Cap_blk_ION","H_Cap_oli_hs","H_Cap_press","H_Cap_usblack","H_Cap_surfer","H_Cap_police","H_MilCap_ocamo","H_MilCap_mcamo","H_MilCap_gry","H_MilCap_dgtl","H_MilCap_blue","H_Bandanna_surfer","H_Bandanna_khk","H_Bandanna_khk_hs","H_Bandanna_cbr","H_Bandanna_sgg","H_Bandanna_sand","H_Bandanna_surfer_blk","H_Bandanna_surfer_grn","H_Bandanna_gry","H_Bandanna_blu","H_Bandanna_camo","H_Bandanna_mcamo","H_Shemag_olive","H_Shemag_olive_hs","H_ShemagOpen_khk","H_ShemagOpen_tan","H_Beret_blk","H_Beret_02","H_Beret_Colonel","H_Watchcap_blk","H_Watchcap_cbr","H_Watchcap_khk","H_Watchcap_camo","H_StrawHat","H_StrawHat_dark","H_Hat_blue","H_Hat_brown","H_Hat_camo","H_Hat_grey","H_Hat_checker","H_Hat_tan"]
```

**Comment by Toakan** [comment]
This occurs with new save instances also. After creating a new game on the Tanoa map, client locally logged the same error message.

**Comment by Toakan** [comment]
[Arma3_x64_2019-11-02_20-31-43.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/3800925/Arma3_x64_2019-11-02_20-31-43.zip)

**Comment by jaj22** [comment]
allCivilianHeadgear is only generated on the server, and not broadcast to clients. I think this is an unintentional omission from the publicVariable list at the end of initVar, as allArmoredHeadgear and allCivilianUniforms are broadcast but not allCivilianHeadgear.

Alternatively some of these lists could be generated on the clients to save some startup bandwidth. The only ones that should need passing around are the unlocked* arrays.

**Comment by PoweredByPot** [comment]
yup jaj22 is correct, i just missed the public declare on it. There are plans for changing the structure of initVar to something a little more efficient soon, so I try not to make any sweeping changes.

I have a branch going that includes multiple fixes for items of different causes, will update this issue when the PR goes up.
