### ISSUE TITLE
Refactor load/save functions

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#473]
The load/save functions are unreadable, have unused calls and process data in a slow and redundant way. These functions need a complete rework.

**Comment by Bob-Murphy** [comment]
Which is the intended milestone for that?
Is somebody already working on it?

**Comment by Bob-Murphy** [comment]
Hazey, you are basically working on this one, right?

**Comment by wurzel0701** [comment]
Refactor issue
