### ISSUE TITLE
Airports fail to spawn items and units correctly.

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#481]
Using **Tembelan Island**

```
17:34:44 "[Antistasi] Spawning Airbase airport_2 (createAIAirplane.sqf)"
17:34:44 "airport_2 does not have any spawn positions set!"
17:34:44 Error in expression <awnPosition;

_vehicle=[_spawnParameter select 0, _spawnParameter select 1,_type>
17:34:44   Error position: <select 0, _spawnParameter select 1,_type>
17:34:44   Error select: Type Number, expected Array,String,Config entry
17:34:44 File functions\CREATE\fn_createAIAirplane.sqf [A3A_fnc_createAIAirplane]..., line 42```

**Comment by Bob-Murphy** [comment]
The markers are set correctly as far as I can see.
![image](https://user-images.githubusercontent.com/50651578/68609111-c4c39d80-04b4-11ea-89d9-b9dc127b76c3.png)

**Comment by wurzel0701** [comment]
airp_2_vehicle is missing, so it has no position to spawn stuff
As well as 3 4 5 an airp_vehicle

**Comment by wurzel0701** [comment]
The scripting issue is the same as #480 and already fixed

**Comment by wurzel0701** [comment]
@Bob-Murphy whatever happened, the required markers are gone, you need to place them again, assigning

**Comment by Bob-Murphy** [comment]
Please elaborate more precisely.

**Comment by wurzel0701** [comment]
There are no vehicle marker on most of the airports, only airp_1_vehicle for airport_1
You need to place airp_X_vehicle marker for airport_X

**Comment by Bob-Murphy** [comment]
Does every airport need a vehicle marker? I thought they are optional.

**Comment by wurzel0701** [comment]
If you want vehicles on them yes, if not, the merge fixes the issue

**Comment by Bob-Murphy** [comment]
merged
