### ISSUE TITLE
Duplication of faction garaged vehicles.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#482]
All players can open faction garage from outposts. They can then all place the same vehicle and get P x that vehicle.

I have thought of 3 solutions:

- Remove faction garage option from outpost flags
- Add an if == theBoss check to opening the faction garage at an outpost
- Add a presence check on placing.

No matter what I think that faction garage should be at least limited to members.

**Comment by SonorousMeerkat** [comment]
I personally believe that the presence check, with member-locking the garage, would be the best option.

**Comment by Spoffy** [comment]
That's what I'll do. TBH though, it should be locked to the boss, because that's what the HQ garage is locked to.

**Comment by Spoffy** [comment]
Garage is now member-locked. Only one person in the game can access the faction garage at a time. Resolved in commit 5889bdf903446ee2de14db8b6b9ba28e0889da58
