### ISSUE TITLE
RoadsDB files for kunduz and tembelan

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#483]
Dear @Spoffy 
Please do your magic.

This one is for kunduz
[Arma3_x64_2019-09-15_17-34-25.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/3832704/Arma3_x64_2019-09-15_17-34-25.zip)

This one is for tembelan
[Arma3_x64_2019-09-16_00-09-48.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/3832707/Arma3_x64_2019-09-16_00-09-48.zip)

Thank you very much in advance.
Best regards and yours sincerely,

Bob Murphy

**Comment by wurzel0701** [comment]
For me it is always: Wurzel do that or die
I feel discriminated

**Comment by Bob-Murphy** [comment]
@wurzel0701 
Shut the fuck up and get back to work.
Also, you are German. You as well as I are not allowed any fun whilst working.
Wörk wörk wörk
![image](https://user-images.githubusercontent.com/50651578/68610838-01919380-04b9-11ea-8cd8-7a55f5618010.png)

**Comment by Spoffy** [comment]
DBs added in 1f4cb0d2bea70b3b3431950b2eacf98689cf8b9a
