### ISSUE TITLE
add randomization to the skin of spawned vehicles in cities

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#486]
All civilian trucks spawn red, same with SUV's. I am sure it happens to other vehicle types and in other mission sets as well. I would like to look into making these skins choose randomly from the available options.

Not a big deal, but all the little touches matter.

**Comment by Bob-Murphy** [comment]
Which is the intended milestone for that?
Is somebody already working on it?

**Comment by PoweredByPot** [comment]
Vehicles are spawned as part of the createCIV script, so I will try and handle this within those changes.

**Comment by CalebSerafin** [comment]
@Bob-Murphy @PoweredByPot I believe this is already fixed, as Civ vehicles spawn with randomised skins.
