### ISSUE TITLE
Improve Weapon Categorisation in RHS

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#492]
Sniper rifles and shotguns are generally mis-classified as assault rifles in RHS. We should fix this.

**Comment by Toakan** [comment]
Is this our issue, or Upstream from RHS?

**Comment by Spoffy** [comment]
Upstream from RHS. But still, we need accurate classification. Shotguns are relatively simple to detect by looking at the ammo. Not sure on snipers yet.

**Comment by Bob-Murphy** [comment]
Which is the intended milestone for that?
Is somebody already working on it?

**Comment by Bob-Murphy** [comment]
@Spoffy 
Will this be fixed by the new template system?

**Comment by Spoffy** [comment]
Fixed by moving from dynamic generation to tool-assisted static lists. Needs grouping with #330

**Comment by jaj22** [comment]
Worked around by categoryOverrides.
