### ISSUE TITLE
Blufor for ALL maps.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#493]
Is this something that is going to be done? I would like it to be as there are a lot of options for sides in the various mods that would allow for a tonne of variety for people playing, at the end of the day I think this is a Bob thing though since he's the one that sets the maps up.

Note: This is in my project due to it coming from a note to make blufor rebels for all environments.

**Comment by Bob-Murphy** [comment]
This is no easy topic.
when we would make it like for Altis and create a separate mission for each side/map combination we would double the amount of missions we have and we would need to maintain everyone of them separately.

Of course it could be done as "only" the units and flags and such would need to be changed, but as I said, in the long run we would make ourselves more work.
Also, the larger the number of missions, the higher the chance that Bohemia/valve again gives us the problem of not being able to update the mission.

I hope that in the future we could have multiple "sides" within 1 mission file.
Maybe place all playable units from all sides which then are deactivated based on the input at mission start/parameters.

**Comment by Spoffy** [comment]
Once #385 is done and and #386 is done, this should be easily doable.

**Comment by Bob-Murphy** [comment]
What I always had in my head is, does it make sense with Antistasi to be able to play on Blufor? Depending on the mods we have it might is not the rebell side anymore and therefore looses the "rebellion" aspekt. It seems more like a fighting against rebells which clearly isn't Antistasi per se.
We need to talk about that.

**Comment by Bob-Murphy** [comment]
Nope, different system in the future
