### ISSUE TITLE
Merge mission updates

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#495]
Merge mission updates from the branch https://github.com/official-antistasi-community/A3-Antistasi/tree/map-overhauls-for-2.2 but take out the damn changes which are automatically created like author and such.

**Comment by Toakan** [comment]
I've removed the auto-generated Authors from the four mission files. If your branch is ready to submit please make a PR for it @Bob-Murphy.
