### ISSUE TITLE
Boss Assignment fails for members

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#512]
On server restart the mission commonly fails to assign commander to any member, even when they join the default commander slot, usually this needs manual allocation of commander via debug script.

This sometimes fixes itself when a new member joins, or an existing one DCs and reconnects. 

Either way, this happens regularly enough that a message here is required.

**Comment by Spoffy** [comment]
Closing this as major rewrites happen. If it's still a thing, we can re-open.
