### ISSUE TITLE
Airstrike sanity

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#524]
The airstrike script drops 8 bombs regardless of what is sent to drop them... This is fairly silly as  the planes don't always have that many hard-points, let alone points that support bombs. I have a couple of ideas in the trello for fully fledged overhauls of airstrikes but otherwise i think it would make a touch of sense to drop it to 4 or 6 at a push until a better idea is implemented.

**Comment by jaj22** [comment]
IIRC both Russian and US aircraft have multiple-bomb racks that can fit six dumb bombs per hardpoint, so I'm not sure there's much realism justification for cutting it. Also the 8-bomb airstrikes are nowhere near as dangerous as the napalm ones were.

**Comment by SonorousMeerkat** [comment]
The multi-bomb hardpoints would be dependent on what bomb is dropped, The ones in the script are too big for those points AFAIK. As for napalm, that is more dangerous because it is broken. the kill radius is massive and well beyond the flame effect's radius.

**Comment by SonorousMeerkat** [comment]
From looking into it ingame, the A-10 can carry 18 mk.82s, the SU-25 can carry 8 mk.82 equivalents, the L159 can carry 6 mk.82s and the tucano can carry 5.

My question is how often do CAS planes get loaded out and sent on carpet bombing runs, they would be given a variety of weapons usually with 2-4 dumb bombs. Or am i completely wrong?

**Comment by wurzel0701** [comment]
I would enable planes to fight for real instead of spawning bombs under them and let them drop, it would improve their efficiency while improving the rebel chance to shoot them down

**Comment by Bob-Murphy** [comment]
Another point I would like to bring up is how they spawn and despawn.
IIRC at the moment they simply spawn and despawn somewhere.
Can't we move the spawning as well as the despawning to their carrier? That makes way more sense.

**Comment by Bob-Murphy** [comment]
Whoever looks at this one, please also look at #546 .

Also, somebody work on this.
