### ISSUE TITLE
patrolCA nonsense when taking back airfield

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#526]
I took the AAC airfield on Altis and Blufor used patrolCA to send units to take it back.
The troops were in 2 troop transporters driving towards the airfield - they were in separate groups.
Once one truck was within area of the airfield the flag got turned as they outnumbered me and the one truck got the successful message.
`15:23:55 "Antistasi Debug patrolCA: Attack from  or outpost_40 to retake airport_4 succesful. Retaken."
`
This truck disembarked the troops and they approached the airfield further.

9 seconds later the second truck got into the area of the airfield and got a failed message.
`15:24:05 "Antistasi Debug patrolCA: Attack from  or outpost_40 to retake airport_4 failed"
`
This truck turned around and drove away.

Right after that the CA finished.

Somebody please make sure that the troops stay together and not split up.

@Spoffy If I'm too stupid to proper explain it, feel free to correct me.

Data in Test RPT 1 in discord.
Timestamps:
Spawning: unknown

Arriving and ending:
15:24:05

**Comment by wurzel0701** [comment]
Where exactly is the bug? I mean it does spams the rpt a little bit with not that clear messages, but overall it is working, or am I missing something?

**Comment by Bob-Murphy** [comment]
In my eyes it makes no sense that two inf. trucks are basically driving together to an objective but are reacting independently of each other.
Both have the same goal but are not working together.

Basically it's like there is a bank robbery, 2 police cars are approaching, car A arrives and investigates and car B sees car A and they "naaah, I'm good."
The second truck should also go to the target and then despawn there instead of simply turning around and driving off.

**Comment by wurzel0701** [comment]
I see, let me have a look why it is like this at all

**Comment by jaj22** [comment]
For what it's worth, the messages are not from separate trucks. What PatrolCA does is give the "success" message, calls markerChange, waits 10 seconds, and then checks whether the marker has actually changed. If it hasn't changed, it logs the "fail" message, and instructs all troops to return to their origin. 

In this case, the second truck probably just did a better job of moving away, and the first would have joined it eventually.

As to why markerChange hasn't completed within 10 seconds, #532 would hopefully tell. If it's really taking that long for a good reason then a better synchronisation check might be necessary, like testing `server getVariable _markerX`, as the date of last change appears to be stored there by markerChange.

#532 shouldn't actually close this issue though, as that success->fail likely means something unacceptable happened even with the current logging.

**Comment by wurzel0701** [comment]
Checked the new kunduz rpt, but the patrolCA failed to take any outpost back, so no data gathered by this rpt. Earlier rpt didn't have the logs active.

Search for "outnumbered the enemy" to find related logs

**Comment by wurzel0701** [comment]
Postponing as it is not a real bug. We should check it once we hear from it again

**Comment by Bob-Murphy** [comment]
@wurzel0701 
Has this already been dealt with /will it be dealt with by you?

**Comment by wurzel0701** [comment]
There are new logs added, but the original problem is not yet taken care of
