### ISSUE TITLE
Which helis are spawning on helipads?

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#529]
With 2.2 we have placed more helipads on airfields, outposts and such.
To my understanding at outposts only spawns what is stored there and there are only helis if a convoy reaches it to supply the position.
Shouldn't there also be other helis on the helipads on airfields besides the smallest ones? I have organically brought the game to war level 4 and all I saw at airfields were littlebirds at Blufor and Kasatkas as Opfor airfields.
No transport-heli, no attack-heli.

Somebody please investigate and give me proper information on what can spawn when so we may can decide on adjustments.

Thank you in advance.

**Comment by jaj22** [comment]
Currently the number of helis spawned is independent of the number of pads, has no dependence on convoys, and only patrol helis are created:

https://github.com/official-antistasi-community/A3-Antistasi/blob/997d6a25b957e61b0d374bbf62a2fc8bd8ca886c/A3-Antistasi/functions/CREATE/fn_milBuildings.sqf#L18-L31

**Comment by wurzel0701** [comment]
As per Dev chat, reducing the number of helis should work for now.
Reduce to `1 + round (random 3)`
