### ISSUE TITLE
Crates and civs broken on headless clients [bug]

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#547]
*Version:* 2.2 test

*Mods:* RPTs from ACE + CBA vanilla. RHS probably differs for the unlockedXXX one.

*Environment*: MP dedi with HCs.

*.rpt attached?* [HClogs.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/3884139/HClogs.zip)

See RPTs. A few issues there:

1. lootXXX arrays not visible on HCs. I think these are purely mod-dependent so they can be locally generated rather than shared.
2. unlockedXXX arrays are publicVariable broadcast, but only in fn_unlockEquipment, not initVar. If there's nothing unlocked (as with shotguns on vanilla) then they won't be visible. Might cause some non-HC problems too.
3. roadsX isn't broadcast or created on HCs. Probably want to create this on HCs because it's huge and should be static.

**Comment by Spoffy** [comment]
Resolved as of 4ec61a4e188b8438c436a4b3f4eab42f4ee63cb9
