### ISSUE TITLE
Open testing error 8 – Panzerfaust has no weight

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#550]
Hi Meerkat,

as you may know the RHS Panzerfaust has no weight and therefore people can load 10k into their backpack and go on a rampage.
Is there another option we could use in the box?

**Comment by SonorousMeerkat** [comment]
RPG-75 or M72 would work, 75 for greenfor rebels and 72 for blufor

**Comment by Bob-Murphy** [comment]
@SonorousMeerkat Could you please change the panzerfaust for that item then?
Thank you.

**Comment by Bob-Murphy** [comment]
@SonorousMeerkat 
The new launchers are added but the Panzerfaust is still available.
Please fix.
Thank you!

**Comment by Bob-Murphy** [comment]
@SonorousMeerkat 
The new launchers are added but the Panzerfaust is still available.
Please fix.
Thank you.

**Comment by Bob-Murphy** [comment]
Fixed
