### ISSUE TITLE
Open testing error 11 - AI-looting rewriting

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#553]
AI looting has multiple problems:
- AI is able to completely overfill vehicles
- Not all items are looted 
- - - - Example: Ammunition vanishes completely
- scalable range (maybe even based on AI training level?!?)

**Comment by killerswin2** [comment]
@Bob-Murphy Evaluate this now that we have the LTC system.

**Comment by Bob-Murphy** [comment]
not needed anymore
