### ISSUE TITLE
Open testing error 12 - Remove possible functional vehicles from civ vehicle list

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#554]
**### Please assign   yourself to the issue or comment your name when you start working on it.**

Vehicles which can have a function like for example the RHS repair truck shouldn't spawn as civilian vehicles.
If we keep the arrays clean we have less work in the future when we (maybe) add functionallity to vehicles.

Every vehicle which falls under this category are vehicles which could properly used for humanitarian as well as engineering/repairing purposes.

**Comment by Spoffy** [comment]
Closed in 3573f18b6db9e69593fb98274a99633c89265729
