### ISSUE TITLE
Open testing error 14 - Traitor clothing can be picked up

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#556]
**### Please assign   yourself to the issue or comment your name when you start working on it.**

As mentioned on discord the clothing of traitors can be picked up.
I'm not sure why this should be possible.
Somebody please investigate, find and fix that problem.

Thank you.

**Comment by SonorousMeerkat** [comment]
Likely due to Officer2 and bodyG being CDF troops (who, while blufor, use gref uniforms)
