### ISSUE TITLE
Open testing error 15 - Dublicated clothing on Blufor campaign

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#557]
Hi Meerkat,

as written in the 2.2 feedback channel in the BluFor campaign friendly AI as well as enemy AI are using the same camo.
Please take a look and fix.

Also, you can decide when to do that because your project an shit.

Cheers

**Comment by SonorousMeerkat** [comment]
Blame RHS
I highly doubt i can fix this.

**Comment by Spoffy** [comment]
We can probably fix it when we make sides use gear templates.

**Comment by SonorousMeerkat** [comment]
Probably, but the rebels might still be able to pick them up, and will no doubt cry about them getting themselves TK'd by PID.

**Comment by jaj22** [comment]
In 2.2, the friendly AIs are having their class template gear almost completely replaced anyway. If the vanilla rebel uniforms are acceptable then all you'd need to do is remove the hasGREF uniform-replacement exception from FIAinit and FIAinitBASES, and then comment out lines 17 and 18 in equipmentSort.

**Comment by SonorousMeerkat** [comment]
General principal is to keep vanilla out of modded as much as possible. Especially where there are suitable replacements in the mod.

**Comment by Lazejun** [comment]
True BUT we use 70% "Vanilla" Uniforms ourself ---> Chad Guerilla Apparel, Scientist Clothes, Worker Uniform the only RHS Uniforms used by Players are the Camo uniforms which feels like being used only by 30% Players due to looking close to enemy forces.

**Comment by SonorousMeerkat** [comment]
IMO; We shouldn't use vanilla millitary uniforms when we have alternatives. Another thing I want to talk to Pot about. RHS only really needs vanilla civilian uniforms as it doesn't add any of its own.

**Comment by Bob-Murphy** [comment]
@SonorousMeerkat 
Do we need this as a separate issue or can that be closed?

**Comment by SonorousMeerkat** [comment]
Old as shit, probably completely redundant thanks to new template system.
