### ISSUE TITLE
Open testing error 16 - Antistasi hates HCs

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#559]
It seems like Antistasi 2.2 has a serious problem with headless clients.

We need more information and it needs to be fixed before release!

**Comment by jaj22** [comment]
More detail in #547, although those probably aren't the only HC bugs.

**Comment by Spoffy** [comment]
Resolved as of 4ec61a4e188b8438c436a4b3f4eab42f4ee63cb9
Fixed all known issues with:
- createCIV
- Loot Crate Spawning
- createAICities
