### ISSUE TITLE
Armored vehicle breaching action is visible but non-functional

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#570]
*Version:* 2.2 test.

fn_startBreachVehicle expects the arrays smallBreachingCharge and largeBreachingCharge to exist. They don't, so it hints that the player needs a small or large breaching charge, regardless of what explosives they're carrying.

If this code is supposed to be working in 2.2 then we'll need some explosives classification. The power part is relatively easy (just the "hit" value in the ammo class), but I'm not sure about the rest. ACE may be a problem.

**Comment by wurzel0701** [comment]
On it, seems like something went wrong while merging this

**Comment by wurzel0701** [comment]
Readded the array, the script will work again, but not for all mods. I tried to implement a system to determine the usability of an explosive based on its indirectHit value. This does not work as the vanilla explosive satchel has a value of 3000, the demo charge 1000. The 200gr TNT block from RHS has 400 and the 400gr TNT block 1000.

There is no easy way to determine which explosive should be able to open which vehicle. The most common mods are working, but beside this nothing will

**Comment by Spoffy** [comment]
I've merged the PR - but going to leave the issue open, as I think we need to take a closer look at mod support

**Comment by wurzel0701** [comment]
Yeah thats fine, there should be a better way

**Comment by jaj22** [comment]
If small demo blocks are common, a better method may be to find all suitable charges in the player's inventory, reverse-sort them by hit value, and then accumulate until it exceeds the threshold. This would still ideally need a general explosives classification though (and one that works with ACE), otherwise you might end up accidentally burning all your grenades and AT rounds.

**Comment by wurzel0701** [comment]
Is there any common mod which is currently not included?

**Comment by wurzel0701** [comment]
If not I would postpone to 2.4

**Comment by jaj22** [comment]
RHS USMC use the M112 charges, not the ec200/400s, so you probably want to add those to the quick fix at least. Classnames are `rhsusf_m112_mag` and `rhsusf_m112x4_mag`. Could also throw in the RHS tetrytol charge, `rhs_charge_M2tet_x2_mag`.

AFRF don't seem to carry any explosives at all, and CDF have one guy with one explosive charge, so you may be reliant on crate rolls there. I don't know about 3CB.

If you wanted to be more generous you could throw in the small & large IEDs, but that probably makes it too easy to steal tanks.

**Comment by Spoffy** [comment]
Not a bad shout. One option on this btw, would be to make it so we used quantity rather than explosive power of charges. So a tank needs 4 explosives, an APC needs 2... something along those lines.

That, or I can look into actually measuring the charges' explosive power.

**Comment by jaj22** [comment]
Issue with quantity from a realism perspective is that there's such a wide range of charge sizes. RHS also has a 75gr TNT charge, for example. On the other hand, the crate generation code doesn't care about charge sizes when it hands them out...

**Comment by wurzel0701** [comment]
Measuring the charges explosive power is not easy. As stated, the hit damage of vanilla charges is alot higher then RHS ones. I don't see a reliable way to detect explosive power along all mods. I could check the damage distance in relation to damage, but I assume it will be the same result.

Another idea would be to implement that into the templates, as the charge can be selected by humans which is alot better than script detection (and way easier). And I guess someone would select explosives, who actually plays with mods

**Comment by SonorousMeerkat** [comment]
In the case that they are put to template, an easy task btw, it would absolutely be a good idea to have the hint for breaching to tell the players what specific charge they need.

**Comment by jaj22** [comment]
The "hit" value is strongly correlated with weight for these charges. The vanilla charges have higher hit values but they're correspondingly heavier. Hence determining explosive power seems to be the easy part: Detecting the difference between an AT magazine, demo charge and AT mine is more difficult.

Still, while it may be a little harsh making vanilla players lug a satchel charge around to crack a tank, the current balance constraint is availability of charges, so manually categorizing charges is reasonable. Listing the required charges on a failed attempt would be a major benefit.
