### ISSUE TITLE
[bug] Loading a hosted game as single player wipes the save

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#582]
*Version:* 2.2

*Mods:* RHS, probably doesn't matter.

*Environment:* SP, MP host

*.rpt attached:* 
[Arma3_x64_2019-12-02_20-56-41.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/3913311/Arma3_x64_2019-12-02_20-56-41.zip)
Last two mission starts are the single player and subsequent hosted starts.

As topic, if you have a hosted save, run as single player and then choose "load previous session", it fails to find any saved data (possibly intentional, as it's not unreasonable to keep them separate). Attempting to reload the game as hosted drops right back to the "choose location for HQ" screen.

This is a bit of a pain given that we're supposed to test SP for every PR. Not sure how new the behaviour is: I think I ran into the same issue a couple of weeks ago when testing the marker init, and it may be much older.

**Comment by Spoffy** [comment]
I just did:
-> Singleplayer, place HQ, save, quit
-> LAN Host, load game, no issues
-> Singleplayer, load game, no issues.

Can you give any more information on how to replicate this? Maybe it's time-sensitive or something?

**Comment by jaj22** [comment]
Hmm. I can do this successfully:
-> LAN Host, place HQ, save, quit
-> Singleplayer, load game, works

I was using a save originally started on an older version, although it's been saved a few times in 2.2 since.

**Comment by Spoffy** [comment]
Yeah, I'm struggling to see any way that the save could fail to be loaded in singleplayer. Clearly it did - I can see it in the logs, but... I've no idea how right now.

**Comment by Spoffy** [comment]
The only thing I can think of right now is if you switched profiles, or the profile vars file became corrupted somehow? 

On 2 December 2019 21:20:05 GMT, jaj22 <notifications@github.com> wrote:
>*Version:* 2.2
>
>*Mods:* RHS, probably doesn't matter.
>
>*Environment:* SP, MP host
>
>*.rpt attached:* 
>[Arma3_x64_2019-12-02_20-56-41.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/3913311/Arma3_x64_2019-12-02_20-56-41.zip)
>Last two mission starts are the single player and subsequent hosted
>starts.
>
>As topic, if you have a hosted save, run as single player and then
>choose "load previous session", it fails to find any saved data
>(possibly intentional, as it's not unreasonable to keep them separate).
>Attempting to reload the game as hosted drops right back to the "choose
>location for HQ" screen.
>
>This is a bit of a pain given that we're supposed to test SP for every
>PR. Not sure how new the behaviour is: I think I ran into the same
>issue a couple of weeks ago when testing the marker init, and it may be
>much older.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/official-antistasi-community/A3-Antistasi/issues/582

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jaj22** [comment]
Having checked the code, I don't see how it can be Antistasi's fault either, given that single player simply never writes to profilenamespace unless you tell it to. I don't need to save the game from single player to replicate, only load it.

As the Antistasi data in this vars file is about a year old, my best guess is that Arma has some version change shim in the vars file that glitches out under specific circumstances. Probably not anything we can fix anyway.

**Comment by Spoffy** [comment]
Any chance you can send me the vars file, if you have a valid copy? I want to look deeper into this, to be totally, 101% certain it isn't us.

**Comment by Spoffy** [comment]
If the save file is old enough that campaignId is 'nil', that would do it, actually.

**Comment by jaj22** [comment]
Sure, here you go:
[John.vars - RHS last.Arma3Profile.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/3917912/John.vars.-.RHS.last.Arma3Profile.zip)

There are also some issues on first (hosted) load where some garrison values appear to be non-existent, causing errors in reinforcementsAI. Those clear up after a save/load though.

**Comment by Spoffy** [comment]
Fixed, in a rather heavyweight fashion, by restructuring de-duplicating Antistasi's init code. Complete as of 4a17c39d4c684a776e5ac247239846ef7f18f0b2
