### ISSUE TITLE
2.2. Hellcat money farm

### ISSUE THREAD

**Issue by CurePindal** [official-antistasi-community/A3-Antistasi#588]
*Version:* 2.2.

*Mods:* none

*Environment*:  MP dedi.

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***
Stolen Hellcats sell for 3900 - endless money farm:

We started a testrun with the current 2.2. files (4 players) and attacked an outpost. We got a massive spam of Mohawks and Hellcats. So we could hijack a nice amount of hellcats and could sell them for wooping 3900 each.
Because we can continue to do so it feels very out of balance.

Expected: Looted vehicle prices are more balanced and not so high that they break the economy part.

**Comment by CurePindal** [comment]
Tried Mohawk, sells for 4k. Too much. =)

**Comment by jaj22** [comment]
Three issues here: 

1. There's probably an (ancient?) bug here where all helicopters are included in the vehPlanes list and so are priced at 4000 (adjusted by damage), while they're intended to be 3000 (attack) or 2000 (transport),

2. Helicopters are too easy to acquire by farming outposts. I already registered my objection to the current algorithm and it's apparently staying for 2.2, but that's something to bear in mind for 2.4.

3. If helicopters are easy to obtain then they should be cheaper. At the current rate, something in the range of 500-1000 per helicopter seems more reasonable.

**Comment by wurzel0701** [comment]
About these points

1) Right, all helicopters are in vehPlanes. Whoever did this messed this up. I will add a PR to fix this.

2) Helicopters are down to three per outpost for 2.2 and will be tied to the new garrison system for 2.4, so it will be fixed in the future.

3) Seems logical, I will adjust prices of transport helicopter in the above mentioned PR
