### ISSUE TITLE
2.2 Arsenal unlock at 25+1 items

### ISSUE THREAD

**Issue by CurePindal** [official-antistasi-community/A3-Antistasi#590]
*Version:* 2.2.

*Mods:* none

*Environment*: MP dedi.

*.rpt attatched?* no

*have you edited the missionfile?*: No

***Issue:***
Items unlock at 25+1 items instead of 25 (value set in parameters)

We had 2 cases where a rifle and a body armor didnt unlock at the set parameter of 25 items. I couldnt properly verify it but it seems they unlocked when we had above 25 items. (Not sure if it was 26 or more). 

An unlock delay was probably not the case - this problem with the rifle persisted over 10mins.
I also took the 25th rifle out  and put it back 3 times. No unlock.

Maybe 15 mins later that rifles were shown to a single player as unlocked in the arsenal. When he took one out it suddenly showed 24 rifles again. Couldnt reproduce this case.

Other items where unlocked, but I couldnt verify at which numbers.

Expected: Arsenal unlocks items at the item amount set in the parameters (25 in this case).

**Comment by Lazejun** [comment]
It does Look in the Arsenal and see X amount in there as soon as you reach 25 when its set to 25 it can unlock on the next Resource tick.

There is a easy way to "Force" the Arsenal to Refresh, if you take a vehicle Load it up with Random shit (The Loadout you are wearing usually is enough) and then hit Transfer to Ammobox its gonna force refresh it and it SHOULD unlock when its still at 25.

**Comment by CurePindal** [comment]
Done that, didnt work. (transfer via vehicle). The Mk20 rifle refused to unlock at 25.

**Comment by jaj22** [comment]
Need a replication case, or maybe a video at worst. Seems impossible in the code, and I've messed around with the arsenal a lot and never seen this.

**Comment by Bob-Murphy** [comment]
I'll close this as a duplicate with more information is open #885
