### ISSUE TITLE
Put a limiter on spawning pvp vehicles

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#591]
At the moment pvp players can spam the "spawn quadbike" button in the z menu when at an outpost and do it so long, until they have a 50.cal humvee.
This is leading to pvp players only driving around in 50 cals all the time.
To balance it out we should put a timer on it so that they can only spawn a vehicle every 5 minutes.

**Comment by SonorousMeerkat** [comment]
It would be worth having a clause that checks for the vehicle existing. This covers the edge case that the vehicle mis-spawns and self-destructs.

**Comment by Bob-Murphy** [comment]
Not needed anymore.
