### ISSUE TITLE
Add Medical vehicles

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#6]

**Comment by wurzel0701** [comment]
Multiple idea on discord currently

> No.1: 
Ambulances. Let us be able to buy civilian ambulances and/or let us steal them like fuel trucks(this would lower support though). These ambulances can either act as implemented in ace medical, making a medic more effective and quicker. and/or they can act as stasis chamber for 1-2 patients in a way that the patient will not deteriorate or die while in there and while a medic is also in there.

> Steal the Ambulance mission: same as ammo/repair except with a much larger aggro hit because medical. could also set as ACE medical vic on spawn. Destroy gives even larger aggro hit because wtf man, why would you just destroy a f*ckin' ambulance.

So maybe its time for this enhancement

**Comment by killerswin2** [comment]
Medical vehicles spawn pretty regularly, this could be could be closed.
@CalebSerafin want to close this?

**Comment by CalebSerafin** [comment]
@killerswin2 I would assume it also means to have medical vehicles affect the speed of vanilla medical. I don't believe they do (Need to check though).

**Comment by killerswin2** [comment]
https://github.com/official-antistasi-community/A3-Antistasi/pull/2542 fixes this with medical tents
