### ISSUE TITLE
TIOW-Antistasi Code only changes flag texture for default Arma 3 Flag Pole and not Custom Poles.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#600]

**Comment by CalebSerafin** [comment]
Hacked in an assertive flagX texture change in the TIOW_Reb_RENE template.

**Comment by CalebSerafin** [comment]
Whoops, closed the wrong issue, this is still a problem.

**Comment by killerswin2** [comment]
I believe that this was fixed 
`_typeVehX = _faction get "flag";
_flagX = createVehicle [_typeVehX, _positionX, [],0, "NONE"];
_flagX allowDamage false;
[_flagX,"take"] remoteExec ["A3A_fnc_flagaction",[teamPlayer,civilian],_flagX];
_vehiclesX pushBack _flagX;
if (flagTexture _flagX != (_faction get "flagTexture")) then {[_flagX,(_faction get "flagTexture")] remoteExec ["setFlagTexture",_flagX]};`
the type of flag is now in the templates.
