### ISSUE TITLE
Unit Template Static Bags superfluous.

### ISSUE THREAD

**Issue by CalebSerafin** [official-antistasi-community/A3-Antistasi#602]

**Comment by CalebSerafin** [comment]
These are the only files that use the static bags variables found in the template files.
\REINF\dismissSquad.sqf
\functions\AI\fn_mortyAI.sqf
\statSave\saveLoop.sqf


These can defiantly use the config method instead of being manually listed.
\REINF\dismissSquad.sqf
\statSave\saveLoop.sqf

I don't even know what fn_mortyAI is for or does because there is no commenting.

**Comment by jaj22** [comment]
mortyAI handles the transition of mortar and HMG teams between a placed static weapon and backpacks. You may notice that it doesn't actually use the bags: They're just aesthetic. It could certainly use the config method, and it wouldn't strictly be a problem if the static weapon didn't have the disassemble capability.

functions/REINF/fn_addFIAsquadHC.sqf also uses the static bag vars, so you may be missing a -i on your greps.

**Comment by CalebSerafin** [comment]
Will ignore for now as it only affects the AT and AA tripod bags.
