### ISSUE TITLE
Vehicles can be garaged in cities. Is it is intended or a byproduct of the code?

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#605]
Rebells can garage vehicles in friendly cities as well as destroyed / friendly roadblocks.
It seems like more accidental like something else.

More information coming.

**Comment by david-kalbermatten** [comment]
Can we please have an option to turn this back on? My friends and I actually liked this a lot :/

**Comment by HakonRydland** [comment]
It was decided that you only should be able to garage in areas with flags

**Comment by killerswin2** [comment]
Closing do to "decided that you only should be able to garage in areas with flags"
