### ISSUE TITLE
2.2 CreateCIV bugs out on HCs due to slow setVariable propagation

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#607]
*Version:* Unstable

*Mods:* Doesn't matter

*Environment*: MP dedi with machine-local HCs

*.rpt attached?* [createCIV HC bug.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/3971646/createCIV.HC.bug.zip)

*have you edited the missionfile?*: No

***Issue:***
fn_createCIV (function that creates cars in towns) is executed on headless clients, but depends on the value of namespace variables (`server getVariable markername`, specifically). Apparently these take so long to propagate that in the case where you have towns within 1km of the HQ, the initial createCIV calls error out due to nil variables, and no civilian vehicles spawn in those towns until everyone leaves spawn range. Saw this one before in someone else's HC logs but couldn't replicate until now.

Two possible solutions spring to mind:
1. waituntil the variable isn't nil.
2. Just pass the required data in the function params.

As it's a tiny amount of data in this case, 2 seems like the superior solution.

This may be a more general problem, if other HC-offloaded functions are relying on namespace variables. The behaviour of createCIV isn't new, so either no-one noticed before (quite possible given the conditions), or some change in the init order made the propagation error more likely.

**Comment by wurzel0701** [comment]
@Spoffy did your HC fixes include this particular case or is it still open?

**Comment by Spoffy** [comment]
Still open, at least, I haven't look into this. Didn't notice it in testing though.

**Comment by jaj22** [comment]
May have been a misdiagnosis, and simply caused by a bug fixed in #713. Will test further.
