### ISSUE TITLE
Player does not gets teleported on mission start and camp replacement

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#614]
Once you start a new game and select a new starting position, all the assets are teleported, but the player is left behind. It is not a real bug, but annoying

**Comment by Spoffy** [comment]
@wurzel0701 - Please re-test this on latest unstable, I believe it should be fixed, as I've done some rewrites to how map placement is handled.

**Comment by wurzel0701** [comment]
Can't really test till 3.1. (european) so it would be better if someone else would test it. To test it:
Start a SP session and replace the camp.
Start a hosted MP session and replace the camp.
Start a dedi MP session and replace the camp.

If you are teleported with the camp everytime it is fixed
