### ISSUE TITLE
Munitions crate overhaul

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#62]
The spawning system for gear into a crate is a bit wonky. It first chooses a list of loot and then removes what has already been unlocked. The result is that you could roll 5 different guns, but end up with none in the crate because they were already unlocked.

I would like to reverse the check on crate contents to only allow what hasn't been unlocked, instead of removing what has.

There is also a second issue. The section for identification of the ACE mod is actually nested inside the section that ensures you DONT have IFA mod running. It only seems to affect the HuntIR monitor from spawning, and since it shouldn't spawn in an IFA campaign even with ACE because of the timeline I am not sure this actually needs to be fixed.

**Comment by SonorousMeerkat** [comment]
The arsenal thing, rather than being reversed, should just be rerun for each item that already exists.
(that way you don't need to generate/write out a massive array of classnames

**Comment by PoweredByPot** [comment]
That is a much better idea than mine.

Let me see if I can get my fix to work, and then I'll try your method.

**Comment by PoweredByPot** [comment]
Have gotten this to be more functional, but I have noticed a few other oddities.

- any possible item may be chosen more than once, and although unlikely could be chosen for every single slot of a given item
- amounts and chances are very inconsistent and should be more unified. (some items have a guaranteed chance but 0 minimum, some have guaranteed quantity but not chance.)
- With starting load-outs stripped down or removed there is currently no way for the player to acquire IND gear

**Comment by PoweredByPot** [comment]
also, backpack choice is quite unusual, seems to be a nested chance which would mean if the first fails you have 0 chance for any other backpack

**Comment by PoweredByPot** [comment]
ready in #258

**Comment by Spoffy** [comment]
Closing as it was sorted in #315
