### ISSUE TITLE
Already unlocked launcher ammunition?!? 

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#624]
@SonorousMeerkat I got this info. Could you please look into it?
Could it me that the ammunition of the initial starting rocket launcher is the one in question and compatible? At least this is the only thing which comes to my mind.
Modset: RHS
Mission: Altis Green current 2.2 unstable
Thank you!

[03:44] XSmartPlatypusX: RPG-7V2 when not infinite will already have one of it's ammo types (PG-7VL) infinite.

**Comment by jaj22** [comment]
Might be a misunderstanding. 2.2 has a behavioural change where ammunition is unlocked separately, so if you find X PG-7VLs before you find X RPG-7s then the ammunition will be unlocked first.

There doesn't appear to be any specific reference to the PG-7VL in the code except for PvP loadouts. It's not in any of the initialRebelEquipment lists.

**Comment by Bob-Murphy** [comment]
Based on the information provided we don't see that as an issue and it can be closed.
