### ISSUE TITLE
[SP] Mission locations move on load.

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#63]
Reloading a saved SP game will successfully reboot tasks, but they are always in a new location from the previous start.

**Comment by Spoffy** [comment]
Does it put the player at the original start location?

**Comment by PoweredByPot** [comment]
yes, everything else about SP load works great. Time of day resets, location of the boxes and flag, players worn gear, etc.

**Comment by wurzel0701** [comment]
Are you sure that this is a bug, pretty sure it is not intended to save the actual position of mission (but I may be wrong on that). I would still double check that, to see if thats not intended behavior

**Comment by PoweredByPot** [comment]
No, I suppose it could be operating as expected. It's not like we get the ability to stay in the field during shut-downs. I usually operate with an 8K limit for missions for a little more diversity and having a mission move 11Km across the map from where it started sucks if you set up an observation post to get troops and supplies in nearby.

**Comment by wurzel0701** [comment]
Couldn't be that hard to actually save the mission position, could it? Just save the mission type and the marker/location and load it on server start. 
Array could look like this
```sqf
saveArray = [[marker1, "Supplies"], [marker2, "Traiter"], [[marker1, marker2], "Convoy"]]```

**Comment by AlexTriada** [comment]
it's not a bug, delete bug mark please

**Comment by Bob-Murphy** [comment]
Singleplayer will be deactivated and integrated into multiplayer - therefore no fix
