### ISSUE TITLE
Remove ADV integration

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#635]
As of the new ACE version 3.13.0 ADV is not compatible anymore and most likely won't be updated anymore. This is stated on their Steam Workshop page (02.01.2020).

Therefore ADV integration can be completely removed.

**Comment by SonorousMeerkat** [comment]
Backwards compatibility? There are people out there spreading misinformation that current ace medical is broken, rather than it just being massively different, meaning people are likely still running legacy versions. I'd say wait a version or two and phase it out.

**Comment by Bob-Murphy** [comment]
Wasn't that already done?!?
If no, somebody please look into it.

**Comment by Spoffy** [comment]
To be done, it still exists

**Comment by Lazejun** [comment]
How dare you slap me with assignements, what are you my Teacher?
