### ISSUE TITLE
Antistasis Revive System with Ace

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#640]
*Version:* 1.0.

*Mods:* ACE

*Environment*: SP, MP LAN, MP host, MP dedi.

*.rpt attatched?* no

*have you edited the missionfile?*: No

***Issue:***

Ace currently doesent overwrite Antistasis Revivesystem/Doesent disable it currently

For Example Friendly AI Garrision at HQ will be Healed by the Box via Ace but will stay in Revive state of Antistasis Revive system and they will bleed out when not "Revived" even tho they are Fully healed in terms of Ace

**Comment by lesnicro** [comment]
Remark:
I just had the same/similar problem.
During a fight my Medic in my team was hit and did not wake up after healing.
So I brought him back to HQ with the idea in mind to heal him via the Box. But it did not work.
So I directly hired another Medic into my team. That Medic healed him. And finally he woke up, ready to bring him back into the fight.

But the new hired Medic did drag the insured medic first .. At HQ .. without any enemy close to the HQ. .. so no reason to drag him first somewhere before healing.
But I still kept some team members close to the enemy location with enemies close to it.

**Comment by Spoffy** [comment]
Interesting point, combining the two (allowing them to run together properly) is something we could look at, rather than locking it off. To be discussed!

**Comment by jaj22** [comment]
Ok, played around with the current ACE medical. How it seems to work with AIs:

1. The ACE damage system is always used for AIs. At least, I didn't find a way to turn it off. This means that AIs will have getDamage = 0 regardless of wounds, and will probably bypass any Antistasi revive/healing code. 
2. You also cannot use Arma orders to make units treat themselves or each other, which is reasonable as they have a damage value of 0.
3. Disabling ACE's "Medic AI" setting will prevent AIs from healing themselves or each other. It will not disable ACE damage.
4. With "Medic AI" enabled, units treat themselves and medics treat squad members reasonably effectively, including use of splints, blood and epi.

From this, the only option that seems to make sense with ACE medical is to enable ACE's "Medic AI" and disable Antistasi revive and autoheal for all AIs. Going "hands off" on medics may also be helpful, as you'd need to avoid overriding ACE's heal orders.
