### ISSUE TITLE
PvP Role Descriptions

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#649]
@Lazejun 
![image](https://user-images.githubusercontent.com/50651578/71818199-97483a00-3088-11ea-8698-09cd88229500.png)

**Comment by Lazejun** [comment]
![Description](https://user-images.githubusercontent.com/57111907/71935747-e5a02a80-31a7-11ea-8b88-43f0fcf1ddd5.png)

**Comment by Bob-Murphy** [comment]
Manually merged
