### ISSUE TITLE
[WW2] AI weapon choice.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#651]
From the Discord.
2.1.2 save updated to 2.2

Changes made to AI equipment choice have lead to normal AI taking things like flamethrowers and AT Rifles from the arsenal which they cannot use, the flamethrower because they don't have ammo.

The flamethrower is no longer a starting weapon in 2.2 but the AT rifle is.

This could be an ongoing issue with other versions where the AI may struggle with some weapons.

**Comment by jaj22** [comment]
Same fundamental problem as #492, I suspect. Mods cannot be relied on to categorise weapons adequately, and tend to dump into Rifles or AssaultRifles by default. `hint str unlockedRifles` should confirm.

In fairness to IFA, Arma doesn't have categories for AT rifles or flamethrowers, but "UnknownWeapon" would have been a better choice.

**Comment by Bob-Murphy** [comment]
As merged and marked as fixed, I'll close this one.
