### ISSUE TITLE
New 2.2 SP bugs

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#658]
*Version:* 2.2

*Environment*: SP

***Issue:***
SP-specific issues added somewhere in 2.2. Will add more if confirmed.

Confirmed so far:
- Player not getting the setUnitTrait to medic+engineer that was in initPlayerLocal. Should probably be in fn_initClient around line 78.
- Garage option in the Y menu adds to personal garage, which is blackholed because the vehicle box lacks an action for it. Not sure how this worked before.

**Comment by SonorousMeerkat** [comment]
We gonna kill SP though... Guess it's good to log them either way.
