### ISSUE TITLE
CUP spawns aircraft carriers as attack boats

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#671]
Multiple reports via discord, that CUP has an aircraft carrier that is detected as an attack boat and spawned at seaports and/or sea patrols. However, as the ship seems to be huge, it beaches as soon as it spawns and has a real impact on performance.

Anyone who knows mods should fix that asap, as we are getting more and more reports

**Comment by SonorousMeerkat** [comment]
Easy. Tell them to not load Cup vehicles (or whatever part they're from) with antistasi.

It isn't compatible yet anyway.

**Comment by Bob-Murphy** [comment]
Correct.
As Meerkat said we won't handle that.
This would be considered and be fixed somewhat in the future if/when CUP factions is added as a compatible mod with templates and shit.

**Comment by Spoffy** [comment]
I disagree - I think given how common this report is, we should throw something in to handle it. Even if it's just blacklisting CUP Factions from the vehicle detection system, which should only be a couple of lines @Bob-Murphy

**Comment by Bob-Murphy** [comment]
let's talk about it later

**Comment by rory-dev** [comment]
I'm running a CUP template on a test server and found that the carriers were being detected as Civilian Boats (not attack boats as reported).  Removing the config search and defining 'civboats' classnames manually in fn_initvarserver, resolved it for me. 

`//CUP Detection
if isClass (configFile >> "CfgFactionClasses" >> "CUP_B_US") then {activeCUP = true; diag_log format ["%1: [Antistasi] | INFO | initVar | CUP Detected.",servertime];};`

is what i'm using, following the mod template system. Could also be used to blacklist or give a warning hint/message to servers running CUP.
