### ISSUE TITLE
Radio towers only rebuild in spirit

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#673]
From the discord bugs channel:
"When a radio tower rebuild disrupt mission is failed it does not actually rebuild the tower physically, it just reappears on the map and blocks comms. The destroyed radio tower remains and you are unable to destroy it again until after a restart." -Gino

(Marked priority because the mission has to be reloaded to fix it)

**Comment by jaj22** [comment]
HC-only bug. `A3A_fnc_repairRuinedBuilding` depends on getVariable values that are only available on the server. There may be a second bug: The function also doesn't attempt to clear the radio tower from the destroyed buildings array, so previously-destroyed radio towers may be destroyed again after loading a save. Need to check that.

Took a while to replicate this, so the fix will be tomorrow.
