### ISSUE TITLE
Map Templates missing new Pictures.

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#674]
Tanoa still has its WOTP picture even tho we have a fancier one on Steam.
(https://steamuserimages-a.akamaihd.net/ugc/781857847564264840/0BAB9EEA9FF8996104CE20C710BB28E68A90318C/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true)
Altis still has its Default Antistasi picture even tho we have a fancier one on Steam.
(https://steamuserimages-a.akamaihd.net/ugc/781857847564263272/785B2AB7E8CF065A11B35090A6022CE28C6B494D/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true)
Altis Bluefor still has its Default Antistasi picture even tho we have a fancier one on Steam.
(https://steamuserimages-a.akamaihd.net/ugc/781857847564263762/5570EFD0C1B5010923EE851709240E75A58C2DFC/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true)

**Comment by Bob-Murphy** [comment]
will look at.

**Comment by Bob-Murphy** [comment]
whiteboard
