### ISSUE TITLE
Remove the ZIL from RHS templates

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#679]
See #469

**Comment by jaj22** [comment]
If you're concerned about seat overlap, you only need to remove the open-top versions of the Zil. The data is correct for the covered version, as there are no standing positions.

**Comment by SonorousMeerkat** [comment]
Impossible, they are designated by model, which both versions share.

**Comment by jaj22** [comment]
You don't need to remove them from JNL, as the data there is correct for the covered versions, which don't suffer from the seat overlap problem anyway. You remove the open-top versions from the templates. Then everything works correctly.

Unless there's some issue with the covered versions that I missed.

**Comment by SonorousMeerkat** [comment]
The code in JNL is just block commented. Due to a slight change of plans, i'm not going to work on the templates for a little bit. Unless the flatbed is _guaranteed_ to not be spawning i'll leave it disabled until i get to the modded templates.

**Comment by killerswin2** [comment]
Old
