### ISSUE TITLE
Marked Towns.

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#680]
On some Maps the Towns that are marked should not be Towns.

which can lead to Missions that spawn in Towns to spawn in FOBs/Airbases/Places that arent Towns.

![20200111032720_1](https://user-images.githubusercontent.com/57111907/72197919-0e822300-3427-11ea-9c82-666a475e237c.jpg)

Anizay: "FobNauzad", "FobObeh" ---------> Outpost and (Heli) Airbase.

![20200111033026_1](https://user-images.githubusercontent.com/57111907/72197718-9581cc00-3424-11ea-97f1-8b0aea88323d.jpg)

Malden: "Malden_C_Airport" --------> Airbase

![20200111033422_1](https://user-images.githubusercontent.com/57111907/72197908-dd095780-3426-11ea-975c-f524c099bbc8.jpg)

Tembelan Island: "DefaultKeyPoint1" (Bessar Airbase), "DefaultKeyPoint2" (Bangunan Site B), "DefaultKeyPoint21" (Bangunan Site A), "DefaultKeyPoint58" (Bawah Naval Base), "DefaultKeyPoint49" (Pengolahan Industrial), "DefaultKeyPoint79" (Eksor), "DefaultKeyPoint60" (Hijau Solar Wind Farm). ----------> Airbase, random Diging site 1, random Diging site 2, Navalbase, Industrial Area not a Town, Industrial Area/Habour, Power Plant.

![20200111033853_1](https://user-images.githubusercontent.com/57111907/72197910-eeeafa80-3426-11ea-9cee-5402e2e947b8.jpg)

Picture of Location called Eksor, its just a Harbor not realy a Town.

fn_initzones.sqf Line 67 would need the Location names added to remove them from being Towns:
(Allready all collected just need confirmation)
!((configName _x) in [""Lakatoro01"", ""Galili01"",""Sosovu01"", ""Ipota01"", ""hill12"", ""V_broad22"", ""FobNauzad"", ""FobObeh"", ""Malden_C_Airport"", ""DefaultKeyPoint1"", ""DefaultKeyPoint2"", ""DefaultKeyPoint21"",""DefaultKeyPoint49"",""DefaultKeyPoint58"",""DefaultKeyPoint60"",""DefaultKeyPoint79""])"

**Comment by Bob-Murphy** [comment]
AgiosAndreas for Altis maybe also needs to be added

**Comment by Lazejun** [comment]
No its just a Hill.

![Unbenannt1](https://user-images.githubusercontent.com/57111907/72206911-99006c00-3493-11ea-9dc8-76613d03ff75.png)

Arma is atleast nice enough to give you the Ingame names of the "Named" locations that will be Towns.
example: Altis

![Unbenannt](https://user-images.githubusercontent.com/57111907/72206916-b46b7700-3493-11ea-9349-e5f6a5846bda.png)

but we might wanna add Moray from Malden (Malden_L_Moray), its on the Northern Island which will be Marked as CSAT area when they are allowed to exist and they would make a Punishment mission realy bad when they choose to go for it.

![20200111163434_1](https://user-images.githubusercontent.com/57111907/72206942-01e7e400-3494-11ea-8bdf-57671a830c94.jpg)

**Comment by Bob-Murphy** [comment]
!!!map specific!!!

**Comment by Bob-Murphy** [comment]
merged into unstable
