### ISSUE TITLE
Vehicle near flag does not get saved

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#692]
*Version:* 2.2

*Mods:* Official supported modset

*Environment*: Dedicated MP

***Issue:***

From Discord (report by Kleeman7)
So we seem to lose vehicles that a near the flag if we return to base hit persistent save then restart the server. If the vehicle has been there thru an auto persistent save it seems to be fine. And this is with the vehicle right next to the flag.

**Comment by jaj22** [comment]
I figured during my 1.3.3 playthrough that this mostly or entirely applied to vehicles which had been towed. The save code doesn't save any vehicles with an attached object, so this suggests that the towing code is leaving something attached.

Save code is arguably too strict anyway, and should be saving the base vehicle at least.

**Comment by wurzel0701** [comment]
Fix is done by #703, closing this
