### ISSUE TITLE
[SP] Player not given parameter choice for fast travel

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#71]
as stated

**Comment by PoweredByPot** [comment]
- also unlock limit
- mission distance from HQ
- civ traffic rate

**Comment by Bob-Murphy** [comment]
Single player have no option to change parameters whatsoever - that is not possible due to Arma itself.
If they would like to get the full experience they should host the game locally and basically play it in MP. We can't change all the pre-start parameters into in-game options.

**Comment by PoweredByPot** [comment]
@Bob-Murphy SP players are presented with the important parameters right after the commander chooses a starting location. Limited fast travel just isn't asked as one of them.

**Comment by Bob-Murphy** [comment]
Sorry, I misunderstood the problem.
Reopening

**Comment by Bob-Murphy** [comment]
Singleplayer will be deactivated and integrated into multiplayer - therefore no fix
