### ISSUE TITLE
How can i play against the russians instead of the americans using RHS?

### ISSUE THREAD

**Issue by n00melol** [official-antistasi-community/A3-Antistasi#714]
The latest version automatically sets the entire map controlled by USAF instead of AFRF.
I found no option to change this anywhere, and a window doesn't pop up like the original version by Barbolani.
So where can I set to fight against russians instead of US?

Sorry if this has been asked before or if i'm wasting time, i've never posted here before

**Comment by SonorousMeerkat** [comment]
While this question is better asked via our Discord, Rebel vs Invader is the option you want. That or playing the blufor version where you play against CDF (discount russians) as well as the AFRF themselves.

**Comment by Bob-Murphy** [comment]
Hi @n00melol 
The GitHub is more for the coding of the mission itself.
For questions like this please go to our discord which you can find https://discord.gg/dcwKf3h and post your question in the help-channel.

Thank you very much for your understanding.

**Comment by n00melol** [comment]
got it thanks
