### ISSUE TITLE
[Feature Request]: How about another building system?

### ISSUE THREAD

**Issue by SkippieDippie** [official-antistasi-community/A3-Antistasi#719]
Have you heard about Vindicta by Sparker95 for Arma 3?
How about implementing something like a building system from that mod?
This is not necessary really, but it would be nice to have.

**Comment by Bob-Murphy** [comment]
Hi Skippie,
as basically all of the developers of Vindicta are former Antistasi Admins and/or Devs we don't only know about that mod but we are in pretty good contact with them. At the moment we are not planning any implementation of a build system as we are focusing on other things and don't see the necessity.
Nevertheless, we will add your suggestion to our list of ideas.
Thank you very much for your input!

**Comment by MeltedPixel** [comment]
Being looked at with #2384

**Comment by Bob-Murphy** [comment]
implemented by #2384 in version 3.4
