### ISSUE TITLE
RHS civilian Urals not detected as civilian vehicles

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#727]
*Version:* 2.2

*Mods:* RHS

*Environment*: Any

***Issue:***
The civilian RHS trucks use the vehicleClass config param of `"rhs_vehclass_truck"`, so they're not detected by the civilian vehicle scraping logic. This has the side effect that the civilian truck you can buy can't be driven undercover, as the undercover check depends on the list of civilian vehicles.

**Comment by Bob-Murphy** [comment]
Anybody has ideas on this one?
More information in the denied and closed PR #781

**Comment by jaj22** [comment]
It'll be fixed by the civilian templates PR that I'm holding back until #839 is merged, as they touch some of the same code. Don't want to put out two PRs that will conflict with each other.

**Comment by Bob-Murphy** [comment]
Number wasn't properly integrated into the PR, therefore wasn't closed.
