### ISSUE TITLE
AI Load option on board doesn't work.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#735]
As of one of the recent version the AI load info option to get a performance readout of connected HCs has stopped working. This is fairly important for server owners/admins to monitor as it can be an indicator of when a restart is needed.

**Comment by Bob-Murphy** [comment]
Is this still an issue? Somebody has information?

**Comment by Spoffy** [comment]
Needs testing, but believed to be still an issue
