### ISSUE TITLE
Hostage/surrenderer release issue

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#739]
[18:52] Meerkat 🌵: Report from steam; Altis Blufor.

For some reason every hostages i release after taking a roadblock out, increase the aggro by +1 for both factions

Releasing surrendered people should LOWER the aggro by one.
Releasing the HOSTAGES at a mission should have no effect on the aggro.

**Comment by jaj22** [comment]
The way it currently works:

- Releasing regular (non-militia) occupants reduces occupant aggro by 0.5 (not 1).
- Releasing militia occupants has the same effect as releasing invaders: You get +1 HR, and aggro increases by 1.

Options:
1. Make occupant militia the same as occupant regulars.
2. Remove (or reverse) the aggro penalty on occupant militia, but keep the HR bonus.
3. As 2, but apply the change to releasing invaders as well.

**Comment by Bob-Murphy** [comment]
what's the difference between occ mil/non-mil?

**Comment by jaj22** [comment]
Depends on the template. In RHS greenfor the milita are rhsgref_nat_pmil. In vanilla blufor they're syndicat. In vanilla greenfor they don't exist, so all of blufor are NATO aside from the gendarmes.

I had a better idea anyway: Always reduce aggro for releasing, but by different amounts depending on faction/militia. Add a separate option for "Recruit" (with highly variable success levels), and leave that one for the aggro boosting.
