### ISSUE TITLE
[SP] Bad respawn positions

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#74]
It's a bit disorienting to be suddenly at Petros's feet. Also, it happens so quick the player is still stuck in the 'incapacitated' animation for about 10 seconds after respawn.

**Comment by Toakan** [comment]
Can this be moved to a few feet away from Petros whilst reviewing the code? 

Happened to spawn **in** a container when Petros was standing next to one.

**Comment by PoweredByPot** [comment]
Yeah, I have also been killed while spawning in, which causes the load progress to fail.

**Comment by wurzel0701** [comment]
It was intended by Barbolani to have the respawn time only in MP, so respawned player are not teleported into the base, while screaming orders or raging over dying. The bad teleport position is another thing, I am renaming the issue

**Comment by Bob-Murphy** [comment]
Singleplayer will be deactivated and integrated into multiplayer - therefore no fix
