### ISSUE TITLE
Change all logs of PatrolReinf to log on the server

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#740]
The patrolReinf script is called by the scheduler but never executed, the logs are showing the call to the scheduler, but the reinf script is never triggered.

**Comment by jaj22** [comment]
Isn't that normal with HCs? The scheduler kicks patrolReinf out to the HCs, and because they only log locally, you never see it again. 

A3A_fnc_log does have a param for logging to server. Needs someone to go through and change all the logging calls in scheduled functions.
