### ISSUE TITLE
Crates near HQ returning with contents after game load

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#754]
*Version:* 1.3+ at least

*Mods:* Any

*Environment*: Any

***Issue:***
The ammo crates used for outpost/airport loot, and the crates dropped by surrendered units are both saved if within 50m of the HQ, probably unintentionally. When the game is reloaded, the default contents of these crates are not wiped.

**Comment by Bob-Murphy** [comment]
We simply could delete said crates when reloaded
