### ISSUE TITLE
Invader outposts and airports have the wrong faction in the marker name

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#756]
*Version:* 2.2.1

*Mods:* RHS greenfor at least

*Environment*: Hosted at least, Altis

***Issue:***
For example, the AFRF airbase is called "USAF airbase". I don't know if this persists (a mrkUpdate call may well fix it) or whether it applies to other factions or islands. `nameInvaders` is set correctly after init, the init order appears to be correct (initVar before initGarrisons) and the code in initGarrisons seems to be correct.

The surface effect is trivial but it may be a sign of deeper problems.

**Comment by Lazejun** [comment]
Its on all Maps and if Outpost(0)/Airport(0) is marked Csat/Nato, the rest will have the same Name

**Comment by Bob-Murphy** [comment]
Is this issue still around? Haven't seen it in a while.

**Comment by jaj22** [comment]
Yeah, can still replicate on unstable with MP hosted + ACE/RHS greenfor Altis.
