### ISSUE TITLE
Debug log for NATOCrate not working properly

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#757]
The current 2.2.1 has no logs for NATOCrate in the log file as it should be.
The logs are created when the mission is in "debug" mode as it currently is, but no sign of any crate logs.
Needs immediate fixing.

**Comment by jaj22** [comment]
NATOCrate is executed on HCs, so you'd need to check the HC logs. I'd log to the server by default personally.

NATOCrate logging does currently have some bugs. Spamming the number of weapons repeatedly, plus a typo in the item count string. Basically works though.
