### ISSUE TITLE
[Feature Request]: Enhanced logs for Zeus activities

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#758]
We require an extended logging of Zeus Actions.
What we need is:
Each time a the gamemaster module is used for an action (list following) it should pop out a log line also containing the person which is currently logged in as admin.
List:
- heal
- injure
- spawning shit in (troops as well as objects)
- using the arsenal (maybe logging the items that changed whilst using said arsenal)
- fire support
- teleportation

Most likely we can't do it within the Antistasi code but would need to go to the Achilles code. Do I see that correct? Please confirm/deny.

**Comment by Bob-Murphy** [comment]
This topic might change as we maybe are changing from Achilles to Zeus Enhanced.
Background: Active development of Achilles is stopped.

**Comment by jaj22** [comment]
Arma fires events for Zeus object editing and placement (https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#Curator). However, Achilles and/or ZEN may not use the built-in functionality for these operations. Heal/injure are not part of curator functionality anyway, so you'd probably need to add code into Achilles/ZEN to hook them.

**Comment by Tiny-DM** [comment]
Current Zeus logging code logs the placement of all modules and objects which includes all criteria listed above, and has been recently been tested as working and as a cheating deterrent. ZEN uses the same for modules and all ZEN actions are also logged. Closing issue.
