### ISSUE TITLE
Status bar can break when controlling AIs

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#760]
*Version:* 2.2.1 and earlier

*Mods:* Any

*Environment*: Any MP

***Issue:***
The status bar display code in fn_statistics doesn't work correctly for players controlling AIs, so if you're controlling an AI when an update happens (usually on resourceCheck ticks), the bar will fail to display your money. This behaviour will persist until the next update.

A more important secondary issue is that the commander check & assign code also doesn't account properly for AI controlling, leaving the commander var in an inconsistent state. Details unconfirmed at present.

**Comment by Bob-Murphy** [comment]
Closed by merging #960
