### ISSUE TITLE
PvP player should spawn in garrisoned AI

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#762]
PvP players are currently not spawning in any garrisoned AI, therefore they can't disturb already set positions and basically have to go to direct confrontation with rebel players.
It would add more dynamic when players could "trigger" and disturb the rebels by attacking their positions.

**Comment by wurzel0701** [comment]
Can do this when fixing the AI spawns at all. Linking the issues.

#718

**Comment by Lazejun** [comment]
Well i allways got Rebell AI to spawn in and got better Gear from Town Garisons, Outpost Garison Roadblocks, Watchposts.

Without Rebell Players nearby.

**Comment by Bob-Murphy** [comment]
I checked it with 2.2.1 on Anizay and got conformation of the rebel commander. This was the reason for opening it. Maybe it's inconsistent.

**Comment by Bob-Murphy** [comment]
PvP will be disabled which makes this issue obsolete.
