### ISSUE TITLE
Helmet duplication

### ISSUE THREAD

**Issue by Brumes-Wolf** [official-antistasi-community/A3-Antistasi#770]
When a player dies, they respawn with their clothing/headgear, however the headgear also includes helmets. This allows for infinite helmets.

I added this between line 66 and 67 in onPlayerRespawn.sqf to fix this duplication issue on our server.

`removeHeadgear _newUnit;`
 
This however also removes any other headgear, regardless of it being a helmet.

**Comment by Lazejun** [comment]
Are you sure thats happening in our Versions?

Cause we would have a whole server noticing that, a lot of Helmets being unlocked.
It doesent happen in Local host cause i just respawned with the Generic Uniform you get depending on Slot and got a Shemag and not the Mich2000 i had on.

**Comment by Brumes-Wolf** [comment]
This file has not been touched before I modified it, It specifically happened with the RHS M1 helmet the local? low tech troops have, but friends reported it also happening with USAF helmets. 
Reading trough the file I also see no reference to anything being done with headgear, only backpacks weapons and such

**Comment by jaj22** [comment]
Multiplayer respawns should just get the stock headgear from their playable unit slot. That would only be a problem if a mission has playable units with armoured headgear. Which mission are you running exactly?

**Comment by Brumes-Wolf** [comment]
I' running the latest version of chernarus summer downloaded from this github. Players seem to respawn with their equipment at time of death, not with their stock equipment

**Comment by wurzel0701** [comment]
Hey @Brumes-Wolf, just wanting to confirm that this is still happening and you are sure that you are using our version. If so, can you post exact steps on how to reproduce this behaviour and send us the server rpt on discord?

**Comment by Brumes-Wolf** [comment]
I just had a good think about it, I'm quite sure this is happening because of the ACE respawn setting that respawns people with what they had at time of death. 
So this is not an issue with your mission, the fix I posted earlier would prevent it from happening to anyone else who has that setting turned on though.

**Comment by Brumes-Wolf** [comment]
The issue can be closed as far as i'm concerned

**Comment by wurzel0701** [comment]
Thanks for the info, might help some other people too, will close this issue
