### ISSUE TITLE
New bug - wavedCA

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#772]
`15:19:13 Error in expression <};
_timeOut = _timeOut + 1;
_pos = _pos findEmptyPosition [0,100,_typeVehX];
sle>
15:19:13   Error position: <findEmptyPosition [0,100,_typeVehX];
sle>
15:19:13   Error 0 elements provided, 3 expected
15:19:13 File functions\CREATE\fn_wavedCA.sqf [A3A_fnc_wavedCA]..., line 156
15:19:14 Error in expression <1;
};
if (count _pos == 0) then {_pos = getMarkerPos _spawnPoint};
_vehicle=[_po>
15:19:14   Error position: <getMarkerPos _spawnPoint};
_vehicle=[_po>
15:19:14   Error getmarkerpos: Type Object, expected Array,String
15:19:14 File functions\CREATE\fn_wavedCA.sqf [A3A_fnc_wavedCA]..., line 159`

RPT will be uploaded.

**Comment by SonorousMeerkat** [comment]
This error is for the trucks, not the planes FYI
