### ISSUE TITLE
Commander eligibility toggle hints are no longer visible

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#775]
*Version:* 2.2+

*Mods:* Any

*Environment*: MP dedi

***Issue:***
The function `fn_theBossToggleEligibility` got bounced to server-side, probably for sync consistency reasons. However, all the hints ("you have resigned" etc) weren't fixed up, so they no longer print in an MP environment.

**Comment by Bob-Murphy** [comment]
Closed by merging #960
