### ISSUE TITLE
RHS doomsday shotgun rounds can spawn in crates

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#783]
*Version:* 2.2+

*Mods:* RHS

*Environment*: Any

***Issue:***
As topic. This is probably unintentional. Could strip them out in `fn_equipmentSort` if I can be bothered to lookup the classname.

**Comment by jaj22** [comment]
Ok, classnames are "rhsusf_5Rnd_doomsday_Buck" and "rhsusf_8Rnd_doomsday_Buck".

However, while these can easily be removed from the magazine lists, the crate code can still choose them randomly when it adds shotguns to a crate, because RHS also includes the doomsday mags in the magazines arrays for the M870s.

There are two fixes that don't involve writing a ton of code: One is to check whether each magazine is present in allMagazines before it's added. This is potentially slow, as allMagazines is huge. The other is to remove shotguns from the crate weapon table.

**Comment by Bob-Murphy** [comment]
@jaj22 You have the go ahead for the solution which you see most fitting.
Just inform me which approach you will take.

**Comment by Lazejun** [comment]
This is in Theory Closed

**Comment by Bob-Murphy** [comment]
Correct.
The number wasn't properly integrated within #964 to be closed.
Will be reopened if problem still persists.
