### ISSUE TITLE
Bring ACRE2 Compatibility up to the same level as TFAR

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#786]
While we've been integrating TFAR into all relevant parts of the mission code, we have been somewhat neglecting ACRE 2. We should probably fix that at some point.

**Comment by Bob-Murphy** [comment]
Hazey, as #812 has influenced the ACRE topic, can you confirm that ACRE is now fully compatible and working?

**Comment by SonorousMeerkat** [comment]
Thing that jumps to mind is startLR. It was never ACRE compatible mainly due to the fact that i didn't see acre stuff when it was created, and i never used acre.

**Comment by SonorousMeerkat** [comment]
Laze has also mentioned TFAR Beta being bundled with this work, but that may be slightly deeper.

**Comment by Bob-Murphy** [comment]
Closed as fix was already merged.
