### ISSUE TITLE
startWithLongRangeRadio not set in SP

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#799]
On SP start there is always this error:

 8:27:01 Error in expression <rodagr","tf_anprc154"]};
if (hasTFAR && startWithLongRangeRadio) then {initialRe>
 8:27:01   Error position: <startWithLongRangeRadio) then {initialRe>
 8:27:01   Error Undefined variable in expression: startwithlongrangeradio

Vanilla_Reb_FIA_Altis.sqf..., line 110

The parameter startWithLongRangeRadio is simply not set due to it being SP.

**Comment by JohnnyDeeee** [comment]
This should cover that
https://github.com/official-antistasi-community/A3-Antistasi/pull/816

**Comment by Bob-Murphy** [comment]
Hazey, as #812 has influenced the ACRE topic, can you confirm that ACRE is now fully compatible and working?

**Comment by wurzel0701** [comment]
@Bob-Murphy issue still present on todays unstable. Will open a PR soon

**Comment by wurzel0701** [comment]
#851 will fix it
