### ISSUE TITLE
Convoy mission vehicles kill themselves/spawn wrong

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#8]

**Comment by Spoffy** [comment]
Needs verification if this is a spawning issue, or Civilian driving on-route.

**Comment by Spoffy** [comment]
havent ever sat down to figure it out, but I envision a system that checks for players within X00 meters when the mission vehicle has been destroyed before spitting out awards and penalty aggression.

An event handler attached to the vehicle might be able to do a better job too, if it works to figure out who the killer was and then verifies the side of the killer before awards.

This of course is all based on the assumption its a civillians fault, and isnt simply exploding when spawned into a house.

**Comment by Spoffy** [comment]
I would bet alot on bad spawning, cause (at least for me) this mostly happens instantly on mission start, there would be no way for the AI to kill itself so quickly. And especially for bigger convoys with multiple vehicles it is unlikely that it is always the target vehicle, that kills itself while driving.

Will look into this with the new convoy system

**Comment by SEBArma** [comment]
contact Sparker, he is back form his trip now and has worked on this in the past

**Comment by Spoffy** [comment]
Being worked on as part of https://github.com/official-antistasi-community/A3-Antistasi-1.4/commits/ConvoySimulation - removed from milestone

**Comment by Bob-Murphy** [comment]
@wurzel0701 
I think this was solved by your new system?
If so, please confirm & close.

**Comment by Spoffy** [comment]
Under the new system, they do still occasionally spawn wrong unfortunately :( It's a limitation of the Arma engine's ability to detect safe locations.

I wrote some code a while back that can sort this though (well, it has a higher % chance of success)

**Comment by wurzel0701** [comment]
The convoy mission are currently using a different code than the reinforcement convoys, so it didn't changed right now. I need to update the code for convoy missions (code is there, it is not getting called anywhere) for it to work

**Comment by Bob-Murphy** [comment]
@wurzel0701 
I bet this one if fixed with the convoy overhaul?!?
If so, please change milestone to 2.2.2 and close.

**Comment by wurzel0701** [comment]
The convoy overhaul is not yet finished (nor started) so I can't give you an ETA or version. But yeah it will be fixed with it

**Comment by wurzel0701** [comment]
This is mostly done isnt it? John did alot of fixes for convoys

**Comment by AlexTriada** [comment]
delete this issue, not actual now
