### ISSUE TITLE
Redo nav grid for malden

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#800]
The island in the left top corner has no nav grid, effectively making it useless, that should be fixed. The airport is still able to send reinforcements but only with air units and the seaport will only get reinforced with air units

**Comment by Lazejun** [comment]
![20200229140252_1](https://user-images.githubusercontent.com/57111907/75608028-396e2680-5afc-11ea-8eb2-143316c3bc2c.jpg)

Malden says no.

**Comment by Bob-Murphy** [comment]
Malden is not well behaving. We need to beat Malden up I guess

**Comment by Bob-Murphy** [comment]
I now also tested getting a point down and tested approx 400 different points. This fucker needs to be fixed another way. We most likely need a slight adaptation of the navGrid code.

**Comment by Bob-Murphy** [comment]
@wurzel0701 
The ball is in your yard.

**Comment by wurzel0701** [comment]
I know, will take some time, I am currently pulling the spoffy with all my projects. Will inform you once I know more about it.

**Comment by CalebSerafin** [comment]
@Bob-Murphy Nija-ed this one and all the other maps with the new navGrid tool. They should be suitable for now but may need another update in the future when more nav requirements are finalised.
