### ISSUE TITLE
Optional helmet popping

### ISSUE THREAD

**Issue by JohnnyDeeee** [official-antistasi-community/A3-Antistasi#809]
After https://github.com/official-antistasi-community/A3-Antistasi/pull/776 helmet popping should work as expected.

I personally do not like helmet popping (especially when i'm trying to unlock helmets...)

Should we turn this feature into an optional feature using the mission parameters?

**Comment by jaj22** [comment]
Could do, although we do have a lot of mission params already. Could maybe wait until we provide a UI for changing params in-game.

Another option would be to put a chance on the helmet popping rather than having it happen on every headshot. It's currently quite punishing with ACE because headshots are by far the best way to kill unarmed enemies with a standard rifle.

**Comment by JohnnyDeeee** [comment]
How about popping helmets cause them the helmets to be dropped as an item on the ground?
This way you still have the popping feature and you can scavenge them after the fight.

**Comment by jaj22** [comment]
Interesting idea. Generally dropping stuff on the ground near a corpse is extremely annoying because the inventory access is hard to find. On the other hand I have a theoretical fix for that.

I'm not sure whether helmet popping was intended as a cute visual headshot feedback effect or intended to make you choose between easy kills and better loot.

**Comment by JohnnyDeeee** [comment]
> Generally dropping stuff on the ground near a corpse is extremely annoying because the inventory access is hard to find.

Yes this is indeed annoying, but we could always spawn the helmet next to the body (when it is killed) so it's easier to find.

> I'm not sure whether helmet popping was intended as a cute visual headshot feedback effect or intended to make you choose between easy kills and better loot.

Personally i think having helmets (and armor in general) unlocked is extremely important if you want to do anything in Antistasi. Especially when you play with a small group of 1-5 players.

**Comment by JohnnyDeeee** [comment]
@jaj22 it seems we got Priority 1, shall we discuss this further to get to a solution?

**Comment by jaj22** [comment]
Turns out that my theoretical dropped objects fix cannot work due to several Arma flaws, so I can't recommend the helmet dropping idea. It'll just be annoying.

Chance of helmet loss (maybe as a param) is workable. I'll add it to the dev meeting notes.

**Comment by JohnnyDeeee** [comment]
@jaj22 i have some working test code for spawning the helmet after the unit dies. We could put that before https://github.com/official-antistasi-community/A3-Antistasi/blob/ddca6ae47b534b55429d50af562468ee29d00a76/A3-Antistasi/functions/Revive/fn_handleDamage.sqf#L11

---

**Result on `unstable` (normal helmet popping)**
![1 52](https://user-images.githubusercontent.com/9005496/75677758-7406c900-5c8c-11ea-9613-8e5cc616002c.png)

**New helmet popping code (test)**
![2 69](https://user-images.githubusercontent.com/9005496/75677767-78cb7d00-5c8c-11ea-93ed-430335cba723.png)

```sqf
_unit = cursorObject; 
_unit setVariable ["headgear", (headgear _unit)]; 
_unit addEventHandler ["Killed", { 
  _unit = (_this select 0); 
  _headgear = _unit getVariable ["headgear", false]; 
   
  if (str _headgear == "false") exitWith {}; 
   
  _weaponHolder = createVehicle ["GroundWeaponHolder", getPosATL _unit, [], 0, "CAN_COLLIDE"]; 
  _weaponHolder addWeaponCargoGlobal [_headgear, 1]; 
}];
```

**Result** 
![3 168](https://user-images.githubusercontent.com/9005496/75677772-7b2dd700-5c8c-11ea-864d-549e2fe07e7e.png)

![4 339](https://user-images.githubusercontent.com/9005496/75677776-7c5f0400-5c8c-11ea-8b01-b8f488b7df14.png)

**Comment by Toakan** [comment]
Would it not make sense to tie this into the strength of the armour? Ie the stronger the armours class of the helmet, the less chance it has of popping off so to speak?

Strength to pop of chance?
Level 1 - 80% 
Level 2 - 65%
Level 3 - 50%
Level 4 - 35%
Level 5 - 20%

A level 1 is more likely to be held on by velcro when a level 5 would be fitted and secured properly.
