### ISSUE TITLE
Error A3A_fnc_fogCheck

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#810]
This error occured on the main server and was spamming a few times.

```
14:15:59 Error in expression <ViewDistanceDecayRate));
0 max (1.0 - _l/_fogViewDistance)
>
14:15:59   Error position: </_fogViewDistance)
>
14:15:59   Error Zero divisor
14:15:59 File functions\Base\fn_fogCheck.sqf [A3A_fnc_fogCheck]..., line 66
```

I'll upload the RPT in the corresponding discord channel

**Comment by jaj22** [comment]
This is theoretically possible if fogParams contains extreme values, so that _fogDistance gets float-underflowed to zero. I don't know if it was especially foggy at the time.

If this is a real case then it should give consistent behaviour if we just return 0 in the case where _fogDistance is 0.
