### ISSUE TITLE
Heal Repair Rearm heals enemy AI

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#824]
When you hit the box it will heal all units in its radius. This includes AI that are unconscious in, say, a bradley:

https://youtu.be/vv1g6c_zx9s

**Comment by jaj22** [comment]
It actually doesn't heal enemies. They were probably still conscious. Issue would be that it repaired the Bradley while it was occupied by live enemies.
