### ISSUE TITLE
[Change Request]: Hide Map Markers

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#826]
We can set Alpha on Outpost/Road/Seaport ............. markers to 0 so they are NEVER Visible which reduces people Reeeeeeeeeeeing at oh this is broken all the Markers are showing.

Before:
![20200227194515_1](https://user-images.githubusercontent.com/57111907/75475814-bcc33700-5999-11ea-9466-18cea0c51d06.jpg)

After:
![20200227194236_1](https://user-images.githubusercontent.com/57111907/75475847-cea4da00-5999-11ea-8539-264553baeec6.jpg)

(ignore Error message, purposefully broken so it still shows the markers)

**Comment by MeltedPixel** [comment]
Note from Discord:
`#826 is probably redundant now because the map markers are loaded very early and very quickly. If you ever see the underlying markers on startup then something broke.`
