### ISSUE TITLE
Allow groups to bypass TP leash if member is part of the group.

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#83]
Add a further check to the TP Leash to verify that the player is part of a group, and that the majority of the group are within the same area before it activates.

If a member is in the group, you can also bypass this restriction as it's likely the group is working together to attack an objective.

Parameters would be:
- Players in group >3 
OR
- Members in group >1
AND
- Distance between 75% of group players > 1000 (1KM)

This would prevent issues were a member player dies and then punishes his group of players because of it.

This would also prevent lone wolfing, as players would need to be in a group to progress out of the area?

**Comment by Toakan** [comment]
`_P = player;
_grp = group player;

player setVariable ["GroupCounter",2];
_grpLimit = _P getVariable "GroupCounter";
_isMember = [_P] call A3A_fnc_isMember;
_lead = leader (group _P);
_leadMember = [_lead] call  A3A_fnc_isMember;
_grpCount = count (units _grp);
if (!(_isMember) && !(_grpCount >= _grpLimit) && !(_leadMember))
then
	{
	_checX = TRUE;
	while (_checkX) do`

**Comment by Toakan** [comment]
#90 Started for this.

**Comment by Toakan** [comment]
Possible full fix to accommodate non-members with their own group of players, groups where the leader is a member but not near and also catches players that are on their own.

```_player = player;
_playerPos = getPos _player;

_grp = group _player;
_grpUnits = units group _player;
_grpCount = count (_grpUnits);
_grplead = leader (group _player);

_isMember = [_player] call A3A_fnc_isMember;
_leadMember = [_grplead] call  A3A_fnc_isMember;

private _distArray = [];
_punish = 0;

if (!(_isMember) && !(_grpCount >= tpLeashGroupSize) && !(_leadMember))
then
	{
		hint "TP THIS PLAYER";
	}
	else
	{
		{ _distArray pushback [_playerPos distance _x]; } forEach _grpUnits;
		{if (_x >= tpLeashGroupDist) then {_punish = _punish + 1} } foreach _distArray;
		if (_punish > (_grpCount /2)) then 
			{
				hint "TP THIS PLAYER";
			}
		else
			{
				hint "Player in Fireteam, leave alone.";
			}
	}
sleep 120;
```

**Comment by wurzel0701** [comment]
Another idea, if a member dies, every non member in a specific radius (lets say 750 meters) gets a variable holding the time of the member death and two minutes added. The system checks for this variable and if the time is lower than the variable, the non member player is immune to the tp leash for these two minutes, that should be enough time for the member to return, or a proper RTB

**Comment by Bob-Murphy** [comment]
The system is working and there were no new complaints.
Also, every community can disable the parameter.
