### ISSUE TITLE
IFA Templates Custom Flag

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#831]
In Every IFA Reb template we are calling for the the AK Flag Texture which only exists in the Chernarus Summer Map Template.

SDKFlagTexture = "ak.jpg"; if (isServer) then {flagX setFlagTexture SDKFlagTexture};

![ak](https://user-images.githubusercontent.com/57111907/75610214-7263c680-5b0f-11ea-8f62-9302f374e1fa.jpg)

Will mostlikely throw an Error on all other maps than Chernarus Summer and have No Flag texture.

-----------> We should find something thats in IFA so we dont have to add the stupid Picture in all Map Templates/Antistasi

**Comment by Bob-Murphy** [comment]
Dealt with in 882
