### ISSUE TITLE
Several bugs and performance issues in mobile civ vehicles

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#833]
*Version:* Ancient
*Mods:* Any
*Environment*: Any

***Issue:***
- initZones incorrectly adds roads to roadsX on maps other than Altis/Tanoa/Chernarus, even though these now have roadsDBs.
- The additional roads are only added on the server, not HCs. This would be more of a problem if using a new map.
- All mobile vehicles for a city spawn operation are incorrectly spawned on the same road due to variable typos.
- The number of mobile vehicles spawned _per city_ is equal to the number of nearby cities, so you essentially get N^2 vehicles with density. This doesn't make sense and will probably be causing performance issues.

**Comment by Bob-Murphy** [comment]
Manually merged
