### ISSUE TITLE
HQ assets become deadly after moving

### ISSUE THREAD

**Issue by doommetal** [official-antistasi-community/A3-Antistasi#834]
*Version:* 2.2.1

*Mods:* None

*Environment*: MP LAN Host

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:*** HQ assets become deadly after moving

---

Currently affects flag and tent.
Steps to reproduce:
1. Start moving the HQ asset by selecting "Move this asset" from the scroll menu
2. While walking forwards select "Drop here"
3. The asset is now deadly.

The asset is deadly until moved and placed correctly (without dying from it). Moving / Rebuilding HQ does not fix the deadly assets.

**Comment by Spoffy** [comment]
This is a one line fix. They're deadly because they have velocity, despite not moving. To fix it (at least in most cases) the velocity needs setting to 0 in A3A_fnc_moveHQObject
