### ISSUE TITLE
Zeus stops working after garbage clean

### ISSUE THREAD

**Issue by doommetal** [official-antistasi-community/A3-Antistasi#835]
*Version:* 2.2.1

*Mods:* None

*Environment*: MP LAN Host

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:*** Zeus stops working after garbage clean

---

Steps to reproduce:
1. Start a new game
2. Die
3. Respawn
4. Do a garbage clean
5. Zeus no longer works

**Comment by jaj22** [comment]
Looks like this is strictly limited to MP hosted. The curator is reassigned correctly with a DS, and SP doesn't respawn. As far as I can tell it's a BIS bug, but the workaround should be straightforward if the bug only applied to hosted.

**Comment by Spoffy** [comment]
Copied from our chat earlier:
```
Spoffy: So, the bug is - the curator script never updates the 'player' object that the curator object thinks is the admin, on LAN Hosts.
Spoffy: Weirdly, this doesn't matter... until the body is deleted.
Spoffy: When it's deleted, the _player reference it keeps internally, and the global variable (which is randomly generated) that it thinks is the admin, both become objNull
Spoffy: As objNull != objNull, it thinks the player isn't the admin/curator anymore, and unassigns it.
Spoffy: The fix, is probably to assign curator ourself in the mission.
```
