### ISSUE TITLE
roadDB.sqf generation?

### ISSUE THREAD

**Issue by igorkis-scrts** [official-antistasi-community/A3-Antistasi#836]
*Version:* 2.2.1

*Mods:* -

*Environment*: -

*.rpt attatched?* -

*have you edited the missionfile?*: -

***Issue:***

Hi, maintainers of this great scenario!
This probably asked a thousand times, but since there is no definitive anwser in Google - is there any way to generate **roadsDB.sqf** file for custom maps (Isla Abramia and Taviana, in my case)?
I want to port Antistasi on another map, but it seems that there is no generator script for this file (like it is for navgrid, for example).

**Comment by Bob-Murphy** [comment]
Hi igorkis,
yes, there is a way to generate the roadsDB files. We have integrated a function for that into the mission. The command to to that is following:

`copyToClipboard ("{roadsX setVariable [_x select 0,_x select 1]} forEach " + str (call A3A_fnc_generateRoadsDB))`

BUT
We already have implemented a new system which is called navGrid (as you already know) and we have started a process to get rid of the roadsDB files as the stored information basically is not needed anymore and can be taken from the navGrid file.
I can't say when exactly this change will be completed but it shouldn't take too long.

**Comment by igorkis-scrts** [comment]
@Bob-Murphy Thank you for quick response! Will try it today 😄

**Comment by Bob-Murphy** [comment]
Could you please do me a solid and send links to the steam workshop pages to these maps? I'm always looking into potential antistasi maps

**Comment by igorkis-scrts** [comment]
@Bob-Murphy yes, of course! I will post it here when i will release them.

**Comment by Bob-Murphy** [comment]
i meant the maps himself, not the ported versions.
Of course I could search myself but there are multiple maps with different versions uploaded

**Comment by igorkis-scrts** [comment]
@Bob-Murphy 
https://steamcommunity.com/sharedfiles/filedetails/?id=1333620906
https://steamcommunity.com/sharedfiles/filedetails/?id=648775794

**Comment by Bob-Murphy** [comment]
Thank you.
I consider this issue closed for now.
If you have other question regarding this, simply contact me us on our discord and ask the questions in the #help channel.
You can join our discord at https://discord.gg/t7JD7eT
