### ISSUE TITLE
SPAR16S spawns with a bipod in loot crates

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#84]
specifically the black variant. Will look at cfg's later and see if there even is a version without one.

**Comment by PoweredByPot** [comment]
also:
-MX SW

**Comment by Spoffy** [comment]
Is this in unstable, or with your changes? (Need to check)

**Comment by PoweredByPot** [comment]
sorry, stuck on the phone with student loan people. It is unstable and does have my crate changes, but I never touched the gear lists.

**Comment by Bob-Murphy** [comment]
I do thing

**Comment by Bob-Murphy** [comment]
The SPAR16S as well as the MX SW and the SPMG are only available including the bipod - there are no versions without the bipod.
Therefore this can't be "fixed".
![image](https://user-images.githubusercontent.com/50651578/62987753-9a286100-be41-11e9-9d99-ce3c1816a9eb.png)

**Comment by PoweredByPot** [comment]
This shouldnt be in this Milestone I dont think. We have solved this problem, but the solution will come in my loot crate PR, and later another in my arsenal PR.

**Comment by PoweredByPot** [comment]
`_crate addWeaponWithAttachmentsCargoGlobal [[ _loot, "", "", "", [], [], ""], _num];`

This is what you need to fix this. "_loot" will be the wrong variable name for you though.

**Comment by PoweredByPot** [comment]
fixed in #258

**Comment by Spoffy** [comment]
#315 got merged, so this is fixed.
