### ISSUE TITLE
Rework fn_VANTinfo

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#842]
Rework needed for:

* [X] Description
* [X] Comments
* [X] Cleanup

**Comment by Bob-Murphy** [comment]
@wurzel0701 What even does this function do?!?

**Comment by Mirv** [comment]
> @wurzel0701 What even does this function do?!?

I was wondering the same thing ... It's used here - [FN_WAVEDCA.sqf](https://github.com/official-antistasi-community/A3-Antistasi/blob/4e919349936d7a63035e66d9e6c50e65d6e0784d/A3-Antistasi/functions/CREATE/fn_wavedCA.sqf)

https://github.com/official-antistasi-community/A3-Antistasi/blob/4e919349936d7a63035e66d9e6c50e65d6e0784d/A3-Antistasi/functions/CREATE/fn_wavedCA.sqf#L410

It's defined in functions as `class VANTinfo` ... but search won't pull it or `vant` up as not an exact match - it looks like an dead stub / orphan / rename.

I was guessing it's Vehicle or Antenna and looking thru functions before I gave up.

**Comment by wurzel0701** [comment]
This function is used for attacks, especially the attack drones cycling the attack destination.

This functions checks every 60 (?) seconds for nearby enemy units and reveals them to all attacking units.

But I think it is nice that we are all on the side regarding the question whether it needs a rework :D

**Comment by wurzel0701** [comment]
Refactor issue, no time for that
