### ISSUE TITLE
Add details to performance logging and reduce loop to 10 seconds

### ISSUE THREAD

**Issue by wurzel0701** [official-antistasi-community/A3-Antistasi#844]
As bob wishes, here is the issue for Spoffy:

From discord:
Spoffy - I suppose it depends on what the test is - real-world performance, or how well the servers scale with AI, for example. Because adding the mods would make the latter less clear. (Although a better test of that in ideal circumstances would be a custom mission anyway).
We probably want a more detailed AI breakdown too. Number of groups, units per group, combat status of each group - as those all have an impact on performance.
Similarly, number of bodies. We also ought to take garbage collection into account, maybe running it at a fixed interval.

Bob - Spoffy, could you add those details to our performance logging and set the timer from 30 to 10 seconds for Debug-level?

**Comment by Bob-Murphy** [comment]
Done in commits 875a9b6fb974aa91d5a7164da04e606abaa08845 and 73d396d2d096ec118dc80edd46d0283ebe154b1a
