### ISSUE TITLE
Rebel mortar teams without a quadbike get stuck in pack/unpack cycle

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#845]
*Version:* Probably any

*Mods:* Tested RHS/ACE, may also affect vanilla

*Environment*: Tested in MP host

***Issue:***
After moving a moderate distance, mortar teams without a vehicle will continually pack and unpack their mortar. Probably caused by unitReady misbehaving. Which is a pain.

**Comment by MeltedPixel** [comment]
Can confirm, I also see this behavior.

**Comment by jaj22** [comment]
First stage of testing: This is caused by the second member (morty0) of the mortar team also trying to get into the mortar. The mortar AI function itself doesn't give any orders to this crewman, so I'm not sure what the cause is yet. I've only replicated in ACE/RHS so far, so it might be caused by one of those.
