### ISSUE TITLE
3CB templates should use Warriors rather than Bradleys

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#849]
*Version:* 2.2+

*Mods:* 3CB

***Issue:***
3CB templates are currently using RHS Bradleys. There are perfectly good Warriors in 3CB which should be used instead.

**Comment by SonorousMeerkat** [comment]
Was already gonna do in the new templates, I believe they were added after i made the 3CB integration otherwise i would have used them.
