### ISSUE TITLE
More things need to be garbage cleaned.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#850]
Certain drones can be fitted with leaflet dropping capabilities and said leaflets do not get garbage cleaned. This can lead, if a player is being a dick, to significant performance loss. 

On a similar vein: Trenches, both GRAD and normal ace should be cleaned.

**Comment by MeltedPixel** [comment]
Adding onto this, we should look into also cleaning up ejection seats.

**Comment by SonorousMeerkat** [comment]
Further extension, doors and rotor blades from ka-52s

**Comment by Toakan** [comment]
The current Garbage cleaning needs to be looked at properly again. If you're looking to use the same method that the current "Surrendered" crate system uses to despawn, an alternative solution would need to be used as it doesn't trigger often enough for effect cleaning.

**Comment by SonorousMeerkat** [comment]
Another thing: ACE Bodybags

**Comment by Lazejun** [comment]
Ace Spraycan Decals aswell

**Comment by jaj22** [comment]
Found so far:

Propaganda leaflets (all): Leaflet_05_F
ACE bodybags: ACE_bodyBagObject
ACE trenches: ACE_envelope_big and ACE_envelope_small

The spraycan decals are UserTexture1m_F but it's possible that some more important things use the same object type. I'm not sure if you can determine which texture is being used, as getObjectTextures returns an empty array.

I guess trenches would need a player distance check, so they'll be more complex than a missionObjects delete.

**Comment by Lazejun** [comment]
rhs_a10_canopy
rhs_a10_acesII_seat
rhs_f22_canopy
RHS_JST_A29_Canopy
RHS_JST_A29_Ejection_Seat
rhs_ka52_blade
rhs_ka52_ejection_vest   Might be unimportant
rhs_t50_canopy
rhs_su25_canopy

some more :D

**Comment by jaj22** [comment]
I'm not sure that the canopies and ejection seats are worth clearing, as the quantity of each can never be that high. Each allMissionObjects call takes about 20ms on a fresh Malden start, and other maps may be worse.

On the flip side, it's less stuff to transfer to new players. Kinda depends how long the server runs for between restarts.

**Comment by SonorousMeerkat** [comment]
We should clean it anyway. when a single ka-50 makes 6 blades, 2 doors, 2 boosters and 2 seats. it stacks up fast.

**Comment by jaj22** [comment]
Fair enough. For finding the classnames, what exactly do you need to do to a ka-50 to make it drop all that shit?

**Comment by SonorousMeerkat** [comment]
use the ejection system in flight.

**Comment by jaj22** [comment]
Tested the ka-52 in VR with nearObjects and as far as I can tell, every object it makes is self-cleaned after a few seconds. Maybe a recent RHS change?

**Comment by jaj22** [comment]
Full RHS long-term aircraft part list, from testing:

"rhs_a10_acesII_seat"                 // A-10 and F-22
"rhs_a10_canopy"                      // other canopies delete on ground contact
"rhs_k36d5_seat"                       // used by all the AFRF stuff
