### ISSUE TITLE
Usage of Logo images in game 

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#863]
*Version:* 2.2.2.

*Mods:* None

*Environment*: MP Dedi

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***

Using a mixture of old logos is not a good idea. We should present a standard logo. 

![image](https://user-images.githubusercontent.com/7566941/76940600-786cec00-68f2-11ea-9d93-e667d16cc91f.png)

**Comment by Bob-Murphy** [comment]
I basically have to redo all the pictures as they get weirdly stretched because fuck you Arma and have to put them into a certain frame so the shown picture itself doesn't get warped.
