### ISSUE TITLE
Unlock system

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#869]
*Version:* 2.2.2

*Mods:* None

*Environment*: MP Dedicated

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***
When looking at the parameters in the game settings there are multiple options for unlocking items.

Which items of these options do Radios for instance fall under?

![image](https://user-images.githubusercontent.com/7566941/77113452-c41eb300-6a22-11ea-961a-42b53a02f857.png)

If it is Magazines it should be changed to Mags, and Accessories.

If it has been moved to one unit of control. The Lablel is completely incorrect and the numerical value upsets the balancing for every item in the game.

**Comment by Bob-Murphy** [comment]
It falls under the first value as the first value is basically the unlock value for weapons, vests, accessoires.
Therefore yes, the label is incorrect.

**Comment by Toakan** [comment]
The word Weapons should really be changed, or the sentence changed to show it means all accessories too then. You don't really hurt people with NVG's.
