### ISSUE TITLE
Enhance server logging

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#87]
For all dialogs created by server side scripts, can we push the timestamp of creation with them to help debug when scripts initialize and finish, where they hang ect.

**Comment by Toakan** [comment]
Need to add Log levels to the base configuration and then apply that to each of the log events. I'd also like to standardise the logs with something like this.

```SQF
diag_log format ["%1: [Antistasi] | INFO | Variable %2 does not exist.",servertime,position _varName];
diag_log format ["%1: [Antistasi] | ERROR | saveFuncs.sqf | Variable %2 does not exist.",servertime,position _varName];
diag_log format ["%1: [Antistasi] | DEBUG | saveFuncs.sqf | Variable %2 does not exist.",servertime,position _varName];

**Comment by wurzel0701** [comment]
Closing this as #336 solves this
