### ISSUE TITLE
[question] Save File Location Documentation

### ISSUE THREAD

**Issue by hypertexthero** [official-antistasi-community/A3-Antistasi#870]
*Version:* 2.2.1

*Mods:* 

*Environment*: MP dedi.

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***

---

Where does Antistasi save mission progress on a dedicated server? Is it saved locally on each user’s computer, or on the dedicated server itself? 

I would like to document this to make it easier to backup the file and avoid losing progress. I think it would be useful to know where the file is saved in every situation, whether SP, MP Lan, and MP Dedi both on Linux and PC.

**Comment by Bob-Murphy** [comment]
Antistasi is saving in the vars file. If played locally it's saving in the local vars file, if a dedi is used, all data (including player data) is saved in the vars file of the server.

**Comment by hypertexthero** [comment]
> Antistasi is saving in the vars file. If played locally it's saving in the local vars file, if a dedi is used, all data (including player data) is saved in the vars file of the server.

Thanks so much for clearing this up. 

One more question, if I may: Would editing the missionfile to remove stamina or add an extra weapon to the starting weapons potentially cause problems with saving mission progress?

**Comment by Bob-Murphy** [comment]
If an edited file would cause a saving error basically depends on your coding capabilities. Therefore the answer is yes.

**Comment by hypertexthero** [comment]
> If an edited file would cause a saving error basically depends on your coding capabilities. Therefore the answer is yes.

Understood, thank you!
