### ISSUE TITLE
Error in SelectIntel

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#874]
*Version:* 1.0.

*Mods:* None
*Environment*: MP Dedi

*.rpt attatched?* ~ Excerpt from client log

*have you edited the missionfile?*: No

***Issue:***
Error found when reviewing RPT File

```
23:23:08 Object WeaponHolderSimulated can't have zero or negative mass! a3\weapons_f\dummyweapon.p3d
23:23:08 Error in expression <


};
case (101):
{
private _nextTick = nextTick - time;
_nextTick = _nextTick *>
23:23:08   Error position: <nextTick - time;
_nextTick = _nextTick *>
23:23:08   Error Undefined variable in expression: nexttick
23:23:08 File functions\Intel\fn_selectIntel.sqf [A3A_fnc_selectIntel]..., line 64
23:23:12 Object WeaponHolderSimulated can't have zero or negative mass! a3\weapons_f\dummyweapon.p3d
```

**Comment by wurzel0701** [comment]
@Toakan can you give me more information how this happened? The code looks solid so far, the only reason would be nexttick not set everywhere

**Comment by Toakan** [comment]
As in Discord, the only information I can give is that it was from a client side RPT from a full 5 hour game. 

I'm not sure when exactly it triggered, the only circumstance I think may have caused it would've been a death of a captain when I was performing an intel search?

**Comment by jaj22** [comment]
You'd need a `publicVariable "nextTick"` after line 13 of `functions/init/fn_resourceCheck.sqf`.

I really think this should be replaced by a countCA report though, which is actually useful and already public.
