### ISSUE TITLE
[Bug]: Double dip to unlock gear with Arsenal.

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#885]
*Version:* 2.2.2

*Mods:* None

*Environment*: MP dedi.

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***

When you "Unlock" gear, you need to add items to the inventory twice in order for the "Tick" to notice that you have actually unlocked any gear.

To replicate, put a piece of gear that will complete your unlock requirements in a vehicle and then use the Arsenal to Vehicle menu function. 

If you then add an additional magazine or any item to that same vehicle and repeat the steps, it will prompt the unlock tick telling all server players that the gear has been unlocked and is now accessible.

**Comment by jaj22** [comment]
How this works:
1. ammunitionTransfer adds cargo to the arsenal box container, and then calls arsenalManage.
2. arsenalManage calls JNA's buttonInvToJNA UI routine (used by the "to crate" arsenal button) to transfer the box cargo into the JNA datalist.
3. buttonInvToJNA (line 2214+, fn_arsenal) assumes that it's being called from a client, and so starts the datalist update with a remoteExec.
4. Control returns to arsenalManage, which then checks the unchanged datalist for possible unlocks.
5. The remoteExec eventually happens and the datalist is updated, probably long after arsenalManage terminates.
 
Probably best to avoid the external buttonInvToJNA abuse entirely and instead use jn_fnc_arsenal_addItem directly from ammunitionTransfer.

**Comment by Toakan** [comment]
Looking back through, this is actually a replicated bug report of #590. 

Now confirming that a Dev has been able to replicate this in Vanilla MP Dedicated situations.

**Comment by Bob-Murphy** [comment]
I'll close the duplicate #590

**Comment by Toakan** [comment]
![image](https://user-images.githubusercontent.com/7566941/77828806-9a961380-7115-11ea-86e3-a02f96a0bdba.png)

Updated from Vehicle cargo pushed us over the limit, we then forced an update by dumping an extra mag.

![image](https://user-images.githubusercontent.com/7566941/77828819-b4cff180-7115-11ea-9ce4-ee6fb480afca.png)

**Comment by AlexTriada** [comment]
is this a bug? really?

**Comment by CalebSerafin** [comment]
I would assume the inconvenience of having to wait for another arsenal tick is not intended for game design or balance. So I would class it as a bug, low priority as it is just an inconvenience.

**Comment by killerswin2** [comment]
This really isn't a bug

**Comment by jaj22** [comment]
This really is a bug :P

The operation orders in ammunitionTransfer and arsenalManage all imply that the intention is to move the equipment into the arsenal and then update it. It's not even clear whether it doesn't work due to remoteExec vs call timing or a mis-held lockout. Spaghetti logic either way.
