### ISSUE TITLE
Contact rep(ort) not working with ACE

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#886]
*Version:* 2.2.2 pre-release

*Mods:* ACE

*Environment*: Any

***Issue:***
Turns out the unconscious and unconsciousAAF functions were generating the contact reports, and those are no longer called when ACE is running.

Contact reports annoyingly lacked an expiry time, so that could be fixed at the same time.

**Comment by Bob-Murphy** [comment]
@jaj22 Please connect this issue to a PR as you have set it to "Merge pending" but no PR is assossiated with it.

**Comment by Lazejun** [comment]
He did a Typo i assume 
https://github.com/official-antistasi-community/A3-Antistasi/pull/926
Or #926 
And Linked #882 by Accident instead of #886

**Comment by Bob-Murphy** [comment]
Good call but I still wait for his confirmation.

**Comment by Bob-Murphy** [comment]
merged.
