### ISSUE TITLE
Logging function update

### ISSUE THREAD

**Issue by Toakan** [official-antistasi-community/A3-Antistasi#891]
Further to #336 

By default it can go to the server on these conditions.
1) It's an error from a Client (player)
2) (Any Log Level) It's from a HC
3) There is a Parameter that can be set in game to stop logging to the server at any point (This can be added to your if at the bottom I bet).

This should fix: #740 & #757

**Comment by jaj22** [comment]
Further notes:
- Log lines should strictly be written to one place or another, not both, correct?
- On point 3, you mean an in-game parameter with a UI like "AI limit" rather than a role-screen parameter?

**Comment by Toakan** [comment]
1) Correct.
2) This will be a runtime parameter for server control so the Role-screen fits. That being said it shouldn't sit on the role-screen param list for now.

**Comment by Bob-Murphy** [comment]
Number wasn't properly integrated into the PR, therefore wasn't closed.
