### ISSUE TITLE
[Change Request]: Make attack missions more efficient

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#9]
Stick around for too long, impacting server performance

**Comment by Bob-Murphy** [comment]
@wurzel0701
I think this was solved by your new system?
If so, please confirm & close.

**Comment by wurzel0701** [comment]
Not yet, scheduled for 2.4

**Comment by wurzel0701** [comment]
Also done by John I assume, he worked on wavedCA shortly

**Comment by jaj22** [comment]
Done.
