### ISSUE TITLE
AI "players"

### ISSUE THREAD

**Issue by doommetal** [official-antistasi-community/A3-Antistasi#914]
I was changing roles from medic to something else to free up the slot. So I do and when I get back ingame I'm some AI unit by the looks of it, moving around without any input and the dude didn't react to my input. Happened both before and after the flyover scene. So I exit the game by just alt-f4ing out and get back in. In the meantime I get a report that I'm "still there but have turned into an AI and can be ordered around" (See video 1). I get back in and play a bit around with the second me to try and figure out what's going on (See video 2). Long day, so the second video is a bit whimsical. Also shadowplay hates me so it didn't record my mic. I think the only intelligent thing I said was that I discovered that Antistasi thought it was a player because I couldn't control it remotely.

**Relevant RPT:**  https://drive.google.com/open?id=1DVhLN6Z7Pfk7883TAvlGic4j6BYOGoUh
**Videos:**
The AI me being ordered around by Mango: https://www.youtube.com/watch?v=qE-hVf17tc0
Me playing around with the second me: https://www.youtube.com/watch?v=oWzVwv80C-A

**Comment by wurzel0701** [comment]
I had a similar case on the test server when Combo changed roles. He said he was initializing and ingame, but I only saw petros. He disconnected and petros vanished. Petros and Combo reappeared after he rejoined. Haven't thought about it as I thought I was just me being stupid, but it seems to be some bigger issue.

**Comment by jaj22** [comment]
I'm guessing that the two disconnections were at 11:47:08 and 11:50:06. The second one is a bit interesting as Arma never fired the mission disconnect handler: As far as it was concerned, you were never quite a player.

I don't think anything in Antistasi can actually cause this. initClient could bug out or stall at any point, and you'd still get a controllable unit. Arma's player unit startup code is probably just a bit flaky.

**Comment by AlexTriada** [comment]
close this issue pls, this is not a antistasi bug at all
