### ISSUE TITLE
Garrissoned mortar firing causes endless aircraft bombing loop

### ISSUE THREAD

**Issue by igorkis-scrts** [official-antistasi-community/A3-Antistasi#923]
*Version:* 2.2.1

*Mods:* -

*Environment*: MP on listen server

*.rpt attatched?* NO

*have you edited the missionfile?*: No

***Issue:***

Hello everyone! I played on Tanoa and noticed that when AI uses mortar to defend the outpost (airbase in our case), **multiple** invader's aircrafts (Neophron in my case) arrives **sequently** and bombs it to hell.
So, basically you're shooting down one aircraft, one or two minutes passed and the second one arrives, you're shooting down it too, one or two minutes passed, the third one arrives too... Basically, it has no end while mortar crew is alive - aircrafts keep coming to destroy it every couple of minutes.

My suggestions:
1. Increase cooldown on counter-battery actions;
2. Introduce some sort of cap/maximum action limit for these kind of actions.

**Comment by Bob-Murphy** [comment]
The airstrike system has been overhauled. That shouldn't be a problem anymore.
Thank you very much for your input!
