### ISSUE TITLE
[Bug] Disappearing Vehicles

### ISSUE THREAD

**Issue by LeiserGeist** [official-antistasi-community/A3-Antistasi#939]
*Version:* 2.2.1 on Livonia

*Mods:* CBA, TFAR, ACE (no medical, up to date), RHS USAF/AFRF/GREF, Blastcore, Improved Grenades, Enhanced Movement, CUP Core, CUP Maps, JSRS Sound Mod, ITC Land Systems, Enhanced Soundscape

*Environment*: MP dedicated with 3 headless clients

*.rpt attatched?* No (Will attach next time it happens)

*have you edited the missionfile?*: No

***Issue:***
Stolen vehicles (namely civilian vehicles) often randomly disappear.
The most recent time, two of us were driving two separate vehicles stolen from the same town, only for them to _both_ disappear at the same time when we got about 1km away from the city where they spawned. We don't remember any distances from the previous occurrence, or the occurrence before that.
**Edit:** We were both driving these vehicles near their top speeds as they disappeared out from under us.
**Edit 2:** This only seems to happen in Livonia/Enoch. Couldn't reproduce it on Altis. May also be related to the specific areas in my [map screenshot,](https://i.imgur.com/dOuU27Z.png) since we haven't had luck reproducing it anywhere else.
Vaguely remember it happening somewhere else, but I could be wrong.

The report spans over many hours, so we'll try again and see if we can get a nice concise report, but I did not see any messages generated in the report when it happened. We may also try without any mods.

**Comment by HakonRydland** [comment]
to clarify, were you still driving the vehicle when it disappeared?

**Comment by LeiserGeist** [comment]
Sorry, yes, we were both driving our vehicles when they both disappeared at once.

**Comment by LeiserGeist** [comment]
We just tried reproducing this without any mods. Completely vanilla server with only the stock 2.2.1 Enoch/Livonia mission, and it still happens every time, easy to reproduce.
https://i.imgur.com/dOuU27Z.png

- HQ on a dirt road past Zalesie
- Drive to Topolin and steal empty civilian vehicle(s)
- Drive stolen civilian vehicle(s) directly towards HQ
- Vehicle(s) disappear half way between them. Either ~1.25km from the town, or ~1.4km from base, unsure which is relevant.

No messages in the rpt when this happens. Will attach the rpt anyway.

**Comment by HakonRydland** [comment]
do you have server membership enabled, and if so are you sure your on the list?

**Comment by jaj22** [comment]
Replicated. It's partly map bug, partly spawn functionality issue. If a marker has a size equal or larger than spawn distance (Topolin is 1000m), the radius check for nearby players is reduced to zero and so everything created by the town is despawned, even if it's currently being driven.

@Bob-Murphy Can we reduce the marker size of Topolin in the SQM or are we stuck with that?

**Comment by Bob-Murphy** [comment]
What we are doing for cities and villages is that we read out the information which is put into the map by the map developer. As far as I know we don't have any code which is for example saying "If size of marker > 500 than set 500" or such and I'd rather not do it as a city like kavala is damn massiv, therefore in case we would like to do something like this we would have to set the cities this should apply to manually.

We are not setting any marker for cities whatsoever.

Therefore the questions are:
- how large of a problem is it
- does it happen on other maps as well
- which size limit is critital (600, 800 or 1000?)
and then depending on the information we need to decide if we go for a surgical approach like only overwrite the parameters for certain cities or more the broadband antibiotic approach and generally set a max number.

Also, I just took a brief look at the config viewer (for only the enoch map) and following are the names of areas >500m in at least one direction :
Adamow 750/750
Bielawa 750/750
Borek 750/750
Dolnik 600/600
Gieraltow 1000/1000
Gliniska 1000/1000
Grabin 1000/1000
Grabinskie 1000/800
Huta 750/750
Jantar 600/600
Karlin 750/750
Kolembrody 1000/1000
Lembork 750/750
Lipina 750/750
Lukow 750/750
Muratyn 750/750
Nabor 1000/1000
Nidek 750/750
Olszanka 750/750
Radacz 750/750
Radunin 1000/1000
Sitnickie 1000/800
Sobotka 750/750
Tarnow 1000/1000
Topolin 1000/1000
Wolikso 600/600
Zalesie 750/750
Zapadlisko 750/750

**Comment by jaj22** [comment]
> how large of a problem is it?
It's certainly very bad if it happens. Every vehicle you attempt to take from a particular city will disappear underneath you when the city is despawned.

> does it happen on other maps as well?
I suspect Livonia is a worst-case, but any marker with a marker size above 600 would be a potential problem.

> which size limit is critital (600, 800 or 1000?)
Depends on spawn distance. Given your Livonia list, playing that map with 600 or 700 spawn distance would be a disaster. Anything 1k+ is particularly bad because that's the default spawn distance.

I think the despawn code needs a rewrite anyway, as it's conceptually faulty and also has performance problems. However, there may be other code with dependencies on marker size that will act very oddly in these cases, so we may need to consider mangling marker sizes too, either with the hard cap or surgical methods.

**Comment by LeiserGeist** [comment]
> how large of a problem is it?
Pretty large I'd say - *twice* we lost two vehicles full of liberated weapons and supplies, causing a good bit of rage from some :(

> does it happen on other maps as well?
We were only able to replicate it from Topolin in Livonia, but didn't do *extensive* testing...
I feel like it's a major enough bug that, if it happened commonly on other maps, someone probably would have reported it by now?


Is there anything that might work as a temporary fix? Do you think setting the mission spawn distance to 1100 as I mentioned will mostly alleviate it? Or will we just run into it in other areas/directions/distances

**Comment by Bob-Murphy** [comment]
@LeiserGeist setting it to 1100 should be a working short time solution for you.

**Comment by Bob-Murphy** [comment]
@jaj22 of you want to rewrite it I won't stop you.
Regarding how we approach that problem, I think we should look into the other maps we have and then rather go with a surgical solution instead of a hard cap. But first we need more information about how many maps have that problem to come to a proper decision.

**Comment by hypertexthero** [comment]
Could disappearing helicopters like unarmed Pawnee’s stolen from enemy outposts on a dedicated server running Altis AntiStasi v.2.2.1 be related to this issue? 

When we land the helicopters loaded with supplies to support a mission near the landing zone they have always disappeared when we go back to them. 

Server membership is disabled and our HQ is *not* on an airfield. When we park the choppers <50m from our flag they do remain in place between server restarts.

**Comment by jaj22** [comment]
@hypertexthero Maybe, but the outpost/city vehicle despawn that causes this particular issue is a one-shot. The check happens only when the outpost you took the helicopter from is next despawned.

Other vehicle have their own despawn rules. The typical standalone vehicle despawner checks every 60 seconds for any spawner units (typically anything that's not a garrison) within spawn distance or HQ within 100m, for example.

**Comment by hypertexthero** [comment]
Thanks for this info, @jaj22 — I will look at the despawner code and see if I can find out what is going on. 

I wonder if maybe it is [intended functionality](https://github.com/official-antistasi-community/A3-Antistasi/commit/f66f4096a1bba1eeac627362530e3d16ae179eec#diff-7d7b0a80555c7a9253fc288d9e4cef42) for stolen vehicles like helicopters to disappear if the player is more than a certain distance from them?

**Comment by Bob-Murphy** [comment]
@jaj22 
Idea by Wurzel:
Change our code to devide every marker number for cities by 2 as our code seems to treat the "diameters" as "radii".

**Comment by jaj22** [comment]
A3A_fnc_sizeMarker is just a max (w, h) wrapper around markerSize, which according to BIS docs returns 1/2 marker width and 1/2 marker height, so as far as I can tell, we're using it correctly.
