### ISSUE TITLE
Steam workshop update commandline stuff

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#941]
You know what I need

**Comment by Bob-Murphy** [comment]
@Spoffy I'm assigning you as doom isn't available

**Comment by Wyqer** [comment]
Don't know if it's what you've in mind. I just can imagine it's about the "so many workshop missions to manually update via Eden".
If that's correct, this might be handy for you and spare you some time:
https://github.com/KillahPotatoes/KP-Steam

If it's not what you've in mind, feel free to remove this comment, as it's not meant to "advertise".

**Comment by Bob-Murphy** [comment]
Exactly that is the problem, especially as for some fucking reason sometimes I can't access a mission I uploaded to update it because fuck knows why.
I (or Spoffy for me) will certainly look at that.

Also no worries, I don't see a link to another GitHub as "advertisement" at all.
Thank you for your input!

**Comment by veteran29** [comment]
If you will encounter any issues feel free to DM me on Discord or create proper Issues on the repo. The CLI tool was not "battle tested" yet.

**Comment by Bob-Murphy** [comment]
Copy that. Already send you a DM in case so I don't need to search you again. Thank you.

**Comment by Spoffy** [comment]
Hah, that tool is exactly what we had in mind @Wyqer, @veteran29 - of course you guys had this just lying around 😉. Thanks 😁

**Comment by Wyqer** [comment]
I'm glad we could help. 👍

**Comment by Bob-Murphy** [comment]
It's working and beautiful!
