### ISSUE TITLE
Give Command to Cursor target [bug]

### ISSUE THREAD

**Issue by chubchubz** [official-antistasi-community/A3-Antistasi#943]
Version:2.2.2

*Mods:* All

*Environment*: MP

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:*** The feature of having command passed to the a eligible player that is marked by your cursor, is no longer functional

**Comment by jaj22** [comment]
If I'm reading this correctly, resigning as commander will also orphan any HC groups: The next commander (even if selected immediately) will have no access to the previous commander's HC groups.

Could you confirm whether this is true in-game?

**Comment by chubchubz** [comment]
> If I'm reading this correctly, resigning as commander will also orphan any HC groups: The next commander (even if selected immediately) will have no access to the previous commander's HC groups.
> 
> Could you confirm whether this is true in-game?


Yes it is very much true no matter what you try you will not get any HC groups from prior commanders.

**Comment by jaj22** [comment]
I found some fallback code that's supposed to find valid HC groups even if there's no commander, but it looks like that's also bugged.
