### ISSUE TITLE
Explain what countCA variable is.

### ISSUE THREAD

**Issue by shoter** [official-antistasi-community/A3-Antistasi#944]
*Version:* 
any
*Mods:* CBA, TFAR, ACE(no-medical)
does not matter
*Environment*: SP, MP LAN, MP host, MP dedi.
does not matter
*.rpt attatched?* YES
does not matter
*have you edited the missionfile?*: 
does not matter
***Issue:***
There is global variable countCA which is ambiguous to me and I am unable to understand what it is doing.

It would be helpfull if that variable would receive any meaningfull comment inside fn_initVarServer.sqf .

**Comment by shoter** [comment]
If you explain at least meaning of this variable here I will do PR by myself with meaningfull comment

**Comment by jaj22** [comment]
It's the time in seconds until the next attack (CA = counter attack, I guess) is launched from the resourceCheck loop. It's increased when the attack finishes, or by doing various missions. The function `timingCA` randomizes these increases and reduces them according to (mostly) war level.

`timingCA` is a piece of shit, for what it's worth. I rewrote it for local games.
