### ISSUE TITLE
Possible cause of failed task updates for JIP's

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#95]
found this in the RPT
 8:29:51 "Antistasi: Server sided Persistent Load done"
 8:29:51 "Antistasi: Error during Persistent Load. The variable tasks does not exist"

**Comment by Spoffy** [comment]
I'll look into it, but unlikely  - this should only be called at the very start of the game, when the server is initialising tasks for the first time. And it should default to an empty task list, I think

**Comment by Toakan** [comment]
Line 33: ./A3-Antistasi/statSave/saveFuncs.sqf

**Comment by Bob-Murphy** [comment]
@Spoffy @PoweredByPot 
Any new information regarding this?

**Comment by Spoffy** [comment]
Haven't heard it crop up recently, but no, still no news other than it's probably a base Arma issue.

**Comment by PoweredByPot** [comment]
apparently JIP detection is broken on any dedicated server using the -autoinit parameter. Since the mission cannot complete init without a player present to choose the starting HQ location anyways, there is really no point in trying to find another way to fix this.
