### ISSUE TITLE
Map marker colours don't always respect the side.

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#954]
This can lead to Invader held outposts having markers coloured in blue and vice versa. Also can effect rebel locations in the same way. This differs from one player to the next meaning this is likely something to do with data being passed from server to client.

**Comment by jaj22** [comment]
Can't be a direct Antistasi bug, as we just use setMarkerColor which has global effect. Most likely it's a general network jam. Might need to look into whether we're throwing excess data around, although I'm not sure where to start with that.

**Comment by SonorousMeerkat** [comment]
Seems more reported on join/init. Happened on the last restart of the community server 1.

**Comment by SonorousMeerkat** [comment]
After discussion on the discord, it may be down to loading a save from the garrison rework version. Will see if it persists after map/modset change.

**Comment by jaj22** [comment]
There's actually a typo bug in #925 that breaks marker colours, although I can't see why that would differ between clients. Will fix that anyway.
