### ISSUE TITLE
3CB QRFs are the size of attack waves

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#967]
As noted on the community servers, the QRFs by the British are the size of attack waves.
They usually consist of 4-8 transport helicopters, a drone, and sometimes an attack helicopter or two.

**Comment by jaj22** [comment]
I'm pretty sure something else is going on here. I'll add more server-logging in the generation functions and then hopefully we can tell.

**Comment by CalebSerafin** [comment]
@jaj22 Is this still a problem?

**Comment by jaj22** [comment]
No-one brought up a case since I added the logging. There was never anything 3CB-specific anyway. If the stars align you could hit a small and large QRF at the same time. Similarly in 2.4 you can get a singleAttack and a QRF at the same time for 12+ helis.
