### ISSUE TITLE
[CURRENT RC] Roadblocks are being 'destroyed' as soon as defender engages.

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi#97]
As soon as the defending force snaps to 'COMBAT' the task system says you have destroyed the roadblock. No one necessarily has to surrender or die.

Also, they are not clearing away structures and the flag like they should once you actually kill everyone and leave the area.

**Comment by PoweredByPot** [comment]
But it does only have one flag!

**Comment by Spoffy** [comment]
Is this an issue introduced in the latest version?

**Comment by PoweredByPot** [comment]
The clearing I think has been around a bit, I can go back a few versions and find out for sure.

The removal of stuff not triggering is new.

**Comment by Spoffy** [comment]
Either way, it's something I'll look into after the next release.

**Comment by PoweredByPot** [comment]
Did clear after a restart. And I feel like somehow this isn't obvious but I'm talking about the flag and pillbox structure only. Cars and bodies are still functioning as expected.

**Comment by Spoffy** [comment]
Does this occur on all of them? Or just the ones with bunkers? And does it occur in multiplayer?

**Comment by PoweredByPot** [comment]
just the bunkers. Yes it does occur in MP.

**Comment by Spoffy** [comment]
I have still had no luck replicating this. Gonna leave it for now - it's at the very least rare.

It's possibly to do with suppression - you can capture the point if you throw enough bullets at them. But not certain.

**Comment by PoweredByPot** [comment]
I'll try again here soon. It happens the moment the group reacts to fire. It like they are being detached from the 'garrison' of the roadblock because they've gone to combat status.

**Comment by Spoffy** [comment]
Odd, that doesn't sound like a situation where they'd all be suppressed. 

Did they shoot back? The vehicle gunner in particular? I'm wondering if they can suppress themselves.

**Comment by Spoffy** [comment]
From a conversation:
Could also be this line
[2:45 PM] Spoffy:
       ``` if (random 1 < 0.5) then {if (count units _groupX > 0) then {_x allowFleeing (1 -(_x skill "courage") + (({!([_x] call A3A_fnc_canFight)} count units _groupX)/(count units _groupX)))}};```
[2:45 PM] Spoffy: If their courage is low enough, and enough of their units are dead, then that could cause the roadblock to instantly rout.
[2:46 PM] Spoffy: Let's say you killed 1 / 5th of them.
[2:46 PM] Spoffy: Though it depends on the courage value
[2:46 PM] Spoffy: If courage < percentage dead, they'll flee.
[2:53 PM] Spoffy: What difficulty do you play on?
[2:53 PM] poweredbypot: its set to easy but chooses normal because of the flaw in params
[2:53 PM] poweredbypot: if the RB populates with IFA units that would make sense
[2:54 PM] poweredbypot: they suck, and we set them very very low for skill
[2:54 PM] poweredbypot: .2 or below would do it
[2:54 PM] poweredbypot: which im pretty sure is exactly what we set it to
[2:54 PM] Spoffy: Default courage for a unit, a War Level 1, on Normal, is 0.12

So 50% chance of fleeing, more or less, assuming one guy dies.

**Comment by Bob-Murphy** [comment]
@PoweredByPot @Spoffy 
Just as a question and for clarification, has anybody of you worked on that?
If yes, please state it. If no, please don't start working on it.

**Comment by PoweredByPot** [comment]
Unable to re-create this issue as I originally reported it. Will close for now and monitor.

**Comment by PoweredByPot** [comment]
still an issue on current steam release

Killing the man in the vehicle causes the rest of the squad to snap into alert and the roadblock is "captured" the minute they seem to react.

**Comment by AlexTriada** [comment]
delete this issue, this is not actual already

**Comment by AlexTriada** [comment]
I found the reason for this issue - 
this is the "pause" that wait for count soldiers who can fight became null

https://github.com/official-antistasi-community/A3-Antistasi/blob/15db28d6dcc2f8888e0cb66d34e61ab12e220481/A3-Antistasi/functions/CREATE/fn_createAIcontrols.sqf#L224

`{[_x,_markerX] call A3A_fnc_canConquer} count _soldiers == 0`

in this file I comment this line and problem was solved

https://github.com/official-antistasi-community/A3-Antistasi/blob/15db28d6dcc2f8888e0cb66d34e61ab12e220481/A3-Antistasi/functions/AI/fn_canConquer.sqf#L3

**Comment by AlexTriada** [comment]
I think, this file is needs to rewrite, it's a junk

https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/CREATE/fn_createAIcontrols.sqf

**Comment by AlexTriada** [comment]
I can offer a simple solution, refuse to get into the brains of bots, but I think you will not agree, as I understand you are very fond of changing the parameters of the skill back and forth in this mission, which I strongly disapprove of.
