### ISSUE TITLE
Garrisons won't use static weapons without a respawn

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#972]
*Version:* Ancient up to unstable

*Mods:* Doesn't matter

*Environment*: Any

***Issue:***
Garrison troops will only enter static weapons when spawned. Even if you put a squad AI into a static and then garrison them, they'll get out.

While the rebel garrison code will probably be replaced soon-ish, I'm tempted to fudge in a fix for 2.2.2, as this is probably the single most annoying AI limitation.

**Comment by wurzel0701** [comment]
I can confirm that this is fixed for the garrison rework, as it is super annoying. You can have a look at the code (file is called fn_manStaticsOnArrival), but I am not sure how useful that is for 2.2.2

**Comment by Bob-Murphy** [comment]
As wurzel said already fixed in another branch, therefore issue not needed.

**Comment by jaj22** [comment]
Reopened because garrison rework didn't happen and it's still the most annoying AI limitation.
